### ISSUE TITLE
Some units are getting Null coordinates

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1000]
**Describe the bug**
- Once in a while, some persons, robots, or vehicles are getting Null coordinates when walking 

**Expected and unexpected behavior**
- Each unit should always have a coordinate instance at a given time.
  
**Discuss any potential problems you have and have not ruled out**
- Now that coordinate is an immutable object, are there any instant of time where the old coordinate is being deleted but the new one has NOT been determined ?

**Java classes involved**
- `Coordinates` 

**Stacktrace**
```
Adir-02:509.650 (Severe) PersonTaskManager : [0.0000 N 0.0000 W] Alessandro Russo - Trouble calling performTask(): 
java.lang.NullPointerException: Cannot invoke "org.mars.sim.mapdata.location.Coordinates.equals(Object)" because the return value of "org.mars_sim.msp.core.vehicle.Vehicle.getCoordinates()" is null
	at org.mars_sim.msp.core.LocalAreaUtil.getAllLocalBoundedObjectsAtLocation(LocalAreaUtil.java:406)
	at org.mars_sim.msp.core.LocalAreaUtil.isPathCollisionFree(LocalAreaUtil.java:686)
	at org.mars_sim.msp.core.LocalAreaUtil.isLinePathCollisionFree(LocalAreaUtil.java:507)
	at org.mars_sim.msp.core.person.ai.task.WalkOutside.determineWalkingPath(WalkOutside.java:168)
	at org.mars_sim.msp.core.person.ai.task.WalkOutside.init(WalkOutside.java:129)
	at org.mars_sim.msp.core.person.ai.task.WalkOutside.<init>(WalkOutside.java:93)
	at org.mars_sim.msp.core.person.ai.task.DigLocal.walkToBin(DigLocal.java:215)
	at org.mars_sim.msp.core.person.ai.task.DigLocal.performMappedPhase(DigLocal.java:194)
	at org.mars_sim.msp.core.person.ai.task.util.Task.executeMappedPhase(Task.java:675)
	at org.mars_sim.msp.core.person.ai.task.util.Task.performTask(Task.java:626)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:82)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:203)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:181)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:118)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:869)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1168)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:904)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:816)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
```

**Specifications (please complete the following information)**
- pre 3.6.0 build 8538

**Additional context**
- The NPE only starts in the last week. It may have to do with the changes in trying to resolve [transfer](#997) issue.

**Comment by mokun** [comment]
@bevans2000 

Have you seen this by any chance ?

**Comment by bevans2000** [comment]
No but it should be easy to resolve. I doubt it's the changes to transfer, more likely the correct transfer has exposed an existing problem.

**Comment by bevans2000** [comment]
I know why the null Coordinate is coming from but it's an odd one. The logic is wrong BUT I can't see exactly how it can occur. So I'm making some changes to make the coordinate logic cleaner an defensive; i.e. a Unit can never have a null Coordinate
