### ISSUE TITLE
Null mineral types when launching a transport item

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1005]
**Describe the bug**
- RandomMineralMap fails to load a set of mineral types. `List<MineralType> minerals` is null.
- This happens right after loading from a saved sim. 

**Expected and unexpected behavior**
- The `List<MineralType> minerals` is generated at the start of each new sim as well as the loaded sim.
- There could be a sync issue causing the 

**Discuss any potential problems you have and have not ruled out**
- The NPE is tripped at `RandomMineralMap`'s createLocalConcentration() 

> Line 234: List<MineralType> minerals = new ArrayList<>(mineralMapConfig.getMineralTypes());

```java
	/**
	 * Creates concentration at a specified location.
	 * 
	 * @param location
	 */
	public void createLocalConcentration(Coordinates location) {
			
		if (mineralMapConfig == null)
			mineralMapConfig = SimulationConfig.instance().getMineralMapConfiguration();
		
		List<MineralType> minerals = new ArrayList<>(mineralMapConfig.getMineralTypes());
		Collections.shuffle(minerals);

```

**Java classes involved**
- `MineralMapConfig`
- `List<MineralType> mineralTypes` is transient and is not serialized
- `RandomMineralMap`'s createLocalConcentration()

**Stacktrace**
```
01-Adir-01:568.387 (Info) AbstractMission : [New Pompeii] Aanya Subramanian - Ended the Emergency Supply #42 with the status flag(s): No available vehicles.
01-Adir-01:568.387 (Info) AbstractMission : [New Pompeii] Aanya Subramanian - Disbanding mission member(s): Aanya Subramanian
01-Adir-01:568.387 (Info) TransportManager : A transport item launched on Port Ares: 01-Adir-01:568.047
01-Adir-01:568.387 (Config) SettlementBuilder : Creating 'Port Ares' based on template 'Phase 2-MS'...
01-Adir-01:568.387 (Config) Settlement : [Port Ares] Ice Collection Rate: 1.9
01-Adir-01:568.387 (Config) Settlement : [Port Ares] Regolith Collection Rate: 17.04
01-Adir-01:568.387 (Severe) MasterClock : Can't send out clock pulse: 
java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at org.mars_sim.msp.core.environment.RandomMineralMap.createLocalConcentration(RandomMineralMap.java:234)
	at org.mars_sim.msp.core.structure.Settlement.initialize(Settlement.java:485)
	at org.mars_sim.msp.core.structure.SettlementBuilder.createSettlement(SettlementBuilder.java:240)
	at org.mars_sim.msp.core.structure.SettlementBuilder.createFullSettlement(SettlementBuilder.java:118)
	at org.mars_sim.msp.core.interplanetary.transport.settlement.ArrivingSettlement.performArrival(ArrivingSettlement.java:190)
	at org.mars_sim.msp.core.interplanetary.transport.Transportable.execute(Transportable.java:172)
	at org.mars_sim.msp.core.events.ScheduledEventManager.timePassing(ScheduledEventManager.java:170)
	at org.mars_sim.msp.core.interplanetary.transport.TransportManager.timePassing(TransportManager.java:119)
	at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1411)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:648)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-01:570.352 (Info) MissionManager : [New Pompeii] Reyansh Sara - Mission 'Emergency Supply'  probability: 17.0  base prob: 17.0  sponsor: 1.0
01-Adir-01:570.352 (Info) AbstractMission : [New Pompeii] Reyansh Sara - Began organizing an Emergency Supply #43 mission.
```

**Specifications (please complete the following information)**
- post 3.6.0 build 8558

**Additional context**
```
2023-08-25T11:35:14.8 (Config) Simulation :                    Info on Saved Simulation                      
2023-08-25T11:35:14.8 (Config) Simulation :  ---------------------------------------------------------
2023-08-25T11:35:14.8 (Config) Simulation :                    Filename : default.sim
2023-08-25T11:35:14.8 (Config) Simulation :                        Path : C:\Users\mkhelios\.mars-sim\saved\
2023-08-25T11:35:14.8 (Config) Simulation :                        Size : 1.46 MB
2023-08-25T11:35:14.8 (Config) Simulation :               Made in Build : 70ee4ef-dirty
2023-08-25T11:35:14.8 (Config) Simulation :   Current Core Engine Build : 70ee4ef-dirty
2023-08-25T11:35:14.8 (Config) Simulation :           System Time Stamp : Aug 25, 2023, 11:28:37 AM
2023-08-25T11:35:14.8 (Config) Simulation :            Earth Time Stamp : 2028-08-18T04:10:34.402
2023-08-25T11:35:14.8 (Config) Simulation :          Martian Time Stamp : 01-Adir-01:518.625
2023-08-25T11:35:14.8 (Config) Simulation :  ---------------------------------------------------------
2023-08-25T11:35:14.8 (Config) Simulation :  Note : The core engine uses the same build as the saved sim.
01-Adir-01:518.625 (Config) EVAOperation : Minimum sunlight for EVA = 7.0
01-Adir-01:518.625 (Config) UnitManager : Setting up 6 thread(s) for running the settlement update.
```
- The loaded sim starts at `01-Adir-01:518.625`
- The transport item was launched at `01-Adir-01:568.387` when the clock pulse was caught with NPE

**Comment by bevans2000** [comment]
Is this on the 3.6.0 release? Will need a bugfix. Has something g changed in this area? Look easy to fix.

**Comment by bevans2000** [comment]
Do you want to assign this to me?

**Comment by mokun** [comment]
> Has something g changed in this area? Look easy to fix.

I don't recall anything I changed recently that would affect that.

But let me know what you find out.

**Comment by mokun** [comment]
>  3.6.0 release? Will need a bugfix.

I don't know if it's easy to create a new brand in Github to do that. 

How should we manage the minor fix ? 

Should we simply go by schedule to release 3.6.1 a month from now ? Then 3.6.2 two months from now, etc. ?  

I suppose it's much less risky to release minor version with 2 or 3 changes, instead of releasing a major version with hundreds of changes.

**Comment by bevans2000** [comment]
This needs to go in a 3.6,1 release as the release his only just happened. Creating a branch is easy.
As to the release strategy we should go for a release schedule.  So for example we do a release every 3 months and use the Milestone to track our progress. But it's important we capture our changes as issues and close them down when completed otherwise we will drown in open issues.

**Comment by mokun** [comment]
Can we keep all xml config files non-serializable ?

We can simply create a new `List<MineralType> minerals` entry in `RandomMineralMap` since `RandomMineralMap` is serializable.

**Comment by bevans2000** [comment]
I think it is fine as it is
