### ISSUE TITLE
error in surefire-reports, specifically org.mars_sim.msp.core.structure.construction.ConstructionStageTest

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#107]
Dear all, 

This was mentioned in passing but guess should be shared - 

```
/games/mars-sim/mars-sim-core/target/surefire-reports$ cat org.mars_sim.msp.core.structure.construction.ConstructionStageTest.txt
-------------------------------------------------------------------------------
Test set: org.mars_sim.msp.core.structure.construction.ConstructionStageTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.005 sec <<< FAILURE!
testIsComplete(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NullPointerException
        at org.mars_sim.msp.core.structure.Settlement.updateAllAssociatedPeople(Settlement.java:1860)
        at org.mars_sim.msp.core.structure.Settlement.<init>(Settlement.java:275)
        at org.mars_sim.msp.core.structure.Settlement.createConstructionStage(Settlement.java:284)
        at org.mars_sim.msp.core.structure.construction.ConstructionStageTest.testIsComplete(ConstructionStageTest.java:103)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testAddWorkTime(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
        at org.mars_sim.msp.core.structure.Settlement.updateAllAssociatedPeople(Settlement.java:1860)
        at org.mars_sim.msp.core.structure.Settlement.<init>(Settlement.java:275)
        at org.mars_sim.msp.core.structure.Settlement.createConstructionStage(Settlement.java:284)
        at org.mars_sim.msp.core.structure.construction.ConstructionStageTest.testAddWorkTime(ConstructionStageTest.java:88)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testGetInfo(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NullPointerException
        at org.mars_sim.msp.core.structure.Settlement.updateAllAssociatedPeople(Settlement.java:1860)
        at org.mars_sim.msp.core.structure.Settlement.<init>(Settlement.java:275)
        at org.mars_sim.msp.core.structure.Settlement.createConstructionStage(Settlement.java:284)
        at org.mars_sim.msp.core.structure.construction.ConstructionStageTest.testGetInfo(ConstructionStageTest.java:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testConstructionStage(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
        at org.mars_sim.msp.core.structure.Settlement.updateAllAssociatedPeople(Settlement.java:1860)
        at org.mars_sim.msp.core.structure.Settlement.<init>(Settlement.java:275)
        at org.mars_sim.msp.core.structure.Settlement.createConstructionStage(Settlement.java:284)
        at org.mars_sim.msp.core.structure.construction.ConstructionStageTest.testConstructionStage(ConstructionStageTest.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testGetCompletedWorkTime(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
        at org.mars_sim.msp.core.structure.Settlement.updateAllAssociatedPeople(Settlement.java:1860)
        at org.mars_sim.msp.core.structure.Settlement.<init>(Settlement.java:275)
        at org.mars_sim.msp.core.structure.Settlement.createConstructionStage(Settlement.java:284)
        at org.mars_sim.msp.core.structure.construction.ConstructionStageTest.testGetCompletedWorkTime(ConstructionStageTest.java:78)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)



```

**Comment by mokun** [comment]
@shirishag75 , can you fill out the issue template in future ? 

It's good to let everyone know the system on which you run the test. Appreciate that.

This seems to be openjdk 11 related.

`ConstructionSiteTest` suffers the same fates as `ConstructionStageTest`.

The `updateAllAssociatedPeople()` is the culprit again.

**Comment by shirishag75** [comment]
I edited the bug so that system information is shared as well.

**Comment by seamlik** [comment]
What version is the Surefire in Debian is irrelevant, as Maven will honor the original POM and download the artifacts online.

Debian's artifacts will only be used when building a Debian package that fully complies to The Debian Policy.

**Comment by shirishag75** [comment]
True, that was my amateur way of motivating you to see if something can be worked out :)

**Comment by shirishag75** [comment]
ah, then perhaps it is that because I have both the jdk installed - 

```
$ sudo update-java-alternatives --list
[sudo] password for shirish: 
java-1.10.0-openjdk-amd64      1101       /usr/lib/jvm/java-1.10.0-openjdk-amd64
java-1.11.0-openjdk-amd64      1111       /usr/lib/jvm/java-1.11.0-openjdk-amd64
```

**Comment by shirishag75** [comment]
Update - 

```
$ sudo update-java-alternatives --list
java-1.11.0-openjdk-amd64      1111       /usr/lib/jvm/java-1.11.0-openjdk-amd64

Tests in error: 
  testIsComplete(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)
  testAddWorkTime(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)
  testGetInfo(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)
  testConstructionStage(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)
  testGetCompletedWorkTime(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)
```

**Comment by shirishag75** [comment]
Thank you for the workaround, hopefully some days down the line we would have a real fix. I was able to move a bit forward but got stuck again, another issue, another day :)

**Comment by mokun** [comment]
Since your are using the headless edition, in your mars-sim's pom.xml, comment out the mars-sim-network, mars-sim-main and mars-sim-ui, before you run maven test. 


```
	<modules>
		<!--module>mars-sim-android</module -->
		<module>mars-sim-core</module>
		<module>mars-sim-headless</module>
		<!--module>mars-sim-main</module -->
		<module>mars-sim-mapdata</module>
		<!--module>mars-sim-network</module -->
		<!-- module>mars-sim-service</module-->
		<!--module>mars-sim-ui</module -->
	</modules>
```

**Comment by shirishag75** [comment]
any update on the java 1 error in ConstructionStageTest, it would be nice if we are able to figure out what's wrong in here and fix it.

**Comment by mokun** [comment]
In my setup, there's nothing wrong with `ConstructionStageTest` at all.

I just re-enabled it and put it to test. See below : 

```

[INFO] --- jdeb:1.6:jdeb (default) @ mars-sim-main ---
[INFO] Creating debian package: D:\eclipse\jee-2018-09\git\mars-sim\mars-sim-main\target\mars-sim-main_3.1.0~b2_all.deb
[INFO] Building conffiles
[INFO] Skipping 'conffiles' generation. No entries defined in maven/pom or ant/build.xml.
[INFO] Creating changes file: D:\eclipse\jee-2018-09\git\mars-sim\mars-sim-main\target\mars-sim-main_3.1.0~b2_all.changes
[INFO] Attaching created debian package D:\eclipse\jee-2018-09\git\mars-sim\mars-sim-main\target\mars-sim-main_3.1.0~b2_all.deb
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ mars-sim-main ---
[INFO] Installing D:\eclipse\jee-2018-09\git\mars-sim\mars-sim-main\target\mars-sim-main-3.1.0-b2.jar to C:\Users\mkhelios\.m2\repository\net\sf\mars-sim\mars-sim-main\3.1.0-b2\mars-sim-main-3.1.0-b2.jar
[INFO] Installing D:\eclipse\jee-2018-09\git\mars-sim\mars-sim-main\pom.xml to C:\Users\mkhelios\.m2\repository\net\sf\mars-sim\mars-sim-main\3.1.0-b2\mars-sim-main-3.1.0-b2.pom
[INFO] Installing D:\eclipse\jee-2018-09\git\mars-sim\mars-sim-main\target\mars-sim-main-3.1.0-b2-jar-with-dependencies.jar to C:\Users\mkhelios\.m2\repository\net\sf\mars-sim\mars-sim-main\3.1.0-b2\mars-sim-main-3.1.0-b2-jar-with-dependencies.jar
[INFO] Installing D:\eclipse\jee-2018-09\git\mars-sim\mars-sim-main\target\mars-sim-main_3.1.0~b2_all.deb to C:\Users\mkhelios\.m2\repository\net\sf\mars-sim\mars-sim-main\3.1.0-b2\mars-sim-main-3.1.0-b2.deb
[INFO] Installing D:\eclipse\jee-2018-09\git\mars-sim\mars-sim-main\target\mars-sim-main-3.1.0-b2-jar-with-dependencies.jar to C:\Users\mkhelios\.m2\repository\net\sf\mars-sim\mars-sim-main\3.1.0-b2\mars-sim-main-3.1.0-b2-jar-with-dependencies.jar
[INFO] Installing D:\eclipse\jee-2018-09\git\mars-sim\mars-sim-main\target\mars-sim-main_3.1.0~b2_all.deb to C:\Users\mkhelios\.m2\repository\net\sf\mars-sim\mars-sim-main\3.1.0-b2\mars-sim-main-3.1.0-b2.deb
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] mars-sim 3.1.0-b2 .................................. SUCCESS [  0.391 s]
[INFO] mars-sim-mapdata ................................... SUCCESS [  2.960 s]
[INFO] mars-sim-core ...................................... SUCCESS [ 47.814 s]
[INFO] mars-sim-headless .................................. SUCCESS [ 15.148 s]
[INFO] mars-sim-network ................................... SUCCESS [  2.359 s]
[INFO] mars-sim-ui ........................................ SUCCESS [01:03 min]
[INFO] mars-sim-main 3.1.0-b2 ............................. SUCCESS [ 39.369 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:34 min (Wall Clock)
[INFO] Finished at: 2018-12-05T12:54:33-08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by shirishag75** [comment]
I am still getting the error, see at https://paste.debian.net/1054577/

**Comment by shirishag75** [comment]
> I just reactivated the two tests.

<snipped>

> For instances, you can use `//` as follows to comment out the `ConstructionSiteTest` in `JUniTests` inside the construction directory if it fails the maven test :
> 
> `// suite.addTestSuite(ConstructionSiteTest.class);`

Can you share the whole path of the Construction directory ?

**Comment by shirishag75** [comment]
This is the end result it shows atm - 

```
Results :

Tests in error: 
  testGetCurrentConstructionStage(org.mars_sim.msp.core.structure.construction.ConstructionSiteTest)
  testAddNewStage(org.mars_sim.msp.core.structure.construction.ConstructionSiteTest)
  testSetUndergoingConstruction(org.mars_sim.msp.core.structure.construction.ConstructionSiteTest)
  testIsAllConstructionComplete(org.mars_sim.msp.core.structure.construction.ConstructionSiteTest)
  testGetNextStageType(org.mars_sim.msp.core.structure.construction.ConstructionSiteTest)
  testIsComplete(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)
  testAddWorkTime(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)
  testGetInfo(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)
  testConstructionStage(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)
  testGetCompletedWorkTime(org.mars_sim.msp.core.structure.construction.ConstructionStageTest)

Tests run: 210, Failures: 0, Errors: 10, Skipped: 0

```

**Comment by mokun** [comment]
> Got it, it seems to be ~/games/mars-sim/mars-sim-core/src/main/java/org/mars_sim/msp/core/structure/construction$ leafpad JUnitTests.java

No. It's inside the `/core/src/test/` directory, not the `/core/src/main/`.

See [JUnitTests](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/test/java/org/mars_sim/msp/core/structure/construction/JUnitTests.java)

**Comment by shirishag75** [comment]
I did but no change - 

```
shirish@debian:~/games/mars-sim/mars-sim-core/src/test/java/org/mars_sim/msp/core/structure/construction$ cat JUnitTests.java

.....
     // suite.addTestSuite(ConstructionManagerTest.class);
     // suite.addTestSuite(ConstructionSiteTest.class);
     // suite.addTestSuite(ConstructionStageInfoTest.class);
     // suite.addTestSuite(ConstructionStageTest.class);
     // suite.addTestSuite(ConstructionVehicleTypeTest.class);
......
```

**Comment by mokun** [comment]
With the new google guice 4.2.2 from the last build, I hope it takes care of the reflection access issue. 

Let me know if you can run maven test successfully. If not, comment out those modules that requires openjfx. See if it has to do with openjfx

```
	<modules>
		<!--module>mars-sim-android</module -->
		<module>mars-sim-core</module>
		<module>mars-sim-headless</module>
		<!--module>mars-sim-main</module -->
		<module>mars-sim-mapdata</module>
		<!--module>mars-sim-network</module -->
		<!-- module>mars-sim-service</module-->
		<!--module>mars-sim-ui</module -->
	</modules>
```

**Comment by shirishag75** [comment]
I am still running into the whole shebang - 

```
testGetCurrentConstructionStage(org.mars_sim.msp.core.structure.construction.ConstructionSiteTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NullPointerException
```

**Comment by mokun** [comment]
Can you post the stack trace on a few lines before and after it encounters `NullPointerException` in ConstructionSiteTest ? Thanks !

**Comment by shirishag75** [comment]
Is this good enough or no ?

**Comment by mokun** [comment]
Can you comment that out in [Settlement.java](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/structure/Settlement.java) to see if the null issues go away ? 

Chances are that it has to do with null UnitManager instance.

```
	private Settlement() {
		super(null, null);
		location = getCoordinates();
//		unitManager = Simulation.instance().getUnitManager();

//		updateAllAssociatedPeople();
//		updateAllAssociatedRobots();
	}
```

**Comment by shirishag75** [comment]
After doing the above, I was able to build without an issue. Got a success at the end - 

```
INFO] Creating debian package: /home/shirish/games/mars-sim/mars-sim-headless/target/mars-sim-headless_3.1.0~b2_all.deb
[INFO] Building conffiles
[INFO] Skipping 'conffiles' generation. No entries defined in maven/pom or ant/build.xml.
[INFO] Creating changes file: /home/shirish/games/mars-sim/mars-sim-headless/target/mars-sim-headless_3.1.0~b2_all.changes
[INFO] Attaching created debian package /home/shirish/games/mars-sim/mars-sim-headless/target/mars-sim-headless_3.1.0~b2_all.deb
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for mars-sim 3.1.0-b2:
[INFO] 
[INFO] mars-sim ........................................... SUCCESS [  0.003 s]
[INFO] mars-sim-mapdata ................................... SUCCESS [  2.153 s]
[INFO] mars-sim-core ...................................... SUCCESS [ 26.335 s]
[INFO] mars-sim-headless .................................. SUCCESS [ 12.906 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  41.531 s
[INFO] Finished at: 2018-12-08T11:16:13+05:30
[INFO] ------------------------------------------------------------------------

```

**Comment by mokun** [comment]
Can you turn on `log finer` to see if people are going from place to place ?

**Comment by mokun** [comment]
Let's close this thread and not mixing in other things here. If encountering any bugs, open a new issue.

**Comment by shirishag75** [comment]
I had to remove Settlement.java, git pull again and again do the fixing so was able to package and play the new version.

**Comment by mokun** [comment]
I'm reading [this](https://winterbe.com/posts/2018/08/29/migrate-maven-projects-to-java-11-jigsaw/) on the java 11 migration.

**Comment by shirishag75** [comment]
sounds like the right thing to do. Having a single pom with reduce complexity like anything.

**Comment by mokun** [comment]
> I tried running mvn versions:display-plugin-updates. Seems we would have to update whole lot of modules. Does seem like lot of work. 

We already have the latest version on all plugins.

**Comment by mokun** [comment]
This is an old. closed
