### ISSUE TITLE
Concurrent access of containerSet

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1104]
**Describe the bug**
- When speeding up the time ratio to 1944x, things begin to break down.
- A lot of missions plans are being scored and considered. 
- When calling `TradeMeta` and `DeliveryMeta`,  `(CommerceUtil` is used to find available containers
- The method `EquipmentInventory::findNumEmptyContainersOfType` is evoked to find empty containers.
- ConcurrentModificationException is tripped.
- Somehow `containerSet` is being accessed elsewhere.

**Expected and unexpected behavior**
- Ensure that `containerSet` is NOT being accessed elsewhere concurrently.
- This issue seems to have popped up once in a while in the past.
 
**Java classes involved**
- `EquipmentInventory`

**Stacktrace**
```
01-Adir-06:232.723 (Warning) RespondToStudyInvitation : [Arcadia] Aimar Pérez - Doing too many studies to accept Botany #9
01-Adir-06:232.723 (Info) Mining [x17] : [Kyocera] 9.0000 N 163.7999 E has a Mining Value of 0.0.
01-Adir-06:232.723 (Info) ReviewMissionPlan : [Kyocera] Yamato Ogawa - Grading Mineral Exploration #188 Plan - Rels: 9, Site: 0.0, Review: 2; Subtotal: 11.0
01-Adir-06:232.723 (Info) ReviewMissionPlan : [Kyocera] Yamato Ogawa - Done reviewing Rui Kaneko's Mineral Exploration #188 mission plan.
01-Adir-06:240.256 (Info) MissionManager : [Heritage] Anna Novák - Mission 'Ice Prospecting' score: Score:0.64 (base:1,settlementratio:1,minerals:4,leader:0.36,extrovert:1,goods:1,population:0.444)
01-Adir-06:240.256 (Info) MissionManager : [Heritage] Anna Novák - Mission 'Regolith Prospecting' score: Score:0.892 (base:1,settlementratio:1.3,minerals:4.286,leader:0.36,extrovert:1,goods:1,population:0.444)
01-Adir-06:240.256 (Info) DeliveryMeta [x2] : [Heritage] Drone 025 - Available for delivery mission.
01-Adir-06:240.256 (Info) CommerceUtil : [Heritage] New best deal for DELIVERY to Dream City profit 1267.2064200636312.
01-Adir-06:240.256 (Info) MissionManager : [Heritage] Anna Novák - Mission 'Delivery' score: Score:200 (base:126.721,settlementratio:1,citizen:6,extrovert:1)
01-Adir-06:240.256 (Info) Settlement [x7] : [System] Investigating mineral site at 22.4000 N 17.9999 W (1.0 km).
01-Adir-06:240.256 (Info) Exploration : [Heritage] A site has an Exploration Value of 73.41.
01-Adir-06:240.256 (Info) MissionManager : [Heritage] Anna Novák - Mission 'Mineral Exploration' score: Score:1.314 (base:1,settlementratio:1.2,minerals:3.65,leader:0.36,extrovert:1,goods:1.25,population:0.667)
01-Adir-06:240.256 (Severe) PersonTaskManager : [Heritage] Anna Novák - Trouble calling performTask(): 
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
	at com.mars_sim.core.equipment.EquipmentInventory.findNumEmptyContainersOfType(EquipmentInventory.java:499)
	at com.mars_sim.core.structure.Settlement.findNumEmptyContainersOfType(Settlement.java:3622)
	at com.mars_sim.core.goods.CommerceUtil.getAvailableContainerForResource(CommerceUtil.java:421)
	at com.mars_sim.core.goods.CommerceUtil.determineLoad(CommerceUtil.java:282)
	at com.mars_sim.core.goods.CommerceUtil.getDesiredBuyLoad(CommerceUtil.java:212)
	at com.mars_sim.core.goods.CommerceUtil.getPotentialDeal(CommerceUtil.java:112)
	at com.mars_sim.core.goods.CommerceUtil.getBestDeal(CommerceUtil.java:73)
	at com.mars_sim.core.goods.GoodsManager.getBestDeal(GoodsManager.java:768)
	at com.mars_sim.core.person.ai.mission.meta.TradeMeta.getSettlementProbability(TradeMeta.java:98)
	at com.mars_sim.core.person.ai.mission.meta.TradeMeta.getProbability(TradeMeta.java:71)
	at com.mars_sim.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:224)
	at com.mars_sim.core.person.ai.Mind.getNewMission(Mind.java:443)
	at com.mars_sim.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:137)
	at com.mars_sim.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:671)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:626)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:100)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:203)
	at com.mars_sim.core.person.ai.Mind.decideTask(Mind.java:175)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:118)
	at com.mars_sim.core.person.Person.timePassing(Person.java:856)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1183)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:904)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:900)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-06:240.256 (Info) MissionManager : [Heritage] Anna Novák - Mission 'Ice Prospecting' score: Score:0.64 (base:1,settlementratio:1,minerals:4,leader:0.36,extrovert:1,goods:1,population:0.444)
01-Adir-06:240.256 (Info) MissionManager : [Heritage] Anna Novák - Mission 'Regolith Prospecting' score: Score:0.892 (base:1,settlementratio:1.3,minerals:4.286,leader:0.36,extrovert:1,goods:1,population:0.444)
01-Adir-06:240.256 (Info) MissionManager : [Heritage] Anna Novák - Mission 'Delivery' score: Score:200 (base:126.721,settlementratio:1,citizen:6,extrovert:1)
01-Adir-06:240.256 (Info) MissionManager : [Heritage] Anna Novák - Mission 'Mineral Exploration' score: Score:1.314 (base:1,settlementratio:1.2,minerals:3.65,leader:0.36,extrovert:1,goods:1.25,population:0.667)

```

**Specifications (please complete the following information)**
- pre 3.7.0 build 8812

**Additional context**
- Should consider reducing the onset of too many missions in order to clear the clutter form stack trace.

**Comment by bevans2000** [comment]
Let's not make any changes for this yet. It needs some careful thought. This is only a problem when the 2 Settlement trading are assigned to different Threads.  I have some ideas what we can do but want to close down all the other changes we are doing first.

**Comment by mokun** [comment]
> This is only a problem when the 2 Settlement trading are assigned to different Threads.

Ok later.

**Comment by mokun** [comment]
Do you think some of these concurrency issues may have to with GenericContainer extending Equipment ?

What if we free GenericContainer from being an Equipment once and for all ?! 

In doing so, what will be impacted and what changes do we have to make ?

**Comment by mokun** [comment]
I have the following again: 

```
01-Adir-12:204.577 (Info) DeliveryMeta [x2] : [Schiaparelli Point] Drone 019 - Available for delivery mission.
01-Adir-12:204.577 (Severe) PersonTaskManager : [Schiaparelli Point] Ruby Cook - Trouble calling performTask(): 
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
	at com.mars_sim.core.equipment.EquipmentInventory.findNumEmptyContainersOfType(EquipmentInventory.java:499)
	at com.mars_sim.core.structure.Settlement.findNumEmptyContainersOfType(Settlement.java:3716)
	at com.mars_sim.core.goods.CommerceUtil.getAvailableContainerForResource(CommerceUtil.java:426)
	at com.mars_sim.core.goods.CommerceUtil.determineLoad(CommerceUtil.java:287)
	at com.mars_sim.core.goods.CommerceUtil.getDesiredBuyLoad(CommerceUtil.java:216)
	at com.mars_sim.core.goods.CommerceUtil.getPotentialDeal(CommerceUtil.java:114)
	at com.mars_sim.core.goods.CommerceUtil.getBestDeal(CommerceUtil.java:73)
	at com.mars_sim.core.goods.GoodsManager.getBestDeal(GoodsManager.java:768)
	at com.mars_sim.core.person.ai.mission.meta.DeliveryMeta.getSettlementProbability(DeliveryMeta.java:105)
	at com.mars_sim.core.person.ai.mission.meta.DeliveryMeta.getProbability(DeliveryMeta.java:69)
	at com.mars_sim.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:244)
	at com.mars_sim.core.person.ai.Mind.getNewMission(Mind.java:450)
	at com.mars_sim.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:137)
	at com.mars_sim.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:688)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:643)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:99)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:203)
	at com.mars_sim.core.person.ai.Mind.decideTask(Mind.java:175)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:118)
	at com.mars_sim.core.person.Person.timePassing(Person.java:859)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1232)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:1006)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:900)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-12:204.577 (Info) CommerceUtil : [Schiaparelli Point] New best deal for a delivery mission to Heritage: Profit -1539.7.

```

**Comment by bevans2000** [comment]
Did you have a Trade or ďelivery operation going? I have an idea on this. We create a temporary ResourceHolder when unloading/loading at a remote Settlement and use this as a transition object. We can create and load it in one Thread and pass it to the other Thread in the other Thread. Needs some thought but would work.
Would add a single pulse delay the deliver reloading task

**Comment by mokun** [comment]
It's too late to go back to see if there's a delivery or trade going on that it accessing this threas that is running DeliveryMeta. I've exited the sim.

**Comment by bevans2000** [comment]
Same problem as #1118

**Comment by bevans2000** [comment]
To fix this we need to address #1197  at the same time. The key concept is that some Unit can be controlled by different Settlements and that can be captured as part of the new Unit Hierarchy. 
@mokun  so we can push both into 3.8 or 3.9 but they should be done together. It's pretty clear in my mind how do solve this but it needs time and effort. At the moment I am looking at smaller tasks due to lack of time.

**Comment by mokun** [comment]
> We create a temporary ResourceHolder when unloading/loading at a remote Settlement and use this as a transition object. We can create and load it in one Thread and pass it to the other Thread in the other Thread. Needs some thought but would work.

So for it to work, where will this *transition object* be located at what thread ? 

Let's say we have 2 settlements, S1 and S2. S1 runs on the thread T1. S2 on T2. 

A few settlers from S1 travelled to S2 on a trading mission.

Does this *transition object* reside on S2 ? or on a new temporary thread T3 that you will create ?

**Comment by bevans2000** [comment]
The correct solution to thus and #1118 is to transfer control of the Units to the visiting Settlement when they arrive there. Then when Units interact they are still in the same Thread. This removes the need to specialise every interaction because the golden rule of Units being in the same Thread is maintained.
This is a job for 3.9.0

**Comment by mokun** [comment]
Do you think we could intentionally put the two nearby settlement together in one thread to partially avoid concurrent issues ? 

If there's no way to do it at startup, we could do it afterward.

**Comment by bevans2000** [comment]
No because it doesn't solve the problem. I have an idea for a good solution but will wait until the next release

**Comment by mokun** [comment]
@bevans2000 

Do you run into this lately ?

Wonder if we can now write a unit test to test the way two settlements would trade or make delivery to see if CommerceUtil would trip up any ConcurrentModificationException.

**Comment by bevans2000** [comment]
No I've not seen this have a good idea of the problem. My guess is there is something in the  UI. Or you have a Tarde going on and a different thread is changing the inventory

**Comment by mokun** [comment]
I just ran into a CME due to CommerceUtil when calling EquipmentInventory's findContainer()

But I'll fix the mission.builder.notEnoughMembers.

```
01-Adir-09:648.475(Info) DeliveryMeta : [Arcadia] D-Drone 005 - Available for delivery mission.
01-Adir-09:648.475(Info) CommerceUtil : Arcadia - No deal for a delivery mission.
01-Adir-09:648.475(Info) Mining : Arcadia - 24.3458 N 29.6239 W has a Mining Value of 3000.0.
01-Adir-09:648.475(Info) AbstractMission : [Arcadia] Lara Schmitz - Began organizing Mining 9-4, members 0
01-Adir-09:648.475(Warning) AbstractVehicleMission : [Arcadia] LUV 005 - Aready assigned to a Mission when assigning Mining 9-4.
01-Adir-09:648.475(Info) AbstractVehicleMission : [Arcadia] Lara Schmitz - Assessing Mining 9-4 using al-Mirrikh.
01-Adir-09:648.715(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:648.715(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:648.715(Severe) TemporalThreadExecutor : New Dubai: Problem with Pulse
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1606)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1629)
	at com.mars_sim.core.equipment.EquipmentInventory.findContainer(EquipmentInventory.java:547)
	at com.mars_sim.core.structure.Settlement.findContainer(Settlement.java:3313)
	at com.mars_sim.core.goods.CommerceUtil.getAvailableContainerForResource(CommerceUtil.java:408)
	at com.mars_sim.core.goods.CommerceUtil.determineLoad(CommerceUtil.java:267)
	at com.mars_sim.core.goods.CommerceUtil.getDesiredBuyLoad(CommerceUtil.java:196)
	at com.mars_sim.core.goods.CommerceUtil.getPotentialDeal(CommerceUtil.java:105)
	at com.mars_sim.core.goods.CommerceUtil.getBestDeal(CommerceUtil.java:64)
	at com.mars_sim.core.goods.GoodsManager.getBestDeal(GoodsManager.java:957)
	at com.mars_sim.core.person.ai.mission.meta.DeliveryMeta.getSettlementProbability(DeliveryMeta.java:133)
	at com.mars_sim.core.person.ai.mission.meta.DeliveryMeta.getProbability(DeliveryMeta.java:98)
	at com.mars_sim.core.mission.MissionControl.scoreMission(MissionControl.java:350)
	at com.mars_sim.core.mission.MissionControl.lambda$calculateMissionProbabilities$0(MissionControl.java:314)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:635)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:652)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:663)
	at com.mars_sim.core.mission.MissionControl.calculateMissionProbabilities(MissionControl.java:316)
	at com.mars_sim.core.mission.MissionControl.getNewMission(MissionControl.java:259)
	at com.mars_sim.core.person.ai.Mind.startNewMission(Mind.java:431)
	at com.mars_sim.core.mission.task.PlanMission.selectingPhase(PlanMission.java:153)
	at com.mars_sim.core.mission.task.PlanMission.performMappedPhase(PlanMission.java:107)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:653)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:613)
	at com.mars_sim.core.person.ai.task.util.TaskManager.executeTask(TaskManager.java:501)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:196)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:176)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:107)
	at com.mars_sim.core.person.Person.timePassing(Person.java:814)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1101)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:977)
	at com.mars_sim.core.unit.TemporalThreadExecutor$TemporalRunnable.run(TemporalThreadExecutor.java:81)
	at java.base/java.lang.Thread.run(Thread.java:1516)

01-Adir-09:648.956(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:648.956(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:648.956(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:648.956(Warning) Unit : Mona Abbas expected pulse #30879 but received #30880.
01-Adir-09:648.956(Warning) Unit : Baynunah expected pulse #30879 but received #30880.
01-Adir-09:648.956(Warning) Unit : Jumeirah expected pulse #30879 but received #30880.
01-Adir-09:648.956(Warning) Unit : D-Drone 036 expected pulse #30879 but received #30880.
01-Adir-09:648.956(Warning) Unit : LUV 047 expected pulse #30879 but received #30880.
01-Adir-09:648.956(Warning) Unit : RepairBot 049 expected pulse #30879 but received #30880.
01-Adir-09:648.956(Warning) Unit : GardenBot 040 expected pulse #30879 but received #30880.
01-Adir-09:648.956(Warning) Unit : MedicBot 021 expected pulse #30879 but received #30880.
01-Adir-09:648.956(Warning) Unit : MakerBot 039 expected pulse #30879 but received #30880.
01-Adir-09:649.198(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.198(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.198(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.441(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.441(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.441(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.686(Warning) MicroInventory [x82] : Halley - Attempting to retrieve 20.0 kg Carbon dioxide from specific amount resource storage but lacking 18.19 kg.
01-Adir-09:649.686(Warning) MicroInventory [x82] : Halley - Attempting to retrieve 18.19 kg Carbon dioxide from stock storage but lacking 18.19 kg.
01-Adir-09:649.686(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.686(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.686(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.931(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.931(Severe) Msg : !! mission.builder.notEnoughMembers ??
01-Adir-09:649.931(Severe) Msg : !! mission.builder.notEnoughMembers 
```

**Comment by bevans2000** [comment]
The commerce until is a problem class as it looks at the inside of many Settlements. We need each to creates it's own shopping list itself and then publish 8t a global market place. The Settlements can just look at what others want instead of trying to calculate each timel
