### ISSUE TITLE
java.lang.IllegalStateException: The office space is full.

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#111]
```
2018-11-06T05:26:05.9 (Warning) Mind : Barry Evans could not get new action
java.lang.IllegalStateException: The office space is full.
        at org.mars_sim.msp.core.structure.building.function.Administration.addstaff(Administration.java:170)
        at org.mars_sim.msp.core.person.ai.task.ReviewMissionPlan.<init>(ReviewMissionPlan.java:94)
        at org.mars_sim.msp.core.person.ai.task.meta.ReviewMissionPlanMeta.constructInstance(ReviewMissionPlanMeta.java:50)
        at org.mars_sim.msp.core.person.ai.task.TaskManager.getNewTask(TaskManager.java:575)
        at org.mars_sim.msp.core.person.ai.Mind.getNewAction(Mind.java:435)
        at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:218)
        at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:197)
        at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:144)
        at org.mars_sim.msp.core.person.Person.timePassing(Person.java:945)
        at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:1977)
        at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1265)
        at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.java:832)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

```
Package: openjdk-11-jre-headless
Version: 11.0.1+13-2
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages openjdk-11-jre-headless depends on:
ii  ca-certificates-java  20180516
ii  java-common           0.70
ii  libasound2            1.1.7-1
ii  libc6                 2.27-8
ii  libcups2              2.2.8-5
ii  libfontconfig1        2.13.1-1
ii  libfreetype6          2.8.1-2
ii  libgcc1               1:8.2.0-9
ii  libjpeg62-turbo       1:1.5.2-2+b1
ii  liblcms2-2            2.9-3
ii  libnss3               2:3.39-1
ii  libpcsclite1          1.8.24-1
ii  libstdc++6            8.2.0-9
ii  libx11-6              2:1.6.7-1
ii  libxext6              2:1.3.3-1+b2
ii  libxi6                2:1.7.9-1
ii  libxrender1           1:0.9.10-1
ii  libxtst6              2:1.2.3-1
ii  util-linux            2.32.1-0.1
ii  zlib1g                1:1.2.11.dfsg-1

openjdk-11-jre-headless recommends no packages.

Versions of packages openjdk-11-jre-headless suggests:
ii  fonts-dejavu-extra    2.37-1
pn  fonts-indic           <none>
ii  fonts-ipafont-gothic  00303-18
ii  fonts-ipafont-mincho  00303-18
ii  fonts-wqy-microhei    0.2.0-beta-3
ii  libnss-mdns           0.14.1-1

-- no debconf information
```

**Comment by mokun** [comment]
Fixed. Closing this.
