### ISSUE TITLE
Null Shipment when negotiating trade in CommerceUtil, unable to load/unload in foreign settlement

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1118]
**Describe the bug**
- On Sol 6, When reloading from a saved sim, it stated that returnLoad was NPE when calling CommerceUtil's negotiateDeal() between the two settlements, namely, *Dream City* and *Heritage*.

**Expected and unexpected behavior**
- It happens after the trade negotiation has been completed.

**Discuss any potential problems you have and have not ruled out**
- Does this NPE have to do with the situation when reloading from saved sim ?

**Java classes involved**
- `CommerceUtil`, `NegotiateTrade`

**Screenshots**
- Both rovers drove 964 km from *Heritage* to *Dream City*. 
- Event though they both departed on sol 5 and arrived on sol 6, their start time and arrival time were different.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/c389d911-ec96-4f67-8901-f26d6ec25f19)

- Realistically speaking, the path between the two settlements shouldn't be a straight shot but a curve on a sphere.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/066183ad-f242-4ef9-b614-5f464c50c567)

- None of the 6 settlers in *Dream City* are aware of the arrival of the 2 trading missions.
- They all stay indoors and are NOT helping to unload cargoes
![image](https://github.com/mars-sim/mars-sim/assets/1168584/37efe9d8-5d24-477b-a32c-ffe62580e809)

- The 2 sleepy head settlers on Rover *Ridge Runner* from Heritage are still in the vehicle.
- The 2 sleepy head settlers on Rover *Solitude* from Heritage are still in the vehicle.
- These 2 rovers are not being displayed on the Settlement Map of *Dream City*, since Settlement's getParkedVehicles() includes only vehicles from the ownedVehicles set. 
![image](https://github.com/mars-sim/mars-sim/assets/1168584/79433151-eff9-423a-b1cc-c74b560ba79f)

- Can't find the 2 rovers from Heritage : 
![image](https://github.com/mars-sim/mars-sim/assets/1168584/40a776fa-5064-49a8-91ae-407b65d1c2fb)

- Nothing has been unloaded yet : 
![image](https://github.com/mars-sim/mars-sim/assets/1168584/aa072b29-e9f4-40ff-8a8a-34477d64da5a)

- Both settlers are healthy and have little fatigue. Why are they sleeping and not unloading cargo ?
![image](https://github.com/mars-sim/mars-sim/assets/1168584/44cf63d2-63bf-4b42-a5e5-58e3f2f0895b)

- Why are the sleeping probability score 1000 for both of them ?
- Why are the base score so high (at 6000) ?
![image](https://github.com/mars-sim/mars-sim/assets/1168584/2b74c18e-9a41-4a02-b43f-9dbad8af8ba6)

- It's totally wrong to say that these 4 individuals are still on EVA Airlock 1 or Residential Quarters 1 in Heritage.
- We should add back the Settlement column to ascertain what base the settlers are in. 
- Other than the trading mission., we should leave provision for them go to other settlement in other future missions such as Diplomatic Exchange missions, etc. 
![image](https://github.com/mars-sim/mars-sim/assets/1168584/c39c17bd-34cf-4ff0-999a-6d338fc536eb)

**Stacktrace**
```
01-Adir-06:720.499 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:720.499 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 10718.9
01-Adir-06:720.499 (Severe) PersonTaskManager : [Dream City] Louis Dubois - Trouble calling performTask(): 
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.goods.Shipment.getCostValue()" because "returnLoad" is null
	at com.mars_sim.core.goods.CommerceUtil.negotiateDeal(CommerceUtil.java:528)
	at com.mars_sim.core.person.ai.task.NegotiateTrade.negotiatingPhase(NegotiateTrade.java:112)
	at com.mars_sim.core.person.ai.task.NegotiateTrade.performMappedPhase(NegotiateTrade.java:218)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:687)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:648)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:101)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:203)
	at com.mars_sim.core.person.ai.Mind.decideTask(Mind.java:175)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:118)
	at com.mars_sim.core.person.Person.timePassing(Person.java:850)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1173)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:904)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:900)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-06:720.499 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:720.499 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 21437.8
01-Adir-06:722.484 (Info) Sleep : [Starcity] Kathleen Torres - Sleep adjusted for shift starts at 730. Duration: 7
01-Adir-06:722.484 (Info) CookMeal : [New Pompeii] Kabir Narayan - Finished cooking Veggie Burger.
01-Adir-06:722.484 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:722.484 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 32156.7
01-Adir-06:722.484 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:722.484 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 42875.6
01-Adir-06:722.484 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:722.484 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 53594.5
01-Adir-06:724.368 (Info) Crop : [Schiaparelli Point - Inflatable Greenhouse 3] Celery - Now in PLANTING.
01-Adir-06:724.368 (Info) ReviewMissionPlan : [Zvezda] Timofei Afanasyev - Grading Delivery #234 Plan - Rels: 9, Site: 0.0, Review: 2; Subtotal: 11.0
01-Adir-06:724.368 (Info) ReviewMissionPlan : [Zvezda] Timofei Afanasyev - Done reviewing Fyodor Egorov's Delivery #234 mission plan.
01-Adir-06:724.368 (Info) OperateVehicle [x24] : [17.3924 N 23.2615 W] Solitude - Case III: Proceeding to Dream City. dist2Dest: 546.955 km  distanceToCover: 3.967 km  uKPH: 62.661 kph  vKPHProposed: 62.661 kph  hrsTime: 0.018 hrs  Time: 63.307 secs  maxAccel: 1.86 m/s2  skillMod: 1.0  lightMod: 3.84  terrainMod: 1.0  idealSpeedMS: 48.354 m/s  topSpeedKPH: 46.276 kph  idealSpeedKPH: 174.075 kph  nextSpeedKPH: 46.276 kph  
01-Adir-06:724.368 (Info) Converse : [Schiaparelli Point] Lena LaGranda - Chatting with Ronald Collins in Same Settlement.
01-Adir-06:724.368 (Info) AbstractMission [x2] : [5.7524 N 163.8884 E - Shi-Ki] Shota Okamoto - Assigned with 'Collecting Resources' to replace 'Analyzing Map Data'.
01-Adir-06:724.368 (Info) AbstractMission : [39.9261 N 100.0534 W - Chongjin] Sua Pak - Assigned with 'Collecting Resources' to replace 'Eating'.
01-Adir-06:724.368 (Info) Converse : [Schiaparelli Point] Ronald Collins - Responding to Lena LaGranda.
01-Adir-06:724.368 (Info) EVAOperation : [5.7524 N 163.8884 E] Kaito Inoue - EVA Collecting Resources aborted: Samples collected exceeded set limits.
01-Adir-06:724.368 (Info) EVAOperation : [0.2540 S 0.2052 E] Deborah Cook - EVA Collecting Resources aborted: No container available.
01-Adir-06:724.368 (Info) AbstractMission [x10] : [Catarina] Francisco Alves - Assigned with 'Loading Vehicle by EVA' to replace 'Reading'.
01-Adir-06:724.368 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:724.368 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 64313.5
01-Adir-06:724.368 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:724.368 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 75032.4
01-Adir-06:724.368 (Info) ReviewMissionPlan : [New Pompeii] Rithvik Raje - Grading Meteorology Field Study #238 Plan - Rels: 9, Site: 0.0, Review: 2; Subtotal: 11.0
01-Adir-06:724.368 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:724.368 (Info) ReviewMissionPlan : [New Pompeii] Rithvik Raje - Done reviewing Rithvik Chauhan's Meteorology Field Study #238 mission plan.
01-Adir-06:724.368 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 85751.3
01-Adir-06:724.368 (Info) AbstractMission : [Dream City] Oscar Thompson - Responsible for 'Trade Negotiating' Mission Phase.
01-Adir-06:726.149 (Info) ExitAirlock : [39.9261 N 100.0534 W - Chongjin] Sua Pak - Airlock is not in egress mode. Current task: Collecting Resources.
01-Adir-06:726.149 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:726.149 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 96470.3
01-Adir-06:726.149 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:726.149 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 107189.3
01-Adir-06:726.149 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:726.149 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 117908.3
01-Adir-06:726.149 (Info) TendGreenhouse : [Schiaparelli Point - Inflatable Greenhouse 2] Keith Ramirez - Looking into growing tissue cultures.
01-Adir-06:726.149 (Info) Farming : [Schiaparelli Point] Inflatable Greenhouse 2 - selectedTissueName: Cilantro Tissue
01-Adir-06:726.149 (Info) TendGreenhouse : [Schiaparelli Point - Inflatable Greenhouse 2] Keith Ramirez - Sampled Cilantro Tissue and added to incubator for growing tissues.
01-Adir-06:726.149 (Info) Crop : [Schiaparelli Point - Large Greenhouse 1] Spring Onion - Harvested a total of 109.79 kg.
01-Adir-06:726.149 (Info) Crop : [Schiaparelli Point - Large Greenhouse 1] Spring Onion - Closed out the final harvest.
01-Adir-06:727.842 (Info) ExitAirlock : [5.7524 N 163.8884 E - Shi-Ki] Shota Okamoto - Tried to step through inner door. Not fit enough.
01-Adir-06:727.842 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:727.842 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 128626.1
01-Adir-06:727.842 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:727.842 (Info) Converse : [Hong Tian] Tu Guo - Chatting with Enlai Pan in Same Settlement.
01-Adir-06:727.842 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 139344.0
01-Adir-06:727.842 (Info) EVAOperation : [19.8000 N 50.9999 W] Jin Mao - EVA Collect Minerals aborted: No more minerals to mine.
01-Adir-06:729.492 (Info) TendGreenhouse : [Kyocera - Inflatable Greenhouse 1] Hinata Hasegawa - Inspecting contamination control.
01-Adir-06:729.492 (Info) NegotiateTrade : [Dream City] Louis Dubois - Trade negotiation completed. Buyer: Heritage. Seller: Dream City. Trade Mod: 1.3
01-Adir-06:729.492 (Info) CreditManager : [Heritage] Account ledger updated for Dream City  Credit: 150061.8
01-Adir-06:729.492 (Severe) PersonTaskManager [x13] : [Dream City] Louis Dubois - Trouble calling performTask(): 
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.goods.Shipment.getCostValue()" because "returnLoad" is null
	at com.mars_sim.core.goods.CommerceUtil.negotiateDeal(CommerceUtil.java:528)
	at com.mars_sim.core.person.ai.task.NegotiateTrade.negotiatingPhase(NegotiateTrade.java:112)
	at com.mars_sim.core.person.ai.task.NegotiateTrade.performMappedPhase(NegotiateTrade.java:218)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:687)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:648)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:101)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:203)
	at com.mars_sim.core.person.ai.Mind.decideTask(Mind.java:175)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:118)
	at com.mars_sim.core.person.Person.timePassing(Person.java:850)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1173)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:904)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:900)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Specifications**
- pre 3.7.0 build 8854

**Additional context**
- Blue Origin's *Dream City* has 8 settlers by default.
```
		<settlement name="Dream City" template="Phase 2-US" persons="8" robots="4" sponsor="BO">
			<location longitude="29.75 W" latitude="10.63 N" />
		</settlement>
```

**Comment by mokun** [comment]
@bevans2000
I just added a few more screenshots above to cover all the issues I've encountered.

**Comment by bevans2000** [comment]
Nice one

**Comment by mokun** [comment]
@bevans2000 

Can we create a test scenario in which two settlements are very close to each other and auto-launch a trading mission to see what else is still not well considered once the foreign settlers arrive at a destination settlement ?

The guest beds will need to be ready for them to rest. They should be on the road after recuperating.

What else are they allowed to do there ?

**Comment by mokun** [comment]
@bevans2000 

Q1: Can we at least test to see if the Sleep task works now in foreign settlement ? 

Q2: What does it take to prevent them from performing other non-essential tasks (such as digging regolith) in a foreign settlement ?

**Comment by bevans2000** [comment]
I want to solve the problem of executing Tasks in a Unit test. Sleep would be a good one lets use this issue to create that.

Stopping the complex Tasks when away should work already. Settlement tasks can be filtered to only Workers in their home Settlement.

**Comment by mokun** [comment]
> Stopping the complex Tasks when away should work already. Settlement tasks can be filtered to only Workers in their home Settlement.

That's great !

But what tasks can still be performed in foreign settlement ?

Can we instead have an UI for players or commanders to choose what tasks are allowed or disallowed ?

**Comment by mokun** [comment]
> But what tasks can still be performed in foreign settlement ?

Let's pay attention to what tasks will be allowed to performed in a foreign settlement.

What "rules" should they follow ?

**Comment by mokun** [comment]
What if we simply create the potential goods list ((same as the loading and unloading list) in UnitManager's main thread ? 

Can the parent thread be sync up if read by child threads ? 

I was reading Java 22's new features of Scoped value in [here](https://www.geeksforgeeks.org/scoped-values-in-java/).

**Comment by bevans2000** [comment]
I found this problem and it's actually not to do with the thread problem. If I remember correctly, it's about the transient of the goods lists. When a Simulation is restored it is null.
I think I might know how to solve this one

**Comment by mokun** [comment]
Guess this thread has more than one bug to resolve. 

So have you already added some unit tests to see if a trader upon arriving at a foreign settlement is able to help out unloading cargoes and loading negotiated resources back to the rover ?

**Comment by mokun** [comment]
> I want to solve the problem of executing Tasks in a Unit test. Sleep would be a good one lets use this issue to create that.

Now that we have closed this thread, do we have a unit test for testing the execution of tasks in a foreign settlement ? 

> Stopping the complex Tasks when away should work already. Settlement tasks can be filtered to only Workers in their home Settlement.

Yes. Can we come up with a label called "Guest" in order to distinguish a person's work status in a foreign settlement ? 

This will go a long way. 

I imagine a future tourist to Mars could also be treated like a guest.

A guest can do volunteer to help out an operation if he has fulfilled whatever his primary objective is (what would that be ? )
