### ISSUE TITLE
Null lab among various tasks

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1145]
**Describe the bug**
- A NPE is encountered when walking to an Astronomy Observatory.
- Somehow the lab instance is null when calling addPersonToLab() in `PerformLaboratoryResearch`
** POST EDIT **
- Null lab is not limited to `PerformLaboratoryResearch`. It also happens with `StudyFieldSamples` and  `PerformLaboratoryExperiment`

**Expected and unexpected behavior**
- Lab should be non-null

**Java classes involved**
- `PerformLaboratoryRsearch`

**Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/fa9dcf70-999c-4b81-b97e-87bd65fb39b8)

**Stacktrace**
```
01-Adir-07:477.476 (Warning) Walk : [Heritage] Carla Borges - Could not exit EVA Airlock 2.
01-Adir-07:477.476 (Severe) EVAOperation : [Heritage] Carla Borges - Cannot walk to outside site.
01-Adir-07:478.440 (Info) Crop : [Heritage - Central Hub A 1] Wheat - Now in HARVESTING.
01-Adir-07:479.400 (Info) EnterAirlock : [Arcadia - EVA Airlock 1] Anna Ferrari - Chamber already depressurized for entry in EVA Airlock 1.
01-Adir-07:479.400 (Warning) Walk : [Hong Tian] Xiaoguang Hu - Could not exit EVA Airlock 1.
01-Adir-07:479.400 (Severe) EVAOperation : [Hong Tian] Xiaoguang Hu - Cannot walk to outside site.
01-Adir-07:479.400 (Warning) Walk : [Heritage] Scott Davis - Could not exit EVA Airlock 2.
01-Adir-07:479.400 (Severe) EVAOperation : [Heritage] Scott Davis - Cannot walk to outside site.
...
01-Adir-07:481.309 (Info) Task : [Heritage] Carla Borges - Ended the task of walking to Astronomy Observatory 1.
01-Adir-07:481.309 (Severe) Research : [Heritage] Astronomy Observatory 1 - Lab has no researchers to remove.
01-Adir-07:481.309 (Severe) PerformLaboratoryResearch : [Heritage] Carla Borges - Couldn't be added to a lab
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.structure.Lab.addResearcher()" because "this.lab" is null
	at com.mars_sim.core.person.ai.task.PerformLaboratoryResearch.addPersonToLab(PerformLaboratoryResearch.java:356)
	at com.mars_sim.core.person.ai.task.PerformLaboratoryResearch.<init>(PerformLaboratoryResearch.java:96)
	at com.mars_sim.core.person.ai.task.meta.PerformLaboratoryResearchMeta.constructInstance(PerformLaboratoryResearchMeta.java:55)
	at com.mars_sim.core.person.ai.task.util.BasicTaskJob.createTask(BasicTaskJob.java:49)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.createTask(PersonTaskManager.java:263)
	at com.mars_sim.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:469)
	at com.mars_sim.core.person.ai.Mind.lookForATask(Mind.java:291)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:248)
	at com.mars_sim.core.person.ai.Mind.decideTask(Mind.java:175)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:118)
	at com.mars_sim.core.person.Person.timePassing(Person.java:851)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1232)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:1006)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:900)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-07:482.257 (Warning) RoverMission : [New Pompeii] Viraj Srivastava - Unable to start walking to Vayu.
01-Adir-07:482.257 (Info) EnterAirlock : [0.1400 N 0.1801 E - Perseverance II] Jason Gomez - Chamber already depressurized for entry in Perseverance II.
01-Adir-07:482.257 (Info) EnterAirlock : [0.1400 N 0.1801 E - Perseverance II] Fred Morris - Chamber already depressurized for entry in Perseverance II.
01-Adir-07:483.202 (Info) Mining : [New Seoul] 40.0001 N 99.9999 W has a Mining Value of 30.16.

```

**Specifications**
- pre 3.7.0 build 8974

**Additional context**
- May have to do with the recent adoption of SettlementTask for `PerformLaboratoryResearchMeta`.
- Or does it have to do with the recent activity spot change ?

**Comment by bevans2000** [comment]
Does this happen all the time?

**Comment by bevans2000** [comment]
I have an idea about this so I will look into it

**Comment by mokun** [comment]
> Does this happen all the time?

I've seen many times already. And it's been there for a while. At least many months back.

It occurs usually after sol 6 or 7.

```
Optimize picking a lab 

08.13.2023	

- change: ensure at least one lab is picked in 
          getSettlementLab() in PerformLaboratoryResearch
```

**Comment by bevans2000** [comment]
Ok. I considered converting this to a SettlementMetaTask pattern which would avoid the problem by preselecting the lab. I will have a look into this

**Comment by mokun** [comment]
On sol 27, I also encountered a null on `StudyFieldSamples` : 

```
01-Adir-27:491.466 (Severe) PersonTaskManager : [Heritage] Maria Ilves - Trouble calling performTask(): 
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.structure.Lab.getTechnologyLevel()" because "this.lab" is null
	at com.mars_sim.core.person.ai.task.StudyFieldSamples.getEffectiveResearchTime(StudyFieldSamples.java:375)
	at com.mars_sim.core.person.ai.task.StudyFieldSamples.studyingSamplesPhase(StudyFieldSamples.java:472)
	at com.mars_sim.core.person.ai.task.StudyFieldSamples.performMappedPhase(StudyFieldSamples.java:398)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:688)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:643)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:99)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:203)
	at com.mars_sim.core.person.ai.Mind.decideTask(Mind.java:181)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:118)
	at com.mars_sim.core.person.Person.timePassing(Person.java:859)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1232)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:1006)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:900)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mokun** [comment]
Also with `PerformLaboratoryExperiment` on sol 28 :  

```
01-Adir-28:546.857 (Severe) PerformLaboratoryExperiment : [Schiaparelli Point] Sara Bailey - Couldn't be added to a lab
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.structure.Lab.addResearcher()" because "this.lab" is null
	at com.mars_sim.core.person.ai.task.PerformLaboratoryExperiment.addPersonToLab(PerformLaboratoryExperiment.java:373)
	at com.mars_sim.core.person.ai.task.PerformLaboratoryExperiment.<init>(PerformLaboratoryExperiment.java:102)
	at com.mars_sim.core.person.ai.task.meta.PerformLaboratoryExperimentMeta.constructInstance(PerformLaboratoryExperimentMeta.java:53)
	at com.mars_sim.core.person.ai.task.util.BasicTaskJob.createTask(BasicTaskJob.java:49)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.createTask(PersonTaskManager.java:263)
	at com.mars_sim.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:469)
	at com.mars_sim.core.person.ai.Mind.lookForATask(Mind.java:291)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:248)
	at com.mars_sim.core.person.ai.Mind.decideTask(Mind.java:175)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:118)
	at com.mars_sim.core.person.Person.timePassing(Person.java:859)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1232)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:1006)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:900)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by bevans2000** [comment]
TH e problem is the Person cannot walk to the selected Lab which then correctly ends the Task. Clearing down the Task releases the Lab as it should do but the calling method does not check that the Walk request was successful. I'll fix it.
The PeformLabExperiment & PerformLabResearch are virtually the same; looks lie one has been copied from the other (very bad). I will consolidate into a new based class for using a Lab.

**Comment by bevans2000** [comment]
I can see no difference between the Experiment & Research Tasks. The only difference is the former filters the ScienceTypes of study by ExperimentalScience. But this is a waste of time because the actual activity is the same in both case. And as the PerformResearch selects any ScienceType everything can be done by the former.
Hence we can remove the Experimental version as it offers nothing unique.
