### ISSUE TITLE
Concurrency in ScientificStudyManager getAllStudies

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1149]
**Describe the bug**
- At the start of a sim or when first loading from a saved sim, ConcurrentModificationException is encountered when starting ObserveAstronomicalObjectsMeta

**Expected and unexpected behavior**
- Should have no concurrency at the beginning

**Java classes involved**
- `ScientificStudyManager`, `ObserveAstronomicalObjectsMeta`

**Stacktrace**
```
01-Adir-01:000.017 (Info) LifeSupport : Overcrowding at EVA Airlock 1.
01-Adir-01:000.017 (Info) CollectResourcesMission : Analyzing sites for Ice Prospecting 1-001.  Total Score: 7.41.  Best Score: 2.53
01-Adir-01:000.017 (Info) CollectResourcesMission : [Arcadia] Voiture - Estimating amount of Ice per site: 666 kg.
01-Adir-01:000.017 (Info) LifeSupport : Overcrowding at Inflatable Greenhouse 2.
01-Adir-01:000.017 (Severe) UnitManager : Problem with pulse on Heritage: null
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1631)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.mars_sim.core.science.ScientificStudyManager.getAllStudies(ScientificStudyManager.java:202)
	at com.mars_sim.core.person.ai.task.meta.ObserveAstronomicalObjectsMeta.getAstroStudies(ObserveAstronomicalObjectsMeta.java:105)
	at com.mars_sim.core.person.ai.task.meta.ObserveAstronomicalObjectsMeta.getSettlementTasks(ObserveAstronomicalObjectsMeta.java:85)
	at com.mars_sim.core.person.ai.task.util.SettlementTaskManager.getTasks(SettlementTaskManager.java:99)
	at com.mars_sim.core.person.ai.task.util.SettlementTaskManager.getTasks(SettlementTaskManager.java:153)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:178)
	at com.mars_sim.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:458)
	at com.mars_sim.core.person.ai.Mind.lookForATask(Mind.java:291)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:248)
	at com.mars_sim.core.person.ai.Mind.decideTask(Mind.java:175)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:118)
	at com.mars_sim.core.person.Person.timePassing(Person.java:859)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1231)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:1005)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:900)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Specifications**
- pre 3.7.0 build 8895

**Additional context**
- `ObserveAstronomicalObjectsMeta` has just been converted to a SettlementTask recently

**Comment by bevans2000** [comment]
Surprised this has taken this long to appear as a problem. It's a known place where we have a single entity across all Settlements. I will solve this
