### ISSUE TITLE
EntityTableModel issue

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1167]
**Describe the bug**
- While viewing the Algae Pond BuildingPanelAlgae in the foreground with the Building tab open in Monitor Tool in the background, a *Meteorite Impact Damage* malfunction occurs and the following exception pops up in stack trace : 
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: column beyond range of TableModel
```

**Expected and unexpected behavior**
- *Meteorite Impact Damage* should not cause this exception
 
**Discuss any potential problems you have and have not ruled out**
- It's connected with how the AWT thread is used in `EntityTableModel`
```
    /**
     * Get the real value of this entity for a specific column. This implementation
     * may involve expensive calculations.
     */
    protected abstract Object getEntityValue(T entity, int column);

    private class TableCellUpdater implements Runnable {

        private int colIndex;
        private int rowIndex;

        public TableCellUpdater(int rowIndex, int colIndex) {
            this.rowIndex = rowIndex;
            this.colIndex = colIndex;
        }

        @Override
        public void run() {
            fireTableCellUpdated(rowIndex, colIndex);
        }
    }
```
- Line 275 refers to calling `fireTableCellUpdated(rowIndex, colIndex)`

See this stack trace line : 
```
at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:275)
```

**Java classes involved**
-`EntityTableModel`

*Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/458dd493-c719-4033-885d-d2e7b5d6167f)

**Stacktrace**
```
01-Adir-04:000.577 (Info) Building : [Hartmann Base] Research Hab 1 - A meteorite impact event was imminent.
01-Adir-04:000.577 (Info) Malfunction : [System] Meteorite Impact Damage - Incident #1. INSIDE repair triggered. Estimated work time: 153.9 millisols.
01-Adir-04:000.577 (Warning) Malfunction : Meteorite Impact Damage - Incident #1 - Repair requires work gloves x1.
Exception in thread "AWT-EventQueue-0" 01-Adir-04:000.577 (Warning) MalfunctionManager : [Hartmann Base] Research Hab 1 - Meteorite Impact Damage - Incident #1. Probable Cause: Acts of God. Caused by 'N/A'.
java.lang.IndexOutOfBoundsException: column beyond range of TableModel
	at java.desktop/javax.swing.DefaultRowSorter.checkColumn(DefaultRowSorter.java:1234)
	at java.desktop/javax.swing.DefaultRowSorter.rowsUpdated(DefaultRowSorter.java:925)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4326)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4180)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:275)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
01-Adir-04:000.577 (Info) Building : [Hartmann Base] Research Hab 1 - Meteorite Impact Damage - Incident #1 registered.
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: column beyond range of TableModel
	at java.desktop/javax.swing.DefaultRowSorter.checkColumn(DefaultRowSorter.java:1234)
	at java.desktop/javax.swing.DefaultRowSorter.rowsUpdated(DefaultRowSorter.java:925)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4326)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4180)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:275)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
01-Adir-04:000.577 (Info) Settlement : [Hartmann Base] On Sol 4, 21.0000 N 24.6000 W was added to be analyzed and explored.
01-Adir-04:000.577 (Info) Settlement : [Hartmann Base] Overall average # of improvement made on all mineral locations: 4.0
01-Adir-04:001.315 (Warning) MalfunctionManager : [Hartmann Base] Research Hab 1 - Oxygen flow restricted to 100.0 % capacity.
01-Adir-04:003.528 (Info) Task : [Hartmann Base] Jakub Novák - Already in my own bed.
```

**Specifications**
- pre 3.7.0 build 9054

**Comment by mokun** [comment]
@bevans2000 

Another one here.

```
01-Adir-07:000.580 (Config) MasterClock :  - - - - - - - - - - - - - - Sol 7 - - - - - - - - - - - - - - 
01-Adir-07:000.580 (Warning) Population : Colony: Yue De  Sponsor: CNSA  Country: China
01-Adir-07:000.580 (Info) Building : [Hartmann Base] Lounge 1 - A meteorite impact event was imminent.
01-Adir-07:000.580 (Info) Malfunction : [System] Meteorite Impact Damage - Incident #1. INSIDE repair triggered. Estimated work time: 279.9 millisols.
01-Adir-07:000.580 (Warning) Malfunction : Meteorite Impact Damage - Incident #1 - Repair requires valve x2.
01-Adir-07:000.580 (Warning) Malfunction : Meteorite Impact Damage - Incident #1 - Repair requires fiberglass cloth x2.
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: column beyond range of TableModel
	at java.desktop/javax.swing.DefaultRowSorter.checkColumn(DefaultRowSorter.java:1234)
	at java.desktop/javax.swing.DefaultRowSorter.rowsUpdated(DefaultRowSorter.java:925)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4326)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4180)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:281)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
01-Adir-07:000.580 (Warning) MalfunctionManager : [Hartmann Base] Lounge 1 - Meteorite Impact Damage - Incident #1. Probable Cause: Acts of God. Caused by 'N/A'.
01-Adir-07:000.580 (Warning) MalfunctionManager :                      Part Name : Valve
01-Adir-07:000.580 (Warning) MalfunctionManager :  (0). Cumulative # of Failures : 2
01-Adir-07:000.580 (Warning) MalfunctionManager :  (1).         Current # Failed : 2
01-Adir-07:000.580 (Warning) MalfunctionManager :  (2).              Sols in Use : 6.0
01-Adir-07:000.580 (Warning) MalfunctionManager :  (3).                     MTBF : 669.00 sols --> 509.25 sols
01-Adir-07:000.580 (Warning) MalfunctionManager :  (4).             Failure Rate : 0.001 % --> 0.002 %
01-Adir-07:000.580 (Warning) MalfunctionManager :  (5).      Percent Reliability : 48.065 % --> 43.328 %
01-Adir-07:000.580 (Warning) MalfunctionManager :  (6).       Repair Probability : 5.000 % --> 4.888 %
01-Adir-07:000.580 (Warning) MalfunctionManager :  (7).  Malfunction Probability : 0.000 % --> 0.000 %
01-Adir-07:000.580 (Warning) MalfunctionManager :                      Part Name : Fiberglass Cloth
01-Adir-07:000.580 (Warning) MalfunctionManager :  (0). Cumulative # of Failures : 2
01-Adir-07:000.580 (Warning) MalfunctionManager :  (1).         Current # Failed : 2
01-Adir-07:000.580 (Warning) MalfunctionManager :  (2).              Sols in Use : 6.0
01-Adir-07:000.580 (Warning) MalfunctionManager :  (3).                     MTBF : 669.00 sols --> 509.25 sols
01-Adir-07:000.580 (Warning) MalfunctionManager :  (4).             Failure Rate : 0.001 % --> 0.002 %
01-Adir-07:000.580 (Warning) MalfunctionManager :  (5).      Percent Reliability : 48.065 % --> 43.328 %
01-Adir-07:000.580 (Warning) MalfunctionManager :  (6).       Repair Probability : 12.927 % --> 12.709 %
01-Adir-07:000.580 (Warning) MalfunctionManager :  (7).  Malfunction Probability : 0.000 % --> 0.000 %
01-Adir-07:000.580 (Info) Building : [Hartmann Base] Lounge 1 - Meteorite Impact Damage - Incident #1 registered.
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: column beyond range of TableModel
	at java.desktop/javax.swing.DefaultRowSorter.checkColumn(DefaultRowSorter.java:1234)
	at java.desktop/javax.swing.DefaultRowSorter.rowsUpdated(DefaultRowSorter.java:925)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4326)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4180)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:281)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
01-Adir-07:000.580 (Info) Building : [Hartmann Base] Server Farm 1 - Meteorite Impact event observed but did not occur in the vicinity.
01-Adir-07:000.580 (Info) PhysicalCondition : [Hartmann Base] Felix Hofer - Suffered from Starvation.
01-Adir-07:000.580 (Info) Settlement : [Hartmann Base] On Sol 7, 25.7999 N 19.8000 W was added to be analyzed and explored.
01-Adir-07:000.580 (Info) Settlement : [Hartmann Base] Overall average # of improvement made on all mineral locations: 53.4
01-Adir-07:001.271 (Warning) MalfunctionManager : [Hartmann Base] Lounge 1 - Oxygen flow restricted to 100.0 % capacity.
01-Adir-07:014.415 (Info) PhysicalCondition : [Hartmann Base] Felix Hofer - Suffered from Starvation.
```

**Comment by bevans2000** [comment]
Which tab is open when you see this?

**Comment by mokun** [comment]
> Which tab is open when you see this?

The Building tab.

**Comment by bevans2000** [comment]
I think i know what the problem is

**Comment by mokun** [comment]
> I think i know what the problem is 

So what have you discovered ?

**Comment by mokun** [comment]
I still had another `ArrayIndexOutOfBoundsException` after the commit.

It happened when I click on another settlement in the combobox while the Monitor Tool's Person tab was open in the background.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/0be6a6be-d967-4c55-95ae-bfc959ff2dd7)

Immediately, the following Swing thread issue is reported. 

Note that somehow it has to do with `(DefaultRowSorter.java:496)`

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(DefaultRowSorter.java:496)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2664)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4237)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4178)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:281)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 4
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(DefaultRowSorter.java:496)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2664)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4237)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4178)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:281)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 14 out of bounds for length 4
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(DefaultRowSorter.java:496)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2664)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4237)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4178)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:281)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 4
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(DefaultRowSorter.java:496)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2664)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4237)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4178)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:281)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 4
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(DefaultRowSorter.java:496)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2664)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4237)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4178)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:281)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 12 out of bounds for length 4
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(DefaultRowSorter.java:496)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2664)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4237)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4178)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:281)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 4
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(DefaultRowSorter.java:496)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2664)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4237)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4178)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:281)
	at com.mars_sim.ui.swing.tool.monitor.EntityTableModel$TableCellUpdater.run(EntityTableModel.java:281)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by bevans2000** [comment]
It's not actually the same problem because this is the rows out of synch. It is due to the Unit thread updating a cell which triggers a resort when the fill the model contents over. The root cause is the JTable design is not thread safe and not suited for updates outside of the Swing dispatcher.
