### ISSUE TITLE
Improve Medical based Tasks

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1315]
**Is your feature request related to a problem? Please describe.**
The various Medical tasks have a lot of duplicate code that is repeated. 
The interaction between Request Medical Treatment & TreatMedicalPatient is also unclear.
In a ```MedicalCare``` the beds locals are not used as Activity Spots neither. Patient & Doctor have to occupy the same slot.

**Describe the goal(s) you have in mind**
Reduce the amount of duplicate code and improve the clarity by adding UnitTests
Also adopt the improvements to Tasks outlined in #1285
Adopt ActivitySpots for bed as per #1180 

**Describe the solution you desire to see**
Develop a common Medical helper class that can hold the common patterns of identifying MedicalAid, HealthProblem etc.
These helper methods can be utilised in the corresponding Meta Class as well.
Get the Beds to be used as ActivitySpot for patients and improve the UI panel to show who is in a Bed and waiting for Treatment.

There are 2 operation covered by the 3 inter-related Health tasks:
- Locate a MdeicalAid to cure a HealthProblem - Done by Self Treat & Request Medical Assistance
- Treat a HealthProblem - Done by Self Treat & Treat Medical Patient

This needs to be reflected in the code base by 2 distinct block of code

**Comment by mokun** [comment]
> Get the Beds to be used as ActivitySpot for patients

To my knowledge, we have never used medical bed properly as the patient-only's activity spots.

So, does it mean we'll need to designate some doctor-only activity spots ?

I imagine there should a pair of patient spot and doctor spot. So how would you define them as a pair ?

But there should be also only standalone spots for doctors to sit down and perform medical research on his own, right ?

**Comment by bevans2000** [comment]
Yes something like that. But if there is only one Activity spot at the moment I can't see how it can hold a patient and doctor.
Nevertheless, I'm not sure the logic is working correctly anyway as the unit tests are not working unless I clean things up.
Should be alright once I get it all sorted

**Comment by bevans2000** [comment]
Include simplification of Health problem class as per #274

**Comment by mokun** [comment]
Note that there's one quarter chance that a saved sim cannot be loaded due to NPE with MedicalManager

Do you think there are some issues with not being able to save a person's health condition ?

```
2024-06-22T22:12:36.0 (Config) MarsProject : Starting Mars Simulation Project pre-3.8.0 - Build 210905e-dirty - 64-bit Java 21.0.1 - 8 Cores
2024-06-22T22:12:36.0 (Config) MarsProject : List of input args : [-load, default.sim]
2024-06-22T22:12:36.0 (Config) SimulationBuilder : ---------------------------------------------------
2024-06-22T22:12:36.0 (Config) SimulationBuilder :     Java Version Full String = 21.0.1+12-LTS-29
2024-06-22T22:12:36.0 (Config) SimulationBuilder : Java Version Feature Element = 21
2024-06-22T22:12:36.0 (Config) SimulationBuilder : Java Version Interim Element = 0
2024-06-22T22:12:36.0 (Config) SimulationBuilder :   Java Patch Element Version = 0
2024-06-22T22:12:36.0 (Config) SimulationBuilder :  Java Update Element Version = 1
2024-06-22T22:12:36.0 (Config) SimulationBuilder :           Java Version Build = 12
2024-06-22T22:12:36.0 (Config) SimulationBuilder :   Java additional build Info = LTS-29
2024-06-22T22:12:36.0 (Config) SimulationBuilder :        Java Pre-Release Info = NA
2024-06-22T22:12:36.8 (Config) SimulationConfig : Done loading all xml config files.
2024-06-22T22:12:36.8 (Config) SimulationBuilder : Loading from C:\Users\mkhelios\.mars-sim\saved\default.sim
2024-06-22T22:12:36.8 (Config) MasterClock : -----------------------------------------------------
2024-06-22T22:12:36.8 (Config) MasterClock :                 Desired time-ratio : 128x
2024-06-22T22:12:36.8 (Config) MasterClock :             Min millisol per pulse : 0.01126440159375963
2024-06-22T22:12:36.8 (Config) MasterClock :         Optimal millisol per pulse : 0.06352140064063433
2024-06-22T22:12:36.8 (Config) MasterClock :             Max millisol per pulse : 14.7959
2024-06-22T22:12:36.8 (Config) MasterClock :  Max elapsed time between 2 pulses : 1000 ms
2024-06-22T22:12:36.8 (Config) MasterClock : -----------------------------------------------------
2024-06-22T22:12:36.8 (Config) Simulation : The file to be loaded is C:\Users\mkhelios\.mars-sim\saved\default.sim
2024-06-22T22:12:36.8 (Config) Simulation : Loading and processing the saved sim. Please wait...
2024-06-22T22:12:37.3 (Config) EVASuit :  -----------------------------------------------------------------------
2024-06-22T22:12:37.3 (Config) EVASuit :   Total Gas Tank Volume : 3.9L
2024-06-22T22:12:37.3 (Config) EVASuit :            Full Tank O2 : 66.62 kPa -> 1.0  kg - Maximum Tank Pressure
2024-06-22T22:12:37.3 (Config) EVASuit :              Nomimal O2 : 20.7  kPa -> 0.31 kg - Suit Target Pressure
2024-06-22T22:12:37.3 (Config) EVASuit :              Minimum O2 : 11.94 kPa -> 0.18 kg - Safety Limit
2024-06-22T22:12:37.3 (Config) EVASuit :  -----------------------------------------------------------------------
2024-06-22T22:12:38.1 (Config) MapDataFactory : imageName: /elevation/megt90n000eb.img
2024-06-22T22:12:38.2 (Info) MEGDRMapMemory : Reading elevation memory mapped to 'megt90n000eb.img' (5760 by 2880).
2024-06-22T22:12:38.2 (Severe) Simulation : Can't find class when loading C:\Users\mkhelios\.mars-sim\saved\default.sim : com.mars_sim.core.structure.building.function.SolarHeatSource
2024-06-22T22:12:38.2 (Config) Simulation :  
2024-06-22T22:12:38.2 (Config) Simulation :                    Info on Saved Simulation                      
2024-06-22T22:12:38.2 (Config) Simulation :  ---------------------------------------------------------
2024-06-22T22:12:38.2 (Config) Simulation :                    Filename : default.sim
2024-06-22T22:12:38.2 (Config) Simulation :                        Path : C:\Users\mkhelios\.mars-sim\saved\
2024-06-22T22:12:38.2 (Config) Simulation :                        Size : 1.69 MB
2024-06-22T22:12:38.2 (Config) Simulation :               Made in Build : unknown
2024-06-22T22:12:38.2 (Config) Simulation :   Current Core Engine Build : pre-3.8.0 - Build 210905e-dirty
2024-06-22T22:12:38.2 (Config) Simulation :           System Time Stamp : Jun 20, 2024, 11:36:46 AM
2024-06-22T22:12:38.2 (Config) Simulation :            Earth Time Stamp : 2028-08-16T17:50:22
2024-06-22T22:12:38.2 (Config) Simulation :          Martian Time Stamp : 01-Adir-01:000.000
2024-06-22T22:12:38.2 (Config) Simulation :  ---------------------------------------------------------
2024-06-22T22:12:38.2 (Config) Simulation :  Note : The core engine does not use the same build as the saved sim.
2024-06-22T22:12:38.2 (Warning) Simulation : Will attempt to load a simulation made in older build unknown under a newer core engine build pre-3.8.0 - Build 210905e-dirty.
01-Adir-01:000.000 (Severe) MarsProject : Problem starting Cannot invoke "com.mars_sim.core.person.health.MedicalManager.initializeInstances(com.mars_sim.core.person.health.MedicalConfig)" because "this.medicalManager" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.person.health.MedicalManager.initializeInstances(com.mars_sim.core.person.health.MedicalConfig)" because "this.medicalManager" is null
	at com.mars_sim.core.Simulation.reinitializeInstances(Simulation.java:596)
	at com.mars_sim.core.Simulation.loadSimulation(Simulation.java:756)
	at com.mars_sim.core.SimulationBuilder.loadSimulation(SimulationBuilder.java:384)
	at com.mars_sim.core.SimulationBuilder.start(SimulationBuilder.java:291)
	at com.mars_sim.ui.main.MarsProject.parseArgs(MarsProject.java:203)
	at com.mars_sim.ui.main.MarsProject.main(MarsProject.java:463)
```

**Comment by bevans2000** [comment]
None of this has been committed to the master branch yet. But the saved SIM is from a different build according to the messages.

**Comment by mokun** [comment]
I see that I'if there's no dedicated doctor or psychologist (would robot medic be good enough? ) in a settlement, then it would have to go for the self-treating option. 

On the other hand, if having either one on duty (not skipping out on a mission or asleep ), then a person can go see them to let them treat the sickness. 

Then ideally we need a queue to treat a line of patients one by one.

**Comment by mokun** [comment]
I see that I'if there's no dedicated doctor or psychologist (would robot medic be good enough? ) in a settlement, then it would have to go for the self-treating option. 

On the other hand, if having either one on duty (not skipping out on a mission or asleep ), then a person can go see them to let them treat the sickness. 

Then ideally we need a queue to treat a line of patients one by one. 

May be using the new group activity concept to schedule for a doctor's appointment is a good idea.

**Comment by mokun** [comment]
Currently, medical beds are always empty. A person won't know how to walk to a medical bed if he is to consult a doctor.

This is because the activity spots of a building with MedicalCare is for the doctor only.

And there's one and only one doctor activity spot in each building (such as Lander Hab, Medical Hab, Infirmary, Outpost Hub) that support MedicalCare.

For patients, they are supposed to show up in one of the medical beds.

Intuitively, we could have an doctor activity spot next to each of the medical bed.

However, we don't have any codes for tracking the usage of these medical beds in `MedicalStation` yet. 

As a result, the patients don't know how to occupy a medical bed.

Fixing it now.

**Comment by mokun** [comment]
After those two commits, patients may go to the medical beds. However, they didn't leave behind their old activity spots yet.

We'll pick up the remaining work in https://github.com/mars-sim/mars-sim/issues/1180.
