### ISSUE TITLE
primaryStudy is null. NPE on getScience

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1332]
**Describe the bug**
- primaryStudy is null. NPE on getScience

**Expected and unexpected behavior**
- Create unit test to verify this condition
- Employ defensive measure to avoid NPE 

**Java classes involved**
In Person, we have
```java
	/** The person's current scientific study. */
	private ScientificStudy study;
```
- When rebuilding the task cache, it looks into CompileScientificStudyResultsMeta.
- In CompileScientificStudyResultsMeta, 
```java
- ScientificStudy primaryStudy = person.getStudy();
```
- In CompileScientificStudyResultsMeta, 
```java
	    RatingScore result = new RatingScore(base);
        Building b = BuildingManager.getAvailableBuilding(primaryStudy.getScience(), person);
        result = assessBuildingSuitability(result, b, person);
        result = applyCommerceFactor(result, person.getAssociatedSettlement(), CommerceType.RESEARCH);
        result = assessPersonSuitability(result, person);

        return createTaskJobs(result);
```
- However, if person.getStudy is null, primaryStudy.getScience will be null.
The line `        Building b = BuildingManager.getAvailableBuilding(primaryStudy.getScience(), person);` generate this NPE.

**Stacktrace**
```
01-Coan-10:771.670 (Info) AbstractMission [x27] : [Tian Cheng - Residential Quarters 1] Huan Tseng - Responsible for 'Collecting Resources' Mission Phase.
01-Coan-10:771.670 (Severe) UnitManager : Problem with pulse on Starcity: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
	at com.mars_sim.core.science.task.CompileScientificStudyResultsMeta.getTaskJobs(CompileScientificStudyResultsMeta.java:105)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:109)
	at com.mars_sim.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:454)
	at com.mars_sim.core.person.ai.Mind.lookForATask(Mind.java:286)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:243)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:176)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:730)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1113)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:924)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:905)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Coan-10:772.113 (Severe) UnitManager : Problem with pulse on Starcity: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
	at com.mars_sim.core.science.task.CompileScientificStudyResultsMeta.getTaskJobs(CompileScientificStudyResultsMeta.java:105)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:109)
	at com.mars_sim.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:454)
	at com.mars_sim.core.person.ai.Mind.lookForATask(Mind.java:286)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:243)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:176)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:730)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1113)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:924)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:905)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Coan-10:772.556 (Severe) UnitManager : Problem with pulse on Starcity: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
	at com.mars_sim.core.science.task.CompileScientificStudyResultsMeta.getTaskJobs(CompileScientificStudyResultsMeta.java:105)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:109)
	at com.mars_sim.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:454)
	at com.mars_sim.core.person.ai.Mind.lookForATask(Mind.java:286)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:243)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:176)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:730)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1113)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:924)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:905)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Coan-10:772.556 (Warning) SystemCondition [x439] : [Terminus - Garage 1] RepairBot 019 - Out of power.
01-Coan-10:772.998 (Severe) UnitManager : Problem with pulse on Starcity: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
	at com.mars_sim.core.science.task.CompileScientificStudyResultsMeta.getTaskJobs(CompileScientificStudyResultsMeta.java:105)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:109)
	at com.mars_sim.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:454)
	at com.mars_sim.core.person.ai.Mind.lookForATask(Mind.java:286)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:243)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:176)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:730)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1113)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:924)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:905)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Coan-10:773.441 (Severe) UnitManager : Problem with pulse on Starcity: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.science.ScientificStudy.getScience()" because "primaryStudy" is null
	at com.mars_sim.core.science.task.CompileScientificStudyResultsMeta.getTaskJobs(CompileScientificStudyResultsMeta.java:105)
	at com.mars_sim.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:109)
	at com.mars_sim.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:454)
	at com.mars_sim.core.person.ai.Mind.lookForATask(Mind.java:286)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:243)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:176)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:730)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1113)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:924)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:905)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

...
01-Coan-11:206.406 (Severe) UnitManager : Problem with pulse on Heritage: null
java.lang.NullPointerException

01-Coan-11:206.406 (Info) Sleep : [New Pompeii - Inflatable Greenhouse 2] Kabir Chandra - Sleep adjusted for shift starts at 239. Duration: 32
01-Coan-11:206.853 (Severe) UnitManager : Problem with pulse on Heritage: null
java.lang.NullPointerException

01-Coan-11:207.300 (Severe) UnitManager : Problem with pulse on Heritage: null
java.lang.NullPointerException

01-Coan-11:207.300 (Info) Charge : [Zvezda - Lander Hab 1] MakerBot 014 - Switching to wireless charging in Lander Hab 1.
01-Coan-11:207.300 (Warning) Task : [New Seoul - Garage 1] Yejun Jung - Ended 'Maintaining Vehicle in Garage' early. LUV 013 No available garage for maintenance.
01-Coan-11:207.746 (Info) ComputingJob [x2] : [New Dubai] Requested computing resources: 1.19 CUs for Connecting Online.
01-Coan-11:207.746 (Severe) UnitManager : Problem with pulse on Heritage: null
java.lang.NullPointerException

01-Coan-11:208.193 (Severe) UnitManager : Problem with pulse on Heritage: null
java.lang.NullPointerException

01-Coan-11:208.640 (Severe) UnitManager : Problem with pulse on Heritage: null
java.lang.NullPointerException

01-Coan-11:208.640 (Info) Sleep : [Arcadia - Residential Quarters 1] Lena Müller - Sleep adjusted for shift starts at 244. Duration: 35
01-Coan-11:209.087 (Warning) SystemCondition [x438] : [Catarina] RepairBot 004 - Out of power.
01-Coan-11:209.087 (Severe) UnitManager : Problem with pulse on Heritage: null
java.lang.NullPointerException

01-Coan-11:209.087 (Warning) SystemCondition [x438] : [Terminus - Lander Hab 2] RepairBot 017 - Out of power.
01-Coan-11:209.534 (Severe) UnitManager : Problem with pulse on Heritage: null
java.lang.NullPointerException

```

**Specifications**
- pre-3.8.0

**Additional context**
- Interesting, I notice this NPE only when resuming my machine from power saving this morning. 
- Without the local time clock in the stacktrace, I'm unable to verify if it happens yesterday or this morning.
- If it happens only this morning as soon as I flipped open my laptop, then it may have to do with power saving. But I doubt it.

**Additional tasks**
- Add a local timestamp at the beginning of each line in stacktrace for easy debugging

**Comment by mokun** [comment]
@bevans2000 

Have you had this ?

**Comment by bevans2000** [comment]
No. Can't see how this could occur. Do you want to assign to me?
There are unit tests already but maybe not broad enough
