### ISSUE TITLE
Unable to manufacture and salvage items

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1410]
**Describe the bug**
- After dozens of sols, it was found that a settlement would rarely choose to manufacture an item automatically, if any.
- Currently, if a player goes to the Manu tab in settlement unit window and select an equipment to salvage. It initiates that process but no one works on it. 
- Also, an *UnsupportedOperationException* due to *ImmutableCollections* was encountered from time to time, when attempting to manufacture a resource (not when salvaging a resource). However, once it's resolved, players still can't salvage an equipment such as something as simple as a *Large Bag*.

**Expected and unexpected behavior**
- Manually starting a salvaging process should prompt settlers to salvage the selected equipment.

**Discuss any potential problems you have and have not ruled out**
- Players have no issue manually starting a manufacturing process that would prompt settlers to manufacture a resource/item/equipment.
- In this case, player can manufacture a *Large Bag* without any issues. However, player cannot salvage a *Large Bag*.

**Suggested Solution**
- Look into *SalvageGood* and *ManufactureGood* task class.
- As a sidenote, suggest adding a parameter to track whether a manufacturing/salvage process is player or settlement initiated.
- In future, allow an authority (sponsor) to order or initiate a manufacturing/salvage process as well.

**Java classes involved**
- ManufactureUtil

**Screenshots**
- The Work percent is at 0% forever. No one works on it.
![image](https://github.com/user-attachments/assets/2fb9079a-3307-4750-ba1a-39787fb8950d)

**Stacktrace**
```
01-Bora-10:321.111 (Severe) MasterClock : Can't send out clock pulse: 
java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$ListItr.remove(ImmutableCollections.java:387)
	at com.mars_sim.core.manufacture.ManufactureUtil.findUnitForSalvage(ManufactureUtil.java:511)
	at com.mars_sim.core.manufacture.ManufactureUtil.canSalvageProcessBeStarted(ManufactureUtil.java:369)
	at com.mars_sim.ui.swing.unit_window.structure.TabPanelManufacture.getAvailableSalvageProcesses(TabPanelManufacture.java:533)
	at com.mars_sim.ui.swing.unit_window.structure.TabPanelManufacture.update(TabPanelManufacture.java:353)
	at com.mars_sim.ui.swing.unit_window.UnitWindow.update(UnitWindow.java:204)
	at com.mars_sim.ui.swing.unit_window.structure.SettlementUnitWindow.update(SettlementUnitWindow.java:256)
	at com.mars_sim.ui.swing.MainDesktopPane.updateWindows(MainDesktopPane.java:627)
	at com.mars_sim.ui.swing.MainDesktopPane.clockPulse(MainDesktopPane.java:809)
	at com.mars_sim.ui.swing.MainWindow.clockPulse(MainWindow.java:712)
	at com.mars_sim.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:761)
	at com.mars_sim.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	
```

**Specifications**
- pre-3.8.1

**Additional**
- Another manufacturing related issue is that when a manually manufacturing process is initiated, suddenly a few other manufacturing processes would pop up in the Manu tab. 
- For instance, as soon as player manually chooses to "Make Sheet Glass", two other manufacturing processes would pop up.
![image](https://github.com/user-attachments/assets/647807ef-1374-4e14-8d12-cf31df087d70)
- Before the player chose this process, it has been **very rare** to see a settlement automatically initiate a manufacturing process. 
- This lack of incentive to manufacture new resources must be investigated as well.

**Comment by mokun** [comment]
@bevans2000 

Looks like ManufactureGoodMeta's getSettlementTasks() always returns empty, unless a process has been manually or directly started without going through the meta task.

**Comment by bevans2000** [comment]
> @bevans2000
> 
> Looks like ManufactureGoodMeta's getSettlementTasks() always returns empty, unless a process has been manually or directly started without going through the meta task.

Sounds like we need to create a unit test

**Comment by mokun** [comment]
Fixing it now. 

The culprit is that the *process* list is just an ongoing list of processes. It shouldn't be used in ManufactureGoodMeta,

**Comment by mokun** [comment]
@bevans2000 

Would you like to work on a global queue for manufacturing and food production ?

**Comment by bevans2000** [comment]
I could yes. Got to complete the unit hierarchy change first

**Comment by bevans2000** [comment]
There is a big problem in the current approach. The UI panels are moving processes from the queue to the Workshop to be processed. This is wrong because if the UI panels were not open this would not happen.
The queue management must be done centrally away from the UI.

**Comment by mokun** [comment]
> The queue management must be done centrally away from the UI.

Sure.

> In addition we should look to consolidate salvage & manufacture processes into a common structure so we can have a single queue.

There are already some common class between manufacturing and salvage. Don't know how to further centrally them.

Can I pass this onto you to find the best way possible way forward  ?

**Comment by bevans2000** [comment]
Sure, do we have a dedicated Issue for creating a central Queue?
