### ISSUE TITLE
NPE on missionProbCache

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1438]
**Describe the bug**
- At Sol 2:000, missionProbCache becomes null.

**Expected and unexpected behavior**
- A person cannot get a new mission when calling MissionManager's getNewMission() if missionProbCache is null.

**Discuss any potential problems you have and have not ruled out**
- This is due to the use of the new CacheCreator generic class in a recent [PR](https://github.com/mars-sim/mars-sim/pull/1428)

**Java classes involved**
- MissionManager, CacheCreator.

In MissionManager, missionProbCache can become null from time to time
```java

	private MissionRating selectMissionFromProbabilities() {
		return missionProbCache.getRandomSelection();
	}
```

**Stacktrace**
```
01-Adir-02:000.445 (Info) MissionManager : [Terminus - Lander Hab 2] Joshua Young - Regolith Prospecting Score: 0.337 (base: 1, minerals: 0.805, leader: 0.31, extrovert: 1, settlement.ratio: 2.7, goods: 0.5)
01-Adir-02:000.445 (Severe) UnitManager : Problem with pulse on Terminus: Cannot invoke "com.mars_sim.core.person.ai.CacheCreator.getRandomSelection()" because "this.missionProbCache" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.person.ai.CacheCreator.getRandomSelection()" because "this.missionProbCache" is null
	at com.mars_sim.core.person.ai.mission.MissionManager.selectMissionFromProbabilities(MissionManager.java:237)
	at com.mars_sim.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:221)
	at com.mars_sim.core.person.ai.Mind.startNewMission(Mind.java:439)
	at com.mars_sim.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:161)
	at com.mars_sim.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:680)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:640)
	at com.mars_sim.core.person.ai.task.util.TaskManager.executeTask(TaskManager.java:498)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:201)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:173)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:721)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1068)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:893)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:853)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Adir-02:000.917 (Info) MissionManager : [Terminus - Lander Hab 2] Joshua Young - Regolith Prospecting Score: 0.337 (base: 1, minerals: 0.805, leader: 0.31, extrovert: 1, settlement.ratio: 2.7, goods: 0.5)
01-Adir-02:000.917 (Severe) UnitManager : Problem with pulse on Terminus: Cannot invoke "com.mars_sim.core.person.ai.CacheCreator.getRandomSelection()" because "this.missionProbCache" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.person.ai.CacheCreator.getRandomSelection()" because "this.missionProbCache" is null
	at com.mars_sim.core.person.ai.mission.MissionManager.selectMissionFromProbabilities(MissionManager.java:237)
	at com.mars_sim.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:221)
	at com.mars_sim.core.person.ai.Mind.startNewMission(Mind.java:439)
	at com.mars_sim.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:161)
	at com.mars_sim.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:680)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:640)
	at com.mars_sim.core.person.ai.task.util.TaskManager.executeTask(TaskManager.java:498)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:201)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:173)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:721)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1068)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:893)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:853)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Specifications**
- pre-3.9.0

FYI:
- @muybien3433

**Comment by mokun** [comment]
Similarly, in another simulation session,

```
01-Adir-07:405.813 (Info) MissionManager : [Teslapolis - Lander Hab 1] Barbara Thomas - Ice Prospecting Score: 0.324 (base: 1, minerals: 0.8, leader: 0.405, extrovert: 1, settlement.ratio: 1, goods: 1)
01-Adir-07:405.813 (Info) Settlement : [Teslapolis] Investigating a mineral site at 35.2062 N 163.8594 E (1.5 km away).
01-Adir-07:405.813 (Info) Exploration : [Teslapolis] A site has an Exploration Value of 1.04.
01-Adir-07:405.813 (Info) MissionManager : [Teslapolis - Lander Hab 1] Barbara Thomas - Mineral Exploration Score: 0.142 (base: 1, minerals: 0.05, leader: 1.013, extrovert: 1, settlement.ratio: 2.1, goods: 1.333)
01-Adir-07:405.813 (Severe) UnitManager : Problem with pulse on Teslapolis: Cannot invoke "com.mars_sim.core.person.ai.CacheCreator.getRandomSelection()" because "this.missionProbCache" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.person.ai.CacheCreator.getRandomSelection()" because "this.missionProbCache" is null
	at com.mars_sim.core.person.ai.mission.MissionManager.selectMissionFromProbabilities(MissionManager.java:237)
	at com.mars_sim.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:221)
	at com.mars_sim.core.person.ai.Mind.startNewMission(Mind.java:439)
	at com.mars_sim.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:161)
	at com.mars_sim.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:676)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:636)
	at com.mars_sim.core.person.ai.task.util.TaskManager.executeTask(TaskManager.java:498)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:201)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:173)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:721)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1068)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:893)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:853)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Adir-07:407.036 (Info) MissionManager : [Teslapolis - Lander Hab 1] Barbara Thomas - Ice Prospecting Score: 0.324 (base: 1, minerals: 0.8, leader: 0.405, extrovert: 1, settlement.ratio: 1, goods: 1)
01-Adir-07:407.036 (Info) MissionManager : [Teslapolis - Lander Hab 1] Barbara Thomas - Mineral Exploration Score: 0.142 (base: 1, minerals: 0.05, leader: 1.013, extrovert: 1, settlement.ratio: 2.1, goods: 1.333)
01-Adir-07:407.036 (Severe) UnitManager : Problem with pulse on Teslapolis: Cannot invoke "com.mars_sim.core.person.ai.CacheCreator.getRandomSelection()" because "this.missionProbCache" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.person.ai.CacheCreator.getRandomSelection()" because "this.missionProbCache" is null
	at com.mars_sim.core.person.ai.mission.MissionManager.selectMissionFromProbabilities(MissionManager.java:237)
	at com.mars_sim.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:221)
	at com.mars_sim.core.person.ai.Mind.startNewMission(Mind.java:439)
	at com.mars_sim.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:161)
	at com.mars_sim.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:676)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:636)
	at com.mars_sim.core.person.ai.task.util.TaskManager.executeTask(TaskManager.java:498)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:201)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:173)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:721)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1068)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:893)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:853)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by mokun** [comment]
@muybien3433 @bevans2000 

After the patch, I'm getting these : 

```
01-Adir-03:223.807 (Info) MissionManager : [Teslapolis - Lander Hab 1] Paul Nelson - Regolith Prospecting Score: 0.321 (base: 1, minerals: 0.803, leader: 0.8, extrovert: 1, settlement.ratio: 1, goods: 0.5)
01-Adir-03:223.807 (Severe) UnitManager : Problem with pulse on Teslapolis: Paul Nelson could not determine a new mission.
java.lang.IllegalStateException: Paul Nelson could not determine a new mission.
	at com.mars_sim.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:225)
	at com.mars_sim.core.person.ai.Mind.startNewMission(Mind.java:439)
	at com.mars_sim.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:161)
	at com.mars_sim.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:680)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:640)
	at com.mars_sim.core.person.ai.task.util.TaskManager.executeTask(TaskManager.java:498)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:201)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:173)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:721)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1068)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:893)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:853)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Adir-03:225.066 (Info) MissionManager : [Teslapolis - Lander Hab 1] Paul Nelson - Regolith Prospecting Score: 0.321 (base: 1, minerals: 0.803, leader: 0.8, extrovert: 1, settlement.ratio: 1, goods: 0.5)
01-Adir-03:225.066 (Severe) UnitManager : Problem with pulse on Teslapolis: Paul Nelson could not determine a new mission.
java.lang.IllegalStateException: Paul Nelson could not determine a new mission.
	at com.mars_sim.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:225)
	at com.mars_sim.core.person.ai.Mind.startNewMission(Mind.java:439)
	at com.mars_sim.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:161)
	at com.mars_sim.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:680)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:640)
	at com.mars_sim.core.person.ai.task.util.TaskManager.executeTask(TaskManager.java:498)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:201)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:173)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:721)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1068)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:893)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:853)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by muybien3433** [comment]
Is it time to time or always?

**Comment by mokun** [comment]
> Is it time to time or always?

It's been unpredictable. Sometimes it happens on sol 2, sometimes on sol 4, sometimes sol 7...

**Comment by muybien3433** [comment]
So basically 

In PersonTaskManager
```	private static synchronized CacheCreator<TaskJob> getDefaultOutsideTasks() {
		if (defaultOutsideTasks == null) {
			defaultOutsideTasks = new CacheCreator<>("Default Outside", null);
```

```	private static synchronized CacheCreator<TaskJob> getDefaultInsideTasks() {
		if (defaultInsideTasks == null) {
			defaultInsideTasks = new CacheCreator<>("Default Inside", null);```

will return null
as well in BotTaskManager

```	private static synchronized CacheCreator<TaskJob> getPowerSaveTaskMap() {
		if (powerSaveMap == null) {
			powerSaveMap = new CacheCreator<>("Power Save Mode", null);```

```	private static synchronized CacheCreator<TaskJob> getChargeTaskMap() {
		if (chargeMap == null) {
			chargeMap = new CacheCreator<>("Robot Charge", null);```

Is there reason to check createdTime or just remove it from getRandomDoubleBasedOnProbability method?

**Comment by mokun** [comment]
> In PersonTaskManager and BotTaskManager will return null

It only affects starting a new *Mission*.

When it comes to selecting a *Task*, things seem to work fine without a hitch.

**Comment by mokun** [comment]
I suppose you just have to add the `List<MissionRating missionCache` into the CacheCreator in getNewMission().

Without that, the cache inside CacheCreator is empty.

**Comment by mokun** [comment]
I just tested the approach above and it works now. 

New missions can be generated again.

It's up to you if you want to create a new constructor to add in the missionCache right off the bat or add it later.

**Comment by bevans2000** [comment]
@muybien3433 can we close this?
