### ISSUE TITLE
Unable to load from a saved sim owing to a container issue or UnitSet issue

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1453]
**Describe the bug**
- After some commits in the last two days, it's unable to load from a saved sim 
- The stacktrace shows CONTAINER (Base ID: 32) has some kind of issues.
- The NPE said it's owing to UnitSet issue when "this.units" is null.

**Java classes involved**
- UnitSet, UnitManager, possibly EquipmentFactory

**Stacktrace**
```
2024-09-23T16:01:23.7 (Config) MarsProject : Starting Mars Simulation Project pre-3.9.0 - 64-bit Java 21.0.4 - 8 Cores
2024-09-23T16:01:23.7 (Config) MarsProject : List of input args : [-load, default.sim]
2024-09-23T16:01:23.8 (Config) SimulationBuilder : ---------------------------------------------------
2024-09-23T16:01:23.8 (Config) SimulationBuilder :     Java Version Full String = 21.0.4+8-LTS-274
2024-09-23T16:01:23.8 (Config) SimulationBuilder : Java Version Feature Element = 21
2024-09-23T16:01:23.8 (Config) SimulationBuilder : Java Version Interim Element = 0
2024-09-23T16:01:23.8 (Config) SimulationBuilder :   Java Patch Element Version = 0
2024-09-23T16:01:23.8 (Config) SimulationBuilder :  Java Update Element Version = 4
2024-09-23T16:01:23.8 (Config) SimulationBuilder :           Java Version Build = 8
2024-09-23T16:01:23.8 (Config) SimulationBuilder :   Java additional build Info = LTS-274
2024-09-23T16:01:23.8 (Config) SimulationBuilder :        Java Pre-Release Info = NA
2024-09-23T16:01:24.8 (Config) SimulationConfig : Done loading all xml config files.
2024-09-23T16:01:24.8 (Config) SimulationBuilder : Loading from C:\Users\mkhelios\.mars-sim\saved\default.sim
2024-09-23T16:01:24.8 (Config) MasterClock : -----------------------------------------------------
2024-09-23T16:01:24.8 (Config) MasterClock :                 Desired time-ratio : 128x
2024-09-23T16:01:24.8 (Config) MasterClock :             Min millisol per pulse : 0.0113
2024-09-23T16:01:24.8 (Config) MasterClock :         Optimal millisol per pulse : 0.0635
2024-09-23T16:01:24.8 (Config) MasterClock :             Max millisol per pulse : 14.7959
2024-09-23T16:01:24.8 (Config) MasterClock :  Max elapsed time between 2 pulses : 1000 ms
2024-09-23T16:01:24.8 (Config) MasterClock : -----------------------------------------------------
2024-09-23T16:01:24.8 (Config) Simulation : The file to be loaded is C:\Users\mkhelios\.mars-sim\saved\default.sim
2024-09-23T16:01:24.8 (Config) Simulation : Loading and processing the saved sim. Please wait...
2024-09-23T16:01:25.3 (Config) EVASuit :  -----------------------------------------------------------------------
2024-09-23T16:01:25.3 (Config) EVASuit :   Total Gas Tank Volume : 3.9L
2024-09-23T16:01:25.3 (Config) EVASuit :            Full Tank O2 : 66.62 kPa -> 1.0  kg - Maximum Tank Pressure
2024-09-23T16:01:25.3 (Config) EVASuit :              Nomimal O2 : 20.7  kPa -> 0.31 kg - Suit Target Pressure
2024-09-23T16:01:25.3 (Config) EVASuit :              Minimum O2 : 11.94 kPa -> 0.18 kg - Safety Limit
2024-09-23T16:01:25.3 (Config) EVASuit :  -----------------------------------------------------------------------
2024-09-23T16:01:25.6 (Config) MapDataFactory : imageName: /elevation/megt90n000eb.img
2024-09-23T16:01:25.6 (Info) MEGDRMapMemory : Reading elevation memory mapped to 'megt90n000eb.img' (5760 by 2880).
2024-09-23T16:01:25.6 (Warning) UnitManager : Unit not found. id: 518. Type of unit: CONTAINER (Base ID: 32).
2024-09-23T16:01:25.6 (Severe) Simulation : Cannot deserialize : Can not find Unit for id: 518
2024-09-23T16:01:25.7 (Config) Simulation :  
2024-09-23T16:01:25.7 (Config) Simulation :                    Info on Saved Simulation                      
2024-09-23T16:01:25.7 (Config) Simulation :  ---------------------------------------------------------
2024-09-23T16:01:25.7 (Config) Simulation :                    Filename : default.sim
2024-09-23T16:01:25.7 (Config) Simulation :                        Path : C:\Users\mkhelios\.mars-sim\saved\
2024-09-23T16:01:25.7 (Config) Simulation :                        Size : 141.97 KB
2024-09-23T16:01:25.7 (Config) Simulation :               Made in Build : pre-3.9.0 - Build e6db569
2024-09-23T16:01:25.7 (Config) Simulation :   Current Core Engine Build : pre-3.9.0 - Build e6db569
2024-09-23T16:01:25.7 (Config) Simulation :           System Time Stamp : Sep 23, 2024, 4:01:12 PM
2024-09-23T16:01:25.7 (Config) Simulation :            Earth Time Stamp : 2028-08-16T21:11:35.823
2024-09-23T16:01:25.7 (Config) Simulation :          Martian Time Stamp : 01-Adir-01:136.006
2024-09-23T16:01:25.7 (Config) Simulation :  ---------------------------------------------------------
2024-09-23T16:01:25.7 (Config) Simulation :  Note : The core engine uses the same build as the saved sim.
01-Adir-01:136.006 (Config) UnitManager : Setting up 1 thread(s) for running the settlement update.
01-Adir-01:136.006 (Config) UnitManager : Setting up a settlement task thread for Terminus.
01-Adir-01:136.006 (Config) SimulationBuilder : Starting the Master Clock...
01-Adir-01:136.006 (Config) Simulation : Setting up autosave to be triggered every 900000 ms (15.0 mins).
01-Adir-01:136.006 (Config) MasterClock : Setting up 1 thread(s) for clock listener.
01-Adir-01:136.006 (Config) MasterClock : Setting up 1 thread for clock executor.
01-Adir-01:136.006 (Warning) MasterClock : [System] MasterClock : Zero elapsed real time. Resetting it back to 96 ms.
01-Adir-01:139.186 (Severe) UnitManager : Problem with pulse on Terminus: Cannot invoke "java.util.Set.iterator()" because "this.units" is null
java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because "this.units" is null
	at com.mars_sim.core.data.UnitSet.iterator(UnitSet.java:74)
	at com.mars_sim.core.malfunction.MalfunctionFactory.getAssociatedMalfunctionables(MalfunctionFactory.java:210)
	at com.mars_sim.core.structure.building.BuildingManager.retrieveMaintPartsFromMalfunctionMgrs(BuildingManager.java:2201)
	at com.mars_sim.core.structure.building.BuildingManager.timePassing(BuildingManager.java:795)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:889)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:849)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Adir-01:142.381 (Severe) UnitManager : Problem with pulse on Terminus: Cannot invoke "java.util.Set.iterator()" because "this.units" is null
java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because "this.units" is null
	at com.mars_sim.core.data.UnitSet.iterator(UnitSet.java:74)
	at com.mars_sim.core.malfunction.MalfunctionFactory.getAssociatedMalfunctionables(MalfunctionFactory.java:210)
	at com.mars_sim.core.structure.building.BuildingManager.retrieveMaintPartsFromMalfunctionMgrs(BuildingManager.java:2201)
	at com.mars_sim.core.structure.building.BuildingManager.timePassing(BuildingManager.java:795)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:889)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:849)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
...
```

**Specifications**
- pre-3.9.0

**Additional context**
- Need to create an unit test to trap deserialization issue when reloading from a saved sim
> (Warning) UnitManager : Unit not found. id: 518. Type of unit: CONTAINER (Base ID: 32).
> (Severe) Simulation : Cannot deserialize : Can not find Unit for id: 518

**Comment by mokun** [comment]
@bevans2000 

I'm currently unable to load from a saved sim.

**Comment by bevans2000** [comment]
There is a unit test to check saving and reloading. It must be something missing from the unit test.
Should be fixable but a bit odd.

**Comment by mokun** [comment]
After this commit with #1445, it doesn't load from saved sim anymore.

![image](https://github.com/user-attachments/assets/f4ae49ed-7d09-4f10-9a81-8a8f0a3e3d32)

**Comment by mokun** [comment]
There's another alternate result when loading from a saved sim : 

They all seem to have to do with a container in UnitManager not being able to serialize correctly in the first place.

> UnitManager : Unit not found. id: 518. Type of unit: CONTAINER (Base ID: 32).
> 2024-09-23T16:27:11.8 (Severe) Simulation : Cannot deserialize : Can not find Unit for id: 518

Thus, when deserializing the UnitManager, one of the *units* set in UnitSet was invalid.

```
2024-09-23T16:27:10.3 (Config) MarsProject : Starting Mars Simulation Project pre-3.9.0 - 64-bit Java 21.0.3 - 8 Cores
2024-09-23T16:27:10.3 (Config) MarsProject : List of input args : [-load, default.sim]
2024-09-23T16:27:10.3 (Config) SimulationBuilder : ---------------------------------------------------
2024-09-23T16:27:10.3 (Config) SimulationBuilder :     Java Version Full String = 21.0.3+9-LTS
2024-09-23T16:27:10.3 (Config) SimulationBuilder : Java Version Feature Element = 21
2024-09-23T16:27:10.3 (Config) SimulationBuilder : Java Version Interim Element = 0
2024-09-23T16:27:10.3 (Config) SimulationBuilder :   Java Patch Element Version = 0
2024-09-23T16:27:10.3 (Config) SimulationBuilder :  Java Update Element Version = 3
2024-09-23T16:27:10.3 (Config) SimulationBuilder :           Java Version Build = 9
2024-09-23T16:27:10.3 (Config) SimulationBuilder :   Java additional build Info = LTS
2024-09-23T16:27:10.3 (Config) SimulationBuilder :        Java Pre-Release Info = NA
2024-09-23T16:27:11.1 (Config) SimulationConfig : Done loading all xml config files.
2024-09-23T16:27:11.1 (Config) SimulationBuilder : Loading from C:\Users\mkhelios\.mars-sim\saved\default.sim
2024-09-23T16:27:11.1 (Config) MasterClock : -----------------------------------------------------
2024-09-23T16:27:11.1 (Config) MasterClock :                 Desired time-ratio : 128x
2024-09-23T16:27:11.1 (Config) MasterClock :             Min millisol per pulse : 0.0113
2024-09-23T16:27:11.1 (Config) MasterClock :         Optimal millisol per pulse : 0.0635
2024-09-23T16:27:11.1 (Config) MasterClock :             Max millisol per pulse : 14.7959
2024-09-23T16:27:11.1 (Config) MasterClock :  Max elapsed time between 2 pulses : 1000 ms
2024-09-23T16:27:11.1 (Config) MasterClock : -----------------------------------------------------
2024-09-23T16:27:11.1 (Config) Simulation : The file to be loaded is C:\Users\mkhelios\.mars-sim\saved\default.sim
2024-09-23T16:27:11.1 (Config) Simulation : Loading and processing the saved sim. Please wait...
2024-09-23T16:27:11.3 (Config) MapDataFactory : imageName: /elevation/megt90n000eb.img
2024-09-23T16:27:11.3 (Info) MEGDRMapMemory : Reading elevation memory mapped to 'megt90n000eb.img' (5760 by 2880).
2024-09-23T16:27:11.6 (Config) EVASuit :  -----------------------------------------------------------------------
2024-09-23T16:27:11.6 (Config) EVASuit :   Total Gas Tank Volume : 3.9L
2024-09-23T16:27:11.6 (Config) EVASuit :            Full Tank O2 : 66.62 kPa -> 1.0  kg - Maximum Tank Pressure
2024-09-23T16:27:11.6 (Config) EVASuit :              Nomimal O2 : 20.7  kPa -> 0.31 kg - Suit Target Pressure
2024-09-23T16:27:11.6 (Config) EVASuit :              Minimum O2 : 11.94 kPa -> 0.18 kg - Safety Limit
2024-09-23T16:27:11.6 (Config) EVASuit :  -----------------------------------------------------------------------
2024-09-23T16:27:11.8 (Warning) UnitManager : Unit not found. id: 518. Type of unit: CONTAINER (Base ID: 32).
2024-09-23T16:27:11.8 (Severe) Simulation : Cannot deserialize : Can not find Unit for id: 518
2024-09-23T16:27:11.8 (Config) Simulation :  
2024-09-23T16:27:11.8 (Config) Simulation :                    Info on Saved Simulation                      
2024-09-23T16:27:11.8 (Config) Simulation :  ---------------------------------------------------------
2024-09-23T16:27:11.8 (Config) Simulation :                    Filename : default.sim
2024-09-23T16:27:11.8 (Config) Simulation :                        Path : C:\Users\mkhelios\.mars-sim\saved\
2024-09-23T16:27:11.8 (Config) Simulation :                        Size : 137.1 KB
2024-09-23T16:27:11.8 (Config) Simulation :               Made in Build : pre-3.9.0 - Build a45f6d7-dirty
2024-09-23T16:27:11.8 (Config) Simulation :   Current Core Engine Build : pre-3.9.0 - Build a45f6d7-dirty
2024-09-23T16:27:11.8 (Config) Simulation :           System Time Stamp : Sep 23, 2024, 4:26:58 PM
2024-09-23T16:27:11.8 (Config) Simulation :            Earth Time Stamp : 2028-08-16T18:47:33.019
2024-09-23T16:27:11.8 (Config) Simulation :          Martian Time Stamp : 01-Adir-01:038.649
2024-09-23T16:27:11.8 (Config) Simulation :  ---------------------------------------------------------
2024-09-23T16:27:11.8 (Config) Simulation :  Note : The core engine uses the same build as the saved sim.
01-Adir-01:038.649 (Config) UnitManager : Setting up 1 thread(s) for running the settlement update.
01-Adir-01:038.649 (Config) UnitManager : Setting up a settlement task thread for Terminus.
01-Adir-01:038.649 (Config) SimulationBuilder : Starting the Master Clock...
01-Adir-01:038.649 (Config) Simulation : Setting up autosave to be triggered every 900000 ms (15.0 mins).
01-Adir-01:038.649 (Config) MasterClock : Setting up 1 thread(s) for clock listener.
01-Adir-01:038.649 (Config) MasterClock : Setting up 1 thread for clock executor.
01-Adir-01:039.123 (Severe) UnitManager : Problem with pulse on Terminus: Cannot invoke "java.util.Set.iterator()" because "this.units" is null
java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because "this.units" is null
	at com.mars_sim.core.data.UnitSet.iterator(UnitSet.java:74)
	at com.mars_sim.core.malfunction.MalfunctionFactory.getAssociatedMalfunctionables(MalfunctionFactory.java:210)
	at com.mars_sim.core.structure.building.BuildingManager.retrieveMaintPartsFromMalfunctionMgrs(BuildingManager.java:2201)
	at com.mars_sim.core.structure.building.BuildingManager.timePassing(BuildingManager.java:795)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:887)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:849)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Adir-01:039.450 (Warning) Unit : Fuel Storage 2 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : EVA Airlock 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Kilopower Reactor 2 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Inflatable Greenhouse 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Ice Storage 2 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Gas Storage 2 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Sand Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Chemical Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : ERV-C 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Ore Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Cement Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : ERV-A 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : MD1 Nuclear Reactor 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Hallway 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Ice Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Lander Hab 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Severe) BuildingManager : [Terminus] Lander Hab 1 - Problem applying pulse to Building
java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because "this.units" is null
	at com.mars_sim.core.data.UnitSet.contains(UnitSet.java:70)
	at com.mars_sim.core.structure.Settlement.containsPerson(Settlement.java:1686)
	at com.mars_sim.core.structure.building.function.LifeSupport.timePassing(LifeSupport.java:219)
	at com.mars_sim.core.structure.building.Building.timePassing(Building.java:1219)
	at com.mars_sim.core.structure.building.BuildingManager.timePassing(BuildingManager.java:800)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:887)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:849)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Adir-01:039.450 (Warning) Unit : Fuel Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Gas Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Lime Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : ERV-I 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Kilopower Reactor 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Regolith Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Large Sabatier Processor 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Concrete Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : ERV-B 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Metal Storage 1 expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Kevin Walker expected pulse #83 but received 84
01-Adir-01:039.450 (Warning) Unit : Kathy Kelly expected pulse #83 but received 84
01-Adir-01:039.450 (Severe) UnitManager : Problem with pulse on Terminus: Cannot invoke "java.util.Set.stream()" because "this.units" is null
java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because "this.units" is null
	at com.mars_sim.core.data.UnitSet.stream(UnitSet.java:136)
	at com.mars_sim.core.person.Person.getInventorySuit(Person.java:1150)
	at com.mars_sim.core.person.Person.getSuit(Person.java:1141)
	at com.mars_sim.core.person.Person.timePassing(Person.java:642)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1066)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:891)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:849)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by mokun** [comment]
May be it's about time we start considering what it takes to switch to JSON or XML for serializing simulation sessions.

**Comment by bevans2000** [comment]
So let's be clear. This is a problem to do with the data structures and not the persistence approach. If we were using JSON the same problem would exist because we have an id that can not be found.
Having said that, Serialisation is not the right solution. But it's a massive changes and needs to be planned out with a prototype. In my opinion, JSON, is not correct either as it also requires everything to reside in memory.
The true correct solution is to use a database and an on demand ORM on the top. Then entities will only be pulled into memory when needed. This will make the solution much more scalable.
So for example SpringBoot JPA would be correct. The problem is our solution is a large object graph needing lots of tables

**Comment by mokun** [comment]
This time, in another session, it pinpointed another id.

```
2024-09-24T12:04:12.4 (Warning) UnitManager : Unit not found. id: 1414. Type of unit: CONTAINER (Base ID: 88).
2024-09-24T12:04:12.4 (Severe) Simulation : Cannot deserialize : Can not find Unit for id: 1414
2024-09-24T12:04:12.4 (Config) Simulation :  
2024-09-24T12:04:12.4 (Config) Simulation :                    Info on Saved Simulation                      
2024-09-24T12:04:12.4 (Config) Simulation :  ---------------------------------------------------------
2024-09-24T12:04:12.4 (Config) Simulation :                    Filename : default.sim
2024-09-24T12:04:12.4 (Config) Simulation :                        Path : C:\Users\mkhelios\.mars-sim\saved\
2024-09-24T12:04:12.4 (Config) Simulation :                        Size : 201.33 KB
2024-09-24T12:04:12.4 (Config) Simulation :               Made in Build : pre-3.9.0 - Build a45f6d7-dirty
2024-09-24T12:04:12.4 (Config) Simulation :   Current Core Engine Build : pre-3.9.0 - Build a45f6d7-dirty
2024-09-24T12:04:12.4 (Config) Simulation :           System Time Stamp : Sep 24, 2024, 11:56:07 AM
2024-09-24T12:04:12.4 (Config) Simulation :            Earth Time Stamp : 2028-08-17T05:29:20.105
2024-09-24T12:04:12.4 (Config) Simulation :          Martian Time Stamp : 01-Adir-01:472.413
2024-09-24T12:04:12.4 (Config) Simulation :  ---------------------------------------------------------
2024-09-24T12:04:12.4 (Config) Simulation :  Note : The core engine uses the same build as the saved sim.
01-Adir-01:472.413 (Config) UnitManager : Setting up 1 thread(s) for running the settlement update.
01-Adir-01:472.413 (Config) UnitManager : Setting up a settlement task thread for Terminus.
01-Adir-01:472.413 (Config) SimulationBuilder : Starting the Master Clock...
01-Adir-01:472.413 (Config) Simulation : Setting up autosave to be triggered every 900000 ms (15.0 mins).
01-Adir-01:472.413 (Config) MasterClock : Setting up 1 thread(s) for clock listener.
01-Adir-01:472.413 (Config) MasterClock : Setting up 1 thread for clock executor.
01-Adir-01:472.413 (Warning) MasterClock : [System] MasterClock : Zero elapsed real time. Resetting it back to 71 ms.
01-Adir-01:472.877 (Severe) BuildingManager : [Terminus] Lander Hab 1 - Problem applying pulse to Building
java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because "this.units" is null
	at com.mars_sim.core.data.UnitSet.contains(UnitSet.java:70)
	at com.mars_sim.core.structure.Settlement.containsPerson(Settlement.java:1686)
	at com.mars_sim.core.structure.building.function.LifeSupport.timePassing(LifeSupport.java:219)
	at com.mars_sim.core.structure.building.Building.timePassing(Building.java:1219)
	at com.mars_sim.core.structure.building.BuildingManager.timePassing(BuildingManager.java:800)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:887)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:851)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Adir-01:472.877 (Severe) UnitManager : Problem with pulse on Terminus: Cannot invoke "java.util.Set.stream()" because "this.units" is null
java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because "this.units" is null
	at com.mars_sim.core.data.UnitSet.stream(UnitSet.java:136)
	at com.mars_sim.core.person.Person.getInventorySuit(Person.java:1150)
	at com.mars_sim.core.person.Person.getSuit(Person.java:1141)
	at com.mars_sim.core.person.Person.timePassing(Person.java:642)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1066)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:891)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:851)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by mokun** [comment]
> The problem is our solution is a large object graph needing lots of tables

XML would capture saved data beyond just key-value pairs and may make more sense than JSON.

Microstream has the potential and it's quite fast and memory efficient.

Note that in this branch, we even tried [microstream](https://github.com/mars-sim/mars-sim/tree/microstream2) to serialize and deserialize a few objects.

**Comment by mokun** [comment]
But the advantage of text-based saved sim format is not just good for debugging what goes wrong with serialization, but also giving us the flexibility of crafting a variety of scenarios. 

Imagine we take a saved sim XML file with 2 settlements and edit it to become 4 settlements with just minimal efforts.

**Comment by bevans2000** [comment]
> But the advantage of text-based saved sim format is not just good for debugging what goes wrong with serialization, but also giving us the flexibility of crafting a variety of scenarios.
> 
> Imagine we take a saved sim XML file with 2 settlements and edit it to become 4 settlements with just minimal efforts.
A single settlement has many objects that would generate many JSON lines and they would all have to be copied with new unique IDs. 
But this bug has nothing to do with serialisation. There is a container created that is not registered in the UnitManager

**Comment by mokun** [comment]
> There is a container created that is not registered in the UnitManager

Right. We'll need to first back track to find out which commit caused this. 

@muybien3433 

Can you by any chance also debug to see up to what point on your branch you were not longer able to load a saved sim ?

**Comment by bevans2000** [comment]
My guess is it was the commit that I did that "cleaned up" the Equipment Factory. In the unit test created as part of that commit add an extra assert in the create equipment test to make sure the unit identifier of the created Equipment is registered in the Unit Manager.

I very briefly looked at the changed code and the addUnit call still looked present in the Equipment Factory, but that would the first place to check.

**Comment by muybien3433** [comment]
> Can you by any chance also debug to see up to what point on your branch you were not longer able to load a saved sim ?

I'm able even with the latest changes.

**Comment by mokun** [comment]
> I'm able even with the latest changes.

Interesting !

@bevans2000 

Can you also check if your local build can reload a saved sim ?

If it turns out I'm the only one affected, then I'll delete my local build and clone the one in the master branch.

**Comment by bevans2000** [comment]
I can't fix it tonight but the problem is in the ```UnitManager.addUnit``` method; line 330
```
        case CONTAINER -> {}
        case EVA_SUIT -> lookupEquipment.put(unitIdentifier, (Equipment) unit);
```

Containers are not added to the equipment list so they can never be retrieved.
I'll leave it with you

**Comment by mokun** [comment]
Thanks for identifying that. Just got fixed.
