### ISSUE TITLE
Remove redundant features from base Unit

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1475]
The ```Unit``` class has features that are only specific to a limited number of the subclasses. To remove the contradictions in the Unit hierarchy these features should be removed and relocated to the correct location:

- Coordinates
- LocationState
- Mass

**Comment by mokun** [comment]
btw, you mentioned in the past you don't like the LocationTag class. How would you deal with it ?

**Comment by bevans2000** [comment]
> btw, you mentioned in the past you don't like the LocationTag class. How would you deal with it ?

Don't know yet but it's in my cross hairs 🤣

**Comment by bevans2000** [comment]
> btw, you mentioned in the past you don't like the LocationTag class. How would you deal with it ?

So we keep LocationTag for now but it's relocated to just the Mobile unit as only that can move around. I am simplifying the logic because it's F it's only applicable to mobile units it's much simpler. Going to move LocationStateType as well. Will force it to be updated when the container changes to keep them synced.

**Comment by muybien3433** [comment]
I see that two tests have failed in SurfaceManagerTest:

```
java.lang.AssertionError: Slice #3 expected:<7> but was:<5>
Expected :7
Actual   :5
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.mars_sim.core.map.location.SurfaceManagerTest.testGetFeaturesCenterVertical(SurfaceManagerTest.java:69)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


java.lang.AssertionError: Slice #3 expected:<4> but was:<3>
Expected :4
Actual   :3
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.mars_sim.core.map.location.SurfaceManagerTest.testGetFeaturesPolarVertical(SurfaceManagerTest.java:91)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

**Comment by bevans2000** [comment]
> I see that two tests have failed in SurfaceManagerTest, which might be related to the recent changes to Coordinates.

Where you seeing these? The Coordinates changes are only on a branch at the moment and that is passing

**Comment by muybien3433** [comment]
My mistake. I was catching up yesterday and glanced through the changes you made, so I automatically assumed it might be related.
