### ISSUE TITLE
TransportManager is null

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1497]
**Describe the bug**
- From time to time (but not all the time), when loading from a saved sim, TransportManager is null and it won't load the sim at all.

**Expected and unexpected behavior**
- TransportManager should always have an instance.

**Discuss any potential problems you have and have not ruled out**
- It's possible that something prevents the old instance of TransportManager from being saved properly in the first place. When reloading a saved sim, it couldn't find that instance. Should it create a new instance of TransportManager and load the resupply data from a xml ?  

**Java classes involved**
- TransportManager, Simulation

**Screenshots**
![image](https://github.com/user-attachments/assets/d0d4bfb8-7006-4d5d-a3b4-0df0fba58829)

**Stacktrace**
```
2024-12-16T12:46:41.4 (Config) MarsProject : Starting Mars Simulation Project pre-3.9.0 - 64-bit Java 21.0.3 - 8 Cores
2024-12-16T12:46:41.4 (Config) MarsProject : List of input args : [-load, default.sim]
2024-12-16T12:46:41.4 (Config) SimulationBuilder : ---------------------------------------------------
2024-12-16T12:46:41.4 (Config) SimulationBuilder :     Java Version Full String = 21.0.3+9-LTS
2024-12-16T12:46:41.4 (Config) SimulationBuilder : Java Version Feature Element = 21
2024-12-16T12:46:41.4 (Config) SimulationBuilder : Java Version Interim Element = 0
2024-12-16T12:46:41.4 (Config) SimulationBuilder :   Java Patch Element Version = 0
2024-12-16T12:46:41.4 (Config) SimulationBuilder :  Java Update Element Version = 3
2024-12-16T12:46:41.4 (Config) SimulationBuilder :           Java Version Build = 9
2024-12-16T12:46:41.4 (Config) SimulationBuilder :   Java additional build Info = LTS
2024-12-16T12:46:41.4 (Config) SimulationBuilder :        Java Pre-Release Info = NA
2024-12-16T12:46:42.2 (Config) SimulationConfig : Done loading all xml config files.
2024-12-16T12:46:42.2 (Config) SimulationBuilder : Loading from C:\Users\mkhelios\.mars-sim\saved\default.sim
2024-12-16T12:46:42.3 (Config) MasterClock : -----------------------------------------------------
2024-12-16T12:46:42.3 (Config) MasterClock :                 Desired time-ratio : 128x
2024-12-16T12:46:42.3 (Config) MasterClock :             Min millisol per pulse : 0.0113
2024-12-16T12:46:42.3 (Config) MasterClock :         Optimal millisol per pulse : 0.0635
2024-12-16T12:46:42.3 (Config) MasterClock :             Max millisol per pulse : 14.7959
2024-12-16T12:46:42.3 (Config) MasterClock :  Max elapsed time between 2 pulses : 1000 ms
2024-12-16T12:46:42.3 (Config) MasterClock : -----------------------------------------------------
2024-12-16T12:46:42.3 (Config) Simulation : The file to be loaded is C:\Users\mkhelios\.mars-sim\saved\default.sim
2024-12-16T12:46:42.3 (Config) Simulation : Loading and processing the saved sim. Please wait...
2024-12-16T12:46:42.9 (Severe) Simulation : Can't read object stream when loading C:\Users\mkhelios\.mars-sim\saved\default.sim : com.mars_sim.core.structure.ExplorationManager; local class incompatible: stream classdesc serialVersionUID = 163207492501629595, local class serialVersionUID = 1
2024-12-16T12:46:42.9 (Config) Simulation :  
2024-12-16T12:46:42.9 (Config) Simulation :                    Info on Saved Simulation                      
2024-12-16T12:46:42.9 (Config) Simulation :  ---------------------------------------------------------
2024-12-16T12:46:42.9 (Config) Simulation :                    Filename : default.sim
2024-12-16T12:46:42.9 (Config) Simulation :                        Path : C:\Users\mkhelios\.mars-sim\saved\
2024-12-16T12:46:42.9 (Config) Simulation :                        Size : 4.24 MB
2024-12-16T12:46:42.9 (Config) Simulation :               Made in Build : unknown
2024-12-16T12:46:42.9 (Config) Simulation :   Current Core Engine Build : pre-3.9.0 - Build c964629-dirty
2024-12-16T12:46:42.9 (Config) Simulation :           System Time Stamp : Dec 16, 2024, 12:28:38 PM
2024-12-16T12:46:42.9 (Config) Simulation :            Earth Time Stamp : 2028-08-16T17:50:22
2024-12-16T12:46:42.9 (Config) Simulation :          Martian Time Stamp : 01-Adir-01:000.000
2024-12-16T12:46:42.9 (Config) Simulation :  ---------------------------------------------------------
2024-12-16T12:46:42.9 (Config) Simulation :  Note : The core engine does not use the same build as the saved sim.
2024-12-16T12:46:42.9 (Warning) Simulation : Will attempt to load a simulation made in older build unknown under a newer core engine build pre-3.9.0 - Build c964629-dirty.
01-Adir-01:000.000 (Severe) MarsProject : Problem starting Cannot invoke "com.mars_sim.core.interplanetary.transport.TransportManager.reinitalizeInstances(com.mars_sim.core.Simulation)" because "this.transportManager" is null
java.lang.NullPointerException: Cannot invoke "com.mars_sim.core.interplanetary.transport.TransportManager.reinitalizeInstances(com.mars_sim.core.Simulation)" because "this.transportManager" is null
	at com.mars_sim.core.Simulation.reinitializeInstances(Simulation.java:599)
	at com.mars_sim.core.Simulation.loadSimulation(Simulation.java:749)
	at com.mars_sim.core.SimulationBuilder.loadSimulation(SimulationBuilder.java:381)
	at com.mars_sim.core.SimulationBuilder.start(SimulationBuilder.java:288)
	at com.mars_sim.ui.swing.main.MarsProject.parseArgs(MarsProject.java:203)
	at com.mars_sim.ui.swing.main.MarsProject.main(MarsProject.java:463)

```

**Specifications**
- pre-3.9.0

**Additional context**
- Note that a minor change on a different class in my case as evident from the stacktrace above, but it is in  affect the TransportManager instance.

**Comment by mokun** [comment]
@bevans2000 @muybien3433 

Have you seen that ?

**Comment by bevans2000** [comment]
That's an odd one. I can have a look so assign it to me

**Comment by bevans2000** [comment]
There is an odd initialisation sequence for this class.

**Comment by bevans2000** [comment]
Actually it's because the Explored location doesn't load. I think adding the serialisation id you have probably fixed it

**Comment by mokun** [comment]
> Actually it's because the Explored location doesn't load. I think adding the serialisation id you have probably fixed it

Probably.

> There is an odd initialisation sequence for this class.

But what should be the 'correct' sequence ? Can you rework it ?

**Comment by bevans2000** [comment]
Interesting observation about the ```TransportManager``` is it's possible to schedule a delivery in the future that actually launched in the past, I'm not sure that is correct, . So I can use the UI to create a new Resupply delivery for tomorrow but that means it took off 65 days in the past; that's not possible. It should only be allowed when building a new Simulation and creating scheduled deliveries.
There is a lot of static references in the Transport logic.

**Comment by mokun** [comment]
> is it's possible to schedule a delivery in the future that actually launched in the past, I'm not sure that is correct,

That's because when we create a resupply mission, it asks for the date the cargo arrives, NOT the date the cargo departs from Earth. 

So we are kind of go back 60 sols prior to find the departure date.

In reality, we need to account for orbital mechanics and calculate the transit time and it should vary based on the mass of the payload and the type of propulsion being used.

**Comment by bevans2000** [comment]
Yes I get that. But do you thinks is right I can schedule a resupply for tomorrow and change the past to say it launched 65 days ago.
It's a minor thing for sure.

**Comment by mokun** [comment]
> But do you thinks is right I can schedule a resupply for tomorrow and change the past to say it launched 65 days ago.

If we are beginning to simulate launching payload on the Moon/Earth toward Mars, then it would be wrong to modify or change something in the past.

But since we're not doing that and at least not yet, I suppose it's still okay.
