### ISSUE TITLE
java.lang.IllegalArgumentException: Task phase is null

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#158]
**Describe the bug/issue**
An exception occurs repeatedly, also this exception is not written to log.

**Affected Area**
- EVAOperation.performMappedPhase
- LoadVehicleEVA.performMappedPhase

**Expected behaviors**
 - No exception
- All exceptions should be written to log

**Actual/Observed Behaviors**
```
java.lang.IllegalArgumentException: Task phase is null
        at org.mars_sim.msp.core.person.ai.task.EVAOperation.performMappedPhase(EVAOperation.java:192)
        at org.mars_sim.msp.core.person.ai.task.LoadVehicleEVA.performMappedPhase(LoadVehicleEVA.java:406)
        at org.mars_sim.msp.core.person.ai.task.Task.performTask(Task.java:528)
        at org.mars_sim.msp.core.person.ai.task.TaskManager.executeTask(TaskManager.java:378)
        at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:228)
        at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:178)
        at org.mars_sim.msp.core.person.Person.timePassing(Person.java:947)
        at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:2092)
        at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1530)
        at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.java:835)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalArgumentException: Task phase is null
        at org.mars_sim.msp.core.person.ai.task.EVAOperation.performMappedPhase(EVAOperation.java:192)
        at org.mars_sim.msp.core.person.ai.task.LoadVehicleEVA.performMappedPhase(LoadVehicleEVA.java:406)
        at org.mars_sim.msp.core.person.ai.task.Task.performTask(Task.java:528)
        at org.mars_sim.msp.core.person.ai.task.TaskManager.executeTask(TaskManager.java:378)
        at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:228)
        at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:178)
        at org.mars_sim.msp.core.person.Person.timePassing(Person.java:947)
        at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:2092)
        at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1530)
        at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.java:835)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Specifications  (please complete the following information):**
 - OS version :Windows 10
 - Java version : Oracle Java 11.0.1
 - mars-sim build version : r4600_headless_java9

**Comment by mokun** [comment]
I guess I made that temporary fix instead of really plowing through each step of way to see why it has a `null` task phase. 

Normally it should always have a task phase because it will be no point of calling `EVAOperation` in the first place for an EVA. 

I suspect it has to do with preparing the EVA suit again. 

Another possibility has to do with the state of the person inside the pressurized/depressurized airlock with its inner/outer door opening/closing. Plus the fact that there are times an operator of the airlock 'resigns'... It's not a trivial task of finding out what went wrong .

There's no atmospheric modeling inside the EVA suit at this point, unlike each building inside the settlement.

At some point, we will rework all the codes for `EVASuit` class.

**Comment by mokun** [comment]
The null task phase been fixed. Closed.
