### ISSUE TITLE
java.lang.NullPointerException in r4688

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#166]
I got the following after trying to run the newest git update - 

```
$ java -jar mars-sim-headless-3.1.0-b2.jar 
Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1024m -new
java.util.logging.ErrorManager: 5
java.lang.NullPointerException
	at org.mars_sim.headless.SimuLoggingFormatter.format(SimuLoggingFormatter.java:91)
	at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:199)
	at java.logging/java.util.logging.FileHandler.publish(FileHandler.java:751)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	at java.logging/java.util.logging.Logger.log(Logger.java:1029)
	at java.logging/java.util.logging.Logger.config(Logger.java:1815)
	at org.mars_sim.headless.MarsProjectHeadless.<init>(MarsProjectHeadless.java:50)
	at org.mars_sim.headless.MarsProjectHeadless.main(MarsProjectHeadless.java:269)
java.util.logging.ErrorManager: 5
java.lang.NullPointerException
	at org.mars_sim.headless.SimuLoggingFormatter.format(SimuLoggingFormatter.java:91)
	at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:199)
	at java.logging/java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:95)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	at java.logging/java.util.logging.Logger.log(Logger.java:1029)
	at java.logging/java.util.logging.Logger.config(Logger.java:1815)
	at org.mars_sim.headless.MarsProjectHeadless.<init>(MarsProjectHeadless.java:50)
	at org.mars_sim.headless.MarsProjectHeadless.main(MarsProjectHeadless.java:269)
2028-08-17 15:23:13 (UT) (Config) UnitManager : The nation of 'India' doesn't have any settlements.
```

I guess it might be due to the commander profile not being updated or something. I am using an old profile and maybe with the updates something got left behind ?

Update - The error gets triggered even before loading commander profile so something is amiss elsewhere. 

Please let me know how can I help ?

**Comment by mokun** [comment]
Noted. It's an instance that didn't get initialized at the start of the sim. I'll need to turn off that `Build 4688` in the release tab and reissue. Thanks!

**Comment by mokun** [comment]
Bug resolved. Closed.
