### ISSUE TITLE
Another java.lang.NullPointerException this time when loading an old profile in Build 4696

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#167]
Got the following java.lang.NullPointerException when loading the old profile - 

```
$ java -jar mars-sim-headless-3.1.0-b2.jar 
Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1024m -new
2018-12-23T12:35:05.6 (Config) MarsProjectHeadless : Starting Mars Simulation Project v3.1.0-b2 - Build 4696 - 64-bit 11.0.1 - 4 CPU threads
2018-12-23T12:35:05.6 (Config) SimulationConfig : Loading xml files...
2018-12-23T12:35:05.9 (Config) MarsProjectHeadless : Please proceed to selecting the Game Mode in the popped-up console.
java.lang.NullPointerException
	at org.mars_sim.msp.core.terminal.Commander.setMarsSocietyStr(Commander.java:120)
	at org.mars_sim.msp.core.terminal.CommanderProfile.loadProperties(CommanderProfile.java:521)
	at org.mars_sim.msp.core.terminal.CommanderProfile.loadCommander(CommanderProfile.java:469)
	at org.mars_sim.msp.core.terminal.CommanderProfile.loadProfile(CommanderProfile.java:447)
	at org.mars_sim.msp.core.terminal.InteractiveTerm.selectMode(InteractiveTerm.java:136)
	at org.mars_sim.msp.core.terminal.InteractiveTerm.startCommanderMode(InteractiveTerm.java:99)
	at org.mars_sim.headless.MarsProjectHeadless.handleNewSimulation(MarsProjectHeadless.java:239)
	at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:142)
	at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2018-12-23T12:35:16.4 (Severe) MarsProjectHeadless : Could not create a new simulation, startup cannot continue
```

**Comment by shirishag75** [comment]
```

/.mars-sim/saved$ cat commander.profile 
#Commander's Profile
#Thu Dec 20 23:35:39 IST 2018
commander.isMarsSocietyAffiliated=n
commander.gender=m
commander.age=42
commander.lastname=agarwal
commander.job=Technician
commander.country=India
commander.firstname=shirish
```

**Comment by shirishag75** [comment]
I thought something must have changed in the commander.profile hence thought it better to report. Anyway, made a new profile and fixed it. The logic should be something which you can add/change over time so if any new variables are added or changed the logger can responder with the invalid or outdated profile warning.

**Comment by mokun** [comment]
> The logic should be something which you can add/change over time so if any new variables are added or changed the logger can responder with the invalid or outdated profile warning.

Making things backward compatible is always a double-edged sword...

As the profile gets more sophisticated containing lots of lines of data, it will make sense to preserve the commander profile. 

At some point, we'll take an account of the colonizing experience of a settler so that we may resend him/her to or from the Moon, Mars or other places, etc.

**Comment by mokun** [comment]
Fixed and closed
