### ISSUE TITLE
Exception in thread "pool-4-thread-1" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#168]
Got this while playing. This was with build 4697 - 

```
2028-10-15 04:59:50 (UT) (Info) UnitManager :  - - - - - - - - - - - - Sol 58 - - - - - - - - - - - - 
2028-10-15 04:59:50 (UT) (Info) Settlement : [Alpha Base] Maintenance Task score : 421.1.
2028-10-15 04:59:50 (UT) (Info) Settlement : [Alpha Base] MaintenanceEVA Task score : 453.6.
2028-10-15 04:59:50 (UT) (Info) Settlement : [Alpha Base] RepairMalfunction Task score : 0.0.
2028-10-15 05:00:00 (UT) (Info) Settlement : [Alpha Base] RepairEVAMalfunction Task score : 0.0.
2028-10-15 05:00:00 (UT) (Info) Settlement : [Plymouth Base] Maintenance Task score : 30.7.
2028-10-15 05:00:00 (UT) (Info) Settlement : [Plymouth Base] MaintenanceEVA Task score : 148.5.
2028-10-15 05:00:00 (UT) (Info) Settlement : [Plymouth Base] RepairMalfunction Task score : 0.0.
2028-10-15 05:00:00 (UT) (Info) Settlement : [Plymouth Base] RepairEVAMalfunction Task score : 0.0.
2028-10-15 05:00:00 (UT) (Info) Settlement : [Schiaparelli Point] Maintenance Task score : 0.0.
2028-10-15 05:00:00 (UT) (Info) Settlement : [Schiaparelli Point] MaintenanceEVA Task score : 6.3.
2028-10-15 05:00:00 (UT) (Info) Settlement : [Schiaparelli Point] RepairMalfunction Task score : 0.0.
2028-10-15 05:00:00 (UT) (Info) Settlement : [Schiaparelli Point] RepairEVAMalfunction Task score : 0.0.
2028-10-15 05:08:19 (UT) (Info) Settlement : [Alpha Base] The detector grid forecast a GCR event is imminent.
2028-10-15 05:40:57 (UT) (Warning) Storage : [Alpha Base] ran out of strawberry.
2028-10-15 05:50:24 (UT) (Config) MasterClock : The simulation is paused.
2028-10-15 05:50:24 (UT) (Config) Simulation : Autosaving the simulation as default.sim.
Exception in thread "pool-4-thread-1" java.lang.StackOverflowError
	at java.base/java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:73)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1130)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
```

The error message just keeps going on.

**Comment by mokun** [comment]
Unfortunately, it doesn't say which object it has trouble serializing. I'll modify the exception handling to at least print the name of the object. And will take a look at a few places where recursive calls are used and hopefully get rid of them. Thanks for reporting it.

**Comment by mokun** [comment]
@shirishag75 , let me know if you see more StackOverflowError.

**Comment by shirishag75** [comment]
sure, will do.

**Comment by shirishag75** [comment]
will do.

**Comment by mokun** [comment]
I haven't seen any stackoverflow error. Closing this. 

On the other hand, there may be situations a simulation would hang after coming out of power saving.
