### ISSUE TITLE
NullPointerException in SolarThermalPowerSource, Test case for NullPointerException

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#176]
**Describe the bug/issue**
A repeated NPE happens in SolarThermalPowerSource when running a simulation, because surface is not initialized. 

**Affected Area**
e.g. Settlement type Trading Outpost

**Expected behaviors**
No exception, function is propertly initialized. Maybe it is a work-around to call `Simulation.reinitializeInstances` after creating a new simulation. But better would be a proper dependency injection when creating functions. 

**Actual/Observed Behaviors**
```
Exception in thread "pool-5-thread-53" java.lang.NullPointerException
	at org.mars_sim.msp.core.structure.building.function.SolarThermalPowerSource.getCurrentPower(SolarThermalPowerSource.java:59)
	at org.mars_sim.msp.core.structure.building.function.PowerGeneration.calculateGeneratedPower(PowerGeneration.java:162)
	at org.mars_sim.msp.core.structure.building.function.PowerGeneration.timePassing(PowerGeneration.java:216)
	at org.mars_sim.msp.core.structure.building.Building.timePassing(Building.java:1315)
	at org.mars_sim.msp.core.structure.building.BuildingManager.timePassing(BuildingManager.java:678)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1170)
	at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:1842)
	at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1694)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.java:943)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Reproduction (optional)**
 Start a new scenario and add a base of the type "Trading Outpost" 

**Specifications  (please complete the following information):**
 - mars-sim build version : r4752

**Comment by mokun** [comment]
Thanks @Urwumpe. That's a good catch. 

How would you write a test case to catch NullPointerException in this case ? All the junit tests were written by previous developers and so far I only modify them to work with the new changes implemented.

**Comment by Urwumpe** [comment]
Depends... Lets say, I would have full artistic freedom. I would then catch this by testing with Mockito that certain dependency injection methods  created by us are called inside a function "injectSimulationEnvironment" into factory classes and to make this simpler, I would create a generic factory creation interface that is used for injecting the environment into the factories we need and implement a registerFactory method (add factory to a list of managed factories) and implement the actual injection as working on a list of factories (so we can define new factories without needing more than copy and paste in one function of simulation).  The first JUnit test would then be as simple as creating a simple factory mock object with [Mockito](https://github.com/mockito/mockito), register it at Simulation, call the "injectSimulationEnvironment" method in Simulation, expecting that "defineSimulationEnviroment" in the factory mock object gets called once. 

Next, I would repeat the test with three factory mocks to make sure it also works with more than one... 

Finally, I would add contract testing to the JUnit tests of all factory implementations: injecting null objects should result in IllegalArgumentExceptions, etc.

Again... with full artistic freedom and a lot of personal taste. For example, its easier for me to spot errors in the creation of factory objects, the function creating them is just made of similar looking likes with helpful indentation, for example:

```
void createFactories() {
    registerFactory( new SettlementFactory() );
    registerFactory( new BuildingFactory() );
    registerFactory( new BuildingFunctionFactory() );
    //....
}
```

**Comment by mokun** [comment]
Closed.
