### ISSUE TITLE
Getting a java.lang.ArrayIndexOutOfBoundsException: Index -1500 out of bounds for length 6

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#181]
I got the following when running a new simulation - 

```
java.lang.ArrayIndexOutOfBoundsException: Index -1500 out of bounds for length 6
	at org.mars_sim.msp.core.equipment.EquipmentType.convertID2Type(EquipmentType.java:83)
	at org.mars_sim.msp.core.Inventory.findNumUnitsOfClass(Inventory.java:1397)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleGarage.loadOptionalEquipment(LoadVehicleGarage.java:811)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleGarage.loadEquipment(LoadVehicleGarage.java:705)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleGarage.loadingPhase(LoadVehicleGarage.java:415)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleGarage.performMappedPhase(LoadVehicleGarage.java:377)
	at org.mars_sim.msp.core.person.ai.task.Task.performTask(Task.java:542)
	at org.mars_sim.msp.core.person.ai.task.TaskManager.executeTask(TaskManager.java:395)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:233)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:183)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:946)
	at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:1939)
	at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1682)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.java:962)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

And after that got this - 

`0000-Adir-05:381.203 (Severe) Person : [Alpha Base] Mary Hirn's Mind was having trouble processing task selection. [ERROR: UNUSED LOG ARGUMENTS]
`

Hope you get some idea as to what went wrong here. This happened on sol 6.

**Comment by mokun** [comment]
Fixed.
