### ISSUE TITLE
illegal reflective access operation still occuring with r4864, weblaf, swing issues in linux

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#185]
I am still getting illegal reflective access operation after compiling the new build. 

This is how the error pops up - 

```
~/games/mars-sim/mars-sim-main/target$ java -jar mars-sim-main-3.1.0-b2-jar-with-dependencies.jar

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alee.utils.ReflectUtils (file:/home/shirish/games/mars-sim/mars-sim-main/target/mars-sim-main-3.1.0-b2-jar-with-dependencies.jar) to method sun.awt.UNIXToolkit.isNativeGTKAvailable()
WARNING: Please consider reporting this to the maintainers of com.alee.utils.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Please fix the issue.

**Comment by Urwumpe** [comment]
You can fix it during starting of java by adding a --add-open parameter to the commandline. 

Those are, as you can see by the `sun.*` in the beginning, mostly legacy dependencies that are no longer updated to modern java versions. We should try removing them, if they are no longer maintained.

**Comment by mokun** [comment]
> com.alee.utils.ReflectUtils

com.alee.* belongs to Weblaf. Unfortunately, we uses Weblaf through its maven dependency and it uses reflection to tinker with Swing.

**Comment by shirishag75** [comment]
with r4870 I am still getting some errors - 

https://paste.debian.net/1065304/

do you want me to do a new bug for this, the second window dies again.

**Comment by Urwumpe** [comment]
That is a different error now, but still related to Weblaf. 

`Caused by: com.alee.managers.style.StyleException: Component 'class
javax.swing.JRootPane' doesn't use WebLaF UI`

**Comment by shirishag75** [comment]
@mokun ^

**Comment by mokun** [comment]
@shirishag75 , can you test it if the exception is gone ?

**Comment by shirishag75** [comment]
nope, it isn't gone. I compiled with the new version and it stil is there. 

See https://paste.debian.net/1065717/

**Comment by mokun** [comment]
I've found the cause and will issue the update.

**Comment by mokun** [comment]
I'm setting up ubuntu on a machine and will test it directly. Linux uses GTK for graphics in Java Swing and behaves differently in Window.

**Comment by mokun** [comment]
btw, both JIDE and Weblaf library internally use reflection and com.sun.* API. Unless we quite using them, we'll have to deal with those warnings.

**Comment by mokun** [comment]
Note that there are other exceptions in linux. I just tested the latest build r4879 in my ubuntu box.

**Comment by mokun** [comment]
They all have to do with the trouble of initializing the Look and Feel (L&F) libraries in linux. There are more issues in Linux than in Windows OS. See https://stackoverflow.com/questions/3954616/java-look-and-feel-lf

**Comment by shirishag75** [comment]
> They all have to do with the trouble of initializing the Look and Feel (L&F) libraries in linux. There are more issues in Linux than in Windows OS. See https://stackoverflow.com/questions/3954616/java-look-and-feel-lf

That actually just talks about the various l&f libraries as options doesn't talk anywhere about how linux is worse than MS-Windows. I upvoted it as it's a good resource for somebody who might be looking at java l&f libraries to know what options there are.

**Comment by mokun** [comment]
Please see the last couple paragraphs at the end of this [page](https://github.com/mgarin/weblaf/wiki/Window-decoration) talking about weblaf. 

Each L&F libraray has their own ways of tweaking Java Swing to look nice over different platform. 

We're hoping Java 9 and above will be more consistent with how graphics are rendered by Java Swing as linux have various versions of [GTK](https://www.infoworld.com/article/3035505/java/java-9-to-address-gtk-gui-pains-on-linux.html) for rendering graphics over the years. 

What you see in Linux is not necessarily the same as what you see in Windows.

We use UI elements from a few L&F libraries (namely, weblaf, nimrod and jide).  We'll pay attention to how well they behave in linux.

**Comment by shirishag75** [comment]
I did see this today while compiling - 
```

[DEBUG] =======================================================================
[DEBUG] Could not find metadata com.weblookandfeel:weblaf-ui:1.2.9-SNAPSHOT/maven-metadata.xml in local (/home/shirish/.m2/repository)
```

**Comment by mokun** [comment]
@shirishag75 , do you want to post that issue in weblookandfeel's git ?

Other people encounter similar issues as well. See https://duckduckgo.com/?q=%5BDEBUG%5D+Could+not+find+metadata&atb=v10&ia=web

**Comment by shirishag75** [comment]
Just shared this issue there, let's see if they respond back.

**Comment by mokun** [comment]
@shirishag75 ,

Can you edit that to be more specific at what we want them to look into ? This thread has a number of issues and they will probably ask you for clarification.

**Comment by mokun** [comment]
I made a change 10 mins ago in [MainWindow](https://github.com/mars-sim/mars-sim/commit/9f3f0dc7cfaa70d34ede6345d3b6742df660f77c#diff-22157001c40fafcec54a8401941ed12b). 

Can you test run to see if the exceptions go away ?

**Comment by shirishag75** [comment]
@mokun I don't even know where that occured so it's going to be hard for me to tell them. 

AFA r4886 is concerned, the issue is still persisting - 
```

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alee.utils.ReflectUtils (file:/home/shirish/games/mars-sim/mars-sim-main/target/mars-sim-main-3.1.0-b2-jar-with-dependencies.jar) to method sun.awt.UNIXToolkit.isNativeGTKAvailable()
WARNING: Please consider reporting this to the maintainers of com.alee.utils.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

**Comment by mokun** [comment]
They already know about that illegal reflective issue. I've asked them if they can do something. It's a well known issue with the XStream library that weblaf and thousands of other app are also using.

What I meant is to just ask them one issue at a time. I would think the metadata.xml one you mentioned earlier is a good one. They won't need to look at our thread to decipher what we need. We just need them to resolve their own piece. 

> [DEBUG] =======================================================================
> [DEBUG] Could not find metadata com.weblookandfeel:weblaf-ui:1.2.9-SNAPSHOT/maven-metadata.xml in local (/home/shirish/.m2/repository)
>

**Comment by mokun** [comment]
```
Exception in thread "Timer-2" java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:848)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:598)
	at com.jidesoft.swing.JideTabbedPane.updateUI(JideTabbedPane.java:329)
```

JIDE library is a separate laf library. It has nothing to do with weblaf.

**Comment by mokun** [comment]
Let's delete that hyperlink that connect their issue tracker to our issue here as courtesy.

**Comment by shirishag75** [comment]
I deleted it there, might take some time for that reference to be cut off.

**Comment by mokun** [comment]
Just made another change in my window platform. See if it still complains about the usage of JideTabbedPane in UnitWindow.

**Comment by shirishag75** [comment]
with 4887 it gives - 

```
Exception in thread "Timer-2" java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:848)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
	at org.mars_sim.msp.ui.swing.unit_window.UnitWindow.<init>(UnitWindow.java:248)
	at org.mars_sim.msp.ui.swing.unit_window.structure.SettlementUnitWindow.<init>(SettlementUnitWindow.java:32)
	at org.mars_sim.msp.ui.swing.unit_window.UnitWindowFactory.getUnitWindow(UnitWindowFactory.java:47)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.openUnitWindow(MainDesktopPane.java:706)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.cacheSettlementUnitWindow(MainDesktopPane.java:1155)
	at org.mars_sim.msp.ui.swing.MainWindow$DelayTimer2.run(MainWindow.java:352)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more

```

**Comment by mokun** [comment]
Jide is at https://github.com/jidesoft/jide-oss/issues

We are currently using an old version since we are using its maven artifact, instead of loading their jar manually and directly.

They haven't updated it in Maven Central for over a year.

Other have asked them [why](https://github.com/jidesoft/jide-oss/issues/27).

**Comment by shirishag75** [comment]
I am guessing this is going to take more time than what we have atm.

**Comment by mokun** [comment]
After the last build, the exceptions are gone in my ubuntu box.

**Comment by mokun** [comment]
See this [thread](https://github.com/x-stream/xstream/issues/101#issuecomment-462185560) regarding the Xstream's use of reflection.

**Comment by shirishag75** [comment]
Everything works except  no audio, perhaps I should file a new bug for that one, this is with r4891

**Comment by shirishag75** [comment]
got this today while running the sim. 

```
WARNING: Illegal reflective access by com.alee.utils.ReflectUtils (file:/home/shirish/games/mars-sim/mars-sim-main/target/mars-sim-main-3.1.0-b2-jar-with-dependencies.jar) to method sun.awt.UNIXToolkit.isNativeGTKAvailable()
WARNING: Please consider reporting this to the maintainers of com.alee.utils.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "AWT-EventQueue-0" com.alee.managers.style.StyleException: Skin 'Light skin' doesn't have any styles for component type: panel[class javax.swing.JPanel, PanelUI, class com.alee.laf.panel.WPanelUI, class com.alee.laf.panel.WebPanelUI, StyleId [ id: 'panel'; parent: null ]]
	at com.alee.managers.style.data.SkinInfo.getStyle(SkinInfo.java:496)
	at com.alee.managers.style.XmlSkin.getStyle(XmlSkin.java:161)
	at com.alee.managers.style.AbstractSkin.applySkin(AbstractSkin.java:64)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:280)
	at com.alee.managers.style.StyleManager.installSkin(StyleManager.java:1125)
	at com.alee.laf.panel.WebPanelUI.installUI(WebPanelUI.java:63)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
	at java.desktop/javax.swing.JRootPane.createGlassPane(JRootPane.java:521)
	at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:348)
	at java.desktop/javax.swing.JInternalFrame.createRootPane(JInternalFrame.java:360)
	at java.desktop/javax.swing.JInternalFrame.<init>(JInternalFrame.java:337)
	at org.mars_sim.msp.ui.swing.toolWindow.ToolWindow.<init>(ToolWindow.java:51)
	at org.mars_sim.msp.ui.swing.tool.commander.CommanderWindow.<init>(CommanderWindow.java:89)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.prepareToolWindows(MainDesktopPane.java:378)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.<init>(MainDesktopPane.java:184)
	at org.mars_sim.msp.ui.swing.MainWindow.<init>(MainWindow.java:175)
	at org.mars_sim.main.MarsProject$DelayTimer.lambda$run$0(MarsProject.java:359)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by yamankatby** [comment]
I have the same issue
[https://stackoverflow.com/questions/59475813/an-illegal-reflective-access-operation-has-occurred](My question on StackOverFlow)

**Comment by shirishag75** [comment]
@yamankatby @mokun see this huge thread  https://github.com/google/guice/issues/1133#issuecomment-568117370 apparently somebody is working on it but when they will be to fix it and send it to upstream to get the code reviewed and then merged is anybody's guess.

**Comment by mokun** [comment]
This is no longer a bug since we have identified the cause and we can't do anything for it right now.

If weblaf begins to release version 2.0, the exception statements will go away.

**Comment by mokun** [comment]
@bevans2000 

Since weblaf has reflective issues, shall we switch from weblaf to [radiance](https://github.com/kirill-grouchnikov/radiance) ?

It's compatible with Java 11 and should be good with 17 when it comes out.

**Comment by bevans2000** [comment]
Yes why not. What is the effort to transition?
Also considering old JARs #83 should be addressed as well.

**Comment by mokun** [comment]
> Yes why not. What is the effort to transition?

It may take a while to switch over. Besides theming, weblaf does have some useful tools that we have been using.

The IconManager can handle svg image well.

The ToolTipManager is a much needed improvement over the old swing based tooltip that output ugly tooltip.

The WebCombobox looks better.

We also use WebSwitch for the pause/play switch and WebMemoryBar for showing memory/heap space.
