### ISSUE TITLE
IndexOutOfBoundsException, SpotBugs

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#186]
I dunno if I should have reopened up #184 or make a new one hence making a new one. This is with rr4864 . I got the following error - 

```
~/games/mars-sim/mars-sim-main/target$ java -jar mars-sim-main-3.1.0-b2-jar-with-dependencies.jar

2019-02-03T11:22:51.6 (Config) Simulation : Done initializing intransient data.
2019-02-03T11:22:51.6 (Warning) UpTimer : Time limit exceeded between the last and this call, total # of pulses : 1
0000-Adir-01:000.004 (Info) UnitManager :  - - - - - - - - - - - - Sol 1 - - - - - - - - - - - - 
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.prepareListeners(MainDesktopPane.java:328)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.<init>(MainDesktopPane.java:162)
	at org.mars_sim.msp.ui.swing.MainWindow.<init>(MainWindow.java:136)
	at org.mars_sim.msp.ui.swing.configeditor.SimulationConfigEditor$4.actionPerformed(SimulationConfigEditor.java:252)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at com.alee.laf.button.WButtonListener.mouseReleased(WButtonListener.java:250)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The simulation sort of works, but then the above error messages come sometime so I do not know whether i can trust the save file. Please fix this issue as well.

**Comment by Urwumpe** [comment]
Its correct to make this a new issue - while its the same kind of error, it takes place in a different location. 

Maybe it would help running FindBugs over MSP during build as well. I don't know how many warnings we will get there when running it now, but I can test it.

**Comment by mokun** [comment]
Somehow when I run it under eclipse IDE and java 8. it wasn't an issue. It's fixed anyway now.

**Comment by mokun** [comment]
> Maybe it would help running FindBugs over MSP during build as well. 

What does it take to set up FindBugs ?

I'm reading [this](https://stackoverflow.com/questions/8564208/how-to-generate-a-html-report-for-findbugs-with-maven-3-x?rq=1)

Will add that to our pom.xml to see what it can do.

**Comment by mokun** [comment]
I'm going to use [spotbugs](https://spotbugs.github.io/) since findbugs is no longer maintained.

**Comment by mokun** [comment]
Fixed.
