### ISSUE TITLE
Could not create a new simulation, startup cannot continue in r4906

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#190]
Dear all, 

Got the following exception - 

```
2019-02-18T01:35:55.2 (Config) CommanderProfile : Commander's profile loaded: {commander.gender=m, commander.age=42, commander.lastname=agarwal, commander.job=Technician, commander.country=India, commander.firstname=shirish, commander.MarsSociety=n}
java.lang.NullPointerException
	at org.mars_sim.msp.core.UnitManager.getCountryID(UnitManager.java:2298)
	at org.mars_sim.msp.core.UnitManager.mapCountry2Sponsor(UnitManager.java:2252)
	at org.mars_sim.msp.core.person.Commander.getSponsor(Commander.java:155)
	at org.mars_sim.msp.core.person.Commander.toString(Commander.java:180)
	at org.mars_sim.msp.core.terminal.InteractiveTerm.selectMode(InteractiveTerm.java:142)
	at org.mars_sim.msp.core.terminal.InteractiveTerm.startModeSelection(InteractiveTerm.java:98)
	at org.mars_sim.main.MarsProject.handleNewSimulation(MarsProject.java:376)
	at org.mars_sim.main.MarsProject.initializeSimulation(MarsProject.java:172)
	at org.mars_sim.main.MarsProject$SimulationTask.run(MarsProject.java:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-02-18T01:35:55.3 (Severe) MarsProject : Could not create a new simulation, startup cannot continue
```

![unable-to-create-a-new-simulation](https://user-images.githubusercontent.com/727626/52918545-2c670680-32f0-11e9-8f74-bf8a177cd711.png)

**Comment by mokun** [comment]
Will look into it. Thanks

Also, I'll rewrite it in such a way that the commander profile will be a json file.

**Comment by mokun** [comment]
Fixed and closed.
