### ISSUE TITLE
NullPointerException when starting simulation in Sandbox mode

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#192]
**Describe the bug/issue**
When you start the simulation in sandbox mode, no GUI appears and a NullPointerException is logged.

**Affected Area**
MarsProject - initializing the GUI.

**Expected behaviors**
GUI is displayed without commander mode extensions (Commander Dashboard)

**Actual/Observed Behaviors**

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mars_sim.msp.ui.swing.tool.commander.CommanderWindow.createTaskPanel(CommanderWindow.java:176)
	at org.mars_sim.msp.ui.swing.tool.commander.CommanderWindow.<init>(CommanderWindow.java:120)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.prepareToolWindows(MainDesktopPane.java:375)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.<init>(MainDesktopPane.java:184)
	at org.mars_sim.msp.ui.swing.MainWindow.<init>(MainWindow.java:175)
	at org.mars_sim.msp.ui.swing.configeditor.SimulationConfigEditor$DelayTimer.lambda$run$0(SimulationConfigEditor.java:384)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Reproduction (optional)**
Just starting the current development revision of the simulation in sandbox mode

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version : JDK11, OpenJFX11, JRE 64-bit 11.0.1
 - mars-sim build version : v3.1.0-b2 - Build 4935

**Comment by Urwumpe** [comment]
GameManager.mode is a rather unfortunate way to tell if the Game is running in commander mode or not. Do we have something smarter in SimulationConfig?

**Comment by mokun** [comment]
Sure. Do feel free to use whatever way to track the game mode.

**Comment by mokun** [comment]
Fixed [here](https://github.com/mars-sim/mars-sim/commit/42ab422493314ed000f80b8a77bf46932deac075)
