### ISSUE TITLE
getting errors while trying to compile r4966 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#202]
I am getting the following errors while trying to compile mars-sim -

```
Aug 17, 2019 7:15:07 PM org.mars_sim.msp.core.SimulationConfig loadDefaultConfiguration
SEVERE: Error reading config file(s) below : Invalid token=CURLYOPEN at (line no=12, column no=4, offset=366). Expected tokens are: [COMMA]
javax.json.stream.JsonParsingException: Invalid token=CURLYOPEN at (line no=12, column no=4, offset=366). Expected tokens are: [COMMA]
	at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:450)
	at org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:79)
	at org.glassfish.json.JsonParserImpl$ArrayContext.getNextEvent(JsonParserImpl.java:557)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
	at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:324)
	at org.glassfish.json.JsonParserImpl.getValue(JsonParserImpl.java:180)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:341)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:173)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:112)
	at org.mars_sim.msp.core.science.ScienceConfig.<init>(ScienceConfig.java:104)
	at org.mars_sim.msp.core.SimulationConfig.loadDefaultConfiguration(SimulationConfig.java:827)
	at org.mars_sim.msp.core.SimulationConfig.loadConfig(SimulationConfig.java:233)
	at org.mars_sim.msp.core.person.ai.task.WalkingStepsTest.testWalkingStepsRoverToBuilding(WalkingStepsTest.java:530)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Aug 17, 2019 7:15:07 PM org.mars_sim.msp.core.SimulationConfig loadDefaultConfiguration
```

While it did compile in the end the above was seen. 

This is the command used for compilation - 
`
~/games/mars-sim$ mvn clean package install -DcompilerArgs -X`

**Comment by mokun** [comment]
My sledge of hand on the keyboard added an unneeded "carriage return" on the file `areology_topics.json`. on line 22. 

That's why the Json reader could NOT parse that file and throw an JsonParsingException.

Thanks for catching that !

**Comment by mokun** [comment]
No all Json parsers behave the same way. See http://seriot.ch/parsing_json.php

May be at some point when we have modding tools or DSL of our own in mars-sim, we can provide better exception handling when things go wrong.

**Comment by Urwumpe** [comment]
> 
> 
> No all Json parsers behave the same way. See http://seriot.ch/parsing_json.php
> 
> May be at some point when we have modding tools or DSL of our own in mars-sim, we can provide better exception handling when things go wrong.

Modding tools sounds like a good plan - at least when using JSON. XML is better suited for letting humans edit the files directly because its syntax allows more precise formulations and structure. 

Also, I meant DSL lately as "internal DSL" - not a scripting language of our own. Just something that works fine with Java and Kotlin and makes it easier to describe complex tasks. Sure it would be only a small challenge to use [javax.script](https://docs.oracle.com/en/java/javase/12/docs/api/java.scripting/javax/script/package-summary.html) to allow putting scripting code into XML or JSON files as well.
