### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#206]
I am getting the following on the console, have no clue why .  - 

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Component.show(Component.java:1679)
	at java.desktop/java.awt.Window.show(Window.java:1059)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at org.mars_sim.msp.ui.swing.MainWindow.init(MainWindow.java:335)
	at org.mars_sim.msp.ui.swing.MainWindow.<init>(MainWindow.java:189)
	at org.mars_sim.main.MarsProject$DelayTimer.lambda$run$0(MarsProject.java:359)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by mokun** [comment]
Is it everytime you are starting a new simulation ?

or when you are loading a saved sim ?

**Comment by shirishag75** [comment]
It was definitely in saved sim but will also see if it happens in a new simulation but that will have to wait probably for tomorrow.

**Comment by mokun** [comment]
> 	at org.mars_sim.msp.ui.swing.MainWindow.init(MainWindow.java:335)

It's when calling setVisible() in `MainWindow.java` that it got messed up.

https://github.com/mars-sim/mars-sim/blob/0773c4b272a9120abeb44864e3854d0dca1288d9/mars-sim-ui/src/main/java/org/mars_sim/msp/ui/swing/MainWindow.java#L335

I have no problem starting a new sim or loading from a saved sim in Windows OS.

Are you clicking anything in the main window or opening anything at that moment ?

**Comment by mokun** [comment]
> Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3

Another thing is that it said `AWT-EventQueue-0`. So it would have to do with the Swing's UI thread having concurrent access issues.  And it said it was looking for a specific component and was erroneously iterate beyond the index of 3.

At the start of a standard simulation, a delay timer in MainWindow is responsible for gradually opening up 3 Settlement Windows (one by one), it was a highly intensive CPU task.

**Comment by mokun** [comment]
@shirishag75 , there isn't enough information about this exception. suggesting closing it if it doesn't pop up on your radar screen anymore.
