### ISSUE TITLE
java.io.FileNotFoundException and other such bugs when compiling r4971

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#210]
Got the following error when trying to compile the new git head r4971

```
java.io.FileNotFoundException: Source 'home/shirish/games/mars-sim/mars-sim-core/target/classes/conf' does not exist
	at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1383)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1346)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1246)
	at org.apache.commons.io.FileUtils.copyDirectoryToDirectory(FileUtils.java:1187)
	at org.mars_sim.msp.core.SimulationConfig.loadConfig(SimulationConfig.java:260)
	at org.mars_sim.msp.core.TestInventory.setUp(TestInventory.java:23)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by mokun** [comment]
The latest build should fix the issue with linux when deriving the path for conf directory

**Comment by shirishag75** [comment]
thank you, that fixed it.
