### ISSUE TITLE
Unable to have a new simulation with r4976, xml files management

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#216]
Hi all, 

I am getting the following error when trying to start a brand new simulation with the new compile - 

```
~/games/mars-sim/mars-sim-headless/target$ java -jar mars-sim-headless-3.1.0-b2-jar-with-dependencies.jar
Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1024m -new
2019-08-25T06:27:22.0 (Config) MarsProjectHeadless : Starting Mars Simulation Project v3.1.0-b2 - Build 4976 - 64-bit 11.0.4 - 4 CPU threads
2019-08-25T06:27:22.1 (Config) SimulationConfig : conf folder already existed. See backup folder. Please make sure you backup all modified xml before proceeding.
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:418)
	at org.mars_sim.msp.core.SimulationConfig.setUpXMLDir(SimulationConfig.java:294)
	at org.mars_sim.msp.core.SimulationConfig.loadConfig(SimulationConfig.java:276)
	at org.mars_sim.headless.MarsProjectHeadless.handleNewSimulation(MarsProjectHeadless.java:226)
	at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:140)
	at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-08-25T06:27:22.3 (Severe) MarsProjectHeadless : Could not create a new simulation, startup cannot continue
```

Please let me know what the issue might be.

**Comment by shirishag75** [comment]
Evem doing new where I was thinking it would ask me to do a new profie and all doesn't work. 

```
$ java -jar mars-sim-headless-3.1.0-b2-jar-with-dependencies.jar 
Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1024m -new
2019-08-27T05:51:28.3 (Config) MarsProjectHeadless : Starting Mars Simulation Project v3.1.0-b2 - Build 4976 - 64-bit 11.0.4 - 4 CPU threads
2019-08-27T05:51:28.4 (Config) SimulationConfig : conf folder already existed. See backup folder. Please make sure you backup all modified xml before proceeding.
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:418)
	at org.mars_sim.msp.core.SimulationConfig.setUpXMLDir(SimulationConfig.java:294)
	at org.mars_sim.msp.core.SimulationConfig.loadConfig(SimulationConfig.java:276)
	at org.mars_sim.headless.MarsProjectHeadless.handleNewSimulation(MarsProjectHeadless.java:226)
	at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:140)
	at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-08-27T05:51:28.5 (Severe) MarsProjectHeadless : Could not create a new simulation, startup cannot continue
```

**Comment by mokun** [comment]
For now, the `loadConfig` method in SimulationConfig will look into the `xml` folder and find the `version.txt` and look up the *build tag* on first line of its content.

It will say, for example, `5015`. If the core engine also runs on build 5015, it means both the xml files and the core engine having the same build. 

At that case, no change is made.

If they are of different build, say, the xml files' build is 5014, then the core engine will 
- copy the `xml` folder into `/backup/5014/` folder
- remove the content of the `xml` folder
- copy over the new xml files there
- create a new `version.txt` file and put in the 5015 build tag

**Comment by mokun** [comment]
Closing this now.
