### ISSUE TITLE
Repairbot walked outside in response to an accident on a vehicle.

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#22]
Tested on r3866.

Questions: 

A. Why are RepairBot allowed to walk outside ?

B. How reasonable is it for strapped personnel inside a broken vehicle to be emergency moved back to the settlement ?

I've pieced together a mishap report detailing the following course of actions (COA) : 

1. An accident (Water Contamination) occurs in a Opportunity II and all occupants were emergency moved back to the settlement.

2. Osprey starting a rescue mission for Opportunity II. Xiaojian Yu and Rufen Xiao are the members of the rescue team.

> Feb 18, 2017 12:27:18 PM(INFO) core.person.ai.mission.Mission Rescue/Salvage Vehicle started by Xiaojian Yu at Alpha Base

3. Water Contamination Emergency repaired finished.

> Feb 18, 2017 12:27:47 PM(INFO) core.malfunction.Malfunction Water Contamination (Code: 47cf5fdf) Emergency repaired finished.
> Feb 18, 2017 12:28:16 PM(INFO) core.person.ai.mission.RescueSalvageVehicle Osprey starting rescue mission for Opportunity II

4. An accident (Electrical Short) occurs in Osprey.  Xiaojian Yu's EVA suit was ruined. He was strapped. 

> Feb 18, 2017 12:32:12 PM(SEVERE) core.person.ai.task.ExitAirlock Xiaojian Yu cannot exit airlock from Osprey since no EVA suit is available.
> Feb 18, 2017 12:32:12 PM(SEVERE) core.person.ai.task.Walk Xiaojian Yu cannot exit airlock at Osprey

5. Note that both Osprey and Opportunity II are still at the settlement's premises and are not departing yet.

6. Finally,  Xiaojian Yu was safely moved to the settlement.

> Feb 18, 2017 12:32:12 PM(SEVERE) core.person.ai.mission.RoverMission Xiaojian Yu unable to walk to building Garage
> Feb 18, 2017 12:32:12 PM(SEVERE) core.person.ai.mission.RoverMission Xiaojian Yu emergency moved to building Garage

7. The two RepairBots 005 and 014 were on sleep mode (calling SleepMeta) but somehow leap into action to walk outside of the settlement toward Opportunity.

> Feb 18, 2017 12:32:13 PM(WARNING) core.robot.ai.BotMind RepairBot 005 could not get new action
> java.lang.NullPointerException
> 	at org.mars_sim.msp.core.person.ai.task.WalkingSteps$WalkState.access$500(WalkingSteps.java:1344)
> 	at org.mars_sim.msp.core.person.ai.task.WalkingSteps.determineWalkingSteps(WalkingSteps.java:300)
> 	at org.mars_sim.msp.core.person.ai.task.WalkingSteps.<init>(WalkingSteps.java:83)
> 	at org.mars_sim.msp.core.person.ai.task.Walk.canWalkAllSteps(Walk.java:527)
> 	at org.mars_sim.msp.core.person.ai.task.Task.createWalkingSubtask(Task.java:1131)
> 	at org.mars_sim.msp.core.person.ai.task.Task.walkToActivitySpotInBuilding(Task.java:821)
> 	at org.mars_sim.msp.core.person.ai.task.Task.walkToActivitySpotInBuilding(Task.java:763)
> 	at org.mars_sim.msp.core.person.ai.task.Sleep.<init>(Sleep.java:294)
> 	at org.mars_sim.msp.core.person.ai.task.meta.SleepMeta.constructInstance(SleepMeta.java:300)
> 	at org.mars_sim.msp.core.robot.ai.task.BotTaskManager.getNewTask(BotTaskManager.java:465)
> 	at org.mars_sim.msp.core.robot.ai.BotMind.getNewAction(BotMind.java:322)
> 	at org.mars_sim.msp.core.robot.ai.BotMind.takeAction(BotMind.java:161)
> 	at org.mars_sim.msp.core.robot.ai.BotMind.takeAction(BotMind.java:150)
> 	at org.mars_sim.msp.core.robot.ai.BotMind.timePassing(BotMind.java:109)
> 	at org.mars_sim.msp.core.robot.Robot.timePassing(Robot.java:409)
> 	at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:1906)
> 	at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:847)
> 	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.java:713)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> Feb 18, 2017 12:32:13 PM(WARNING) core.robot.ai.BotMind RepairBot 014 could not get new action
> java.lang.NullPointerException
> 	at org.mars_sim.msp.core.person.ai.task.WalkingSteps$WalkState.access$500(WalkingSteps.java:1344)
> 	at org.mars_sim.msp.core.person.ai.task.WalkingSteps.determineWalkingSteps(WalkingSteps.java:300)
> 	at org.mars_sim.msp.core.person.ai.task.WalkingSteps.<init>(WalkingSteps.java:83)
> 	at org.mars_sim.msp.core.person.ai.task.Walk.canWalkAllSteps(Walk.java:527)
> 	at org.mars_sim.msp.core.person.ai.task.Task.createWalkingSubtask(Task.java:1131)
> 	at org.mars_sim.msp.core.person.ai.task.Task.walkToActivitySpotInBuilding(Task.java:821)
> 	at org.mars_sim.msp.core.person.ai.task.Task.walkToActivitySpotInBuilding(Task.java:763)
> 	at org.mars_sim.msp.core.person.ai.task.Sleep.<init>(Sleep.java:294)
> 	at org.mars_sim.msp.core.person.ai.task.meta.SleepMeta.constructInstance(SleepMeta.java:300)
> 	at org.mars_sim.msp.core.robot.ai.task.BotTaskManager.getNewTask(BotTaskManager.java:465)
> 	at org.mars_sim.msp.core.robot.ai.BotMind.getNewAction(BotMind.java:322)
> 	at org.mars_sim.msp.core.robot.ai.BotMind.takeAction(BotMind.java:161)
> 	at org.mars_sim.msp.core.robot.ai.BotMind.takeAction(BotMind.java:150)
> 	at org.mars_sim.msp.core.robot.ai.BotMind.timePassing(BotMind.java:109)
> 	at org.mars_sim.msp.core.robot.Robot.timePassing(Robot.java:409)
> 	at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:1906)
> 	at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:847)
> 	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.java:713)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 

see [stacktrace.txt](https://github.com/mars-sim/mars-sim/files/785320/stacktrace.txt)

see pic 1 : ![osprey rescuing opportunity ii](https://cloud.githubusercontent.com/assets/1168584/23097000/046122b6-f5de-11e6-988d-5c3acd483105.png)

see pic 2 : ![both osprey and opportunity ii at premise](https://cloud.githubusercontent.com/assets/1168584/23096971/1b1e34f4-f5dd-11e6-860e-a10fe0607e91.png)

see pic 3 : ![two members of rescue team](https://cloud.githubusercontent.com/assets/1168584/23096969/14fa436a-f5dd-11e6-9b80-f7f943e2b1e9.png)

**Comment by mokun** [comment]
In addition to the RepairBot issue, I found out there is incomplete coding error :

Line 459 was executed in performDisembarkToSettlementPhase() in RoverMission to log how a person is "unable to walk to building" xyz.

Immediately after, however, line 460 was executed to instantly "emergency moved" a person from a broken Vehicle to a Settlement.
```

// TODO Refactor.
if (member instanceof Person) {
    Person person = (Person) member;
    if (Walk.canWalkAllSteps(person, adjustedLoc.getX(), adjustedLoc.getY(), destinationBuilding)) {
        assignTask(person, new Walk(person, adjustedLoc.getX(), adjustedLoc.getY(), destinationBuilding));
    }
    else {
        logger.severe(Msg.getString("RoverMission.log.unableWalkBuilding",person.getName(),destinationBuilding.getName())); //$NON-NLS-1$
        logger.severe(Msg.getString("RoverMission.log.emergencyEnterBuilding",person.getName(),destinationBuilding.getName())); //$NON-NLS-1$
        if (person.getLocationSituation() == LocationSituation.IN_VEHICLE) {
            person.getVehicle().getInventory().retrieveUnit(person);
        }
        disembarkSettlement.getInventory().storeUnit(person);
        BuildingManager.addPersonOrRobotToBuilding(person, destinationBuilding, adjustedLoc.getX(), adjustedLoc.getY());
    }
}
```

This is like "cheating" since it doesn't involve any logical progression of a rescue operation of this strapped person.

**Comment by mokun** [comment]
Just commented out more codes that have to do with making repairbot go out for an EVA repair in [r3898](https://github.com/mars-sim/mars-sim/commit/9e533191c8e00eceea7b5ff9b4a2c8b8d3e5b9f6) and 
[r3901](https://github.com/mars-sim/mars-sim/commit/05f9326eb32cddfea6532baff3c8fe74e8394059)

**Comment by mokun** [comment]
closed. no bots have been reported to leave the settlement.
