### ISSUE TITLE
Still have issues compiling with r5034

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#227]
I was informed by Manny Kung that the test cases which had problems had been commented out, but I still have not been able to compile successfully if I don't use 

`~/games/mars-sim$ mvn -DskipTests clean kotlin:compile package install`

If I take out ` -DskipTests` I get the following errors still. It starts from - 

```
[INFO] Running org.mars_sim.msp.core.person.ai.task.WalkOutsideTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.123 s <<< FAILURE! - in org.mars_sim.msp.core.person.ai.task.WalkOutsideTest
[ERROR] testDetermineWalkingPath(org.mars_sim.msp.core.person.ai.task.WalkOutsideTest)  Time elapsed: 0.067 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.WalkOutsideTest.testDetermineWalkingPath(WalkOutsideTest.java:285)

[ERROR] testGetLocalObstacleSearchLimits(org.mars_sim.msp.core.person.ai.task.WalkOutsideTest)  Time elapsed: 0.056 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.WalkOutsideTest.testGetLocalObstacleSearchLimits(WalkOutsideTest.java:372)

[INFO] Running org.mars_sim.msp.core.person.ai.task.JUnitTests
[ERROR] Tests run: 12, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.455 s <<< FAILURE! - in org.mars_sim.msp.core.person.ai.task.JUnitTests
[ERROR] testDetermineWalkingPath(org.mars_sim.msp.core.person.ai.task.WalkOutsideTest)  Time elapsed: 0.068 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.WalkOutsideTest.testDetermineWalkingPath(WalkOutsideTest.java:285)

[ERROR] testGetLocalObstacleSearchLimits(org.mars_sim.msp.core.person.ai.task.WalkOutsideTest)  Time elapsed: 0.047 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.WalkOutsideTest.testGetLocalObstacleSearchLimits(WalkOutsideTest.java:372)
```
The WalkOutside test seems to have issues still, maybe that needs to be commented or fixed.  :(

**Comment by mokun** [comment]
You can run one test case at a time. 

There's a good chance that if you run `WalkOutside all by itself, it will pass.

**Comment by mokun** [comment]
See https://stackoverflow.com/questions/1873995/run-a-single-test-method-with-maven#5988315

**Comment by shirishag75** [comment]
> You can run one test case at a time.
> 
> There's a good chance that if you run `WalkOutside` all by itself, it will pass.
> 
> And you can also run one _method_ at a time within a big test class.

Please share how can I do that ?  I tried - 

~```
/games/mars-sim/mars-sim-mapdata$ mvn -e test -Dtest=WalkOutsideTest 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.github.mars-sim:mars-sim-mapdata >----------------
[INFO] Building mars-sim-mapdata 3.1.0-b2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mars-sim-mapdata ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (java-compile) @ mars-sim-mapdata ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ mars-sim-mapdata ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/shirish/games/mars-sim/mars-sim-mapdata/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (java-test-compile) @ mars-sim-mapdata ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ mars-sim-mapdata ---
[INFO] No tests to run.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.666 s
[INFO] Finished at: 2019-09-15T15:34:25+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project mars-sim-mapdata: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project mars-sim-mapdata: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:841)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
Give me something step-by-step so I know what I should be doing and will try to accomplish the same.

**Comment by mokun** [comment]
Actually in [WalkOutsideTest](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/test/java/org/mars_sim/msp/core/person/ai/task/WalkOutsideTest.java), everything has been commented out :D

However, in that ` JUnitTests` class in the same directory : 

 https://github.com/mars-sim/mars-sim/blob/a9529d7a543004d5d21509e8dc2f5b27d07fb412/mars-sim-core/src/test/java/org/mars_sim/msp/core/person/ai/task/JUnitTests.java#L48-L61

We should have added "//" in front of this line to comment it out as well so that it will not look for tests in `WalkOutsideTest` at all.

//	    suite.addTestSuite(WalkOutsideTest.class);

**Comment by shirishag75** [comment]
I did that and tried - 

	```
public static Test suite() {
	    TestSuite suite = new TestSuite(thisClass);
	    
	    suite.addTestSuite(LoadVehicleTest.class);
	    suite.addTestSuite(UnloadVehicleTest.class);
//	    suite.addTestSuite(WalkingStepsTest.class);
	    suite.addTestSuite(WalkInteriorTest.class);
//	    suite.addTestSuite(WalkOutsideTest.class);
```

And now it errors out at - 

[INFO] Running org.mars_sim.msp.core.person.ai.task.WalkOutsideTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.14 s <<< FAILURE! - in org.mars_sim.msp.core.person.ai.task.WalkOutsideTest
[ERROR] testDetermineWalkingPath(org.mars_sim.msp.core.person.ai.task.WalkOutsideTest)  Time elapsed: 0.062 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.WalkOutsideTest.testDetermineWalkingPath(WalkOutsideTest.java:285)

```
[ERROR] testGetLocalObstacleSearchLimits(org.mars_sim.msp.core.person.ai.task.WalkOutsideTest)  Time elapsed: 0.077 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.WalkOutsideTest.testGetLocalObstacleSearchLimits(WalkOutsideTest.java:372)
```
```

[ERROR] Errors: 
[ERROR]   WalkOutsideTest.testDetermineWalkingPath:285 » NullPointer
[ERROR]   WalkOutsideTest.testGetLocalObstacleSearchLimits:372 » NullPointer
[INFO] 
[ERROR] Tests run: 450, Failures: 0, Errors: 2, Skipped: 0
```
Hence unable to compile :(

**Comment by mokun** [comment]
I only have one method in WalkOutsideTest that is still not commented out. You can comment out the whole WalkOutsideTest or delete it if you like. In my machine it works fine.

**Comment by shirishag75** [comment]
In 5048 I am able to compile without using `-DSkipTests `so thank you :)
