### ISSUE TITLE
Unable to compile with r5065

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#232]
.I tried `/home/shirish/games/mars-sim/$ mvn clean kotlin:compile package install` it didn't compile, then tried `/home/shirish/games/mars-sim/$ mvn clean kotlin:compile package install -X ` to figure out where the problem strarts and got the following, it starts from here . 
```

INFO: Mock Unit 1 is outside on Mars
[ERROR] Tests run: 40, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 2.43 s <<< FAILURE! - in org.mars_sim.msp.core.TestInventory
[ERROR] testInventoryItemResourceStoreDeep(org.mars_sim.msp.core.TestInventory)  Time elapsed: 0.049 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.TestInventory.testInventoryItemResourceStoreDeep(TestInventory.java:396)

[ERROR] testInventoryRetrieveUnitGood(org.mars_sim.msp.core.TestInventory)  Time elapsed: 0.041 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.TestInventory.testInventoryRetrieveUnitGood(TestInventory.java:736)

[ERROR] testInventoryAmountResourceRemainingCapacityDeepLimitedGeneral(org.mars_sim.msp.core.TestInventory)  Time elapsed: 0.041 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.TestInventory.testInventoryAmountResourceRemainingCapacityDeepLimitedGeneral(TestInventory.java:251)

[ERROR] testInventoryAmountResourcePhaseStoreDeep(org.mars_sim.msp.core.TestInventory)  Time elapsed: 0.042 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.TestInventory.testInventoryAmountResourcePhaseStoreDeep(TestInventory.java:186)

[ERROR] testInventoryAmountResourceAllResources(org.mars_sim.msp.core.TestInventory)  Time elapsed: 0.039 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.TestInventory.testInventoryAmountResourceAllResources(TestInventory.java:360)

[ERROR] testInventoryItemResourceRetrieveDeep(org.mars_sim.msp.core.TestInventory)  Time elapsed: 0.039 s  <<< ERROR!
java.lang.NullPointerException
	at org.mars_sim.msp.core.TestInventory.testInventoryItemResourceRetrieveDeep(TestInventory.java:491)
```

And then - 
```

Oct 02, 2019 12:16:19 AM org.mars_sim.msp.core.mars.RandomMineralMap determineMineralConcentrations
SEVERE: Error creating random mineral map.
java.lang.NullPointerException
	at org.mars_sim.msp.core.mars.MineralMapConfig.getMineralTypes(MineralMapConfig.java:47)
	at org.mars_sim.msp.core.mars.RandomMineralMap.determineMineralConcentrations(RandomMineralMap.java:94)
	at org.mars_sim.msp.core.mars.RandomMineralMap.<init>(RandomMineralMap.java:79)
	at org.mars_sim.msp.core.mars.SurfaceFeatures.<init>(SurfaceFeatures.java:98)
	at org.mars_sim.msp.core.mars.Mars.<init>(Mars.java:43)
	at org.mars_sim.msp.core.Simulation.testRun(Simulation.java:405)
	at org.mars_sim.msp.core.structure.construction.ConstructionManagerTest.setUp(ConstructionManagerTest.java:30)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

java.lang.NullPointerException
	at org.mars_sim.msp.core.mars.MineralMapConfig.getMineralTypes(MineralMapConfig.java:47)
	at org.mars_sim.msp.core.mars.RandomMineralMap.determineMineralConcentrations(RandomMineralMap.java:94)
	at org.mars_sim.msp.core.mars.RandomMineralMap.<init>(RandomMineralMap.java:79)
	at org.mars_sim.msp.core.mars.SurfaceFeatures.<init>(SurfaceFeatures.java:98)
	at org.mars_sim.msp.core.mars.Mars.<init>(Mars.java:43)
	at org.mars_sim.msp.core.Simulation.testRun(Simulation.java:405)
	at org.mars_sim.msp.core.structure.construction.ConstructionManagerTest.setUp(ConstructionManagerTest.java:30)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by shirishag75** [comment]
and then of course the - 

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.055 s <<< FAILURE! - in org.mars_sim.msp.core.person.ai.task.WalkingStepsTest
[ERROR] testWalkingStepsBuildingToBuildingPath(org.mars_sim.msp.core.person.ai.task.WalkingStepsTest)  Time elapsed: 0.055 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.mars_sim.msp.core.person.ai.task.WalkingStepsTest.testWalkingStepsBuildingToBuildingPath(WalkingStepsTest.java:92)
Caused by: java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.WalkingStepsTest.testWalkingStepsBuildingToBuildingPath(WalkingStepsTest.java:92)

[INFO] Running org.mars_sim.msp.core.person.ai.task.WalkOutsideTest
Oct 02, 2019 12:16:20 AM org.mars_sim.msp.core.Unit <init>
INFO: Mars Surface is outside on Mars
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.123 s - in org.mars_sim.msp.core.person.ai.task.WalkOutsideTest

```

**Comment by mokun** [comment]
@shirishag75 , r5066 should have no issues for now. Let me know.

**Comment by shirishag75** [comment]
yup, just compiled without an issue.
