### ISSUE TITLE
How do I begin? Incompatibilies with Java 13 

### ISSUE THREAD

**Issue by Ranged** [mars-sim/mars-sim#236]
Apologies if this is made clear somewhere, but I've scoured both the github wiki and the project website and found *nothing* to help me here.

How do I actually run the simulation, as shown on the website?

I've tried downloading and running the latest release, but that only seems to have a console version(?).

I then tried to download build 4950, which I assumed to be a GUI version. It opened a console and once I reached the point where the simulation should start, the console froze.

v3.1.0 straight-up refuses to open at all, both batch and java version.

What am I supposed to do if I want to actually run/play this mars simulation? I've been looking for over an hour now.

**Comment by mokun** [comment]
> I then tried to download build 4950, which I assumed to be a GUI version. It opened a console and once I reached the point where the simulation should start, the console froze.

sorry for the freeze. 

May I know what OS platform you are using ? Windows, macOS or linux ?

For now, you only need to have the plain Java 11 SE or openjdk 11 installed. No openjfx is needed as we have gone back to using the Swing AI for prototyping more features.

I've just uploaded the build [5162](https://github.com/mars-sim/mars-sim/releases/tag/5162)

Since the debian editions requires the debian installer and is for linux only, I would recommend you try out the *Jar Swing Edition*, the one with the filename `5162_swing_java11.jar`.

Do let us know and for any feedback/comments/support.

**Comment by Ranged** [comment]
Thanks for the reply.

The latest release you uploaded does work, but it only opens the console version for me.
https://i.imgur.com/8C0DRnq.png

How do I get to the GUI version of the simulation from here? This is the swing edition.

**Comment by mokun** [comment]
What OS platform are you on ?

Which Java version do you use, is it openjdk or Oracle Java ? Please be specific as it helps debugging.
Looks like you use 13.0.1. 

Let's type : 
> java -version 
 
and cut and paste the result here on this thread.

Also, to know why it can't load the swing, let's start mars-sim in a terminal/command prompt and type the following and hit enter : 
>  java -jar 5162_swing_java11.jar

Also, if you choose (1) in the console menu at some point, it should open the *Site Editor* using Java Swing. Can you see it ?

**Comment by Urwumpe** [comment]
Works for me just by double-clicking on the final jar file, but it seems to freeze up using the IDE for starting Mars-sim. Will test the behaviour more precisely later, maybe just an outdated maven build.

**Comment by mokun** [comment]
@Urwumpe , are you on linux and what java version do you have ?

I use this laptop running windows 10 with oracle jdk 11 to compile the 5162 build. 

May be I can download openjdk 13 to see if it can run.

**Comment by Urwumpe** [comment]
Windows 10, default JRE is Hotspot 11.0.1 VM, a bit outdated already.

**Comment by mokun** [comment]
I just tried running it on Java 13.0.1 in Win 10. It doesn't work. 

The Weblaf API still uses reflection internally. 

It can't handle something. 

```

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alee.utils.ReflectUtils (file:/C:/Users/mkhelios/.m2/repository/com/weblookandfeel/weblaf-core/1.2.10/weblaf-core-1.2.10.jar) to method sun.font.FontUtilities.fontSupportsDefaultEncoding(java.awt.Font)
WARNING: Please consider reporting this to the maintainers of com.alee.utils.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[pool-1-thread-1] ERROR com.alee.managers.style.data.ComponentStyle - Unable to merge property 'decorations' values: 'null' and 'com.alee.painter.decoration.Decorations@34158b1e'
com.alee.api.clone.CloneException: Unable to clone object field: private java.util.List com.alee.painter.decoration.Decorations.decorations
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:133)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:132)
	at com.alee.api.clone.Clone.clone(Clone.java:104)
	at com.alee.api.merge.clonepolicy.PerformClonePolicy.clone(PerformClonePolicy.java:37)
	at com.alee.api.merge.Merge.cloneMerged(Merge.java:260)
	at com.alee.api.merge.Merge.merge(Merge.java:180)
	at com.alee.managers.style.data.ComponentStyle.mergeProperties(ComponentStyle.java:843)
	at com.alee.managers.style.data.ComponentStyle.mergePainters(ComponentStyle.java:793)
	at com.alee.managers.style.data.ComponentStyle.extend(ComponentStyle.java:664)
	at com.alee.managers.style.data.ComponentStyle.merge(ComponentStyle.java:647)
	at com.alee.managers.style.data.SkinInfo.performOverride(SkinInfo.java:728)
	at com.alee.managers.style.data.SkinInfo.performOverride(SkinInfo.java:644)
	at com.alee.managers.style.data.SkinInfo.ensureCacheInitialized(SkinInfo.java:513)
	at com.alee.managers.style.data.SkinInfo.getStyle(SkinInfo.java:457)
	at com.alee.managers.style.XmlSkin.getStyle(XmlSkin.java:162)
	at com.alee.managers.style.AbstractSkin.applySkin(AbstractSkin.java:64)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:297)
	at com.alee.managers.style.StyleData.install(StyleData.java:124)
	at com.alee.managers.style.StyleManager.installSkin(StyleManager.java:1148)
	at com.alee.laf.panel.WebPanelUI.installUI(WebPanelUI.java:65)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
	at com.alee.laf.panel.WebPanel.setUI(WebPanel.java:982)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.alee.utils.ReflectUtils.callMethod(ReflectUtils.java:1651)
	at com.alee.utils.LafUtils.setUI(LafUtils.java:109)
	at com.alee.managers.style.AbstractComponentDescriptor.updateUI(AbstractComponentDescriptor.java:236)
	at com.alee.laf.panel.WebPanel.updateUI(WebPanel.java:988)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:95)
	at com.alee.laf.panel.WebPanel.<init>(WebPanel.java:123)
	at com.alee.managers.glasspane.WebGlassPane.<init>(WebGlassPane.java:97)
	at com.alee.laf.rootpane.WebRootPane.createGlassPane(WebRootPane.java:91)
	at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:348)
	at com.alee.laf.rootpane.WebRootPane.<init>(WebRootPane.java:75)
	at com.alee.laf.window.WebFrame$WebFrameRootPane.<init>(WebFrame.java:755)
	at com.alee.laf.window.WebFrame.createRootPane(WebFrame.java:227)
	at com.alee.laf.window.WebFrame.initialize(WebFrame.java:185)
	at com.alee.laf.window.WebFrame.<init>(WebFrame.java:165)
	at com.alee.laf.window.WebFrame.<init>(WebFrame.java:150)
	at com.alee.laf.window.WebFrame.<init>(WebFrame.java:125)
	at com.alee.laf.window.WebFrame.<init>(WebFrame.java:78)
	at org.mars_sim.msp.ui.swing.MainWindow.<init>(MainWindow.java:177)
	at org.mars_sim.main.MarsProject.setupMainWindow(MarsProject.java:387)
	at org.mars_sim.main.MarsProject.handleNewSimulation(MarsProject.java:433)
	at org.mars_sim.main.MarsProject.initializeSimulation(MarsProject.java:191)
	at org.mars_sim.main.MarsProject$SimulationTask.run(MarsProject.java:164)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.alee.api.clone.CloneException: Unable to clone collection: [WebDecoration [ id=default; visible=true ]]
	at com.alee.api.clone.behavior.CollectionCloneBehavior.clone(CollectionCloneBehavior.java:122)
	at com.alee.api.clone.behavior.CollectionCloneBehavior.clone(CollectionCloneBehavior.java:37)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:132)
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:125)
	... 54 more
```

**Comment by mokun** [comment]
@Ranged, 

In summary, for now, only Java 11 is supported. 

We depend on a library called `weblaf ` and will have to wait for weblaf to get fixed running under Java 13.

Sorry about the inconvenience.

**Comment by mokun** [comment]
It supports Java 12 now.

**Comment by shirishag75** [comment]
also works with java 14, at least the headless mode. The swing module also works.
