### ISSUE TITLE
java.lang.nullpointerexception while trying to save game in mars-sim-headless in java 14, r5220

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#242]
I got the following nullpointer exception while trying to save game in mars-sim-headless. 

```
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.DigLocalRegolith.collectRegolith(DigLocalRegolith.jav
	at org.mars_sim.msp.core.person.ai.task.DigLocalRegolith.performMappedPhase(DigLocalRegolith.
	at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:610)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:556)
	at org.mars_sim.msp.core.person.ai.task.utils.TaskManager.executeTask(TaskManager.java:473)
at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:238)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:148)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:1004)
	at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:2177)
	at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1922)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.java:1065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

The above exception was running in a loop, hope it gives some more insight. Let me know if you need any more info. 

The version I am using and other details can be had at - 

```
Package: openjdk-14-jre-headless
Version: 14~19-1

-- System Information:
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (900, 'testing'), (500, 'testing-debug'), (100, 'unstable-debug'), (100, 'experimental'), (100, 'unstable'), (50, 'experimental-debug')
Architecture: amd64 (x86_64)

Kernel: Linux 5.3.0-3-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages openjdk-14-jre-headless depends on:
ii  ca-certificates-java  20190909
ii  java-common           0.72
ii  libasound2            1.1.9-1
ii  libc6                 2.29-3
ii  libcups2              2.3.0-7
ii  libfontconfig1        2.13.1-2+b1
ii  libfreetype6          2.10.1-2
ii  libgcc1               1:9.2.1-21
ii  libjpeg62-turbo       1:1.5.2-2+b1
ii  liblcms2-2            2.9-3+b1
ii  libnss3               2:3.45-1
ii  libpcsclite1          1.8.25-3
ii  libstdc++6            9.2.1-21
ii  libx11-6              2:1.6.8-1
ii  libxext6              2:1.3.3-1+b2
ii  libxi6                2:1.7.9-1
ii  libxrender1           1:0.9.10-1
ii  libxtst6              2:1.2.3-1
ii  util-linux            2.34-0.1
ii  zlib1g                1:1.2.11.dfsg-1+b1

openjdk-14-jre-headless recommends no packages.

Versions of packages openjdk-14-jre-headless suggests:
ii  fonts-dejavu-extra    2.37-1
pn  fonts-indic           <none>
ii  fonts-ipafont-gothic  00303-20
ii  fonts-ipafont-mincho  00303-20
ii  fonts-wqy-microhei    0.2.0-beta-3
ii  libnss-mdns           0.14.1-1

-- no debconf information
```

Was running the latest r5220

**Comment by mokun** [comment]
Wow it looks like you didn't run into any issues with java 14 in headless mode and that's good news :D

Having said that, I do know there are issues with weblaf package even on Java 13 in Swing mode.

**Comment by mokun** [comment]
Fixing the NPE from some minor changes in 'DigLocalRegolith' and DigLocalIce` task now.

**Comment by shirishag75** [comment]
seems to have been fixed, thank you.
