### ISSUE TITLE
java.lang.NullPointerException with build 5223

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#246]
/games/mars-sim/mars-sim-headless/target$ java -jar mars-sim-headless-3.1.0.jar
Command: java -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1536m -new
2019-12-16T12:05:22.8 (Config) MarsProjectHeadless : Starting Mars Simulation Project v3.1.0 - Build 5223 - 64-bit 14-ea - 4 CPU threads
2019-12-16T12:05:22.9 (Config) SimulationConfig : /xml folder already existed.
2019-12-16T12:05:22.9 (Config) SimulationConfig : Your version.txt already has the same BUILD 5223 as the core engine.
2019-12-16T12:05:23.2 (Config) SimulationConfig : Done loading all xml files.
2019-12-16T12:05:23.2 (Config) MarsProjectHeadless : Please proceed to selecting the type of Game Mode in the popped-up console.
java.lang.NullPointerException
	at org.mars.sim.console.SwingHandler.<init>(SwingHandler.java:85)
	at org.mars.sim.console.InteractiveTerm.startConsoleMainMenu(InteractiveTerm.java:144)
	at org.mars_sim.headless.MarsProjectHeadless.handleNewSimulation(MarsProjectHeadless.java:235)
	at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:145)
	at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:98)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
2019-12-16T12:05:23.2 (Severe) MarsProjectHeadless : Could not create a new simulation, startup cannot continue

Please fix the issue as shown above :)

**Comment by shirishag75** [comment]
it seems it could be fixed with just using the -new switch. Hence closing it atm, although it shouldn't need to be.

**Comment by mokun** [comment]
> Command: java -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -Djava.util.logging.config.file=logging.properties -cp .::jars/ org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1536m -new

This is strange and I have no idea why.

The `-new` switch should have already been embedded inside `MarsProjectHeadlessStarter` and thus not needed.

**Comment by shirishag75** [comment]
I have no clue also mate. Let me know if you want me to do some more tests, IIRC, by default whenever you get a new build compile, it examines the old build id with the new build id. If both are the same, then it should ask you whether you want to load a saved game and continue from there. If not, then it should directly ask you to a new game. Or maybe I'm mis-remembering it ?
