### ISSUE TITLE
Out of memory issue on r5225 - this is a new one, how could this happen - 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#248]
While autosaving a new game on got this - 

```
00-Adir-01:432.351 (Config) Simulation : Autosaving the simulation as default.sim.
00-Adir-01:432.351 (Config) Simulation : heapSize: 5.63 GB    heapMaxSize: 5.84 GB    heapFreeSize: 
00-Adir-01:432.351 (Config) Simulation : Encoder memory usage : 95.16 MB
00-Adir-01:432.351 (Config) Simulation : Decoder memory usage : 8.3 MB
Exception in thread "pool-3-thread-1" java.lang.OutOfMemoryError: Java heap space
	at org.tukaani.xz.ArrayCache.getIntArray(Unknown Source)
	at org.tukaani.xz.lz.BT4.<init>(Unknown Source)
	at org.tukaani.xz.lz.LZEncoder.getInstance(Unknown Source)
	at org.tukaani.xz.lzma.LZMAEncoderNormal.<init>(Unknown Source)
	at org.tukaani.xz.lzma.LZMAEncoder.getInstance(Unknown Source)
	at org.tukaani.xz.LZMA2OutputStream.<init>(Unknown Source)
	at org.tukaani.xz.LZMA2Options.getOutputStream(Unknown Source)
	at org.tukaani.xz.LZMA2Encoder.getOutputStream(Unknown Source)
	at org.tukaani.xz.BlockOutputStream.<init>(Unknown Source)
	at org.tukaani.xz.XZOutputStream.write(Unknown Source)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:112)
	at org.mars_sim.msp.core.Simulation.serialize(Simulation.java:1391)
	at org.mars_sim.msp.core.Simulation.saveSimulation(Simulation.java:1303)
	at org.mars_sim.msp.core.time.MasterClock.checkSave(MasterClock.java:962)
	at org.mars_sim.msp.core.time.MasterClock$ClockThreadTask.run(MasterClock.java:849)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

This was during autosave, so maybe something that needs to be fixed. 

And this is when I have more than enough memory - 

`$free` -h 
                    total        used        free      shared  buff/cache   available
Mem:           23Gi       6.5Gi        10Gi       317Mi       6.4Gi        16Gi
Swap:          59Gi          0B        59Gi

              total        used        free      shared  buff/cache   available

**Comment by mokun** [comment]
> 00-Adir-01:432.351 (Config) Simulation : Autosaving the simulation as default.sim.
> 00-Adir-01:432.351 (Config) Simulation : heapSize: 5.63 GB    heapMaxSize: 5.84 GB    heapFreeSize: 
> 00-Adir-01:432.351 (Config) Simulation : Encoder memory usage : 95.16 MB
> 00-Adir-01:432.351 (Config) Simulation : Decoder memory usage : 8.3 MB
> Exception in thread "pool-3-thread-1" java.lang.OutOfMemoryError: Java heap space
> 

The value of `heapFreeSize` was missing from above. 

I read from somewhere that `OutOfMemoryError` occurs even if `heapFreeSize` is above zero since the heap memory space is usually a bit than `heapFreeSize`.  

From above, I guess it's ~(190MB + delta).

We don't know what the value of delta is at that moment. 

The encoder and decoder will use ~100 MB. 

So delta has to be less than 90MB (=190 - 100), or else we have `OutOfMemoryError`.

**Comment by mokun** [comment]
I'll do the following :

```
		if (heapFreeSize < 250) {
			logger.config("Please try again. Ensure enough free heap space available beforehand.");
		}
		else {
			// Serialize the file
			serialize(type, file, srcPath, destPath);
		}
```

This will give more room for the delta value.

If heapFreeSize is less than 250, it won't save and thus it won't throw the `OutOfMemoryError`

**Comment by mokun** [comment]
This is where the importance of having an efficient Garbage Collector comes to play a big role in clearing memory

**Comment by mokun** [comment]
Do let me know if you see `OutOfMemoryError` again when saving/autosaving. 

We might need to increase the threshold to 300 MB, etc.

**Comment by shirishag75** [comment]
so this is just memory issue or is it hdd issue as well . One of the things that I noticed was I had only 40 MB as HDD space. Could that have contributed to the problem as well ?

**Comment by mokun** [comment]
> only 40 MB as HDD space.

Do you mean you have only 40 MB left on your hard drive ?

If that's the case, let's deleting all the old autosave sim in the /autosave/ folder.

**Comment by mokun** [comment]
> Could that have contributed to the problem as well ?

No. the heap space is strictly RAM.

**Comment by shirishag75** [comment]
> > only 40 MB as HDD space.
> 
> Do you mean you have only 40 MB left on your hard drive ?
> 
> If that's the case, let's deleting all the old autosave sim in the /autosave/ folder.

I did that, it did make a difference but not a lot.

**Comment by mokun** [comment]
Resolved and closed.
