### ISSUE TITLE
getting a java.lang.nullpointerexception with build 5230

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#252]
I got the following - 

```
2019-12-17T16:59:44.4 (Config) MarsProjectHeadless : Please proceed to selecting the type of Game Mode in the popped-up console.
java.lang.NullPointerException
	at org.mars.sim.console.SwingHandler.<init>(SwingHandler.java:85)
	at org.mars.sim.console.InteractiveTerm.startConsoleMainMenu(InteractiveTerm.java:144)
	at org.mars_sim.headless.MarsProjectHeadless.handleNewSimulation(MarsProjectHeadless.java:235)
	at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:145)
	at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:98)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
2019-12-17T16:59:44.4 (Severe) MarsProjectHeadless : Could not create a new simulation, startup cannot continue
```

Can you fix it, please.

**Comment by mokun** [comment]
This is the same issue as https://github.com/mars-sim/mars-sim/issues/246

**Comment by mokun** [comment]
Can you describe how *often* you get this ? Is it everytime or just sometimes you are getting this NPE ?

We need to pin down under what circumstances it pops up and stops you from starting a new simulation.

> 2019-12-17T16:59:44.4 (Config) MarsProjectHeadless : Please proceed to selecting the type of Game Mode in the popped-up console.
> java.lang.NullPointerException

Can you also post the few lines above that ? It will tell me what Java version you are running.

I'm hoping to duplicate the initial setup on my machine so that I can see it. 

Thanks!

**Comment by mokun** [comment]
In my machine, I have no issues starting a new sim in headless mode :

![image](https://user-images.githubusercontent.com/1168584/71016422-faf2cf00-20a9-11ea-9e54-59a3d04a0269.png)

**Comment by shirishag75** [comment]
This is at my end - 

```
~/games/mars-sim/mars-sim-headless/target$ java -jar mars-sim-headless-3.1.0-jar-wi
th-dependencies.jar 
Command: java -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -Djava.util.logging.config.file=logging.properties -c
p .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1536m -new
2019-12-17T22:23:33.9 (Config) MarsProjectHeadless : Starting Mars Simulation Project v3.1.0 - Build 5230 - 64-bit 14-ea 
- 4 CPU threads
2019-12-17T22:23:33.9 (Config) SimulationConfig : /xml folder already existed.
2019-12-17T22:23:33.9 (Config) SimulationConfig : Your version.txt already has the same BUILD 5230 as the core engine.
2019-12-17T22:23:34.4 (Config) SimulationConfig : Done loading all xml files.
2019-12-17T22:23:34.4 (Config) MarsProjectHeadless : Please proceed to selecting the type of Game Mode in the popped-up c
onsole.
java.lang.NullPointerException
```

**Comment by shirishag75** [comment]
java is -

```
 ~$ java -version
openjdk version "14-ea" 2020-03-17
OpenJDK Runtime Environment (build 14-ea+27-Debian-1)
OpenJDK 64-Bit Server VM (build 14-ea+27-Debian-1, mixed mode, sharing)
```

**Comment by mokun** [comment]
Can you switch back to Java 12 to see if it goes away ?

**Comment by mokun** [comment]
Q1 : Can you describe how often you get this ?

Q2: Is it everytime or just sometimes you are getting this NPE ?

Q3: exactly at what point you see this ? Was it before or after the beryx console come up and you choose "1. Start a new Sim" at the first screen of the Main Menu ? OR on the 2nd or 3rd menu ?

**Comment by shirishag75** [comment]
java 12 is not there in debian archive anymore. What we have is openjdk13 but this will mean I will have to purge openjdk-14 and get openjdk-13 . Let's see if that is anything better or good on the system. If you look at it, the time for free updates for openjdk12 was over in September 2019 itself. It is now either openjdk-11 or openjdk-13 which will have a short shelf life of only 3 months

**Comment by shirishag75** [comment]
This happened again, this time with openjdk-13 - 

```
~/games/mars-sim/mars-sim-headless/target$$ java -jar mars-sim-headless-3.1.0-jar-with-dependencies.jar 
Command: java -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1536m -new
2019-12-18T03:02:33.4 (Config) MarsProjectHeadless : Starting Mars Simulation Project v3.1.0 - Build 5235 - 64-bit 13.0.1 - 4 CPU threads
2019-12-18T03:02:33.4 (Config) SimulationConfig : /xml folder already existed.
2019-12-18T03:02:33.4 (Config) SimulationConfig : Your version.txt already has the same BUILD 5235 as the core engine.
2019-12-18T03:02:33.8 (Config) SimulationConfig : Done loading all xml files.
2019-12-18T03:02:33.9 (Config) MarsProjectHeadless : Please proceed to selecting the type of Game Mode in the popped-up console.
java.lang.NullPointerException
	at org.mars.sim.console.SwingHandler.<init>(SwingHandler.java:85)
	at org.mars.sim.console.InteractiveTerm.startConsoleMainMenu(InteractiveTerm.java:144)
	at org.mars_sim.headless.MarsProjectHeadless.handleNewSimulation(MarsProjectHeadless.java:235)
	at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:145)
	at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:98)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2019-12-18T03:02:33.9 (Severe) MarsProjectHeadless : Could not create a new simulation, startup cannot continue
```

Openjdk-13 and build 5235

**Comment by shirishag75** [comment]
> Q1 : Can you describe how often you get this ?
> 
> Q2: Is it everytime or just sometimes you are getting this NPE ?
> 
> Q3: exactly at what point you see this ? Was it before or after the beryx console come up and you choose "1. Start a new Sim" at the first screen of the Main Menu ? OR on the 2nd or 3rd menu ?

I just shared the re-ocurrence now again. This is happening at when I'm trying to start the simulation itself. One thing to note is that there is no default.sim nor previous.sim . I rm -rf it, dunno if that made the difference or not. Although it shouldn't but perhaps it did.

**Comment by shirishag75** [comment]
This seems to have been fixed by r5237 .
