### ISSUE TITLE
java.lang.NullPointer exception in r5247

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#262]
Got the following issue/error at my end - 

```
~/games/mars-sim/mars-sim-headless/target$ java -jar mars-sim-headless-3.1.0-jar-with-dependencies.jar -template:1A -country:India -sponsor:ISRO
Command: java -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -Djava.util.logging.config.file=logging.properties -c
p .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1536m -new
2019-12-21T15:23:13.7 (Config) MarsProjectHeadless : Starting Mars Simulation Project v3.1.0 - Build 5247 - 64-bit 13.0.1
 - 4 CPU threads
2019-12-21T15:23:13.8 (Config) SimulationConfig : /xml folder already existed.
2019-12-21T15:23:13.8 (Config) SimulationConfig : Your version.txt already has the same BUILD 5247 as the core engine.
2019-12-21T15:23:14.2 (Config) SimulationConfig : Done loading all xml files.
2019-12-21T15:23:14.2 (Config) MarsProjectHeadless : Please proceed to selecting the type of Game Mode in the popped-up c
onsole.
java.lang.NullPointerException
	at org.mars.sim.console.InteractiveTerm.startConsoleMainMenu(InteractiveTerm.java:149)
	at org.mars_sim.headless.MarsProjectHeadless.handleNewSimulation(MarsProjectHeadless.java:388)
	at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:213)
	at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:121)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2019-12-21T15:23:14.2 (Severe) MarsProjectHeadless : Could not create a new simulation, startup cannot continue
```

**Comment by mokun** [comment]
Can you run it multiple times ? 

If it only happens sometimes, then we know it's a threading issue. 

I'll need to put all the UI building tasks on Swing's EDT to avoid that.

For now it sounds like a threading issue.

**Comment by shirishag75** [comment]
It happens once, the next time I run it, it doesn't. The third time it happens again, the fourth time it doesn't.

**Comment by shirishag75** [comment]
Even with this I got - 

```
java.lang.NullPointerException
at org.mars.sim.console.InteractiveTerm.selectMenu(InteractiveTerm.java:162)
at org.mars.sim.console.InteractiveTerm.startConsoleMainMenu(InteractiveTerm.java:149)
at org.mars_sim.headless.MarsProjectHeadless.handleNewSimulation(MarsProjectHeadless.java:388)
at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:213)
at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:121)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
2019-12-23T19:10:49.4 (Severe) InteractiveTerm : RuntimeException detected.
```

**Comment by shirishag75** [comment]
the game starts but doesn't ask me to set anything or do anything in the command-mode or anything.

```
~/games/mars-sim/mars-sim-headless/target
th-dependencies.jar -template:1 country:India -sponsor:ISRO 
```

**Comment by mokun** [comment]
> the game starts but doesn't ask me to set anything or do anything in the command-mode or anything.

What do you want it to ask you ?

**Comment by shirishag75** [comment]
It should ask me about at least setting up the commander.profile, shouldn't it. It doesn't.

**Comment by mokun** [comment]
> It should ask me about at least setting up the commander.profile, shouldn't it. It doesn't.

You have to choose `1. Start a new sim`

![image](https://user-images.githubusercontent.com/1168584/71449381-c5389080-2710-11ea-8470-db949bbd2600.png)

**Comment by shirishag75** [comment]
It actually doesn't do that. It straight starts the simulation and I get the following screenshot. 
![mars-sim-console](https://user-images.githubusercontent.com/727626/71449744-66443d00-274b-11ea-9773-d075b2e3bffd.png)

It seems the java.lang.nullpointer exception happens at the start sim end itself. 

```
019-12-26T00:46:55.8 (Config) MarsProjectHeadless : Please proceed to selecting the type of Game Mode in the popped-up console.
Java.lang.NullPointerException
at org.mars.sim.console.InteractiveTerm.selectMenu(InteractiveTerm.java:162)
at org.mars.sim.console.InteractiveTerm.startConsoleMainMenu(InteractiveTerm.java:149)
at org.mars_sim.headless.MarsProjectHeadless.handleNewSimulation(MarsProjectHeadless.java:388)
at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:213)
at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:121)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
2019-12-26T00:46:55.8 (Severe) InteractiveTerm : RuntimeException detected.
2019-12-26T00:46:55.9 (Config) Simulation : Initiating the simulation core engine...
```

**Comment by shirishag75** [comment]
The startup bit got fixed by r5249 commit hence closing this, the other issue remains.

**Comment by mokun** [comment]
Do you also provide the `-new` argument ?

**Comment by shirishag75** [comment]
> Do you also provide the `-new` argument ?

I don't understand, if I take `-new` argument then why should I need to go to main menu to start new sim ? It seems counter-intuitive. So the whole command should be the following ?
`
~/games/mars-sim/mars-sim-headless/target$ java -jar mars-sim-headless-with-dependencies.jar -new -template:1 country:India -sponsor:ISRO `
