### ISSUE TITLE
IndexOutOfBoundsException with r5250, selecting sponsor 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#263]
I compiled the new package and then ran it and tried to use the command mode, made a profile and then got hit by the following - 

```
2019-12-27T13:52:47.1 (Config) MarsProjectHeadless : Please proceed to selecting the type of Game Mode in the popped-up console.
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:425)
	at org.mars_sim.msp.core.UnitManager.getSponsorByID(UnitManager.java:2574)
	at org.mars_sim.msp.core.person.Commander.getSponsorStr(Commander.java:111)
	at org.mars_sim.msp.core.person.Commander.toString(Commander.java:227)
	at org.mars.sim.console.CommanderProfile.accept(CommanderProfile.java:128)
	at org.mars.sim.console.InteractiveTerm.selectCommandMode(InteractiveTerm.java:491)
	at org.mars.sim.console.InteractiveTerm.selectMode(InteractiveTerm.java:338)
	at org.mars.sim.console.InteractiveTerm.selectMenu(InteractiveTerm.java:195)
	at org.mars.sim.console.InteractiveTerm.startConsoleMainMenu(InteractiveTerm.java:148)
	at org.mars_sim.headless.MarsProjectHeadless.createNewSettlement(MarsProjectHeadless.java:305)
	at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:209)
	at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:121)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2019-12-27T13:53:14.9 (Severe) InteractiveTerm : RuntimeException detected.

```

**Comment by mokun** [comment]
> 	at org.mars_sim.msp.core.UnitManager.getSponsorByID(UnitManager.java:2574)

@shirishag75 , it's at this line that something went wrong.

You can google `IndexOutOfBoundsException` to understand what's at stake :D

**Comment by mokun** [comment]
I can successfully create a brand new commander profile and start a settlement. I cannot reproduce this exception in my machine. 

Exactly at what step did you encounter this exception ?and how often ? 

Can you capture some screen shot from beryx console so that I can at least back trace the issue ?

Thanks for documenting it next time you see it.

**Comment by shirishag75** [comment]
I think it happens as you put the country of origin and sponsor again, so guess I shouldn't pass the full template perhaps ?

![index-out-of-bounds](https://user-images.githubusercontent.com/727626/71527586-fe6d2e00-28d3-11ea-9950-0446bc394701.png)

maybe just have ` -template:1 `and leave it that ?

![mars-command-box](https://user-images.githubusercontent.com/727626/71527617-1c3a9300-28d4-11ea-89d6-7315d9da2bc2.png)

**Comment by shirishag75** [comment]
If I try just having template:1 string I get this - 

```
2019-12-27T23:40:47.8 (Info) MarsProjectHeadless : has -template:1
2019-12-27T23:40:47.8 (Info) MarsProjectHeadless : Found templatePhaseString: 1
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at org.mars_sim.msp.core.structure.SettlementConfig.getSettlementNameList(SettlementConfig.java:1001)
	at org.mars_sim.headless.MarsProjectHeadless.loadSettlementTemplate(MarsProjectHeadless.java:274)
	at org.mars_sim.headless.MarsProjectHeadless.createNewSettlement(MarsProjectHeadless.java:301)
	at org.mars_sim.headless.MarsProjectHeadless.initializeSimulation(MarsProjectHeadless.java:209)
	at org.mars_sim.headless.MarsProjectHeadless$SimulationTask.run(MarsProjectHeadless.java:121)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2019-12-27T23:40:47.8 (Severe) MarsProjectHeadless : Could not create a new simulation, startup cannot continue
```

**Comment by mokun** [comment]
It's fixed now ! Thanks for pointing that out.

**Comment by shirishag75** [comment]
fixed at my end hence closing it.
