### ISSUE TITLE
Task & Building classes are not Serialised

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#334]
**Describe the bug**
The Task and Function classes are not Serialized in a save. This is due to transient properties in `TaskManager` and `Building`. 
The issue is some Task instance are referencing `Function` implementation that are not fully serializable which means IF the TaskManager persisted the current task there is a change that it will fail depending upon what the concreate Task references.
Other impacts are in the Greenhouse all Crops get reset on every reload; previous growing effort is lost. CookedMeals get dropped on a reload, etc,, etc.
This may also account for odd behaviour when a simulation is reloaded and there is a change the object states will be inconsistent since should are persisted and some reset.

**Expected behavior**
Both Functions and Tasks should be persisted. This means the various Function concrete classes need to be made serializable; the problem is probably in the internal private objects.

**Comment by mokun** [comment]
> The issue is some Task instance are referencing `Function` implementation that are not fully serializable

I thought you worked on the need to serialize the `Function` already.

**Comment by mokun** [comment]
After this [commit](https://github.com/mars-sim/mars-sim/commit/fb45fae18652d37eb11569b44235a2559bd29506), I have the heap size error when saving the sim. The sim also went frozen.

I went and look at he memory bar on the bottom right of the main window. It was 1.29GB when it happened.

```
00-Adir-03:317.931 (Config) Simulation : Saving the simulation as default.sim.
00-Adir-03:317.931 (Config) Simulation : heapSize: 1.50 GB    heapMaxSize: 1.50 GB    heapFreeSize: 203.67 MB
Exception in thread "masterclock-0" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.io.ObjectOutputStream$HandleTable.growEntries(ObjectOutputStream.java:2365)
	at java.base/java.io.ObjectOutputStream$HandleTable.assign(ObjectOutputStream.java:2294)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1437)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1387)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.base/java.io.ObjectOutputStream$PutFieldImpl.writeFields(ObjectOutputStream.java:1723)
	at java.base/java.io.ObjectOutputStream.writeFields(ObjectOutputStream.java:487)
	at java.base/java.util.concurrent.ConcurrentHashMap.writeObject(ConcurrentHashMap.java:1417)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1196)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.writeObject(ConcurrentLinkedQueue.java:824)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1196)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
```

**Comment by bevans2000** [comment]
> > The issue is some Task instance are referencing `Function` implementation that are not fully serializable
> 
> I thought you worked on the need to serialize the `Function` already.

No because I knew it was not a small problem.

**Comment by bevans2000** [comment]
Well I changed nothing to do with the transient fields. I ran a sim up to 11 sols yesterday without problem including auto saves.

**Comment by mokun** [comment]
@bevans2000 ,

I suppose all the tasks and building function classes are now serializable. 

Closing this now ?

**Comment by bevans2000** [comment]
No not done. This is next for me

**Comment by mokun** [comment]
building functions are standard for each building type. Why do we need to serialize it?

**Comment by bevans2000** [comment]
Functions are not stateless, they have a state which needs to be saved. Farming has Crops, VehcileMaintenace has parked vehicles, Fishery has Fish stocks, etc

**Comment by mokun** [comment]
> Functions are not stateless, they have a state which needs to be saved.

That's true. I forgot.

So, currently we have the following object instances that are transient.

Ideally, we'll need to create a specific list of these objects for each unique building, since a building doesn't need all of the functions.


```
	private transient Communication comm;
	private transient ThermalGeneration furnace;
	private transient PowerGeneration powerGen;
	private transient PowerStorage powerStorage;
	private transient LifeSupport lifeSupport;
	private transient RoboticStation roboticStation;
	private transient Heating heating;
	private transient EVA eva;
	private transient Farming farm;
	private transient Fishery fish;
	private transient LivingAccommodations livingAccommodations;
	private transient PreparingDessert preparingDessert;
	private transient Cooking cooking;
	private transient Management management;
	private transient MedicalCare medical;
	private transient WasteDisposal waste;
	private transient VehicleMaintenance garage;
	private transient FoodProduction foodFactory;
	private transient ResourceProcessing processing;
	private transient Research lab;
	private transient Manufacture workshop;
	private transient Administration admin;
	private transient Recreation rec;
	private transient Dining dine;
	private transient GroundVehicleMaintenance maint;
	private transient AstronomicalObservation astro;
	private transient Exercise gym;
	private transient Storage storage;
```

So, we'll need to change how to load them for a new sim and how to reload them from a saved sim. 

And we'll need to change how to access them during the sim.

Anything else we need to think of ?

**Comment by bevans2000** [comment]
The `Building` class is an odd one because it is a container of the various Functions. Feel wrong have all these explicit properties and get methods. But the callers expect the specific sub-class Function to be returned

**Comment by mokun** [comment]
> The `Building` class is an odd one because it is a container of the various Functions. Feel wrong have all these explicit properties and get methods. But the callers expect the specific sub-class Function to be returned

Is there a way to make their relationship more loosely coupled or more composable ?

**Comment by mokun** [comment]
If we save the Function objects that a building initializes into a List and serialize that list, then we would also need to match the new reference for each Function when loading from a saved sim.

**Comment by bevans2000** [comment]
I think we just remove the transient keyword from the attributes.

**Comment by mokun** [comment]
> I think we just remove the transient keyword from the attributes.

But would it waste creating a lot of unneeded objects ? 

or any unused one would be null ?

**Comment by bevans2000** [comment]
Unused are null so it just occurs the pointer space.
