### ISSUE TITLE
Cannot deserialize a particular class when loading from a saved sim

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#342]
**Describe the bug/issue**
 - Cannot deserialize when loading from a saved sim

**Affected Area**
 - It complains about `PersonTaskManager` having no valid constructor
- The saved sim is corrupted

**Expected behaviors**
 - It should be able to load a saved sim

**Actual/Observed Behaviors**
 - InvalidClassException and the saved sim is rendered useless

**Reproduction (optional)**
 - Save a sim when some settlers are in an airlock
 - Exit the simulation
 - Load from that saved sim
 - It cannot load the saved sim

**Specifications  (please complete the following information):**
 - mars-sim build version :  r5693

See stacktrace below : 
```
00-Adir-01:000.000 (Config) Simulation : Loading and processing the saved sim. Please wait...
java.io.InvalidClassException: org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager; no valid constructor
	at java.base/java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:159)
	at java.base/java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:864)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2116)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.readObject(ConcurrentLinkedQueue.java:844)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2271)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at java.base/java.util.HashSet.readObject(HashSet.java:341)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
```

**Comment by mokun** [comment]
@bevans2000 ,

This has been happening *sporadically* in recent builds.

I can't pinpoint when it started to happen.

In the latest incident, I was examining why an airlock has issues with depressurization.

So I suspect it may have to do with the airlock.

However, I cannot tell 100% if it does.

**Comment by mokun** [comment]
@bevans2000 

As I looked further down the stacktrace, I saw this line 

> 	at org.mars_sim.msp.core.Simulation.deserialize(Simulation.java:678)

```
	at org.mars_sim.msp.core.Simulation.deserialize(Simulation.java:678)
	at org.mars_sim.msp.core.Simulation.readFromFile(Simulation.java:830)
	at org.mars_sim.msp.core.Simulation.loadSimulation(Simulation.java:564)
	at org.mars_sim.main.MarsProject.handleLoadSimulation(MarsProject.java:529)
	at org.mars_sim.main.MarsProject.initializeSimulation(MarsProject.java:223)
	at org.mars_sim.main.MarsProject$SimulationTask.run(MarsProject.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
00-Adir-01:000.000 (Severe) Simulation : Quitting mars-sim with ObjectStreamException when loading C:\Users\mkhelios\.mars-sim\saved\default.sim : org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager; no valid constructor
```

Line 678 is in `Simulation` :
			`mars = (Mars) ois.readObject();`

Have you changed `Mars` lately by any chance ?

**Comment by bevans2000** [comment]
Let me have a look later. Certainly looks related to the #337 changes.

**Comment by mokun** [comment]
@bevans2000 ,

In recent builds since switching back to gzip, I'm getting something like that once in a while when loading from a saved sim

Can you check ? 

I didn't change anything in mars-sim-core that would cause exception when deserializing a saved sim.

```
2021-06-22T22:34:07.4 (Config) MarsProject : Starting Mars Simulation Project v3.2.0 - Build 5851 - 64-bit Java 13.0.2 - 8 CPU threads
2021-06-22T22:34:07.5 (Config) MarsProject$SimulationTask : List of input args : [-load] [default.sim] 
2021-06-22T22:34:07.5 (Config) SimulationConfig : The xml folder already existed.
2021-06-22T22:34:07.6 (Config) SimulationConfig : The version.txt has the same BUILD 5851 as the core engine's.
2021-06-22T22:34:08.2 (Config) SimulationConfig : Done loading all xml files.
2021-06-22T22:34:08.2 (Config) SimulationConfig : Please go to the mars-sim console's Main Menu to choose an option.
2021-06-22T22:34:08.2 (Config) Simulation : Initiating the simulation core engine...
2021-06-22T22:34:08.2 (Config) MasterClock : -----------------------------------------------------
2021-06-22T22:34:08.2 (Config) MasterClock :          User defined time-ratio : 128.0x
2021-06-22T22:34:08.2 (Config) MasterClock :               Min msol per pulse : 0.02
2021-06-22T22:34:08.2 (Config) MasterClock :               Max msol per pulse : 2.0
2021-06-22T22:34:08.2 (Config) MasterClock :  Max elapsed time between pulses : 1000 ms
2021-06-22T22:34:08.2 (Config) MasterClock :                    Accuracy bias : 0.5
2021-06-22T22:34:08.2 (Config) MasterClock : -----------------------------------------------------
00-Adir-01:000.000 (Config) Simulation : The file to be loaded is C:\Users\mkhelios\.mars-sim\saved\default.sim
00-Adir-01:000.000 (Config) Simulation : Loading and processing the saved sim. Please wait...
00-Adir-01:000.000 (Config) EVASuit :  EVA suit's unloaded weight : 20.3 kg
00-Adir-01:000.000 (Config) EVASuit :       Total gas tank volume : 3.9L
00-Adir-01:000.000 (Config) EVASuit :                Full Tank O2 : 66.62 kPa -> 1.0    kg - The Maximum tank pressure
00-Adir-01:000.000 (Config) EVASuit :                  Nomimal O2 : 17.0  kPa -> 0.2552 kg - The suit target pressure
00-Adir-01:000.000 (Config) EVASuit :                  Minimum O2 : 11.94 kPa -> 0.1792 kg - The safety limit
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
	at java.base/java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2800)
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2816)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readInt(ObjectInputStream.java:3337)
	at java.base/java.io.ObjectInputStream.readHandle(ObjectInputStream.java:1760)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1821)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2115)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2048)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1634)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:600)
	at java.base/java.util.concurrent.ConcurrentHashMap.readObject(ConcurrentHashMap.java:1448)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2271)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:600)
	at org.mars_sim.msp.core.Inventory.readObject(Inventory.java:3155)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2271)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.readObject(ConcurrentLinkedQueue.java:844)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2271)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at java.base/java.util.HashSet.readObject(HashSet.java:341)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2271)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.readObject(ConcurrentLinkedQueue.java:844)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2271)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.readObject(CopyOnWriteArrayList.java:942)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2271)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.mars_sim.msp.core.Simulation.deserialize(Simulation.java:632)
	at org.mars_sim.msp.core.Simulation.readFromFile(Simulation.java:772)
	at org.mars_sim.msp.core.Simulation.loadSimulation(Simulation.java:549)
	at org.mars_sim.main.MarsProject.handleLoadSimulation(MarsProject.java:575)
	at org.mars_sim.main.MarsProject.initializeSimulation(MarsProject.java:219)
	at org.mars_sim.main.MarsProject$SimulationTask.run(MarsProject.java:177)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
00-Adir-01:000.000 (Severe) Simulation : Quitting mars-sim. Unexpected End of File error on C:\Users\mkhelios\.mars-sim\saved\default.sim : Unexpected end of ZLIB input stream
```

**Comment by mokun** [comment]
It points to `mars = (Mars) ois.readObject();` in Simulation Line 632 :

```
		// Load remaining serialized objects
			malfunctionFactory = (MalfunctionFactory) ois.readObject();
			mars = (Mars) ois.readObject();
			mars.initializeTransientData();
			missionManager = (MissionManager) ois.readObject();
			medicalManager = (MedicalManager) ois.readObject();
			scientificStudyManager = (ScientificStudyManager) ois.readObject();
			transportManager = (TransportManager) ois.readObject();
			creditManager = (CreditManager) ois.readObject();
			eventManager = (HistoricalEventManager) ois.readObject();
			relationshipManager = (RelationshipManager) ois.readObject();		
			unitManager = (UnitManager) ois.readObject();		
			masterClock = (MasterClock) ois.readObject();

```

**Comment by bevans2000** [comment]
But in the stack trace there is a call to Inventory.readObject. Do we customise the serialization of the Inventory class.?
Nevertheless it suggests the file is corrupted. That could be gzip problem or a saving problem.
I have seen something similar if I stop the simulation when it is half way through doing a save. It leaves an incomplete file.
But we could change back to XZ compression but use it in a stream mode instead of the byte array approach. This may give us heap problem but not as bad as the byte copy approach. I don't mind what compression we use as long as we do not use an inter immediate byte array.

**Comment by mokun** [comment]
> I have seen something similar if I stop the simulation when it is half way through doing a save

But I didn't stop or quit the sim when saving the session. 

So i don't know why it happens.

Btw, we can rename `Mars` to `MarsData` since in near future, we need to have Mars, Moon, Earth as a super location of some sort.
