### ISSUE TITLE
MersenneTwisterFast is not Thread safe

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#362]
**Describe the bug**
An ArrayIndexOutOfBoundException is generated when generating a random number. Looking at the code of the `MersenneTwisterFast` class the nextInt method check the index against the size before calling. Therefore it must be due to a thread safe issue with 2 threads access the method at the same time and one advancing the pointer after the other Thread has checked the size. 
Making the `synchronized` is not ideal as it will create a singleton method as the simulation relies heavily on the random number generator. Standard java.util.Random IS Thread safe by design, in fact for multiple Threaded application we should use  be using `ThreadLocalRandom` that uses a Thread local implementation.
This is the first time I have seen such a problem.
**To Reproduce**
Not easy but leave the simulation to run and eventually the stack trace may arise.

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 624 out of bounds for length 624
	at org.mars_sim.msp.core.tool.MersenneTwisterFast.nextInt(MersenneTwisterFast.java:1208)
	at org.mars_sim.msp.core.tool.RandomUtil.getRandomInt(RandomUtil.java:77)
	at org.mars_sim.msp.core.person.ai.task.meta.SleepMeta.getProbability(SleepMeta.java:81)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:170)
	at org.mars_sim.msp.core.person.ai.task.utils.TaskManager.startNewTask(TaskManager.java:490)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.startNewTask(PersonTaskManager.java:201)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:304)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:244)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:122)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:938)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1475)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:2943)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	... 4 more
```

**Comment by mokun** [comment]
I've seen this once in a while when loading from a saved sim.

**Comment by bevans2000** [comment]
I think the correct thing is to replace with a ThreadLocalRandom.

**Comment by bevans2000** [comment]
ac4914051427f417a177b98cf0e7628ca901140c
