### ISSUE TITLE
Commander's Profile not loading

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#367]
**Describe the bug**
- If choosing to play the *Command Mode*, after setting up a Commander's Profile, the simulation doesn't load up.

**Expected behavior**
- It should be able to process the Job Type and the Gender Type saved in *commander.txt*.

**Desktop (please complete the following information):**
 - Build 5840

**Additional context**

The GenderType doesn't match. 
```
2021-06-19T00:20:54.6 (Config) GameManager : The country of 'USA' does have a settlement called 'New Plymouth'.
2021-06-19T00:20:54.6 (Config) Person : [New Plymouth] The Mission Control replaced the member 'Gladys Flores' with 'Manny Kung'.
2021-06-19T00:20:54.6 (Severe) Simulation$CreateNewSimTask : Failed to create simulation java.lang.IllegalArgumentException: No enum constant org.mars_sim.msp.core.person.GenderType.M
java.lang.IllegalArgumentException: No enum constant org.mars_sim.msp.core.person.GenderType.M
	at java.base/java.lang.Enum.valueOf(Enum.java:266)
	at org.mars_sim.msp.core.person.GenderType.valueOf(GenderType.java:12)
	at org.mars_sim.msp.core.person.GenderType.valueOfIgnoreCase(GenderType.java:41)
	at org.mars_sim.msp.core.structure.ChainOfCommand.updateCommander(ChainOfCommand.java:454)
	at org.mars_sim.msp.core.structure.ChainOfCommand.applyCommander(ChainOfCommand.java:436)
	at org.mars_sim.msp.core.structure.Settlement.setDesignatedCommander(Settlement.java:4273)
	at org.mars_sim.msp.core.GameManager.placeInitialCommander(GameManager.java:105)
	at org.mars_sim.msp.core.Simulation.initializeIntransientData(Simulation.java:446)
	at org.mars_sim.msp.core.Simulation.createNewSimulation(Simulation.java:320)
	at org.mars_sim.msp.core.Simulation$CreateNewSimTask.run(Simulation.java:292)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2021-06-19T00:20:54.7 (Warning) MasterClock : Clock Thread stopping

```

In another case, when trying to load up an old commander.txt, the JobType doesn't match.

```
2021-06-19T00:08:14.8 (Config) MarsProject : Starting Mars Simulation Project v3.1.2-Snapshot - Build 5840 - 64-bit Java 13.0.2 - 8 CPU threads
2021-06-19T00:08:14.8 (Config) MarsProject$SimulationTask : List of input args : [-new] 
2021-06-19T00:08:14.9 (Config) MarsProject : Please proceed to selecting the type of Game Mode in the popped-up console.
2021-06-19T00:08:14.9 (Config) SimulationConfig : The xml folder already existed.
2021-06-19T00:08:14.9 (Config) SimulationConfig : The version.txt in your home xml folder shows BUILD 5839. The core engine uses BUILD 5840.
2021-06-19T00:08:14.9 (Config) SimulationConfig : Case A1 : The build folder doesn't exist yet. Back up to C:\Users\mkhelios\.mars-sim\backup\5839
2021-06-19T00:08:14.9 (Config) SimulationConfig : A new xml folder was just created.
2021-06-19T00:08:14.9 (Config) SimulationConfig : A new version.txt file was just created.
2021-06-19T00:08:14.9 (Config) SimulationConfig : A new exception.txt file was just created.
2021-06-19T00:08:15.0 (Config) SimulationConfig : simulation.xml didn't exist. Just got created.
2021-06-19T00:08:15.0 (Config) SimulationConfig : resources.xml didn't exist. Just got created.
2021-06-19T00:08:15.1 (Config) SimulationConfig : parts.xml didn't exist. Just got created.
2021-06-19T00:08:15.1 (Config) SimulationConfig : part_packages.xml didn't exist. Just got created.
2021-06-19T00:08:15.2 (Config) SimulationConfig : people.xml didn't exist. Just got created.
2021-06-19T00:08:15.2 (Config) SimulationConfig : crew.xml didn't exist. Just got created.
2021-06-19T00:08:15.3 (Config) SimulationConfig : medical.xml didn't exist. Just got created.
2021-06-19T00:08:15.3 (Config) SimulationConfig : landmarks.xml didn't exist. Just got created.
2021-06-19T00:08:15.3 (Config) SimulationConfig : minerals.xml didn't exist. Just got created.
2021-06-19T00:08:15.3 (Config) SimulationConfig : malfunctions.xml didn't exist. Just got created.
2021-06-19T00:08:15.3 (Config) SimulationConfig : crops.xml didn't exist. Just got created.
2021-06-19T00:08:15.3 (Config) SimulationConfig : vehicles.xml didn't exist. Just got created.
2021-06-19T00:08:15.4 (Config) SimulationConfig : buildings.xml didn't exist. Just got created.
2021-06-19T00:08:15.4 (Config) SimulationConfig : resupplies.xml didn't exist. Just got created.
2021-06-19T00:08:15.4 (Config) SimulationConfig : settlements.xml didn't exist. Just got created.
2021-06-19T00:08:15.5 (Config) SimulationConfig : manufacturing.xml didn't exist. Just got created.
2021-06-19T00:08:15.5 (Config) SimulationConfig : construction.xml didn't exist. Just got created.
2021-06-19T00:08:15.6 (Config) SimulationConfig : foodProduction.xml didn't exist. Just got created.
2021-06-19T00:08:15.6 (Config) SimulationConfig : meals.xml didn't exist. Just got created.
2021-06-19T00:08:15.6 (Config) SimulationConfig : robots.xml didn't exist. Just got created.
2021-06-19T00:08:15.6 (Config) SimulationConfig : quotations.xml didn't exist. Just got created.
2021-06-19T00:08:15.7 (Config) SimulationConfig : Done loading all xml files.
2021-06-19T00:08:15.7 (Config) SimulationConfig : Please go to the mars-sim console's Main Menu to choose an option.
java.lang.IllegalArgumentException: No enum constant org.mars_sim.msp.core.person.ai.job.JobType.Botanist
	at java.base/java.lang.Enum.valueOf(Enum.java:266)
	at org.mars_sim.msp.core.person.ai.job.JobType.valueOf(JobType.java:14)
	at org.mars.sim.console.CommanderProfile.loadProperties(CommanderProfile.java:502)
	at org.mars.sim.console.CommanderProfile.loadProfile(CommanderProfile.java:483)
	at org.mars.sim.console.InteractiveTerm.loadPreviousProfile(InteractiveTerm.java:564)
	at org.mars.sim.console.InteractiveTerm.selectCommandMode(InteractiveTerm.java:449)
	at org.mars.sim.console.InteractiveTerm.selectMode(InteractiveTerm.java:294)
	at org.mars.sim.console.InteractiveTerm.selectMenu(InteractiveTerm.java:153)
	at org.mars.sim.console.InteractiveTerm.startConsoleMainMenu(InteractiveTerm.java:109)
	at org.mars_sim.main.MarsProject.handleNewSimulation(MarsProject.java:728)
	at org.mars_sim.main.MarsProject.initializeSimulation(MarsProject.java:244)
	at org.mars_sim.main.MarsProject$SimulationTask.run(MarsProject.java:177)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2021-06-19T00:08:24.9 (Severe) InteractiveTerm : RuntimeException detected.
2021-06-19T00:08:25.1 (Config) Simulation : Initiating the simulation core engine...
2021-06-19T00:08:25.4 (Config) MasterClock : -----------------------------------------------------
2021-06-19T00:08:25.4 (Config) MasterClock :          User defined time-ratio : 128.0x
2021-06-19T00:08:25.4 (Config) MasterClock :               Min msol per pulse : 0.02
2021-06-19T00:08:25.4 (Config) MasterClock :               Max msol per pulse : 2.0
2021-06-19T00:08:25.4 (Config) MasterClock :  Max elapsed time between pulses : 1000 ms
2021-06-19T00:08:25.4 (Config) MasterClock :                    Accuracy bias : 0.5
2021-06-19T00:08:25.4 (Config) MasterClock : -----------------------------------------------------
2021-06-19T00:08:26.7 (Config) TerrainElevation : [New Plymouth]                 Elevation : -2.217 km
2021-06-19T00:08:26.7 (Config) TerrainElevation : [New Plymouth]         Terrain Steepness : 1.6
2021-06-19T00:08:26.7 (Config) TerrainElevation : [New Plymouth]       Ice Collection Rate : 0.94 kg/millisol
2021-06-19T00:08:27.2 (Config) EVASuit :  EVA suit's unloaded weight : 20.3 kg
2021-06-19T00:08:27.2 (Config) EVASuit :       Total gas tank volume : 3.9L
2021-06-19T00:08:27.2 (Config) EVASuit :                Full Tank O2 : 66.62 kPa -> 1.0    kg - The Maximum tank pressure
2021-06-19T00:08:27.2 (Config) EVASuit :                  Nomimal O2 : 17.0  kPa -> 0.2552 kg - The suit target pressure
2021-06-19T00:08:27.2 (Config) EVASuit :                  Minimum O2 : 11.94 kPa -> 0.1792 kg - The safety limit
2021-06-19T00:08:27.3 (Config) TerrainElevation : [Europa]                 Elevation : -3.06 km
2021-06-19T00:08:27.3 (Config) TerrainElevation : [Europa]         Terrain Steepness : 0.0
2021-06-19T00:08:27.3 (Config) TerrainElevation : [Europa]       Ice Collection Rate : 0.81 kg/millisol
2021-06-19T00:08:27.3 (Config) TerrainElevation : [Tian Cheng]                 Elevation : -2.86 km
2021-06-19T00:08:27.3 (Config) TerrainElevation : [Tian Cheng]         Terrain Steepness : 0.0
2021-06-19T00:08:27.3 (Config) TerrainElevation : [Tian Cheng]       Ice Collection Rate : 0.8 kg/millisol
2021-06-19T00:08:27.3 (Config) TerrainElevation : [New Pompeii]                 Elevation : 0.033 km
2021-06-19T00:08:27.3 (Config) TerrainElevation : [New Pompeii]         Terrain Steepness : 0.1
2021-06-19T00:08:27.3 (Config) TerrainElevation : [New Pompeii]       Ice Collection Rate : 0.72 kg/millisol
2021-06-19T00:08:27.4 (Config) Fishery : [New Pompeii] Fish Farm 1 - # of fish: 146  # of weeds: 2250.
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Kyocera]                 Elevation : -3.932 km
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Kyocera]         Terrain Steepness : 0.0
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Kyocera]       Ice Collection Rate : 0.84 kg/millisol
2021-06-19T00:08:27.4 (Config) Fishery : [Kyocera] Fish Farm 1 - # of fish: 146  # of weeds: 2250.
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Starcity]                 Elevation : -1.619 km
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Starcity]         Terrain Steepness : 0.0
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Starcity]       Ice Collection Rate : 0.76 kg/millisol
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Zvezda]                 Elevation : 0.561 km
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Zvezda]         Terrain Steepness : 0.4
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Zvezda]       Ice Collection Rate : 0.73 kg/millisol
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Schiaparelli Point]                 Elevation : -1.482 km
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Schiaparelli Point]         Terrain Steepness : 0.0
2021-06-19T00:08:27.4 (Config) TerrainElevation : [Schiaparelli Point]       Ice Collection Rate : 0.76 kg/millisol
2021-06-19T00:08:27.5 (Config) Fishery : [Schiaparelli Point] Large Greenhouse 1 - # of fish: 14  # of weeds: 270.
```

**Comment by bevans2000** [comment]
2c44ed80539b377231a54a4f21c5d9256cf4848a

**Comment by mokun** [comment]
@bevans2000 

Currently at build 5863, when I choose `Command Mode` and load the commander profile, it immediately starts the sim without showing me what the profile looks like. 

In the past, we would have a chance to confirm if we want this profile.

If yes, it goes to the next menu.

If not, it goes back.

Can you check ?

**Comment by bevans2000** [comment]
Sure. I tested this and it was ok because I added back the display of the Commander Profile but I'll check it.

**Comment by mokun** [comment]
> display of the Commander Profile

The profile is not shown when I click 

`3. Load commander profile`

**Comment by mokun** [comment]
Also, if I use the *single settlement CLI* to create a settlement. Then choose `Command Mode`, and open the Site Editor to customize my settlement, I find the Site Editor loading up a default list of settlements, instead of, say, ONE SINGLE SpaceX settlement.

This doesn't happen in `Sandbox Mode` somehow. I'll investigate that to see how to fix the logic behind.

**Comment by mokun** [comment]
I guess the logic in SimulationConfigEditor class is bad.

But should we simply create a third mode call *One Settlement Mode* for using the so-called *single settlement CLI* to start a sim ?

**Comment by mokun** [comment]
@bevans2000 ,

I'm fixing some of the logics in *InteractiveTerm* as we speak. Stay tune.

**Comment by bevans2000** [comment]
Did you have success? I can see changes.

**Comment by mokun** [comment]
Yes. They've been fixed.

I also added the ability to reverse decision and go back two steps to change to whatever mode the player wants.

**Comment by mokun** [comment]
Related to https://github.com/mars-sim/mars-sim/commit/d3cac8411aa2b5173615a0f6cb1dcb47b85a3468#commitcomment-69079271
