### ISSUE TITLE
NPE at HaveConversation 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#373]
**Describe the bug**
An unknown NPE is occurring at HaveConversation from time to time when starting a new sim. It shows up in the first 10 seconds.

**Expected behavior**
No NPE is expected. 

**Desktop**
 - build r5947

**Additional context**

```
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.HaveConversation.havingConversation(HaveConversation.java:355)
	at org.mars_sim.msp.core.person.ai.task.HaveConversation.performMappedPhase(HaveConversation.java:164)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:636)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:597)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.executeTask(PersonTaskManager.java:103)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:198)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:121)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:859)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1189)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:696)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mokun** [comment]
It points to the line  `double currentOpinion = relationship.getPersonOpinion(invitee);`

It's not possible for invitee to be null.

Also, relationship cannot be null.

```
   /**
     * Performs reading phase.
     * @param time the amount of time (millisols) to perform the phase.
     * @return the amount of time (millisols) left over after performing the phase.
     */
    private double havingConversation(double time) {

        if (isDone() || invitee == null) {
        	endTask();
            return time;
        }

        // If duration, send invitation.
        if (getDuration() <= (getTimeCompleted() + time)) {
        	
        	if (invitee != null) {
	        	// List 8 situations for having a conversation
	            if (person.isInSettlement()) {
	            	talkTo(invitee);
	            }
	            else if (person.isInVehicle()) {
	            	talkTo(invitee);
	            }

	            if (relationshipManager != null && !relationshipManager.hasRelationship(invitee, person)) {
	                // Add new communication meeting relationship.
	                relationshipManager.addRelationship(invitee, person, Relationship.COMMUNICATION_MEETING);
	                
	                // Add 1 point to invitee's opinion of the one who starts the conversation
	                Relationship relationship = relationshipManager.getRelationship(invitee, person);
	                double currentOpinion = relationship.getPersonOpinion(invitee);
	                relationship.setPersonOpinion(invitee, currentOpinion + RandomUtil.getRandomDouble(1));
	            }
        	}
        }

        return 0D;
    }
```

**Comment by bevans2000** [comment]
I think this is due to a Thread safe condition as the RelationshipManager is a shared singleton. Put a synchronised modifier on the create method.

**Comment by mokun** [comment]
Closing this. It doesn't apply anymore as RelationshipManager has gone through refactoring.
