### ISSUE TITLE
ClassCast exception starting a RescueMission

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#401]
**Describe the bug**
When starting a Rescue Mission a Drone was selected as the Rescue Vehicle which causes problem with the subsequent logic. 
```
00-Adir-03:005.073 (Info) Mission : [Schiaparelli Point] Lukáš Svoboda - Began organizing a Vehicle Rescue mission.
java.lang.ClassCastException: class org.mars_sim.msp.core.vehicle.Drone cannot be cast to class org.mars_sim.msp.core.vehicle.Rover (org.mars_sim.msp.core.vehicle.Drone and org.mars_sim.msp.core.vehicle.Rover are in unnamed module of loader 'app')
	at org.mars_sim.msp.core.person.ai.mission.RoverMission.getRover(RoverMission.java:135)
	at org.mars_sim.msp.core.person.ai.mission.RescueSalvageVehicle.<init>(RescueSalvageVehicle.java:118)
	at org.mars_sim.msp.core.person.ai.mission.meta.RescueSalvageVehicleMeta.constructInstance(RescueSalvageVehicleMeta.java:38)
	at org.mars_sim.msp.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:394)
	at org.mars_sim.msp.core.person.ai.Mind.getNewMission(Mind.java:478)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:141)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:113)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:646)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:601)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.executeTask(PersonTaskManager.java:103)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:198)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:121)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:854)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1176)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:697)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**
Have only seen this the once but not seen many RescueMissions in general !!

**Expected behavior**
Probably only a Rover should be selected as the Rescue vehicle so I guess the problem lies there; probably in the constructor of the mission.

**Comment by mokun** [comment]
Okay. I just get this fixed. 

Now it will pick a list of drones if it's a delivery mission. Or else, it will pick a list of rovers.

I suppose for now we'll use drones to do cargo delivery only. 

But it would make sense to use drones to drop in emergency resupply or for medevac as well in near future.
