### ISSUE TITLE
NPE due to threading in finding dead people

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#447]
Problem: 
- Threading issue with cleanDeadCollaborators() in ScientificStudy at the start of the sim.

```
	private void cleanDeadCollaborators() {
		List<Person> dead = findDeadPeople(collaborators.keySet());
		for(Person d : dead) {
			logger.log(primaryResearcher, Level.INFO, 0, 
					"Remove dead collaborator " + d.getName() + ".");
			removeCollaborativeResearcher(d);
		}
	}
```
	
Is getPersonByID() below the culprit again ?

```
	private static List<Person> findDeadPeople(Set<Integer> ids) {
		List<Person> dead = new ArrayList<>();
	
		UnitManager um = getUnitManager();
		for(Integer id : ids) {
			Person p = um.getPersonByID(id);
			if (p.getPhysicalCondition().isDead()) {
				dead.add(p);
			}
		}
		return dead;
	}

```

```
00-Adir-01:052.921 (Severe) Settlement [x2] : [Kyocera] Problem applying pulse : null
java.lang.NullPointerException
	at org.mars_sim.msp.core.science.ScientificStudy.cleanDeadCollaborators(ScientificStudy.java:462)
	at org.mars_sim.msp.core.science.ScientificStudy.timePassing(ScientificStudy.java:1052)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:844)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1181)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1166)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:706)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mokun** [comment]
It turns out this issue has to do with the file separator issue in https://github.com/mars-sim/mars-sim/issues/446. When #446 is fixed, this tissue is fixed also.

**Comment by bevans2000** [comment]
Really, I'm interested. How are these 2 related ?
This when running on the command line ?
I've think I've just fixed #446 so give it a try.

**Comment by mokun** [comment]
That's because I changed EXPERIMENTS_FILE to something else and it didn't work. So when I reverts back it works again. I should not even post it since I never did the commit. I'm closing this now.

**Comment by bevans2000** [comment]
Right, so the system must have got itself in to a confused state with missing config files.
