### ISSUE TITLE
Replace the use of Inventory in Settlement with a new lightweight inventory concept.

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#476]
**Describe the improvement**
There is a new approach to handling inventory based on small and simpler classes, e.g. ```EquipmentInventory```. The current Inventory implementation appears to have problems concerning the complex caching.
It should be replaced with a simpler ```DemandInventory``` that is based on the ```EquipmentInventory``` but the recording of resource demand would be done automatically when the retrieve methods are called.  This would simplify the calling code which commonly have the same calling pattern.
```
      inventory.recordDemand()
      inventory.retieveResource()
```
The new inventory would automatically maintain the demand stats when a resource was retreived.

**Comment by mokun** [comment]
Will see if I can finish the conversion for Settlement today. If not, tomorrow.

**Comment by mokun** [comment]
Alternatively, it complains of NPE when calling hasNeedyMedicalAidsAtSettlement()

```
00-Adir-01:001.461 (Severe) Settlement : [McKay Base] Problem applying pulse : null
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.task.meta.TreatMedicalPatientMeta.hasNeedyMedicalAidsAtSettlement(TreatMedicalPatientMeta.java:116)
	at org.mars_sim.msp.core.person.ai.task.meta.TreatMedicalPatientMeta.hasNeedyMedicalAids(TreatMedicalPatientMeta.java:96)
	at org.mars_sim.msp.core.person.ai.task.meta.TreatMedicalPatientMeta.getProbability(TreatMedicalPatientMeta.java:66)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:165)
	at org.mars_sim.msp.core.person.ai.task.utils.TaskManager.startNewTask(TaskManager.java:528)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.startNewTask(PersonTaskManager.java:205)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:321)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:243)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:121)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:870)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1165)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1150)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:704)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:685)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mokun** [comment]
Oh. It has to do with unit not having called setContainerUnit(). It used to be handled by Inventory when calling storeUnit() but now we have to do it manually. 

So a person doesn't belong to a settlement unless we calling setContainerUnit().

**Comment by mokun** [comment]
Now, it looks like the thread is not working. I have endless messages like this on each one of the EVA suits.

```
00-Adir-01:001.455 (Config) UnitManager : Setting up 1 thread(s) for running the settlement update.
00-Adir-01:001.455 (Severe) Unit : EVA Suit 001 rejected pulse #1, last pulse was 1
00-Adir-01:001.455 (Severe) Unit : EVA Suit 002 rejected pulse #1, last pulse was 1
00-Adir-01:001.455 (Severe) Unit : EVA Suit 003 rejected pulse #1, last pulse was 1
00-Adir-01:001.455 (Severe) Unit : EVA Suit 004 rejected pulse #1, last pulse was 1
00-Adir-01:001.455 (Severe) Unit : EVA Suit 005 rejected pulse #1, last pulse was 1
00-Adir-01:001.455 (Severe) Unit : EVA Suit 006 rejected pulse #1, last pulse was 1
00-Adir-01:001.455 (Severe) Unit : EVA Suit 007 rejected pulse #1, last pulse was 1
00-Adir-01:001.455 (Severe) Unit : EVA Suit 008 rejected pulse #1, last pulse was 1
00-Adir-01:001.621 (Severe) Unit : EVA Suit 001 rejected pulse #2, last pulse was 2
00-Adir-01:001.621 (Severe) Unit : EVA Suit 002 rejected pulse #2, last pulse was 2
00-Adir-01:001.621 (Severe) Unit : EVA Suit 003 rejected pulse #2, last pulse was 2
00-Adir-01:001.621 (Severe) Unit : EVA Suit 004 rejected pulse #2, last pulse was 2
00-Adir-01:001.621 (Severe) Unit : EVA Suit 005 rejected pulse #2, last pulse was 2
00-Adir-01:001.621 (Severe) Unit : EVA Suit 006 rejected pulse #2, last pulse was 2
00-Adir-01:001.621 (Severe) Unit : EVA Suit 007 rejected pulse #2, last pulse was 2
00-Adir-01:001.621 (Severe) Unit : EVA Suit 008 rejected pulse #2, last pulse was 2
00-Adir-01:001.661 (Severe) Unit : EVA Suit 001 rejected pulse #3, last pulse was 3
00-Adir-01:001.661 (Severe) Unit : EVA Suit 002 rejected pulse #3, last pulse was 3
00-Adir-01:001.661 (Severe) Unit : EVA Suit 003 rejected pulse #3, last pulse was 3
00-Adir-01:001.661 (Severe) Unit : EVA Suit 004 rejected pulse #3, last pulse was 3
00-Adir-01:001.661 (Severe) Unit : EVA Suit 005 rejected pulse #3, last pulse was 3
00-Adir-01:001.661 (Severe) Unit : EVA Suit 006 rejected pulse #3, last pulse was 3
00-Adir-01:001.661 (Severe) Unit : EVA Suit 007 rejected pulse #3, last pulse was 3
00-Adir-01:001.661 (Severe) Unit : EVA Suit 008 rejected pulse #3, last pulse was 3
00-Adir-01:001.701 (Severe) Unit : EVA Suit 001 rejected pulse #4, last pulse was 4
00-Adir-01:001.701 (Severe) Unit : EVA Suit 002 rejected pulse #4, last pulse was 4
00-Adir-01:001.701 (Severe) Unit : EVA Suit 003 rejected pulse #4, last pulse was 4
00-Adir-01:001.701 (Severe) Unit : EVA Suit 004 rejected pulse #4, last pulse was 4
00-Adir-01:001.701 (Severe) Unit : EVA Suit 005 rejected pulse #4, last pulse was 4
00-Adir-01:001.701 (Severe) Unit : EVA Suit 006 rejected pulse #4, last pulse was 4
00-Adir-01:001.701 (Severe) Unit : EVA Suit 007 rejected pulse #4, last pulse was 4
00-Adir-01:001.701 (Severe) Unit : EVA Suit 008 rejected pulse #4, last pulse was 4
00-Adir-01:001.748 (Severe) Unit : EVA Suit 001 rejected pulse #5, last pulse was 5
00-Adir-01:001.748 (Severe) Unit : EVA Suit 002 rejected pulse #5, last pulse was 5
00-Adir-01:001.748 (Severe) Unit : EVA Suit 003 rejected pulse #5, last pulse was 5
00-Adir-01:001.748 (Severe) Unit : EVA Suit 004 rejected pulse #5, last pulse was 5
00-Adir-01:001.748 (Severe) Unit : EVA Suit 005 rejected pulse #5, last pulse was 5
00-Adir-01:001.748 (Severe) Unit : EVA Suit 006 rejected pulse #5, last pulse was 5
00-Adir-01:001.748 (Severe) Unit : EVA Suit 007 rejected pulse #5, last pulse was 5
00-Adir-01:001.748 (Severe) Unit : EVA Suit 008 rejected pulse #5, last pulse was 5
00-Adir-01:001.788 (Severe) Unit : EVA Suit 001 rejected pulse #6, last pulse was 6
00-Adir-01:001.788 (Severe) Unit : EVA Suit 002 rejected pulse #6, last pulse was 6
00-Adir-01:001.788 (Severe) Unit : EVA Suit 003 rejected pulse #6, last pulse was 6
00-Adir-01:001.788 (Severe) Unit : EVA Suit 004 rejected pulse #6, last pulse was 6
00-Adir-01:001.788 (Severe) Unit : EVA Suit 005 rejected pulse #6, last pulse was 6
00-Adir-01:001.788 (Severe) Unit : EVA Suit 006 rejected pulse #6, last pulse was 6
00-Adir-01:001.788 (Severe) Unit : EVA Suit 007 rejected pulse #6, last pulse was 6
00-Adir-01:001.788 (Severe) Unit : EVA Suit 008 rejected pulse #6, last pulse was 6
00-Adir-01:001.827 (Severe) Unit : EVA Suit 001 rejected pulse #7, last pulse was 7
00-Adir-01:001.827 (Severe) Unit : EVA Suit 002 rejected pulse #7, last pulse was 7
00-Adir-01:001.827 (Severe) Unit : EVA Suit 003 rejected pulse #7, last pulse was 7
00-Adir-01:001.827 (Severe) Unit : EVA Suit 004 rejected pulse #7, last pulse was 7
```
