### ISSUE TITLE
Mission Tool not working: NoClassDefFoundError; Cannot select a mission in MissionWindow

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#499]
**Describe the bug**
- `NoClassDefFoundError` when calling SwingUtilities.invokeLater(new MissionListUpdater((....))) in `addMission()` and `removeMission()` in `MissionListModel`.

**To Reproduce**
1. Open the Mission Tool
2. See `NoClasDefFoundError` in stacktrace

**Version**
Build 6421

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/140863421-9f404cd1-df9e-4e16-8fd4-80c0f1d2efbe.png)

**StackTrace**
```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/mars_sim/msp/ui/swing/tool/mission/MissionListModel$MissionListUpdater
	at org.mars_sim.msp.ui.swing.tool.mission.MissionListModel.addMission(MissionListModel.java:95)
	at org.mars_sim.msp.ui.swing.tool.mission.MissionListModel.populateMissions(MissionListModel.java:76)
	at org.mars_sim.msp.ui.swing.tool.mission.MissionWindow.selectSettlement(MissionWindow.java:327)
	at org.mars_sim.msp.ui.swing.tool.mission.MissionWindow$1.mouseClicked(MissionWindow.java:103)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6638)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
00-Adir-03:848.333 (Info) MissionManager : [Zvezda] Viktor Balandin - Regolith Prospecting mission planning cumulative score : 56.4 (10.0% review completed)
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/mars_sim/msp/ui/swing/tool/mission/MissionListModel$MissionListUpdater
	at org.mars_sim.msp.ui.swing.tool.mission.MissionListModel.removeMission(MissionListModel.java:112)
	at org.mars_sim.msp.ui.swing.tool.mission.MissionListModel.populateMissions(MissionListModel.java:68)
	at org.mars_sim.msp.ui.swing.tool.mission.MissionWindow.selectSettlement(MissionWindow.java:327)
	at org.mars_sim.msp.ui.swing.tool.mission.MissionWindow$1.mouseClicked(MissionWindow.java:103)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6638)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by bevans2000** [comment]
This can only happen if it ran with out of sync class files. A bit odd. It's working fine in my branch. I will merge my changes in tonight.

**Comment by bevans2000** [comment]
Has this gone now? Can we close this?

**Comment by mokun** [comment]
Closing it.

**Comment by mokun** [comment]
I also found the nav tab cannot show the navpoints in a stable manner. 

When I click and hold on a mission, it show the navpoints temporarily.

As soon as I release the mouse button on a mission, the navpoint table disappears.

This is due to call populateMissions() that in turns would call removeMission() whenever clicking on a mission.  

Fixing it now.

**Comment by bevans2000** [comment]
I've seen that

**Comment by bevans2000** [comment]
The original problem of class not found is resolved so let's close this.
