### ISSUE TITLE
NPE in calling RoverMission constructor

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#505]
**Describe the bug**
- Encounter an NPE at Line 100 when calling `calculateMissionCapacity()` with RoverMission when creating an *Emergency Supply( mission.

**Methods**

```java
	/**
	 * Constructor 1.
	 *
	 * @param name           the name of the mission.
	 * @param startingMember the mission member starting the mission.
	 */
	protected RoverMission(String name, MissionType missionType, MissionMember startingMember) {
		// Use VehicleMission constructor.
		super(name, missionType, startingMember);
		calculateMissionCapacity(getRover().getCrewCapacity());
	}
```

From Mission's calculateMissionCapacity() :
```java
	/**
	 * Calculate the mission capacity the lower of desired capacity or number of EVASuits
	 */
	protected void calculateMissionCapacity(int desiredCap) {
		if (!isDone()) {
			// Set mission capacity.
			int availableSuitNum = Mission.getNumberAvailableEVASuitsAtSettlement(getStartingPerson().getAssociatedSettlement());
			if (availableSuitNum < desiredCap) {
				desiredCap = availableSuitNum;
			}
			setMissionCapacity(desiredCap);
		}
	}

```
**Version**
 - Build 6445

**Additional context**
```
00-Adir-02:352.791 (Info) Mission : [Schiaparelli Point] Mohamed Willems - Began organizing an Emergency Supply mission.
00-Adir-02:352.791 (Info) Mission : [Schiaparelli Point] Mohamed Willems - Ended the Emergency Supply #17 with the status flag(s): No reservable vehicles
00-Adir-02:352.791 (Info) Mission : [Schiaparelli Point] Mohamed Willems - Disbanded mission member(s) : [Mohamed Willems]
00-Adir-02:353.122 (Info) MissionManager : [Schiaparelli Point] Tao Peng - Mission Emergency Supply with probability=100.0
00-Adir-02:353.122 (Info) Mission : [Schiaparelli Point] Tao Peng - Began organizing an Emergency Supply mission.
00-Adir-02:353.122 (Info) Mission : [Schiaparelli Point] Tao Peng - Ended the Emergency Supply #18 with the status flag(s): No reservable vehicles
00-Adir-02:353.122 (Info) Mission : [Schiaparelli Point] Tao Peng - Disbanded mission member(s) : [Tao Peng]
00-Adir-02:353.122 (Warning) VehicleMission : [Schiaparelli Point] Tao Peng - Could not reserve a vehicle for Emergency Supply #18.
00-Adir-02:353.122 (Severe) PersonTaskManager : [Schiaparelli Point] Tao Peng - Trouble calling performTask(): 
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.mission.RoverMission.<init>(RoverMission.java:100)
	at org.mars_sim.msp.core.person.ai.mission.EmergencySupply.<init>(EmergencySupply.java:100)
	at org.mars_sim.msp.core.person.ai.mission.meta.EmergencySupplyMissionMeta.constructInstance(EmergencySupplyMissionMeta.java:32)
	at org.mars_sim.msp.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:299)
	at org.mars_sim.msp.core.person.ai.Mind.getNewMission(Mind.java:487)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:134)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:111)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:650)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:605)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.executeTask(PersonTaskManager.java:100)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:198)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:121)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:869)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1174)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:723)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

00-Adir-02:356.091 (Info) MissionManager : [Schiaparelli Point] Lara Weber - Mission Emergency Supply with probability=100.0
00-Adir-02:356.091 (Info) Mission : [Schiaparelli Point] Lara Weber - Began organizing an Emergency Supply mission.
00-Adir-02:356.091 (Info) Mission : [Schiaparelli Point] Lara Weber - Ended the Emergency Supply #19 with the status flag(s): No reservable vehicles
00-Adir-02:356.091 (Info) Mission : [Schiaparelli Point] Lara Weber - Disbanded mission member(s) : [Lara Weber]
00-Adir-02:356.091 (Warning) VehicleMission : [Schiaparelli Point] Lara Weber - Could not reserve a vehicle for Emergency Supply #19.
00-Adir-02:356.091 (Severe) PersonTaskManager : [Schiaparelli Point] Lara Weber - Trouble calling performTask(): 
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.mission.RoverMission.<init>(RoverMission.java:100)
	at org.mars_sim.msp.core.person.ai.mission.EmergencySupply.<init>(EmergencySupply.java:100)
	at org.mars_sim.msp.core.person.ai.mission.meta.EmergencySupplyMissionMeta.constructInstance(EmergencySupplyMissionMeta.java:32)
	at org.mars_sim.msp.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:299)
	at org.mars_sim.msp.core.person.ai.Mind.getNewMission(Mind.java:487)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:134)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:111)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:650)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:605)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.executeTask(PersonTaskManager.java:100)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:198)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:121)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:869)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1174)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:723)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by mokun** [comment]
> 00-Adir-02:353.122 (Warning) VehicleMission : [Schiaparelli Point] Tao Peng - Could not reserve a vehicle for Emergency Supply #18.

Looks like the reason for NPE is that the vehicle is null, therefore, getRover() is null.

**Comment by mokun** [comment]
@bevans2000 

> 00-Adir-02:353.122 (Warning) VehicleMission : [Schiaparelli Point] Tao Peng - Could not reserve a vehicle for Emergency Supply #18.

Looks like the reason for NPE is that the vehicle is null, therefore, getRover() is null.

**Comment by bevans2000** [comment]
Yes, I know what this is. The isDone check should be in the constructor not the calculateMissionCapacity method. The Mission must be failing to reserve a vehicle since when coming ot of the constructor the Vehicle will be assigned otherwise the mission is aborted.
I knew of this issue but thought I had already changed it.

**Comment by bevans2000** [comment]
If you in your log snippet you can see the Mission was aborted because it could not reserve a vehicle.
