### ISSUE TITLE
ClassCastException in calculateSolarIrradiance() in SurfaceFeatures

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#592]
**Describe the bug**
1. When driving a rover, settlers cannot perform the task in PersonTaskManager.
2. The stack trace shows it run into ClassCastException, namely, the "opticalDepthMap" map in calculateSolarIrradiance() in SurfaceFeatures cannot be cast to class java.util.HashMap$TreeNode.

**To Reproduce**
1. It happens especially at 1024x or 2048x speed.

**Desktop (please complete the following information):**
 - pre-3.4.0 build 6782

**Additional context**
```
00-Adir-01:820.644 (Severe) PersonTaskManager : [34.72 N 147.78 W - Ku-Se] Rio Mori - Trouble calling performTask(): 
java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1900)
	at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:2016)
	at java.base/java.util.HashMap.treeifyBin(HashMap.java:768)
	at java.base/java.util.HashMap.putVal(HashMap.java:640)
	at java.base/java.util.HashMap.put(HashMap.java:608)
	at org.mars_sim.msp.core.environment.SurfaceFeatures.calculateSolarIrradiance(SurfaceFeatures.java:441)
	at org.mars_sim.msp.core.environment.SurfaceFeatures.getSolarIrradiance(SurfaceFeatures.java:301)
	at org.mars_sim.msp.core.environment.SurfaceFeatures.getSunlightRatio(SurfaceFeatures.java:270)
	at org.mars_sim.msp.core.person.ai.task.DriveGroundVehicle.checkForAccident(DriveGroundVehicle.java:403)
	at org.mars_sim.msp.core.person.ai.task.OperateVehicle.mobilizeVehiclePhase(OperateVehicle.java:300)
	at org.mars_sim.msp.core.person.ai.task.OperateVehicle.performMappedPhase(OperateVehicle.java:220)
	at org.mars_sim.msp.core.person.ai.task.DriveGroundVehicle.performMappedPhase(DriveGroundVehicle.java:153)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:630)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:585)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.executeTask(PersonTaskManager.java:100)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:200)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:844)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1124)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:998)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:953)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:753)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

00-Adir-01:829.225 (Severe) PersonTaskManager : [34.72 N 147.81 W - Ho-To] Ibuki Murakami - Trouble calling performTask(): 
java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1900)
	at java.base/java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2079)
	at java.base/java.util.HashMap.putVal(HashMap.java:634)
	at java.base/java.util.HashMap.put(HashMap.java:608)
	at org.mars_sim.msp.core.environment.SurfaceFeatures.calculateSolarIrradiance(SurfaceFeatures.java:441)
	at org.mars_sim.msp.core.environment.SurfaceFeatures.getSolarIrradiance(SurfaceFeatures.java:301)
	at org.mars_sim.msp.core.environment.SurfaceFeatures.getSunlightRatio(SurfaceFeatures.java:270)
	at org.mars_sim.msp.core.person.ai.task.DriveGroundVehicle.checkForAccident(DriveGroundVehicle.java:403)
	at org.mars_sim.msp.core.person.ai.task.OperateVehicle.mobilizeVehiclePhase(OperateVehicle.java:300)
	at org.mars_sim.msp.core.person.ai.task.OperateVehicle.performMappedPhase(OperateVehicle.java:220)
	at org.mars_sim.msp.core.person.ai.task.DriveGroundVehicle.performMappedPhase(DriveGroundVehicle.java:153)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:630)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:585)
	at org.mars_sim.msp.core.person.ai.task.utils.PersonTaskManager.executeTask(PersonTaskManager.java:100)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:200)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:844)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1124)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:998)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:953)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:753)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

00-Adir-01:840.299 (Info) Sleep : [38.89 N 164.99 E - Roadster] Laurence Li - Sleep adjusted for shift starts at 841. Duration: 1
00-Adir-01:845.351 (Severe) PersonTaskManager : [38.87 N 164.99 E - Roadster] Fred Torres - Trouble calling performTask(): 
java.lang.ClassCastException
```

**Comment by mokun** [comment]
@bevans2000 

Have you seen this ? especially in higher speed ? 

How would you avoid threading issue like this ?
