### ISSUE TITLE
repeat command is buggy 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#596]
**Describe the bug**
- Type '/rt' or 'repeat' in console and you'll get NPE

**Screenshots**
```
00-Adir-01:309 Hawthorne >  ​/rt
Sorry I had a problem doing that null
java.lang.NullPointerException
	at org.mars.sim.console.chat.command.RepeatCommand.execute(RepeatCommand.java:40)
	at org.mars.sim.console.chat.command.InteractiveChatCommand.execute(InteractiveChatCommand.java:138)
	at org.mars.sim.console.chat.Conversation.interact(Conversation.java:146)
	at org.mars.sim.console.InteractiveTerm.loadTerminalMenu(InteractiveTerm.java:605)
	at org.mars_sim.main.MarsProject$ConsoleTask.run(MarsProject.java:423)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

See below : Is it how I make the waste command running every 10 seconds ?

```
00-Adir-01:630 Hawthorne >  ​repeat 10 waste
Sorry I had a problem doing that For input string: "waste"
java.lang.NumberFormatException: For input string: "waste"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.mars.sim.console.chat.command.RepeatCommand.execute(RepeatCommand.java:46)
	at org.mars.sim.console.chat.command.InteractiveChatCommand.execute(InteractiveChatCommand.java:138)
	at org.mars.sim.console.chat.Conversation.interact(Conversation.java:146)
	at org.mars.sim.console.InteractiveTerm.loadTerminalMenu(InteractiveTerm.java:605)
	at org.mars_sim.main.MarsProject$ConsoleTask.run(MarsProject.java:423)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Desktop (please complete the following information):**
 - pre-3.4.0 build 6789

**Comment by mokun** [comment]
@bevans2000 

The repeat command is not listed in the help menu. Is it because it's not working yet ?

**Comment by bevans2000** [comment]
Hmm, I thought it was working fine. Maybe it's not as resilient as I thought. I will take this Issue

**Comment by bevans2000** [comment]
Updated the error checking
