### ISSUE TITLE
UnitManager$SettlementTask : Problem with pulse on Starcity: settlement is null

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#599]
**Describe the bug**
1. There's problem with calling hasEnoughSupplies() in LoadVehicleGarage.java at line 283
2. One reason is that `java.lang.IllegalArgumentException: settlement is null`
3. It could be a concurrency issue due to UnitManger's global reach.

**Expected behavior**
1. It should see that the settlement instance is not null.

**Version **
- pre-3.4.0 build 6807

**Additional context**
```
00-Adir-05:476.927 (Info) Mission : [Starcity] Charlotte Thibault - Getting ready to embark on Mineral Exploration.
00-Adir-05:476.927 (Info) UnloadVehicleGarage : [Schiaparelli Point] Anna Steiner - Just unloaded 2.05 kg of resources from Wind Runner.
00-Adir-05:481.397 (Warning) RespondToStudyInvitation : [41.01 N 165.32 E - Drifter] Leo Richard - Doing too many studies to accept Botany #22
00-Adir-05:481.397 (Info) DriveGroundVehicle : [41.01 N 165.32 E - Drifter] Leo Richard - Took the wheel of the rover.
00-Adir-05:481.397 (Warning) DroneMission [x6] : [36.18 N 153.52 W] Drone 008 - Out of fuel. Quit assigning the driving task.
00-Adir-05:482.245 (Info) OperateVehicle [x14] : [41.01 N 165.32 E] Drifter - type: explorer rover   mass: 2503.82 kg   distanceTraveled: 0.1664 km   v: 8.7 km/h   F_initialFriction: 2.069 N   F_againstGravity: 0.0 N   F_aeroDragForce: 0.219 N   F_rolling: 1024.5633 N   F_total: 1026.8512 N   power: 2481.5572 kW   energy: 0.04746 kWh   fuelUsed: 0.002 kg   estFE: 9.539 km/kg   initFE: 9.539 km/kg   iFE: 83.148 km/kg   iFE: 3.506 km/kWh   aveP: 2.482 kW   
00-Adir-05:486.564 (Severe) Walk : [Schiaparelli Point] Yaping Liu - Was supposed to be in a rover.
00-Adir-05:490.942 (Info) Mission : [Schiaparelli Point] Yaping Liu - Ended the Regolith Prospecting #40 with the status flag(s): Mission Accomplished
00-Adir-05:490.942 (Info) Mission : [Schiaparelli Point] Yaping Liu - Disbanded mission member(s) : [Yaping Liu, Karen Andersen, Isabella Taylor, Anna Steiner]
00-Adir-05:493.543 (Severe) Walk : [Schiaparelli Point] Karen Andersen - Was supposed to be in a rover.
00-Adir-05:494.391 (Info) VehicleMission [x3] : [18.39 N 50.78 W] Merih - 1. Mineral Exploration #12 has an estimated remaining distance of 173.3 km.
00-Adir-05:496.974 (Info) VehicleMission [x3] : [40.96 N 165.28 E] Drifter - 1. Mineral Exploration #41 has an estimated remaining distance of 475.0 km.
00-Adir-05:496.974 (Info) VehicleMission : [40.96 N 165.28 E] Drifter - Mineral Exploration #41 has an estimated remaining trip time of 1244.4 millisols.
00-Adir-05:496.974 (Severe) UnitManager$SettlementTask : Problem with pulse on Starcity: settlement is null
java.lang.IllegalArgumentException: settlement is null
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleGarage.hasEnoughSupplies(LoadVehicleGarage.java:283)
	at org.mars_sim.msp.core.person.ai.mission.VehicleMission.isVehicleLoadable(VehicleMission.java:628)
	at org.mars_sim.msp.core.person.ai.mission.VehicleMission.determineNewPhase(VehicleMission.java:682)
	at org.mars_sim.msp.core.person.ai.mission.Exploration.determineNewPhase(Exploration.java:256)
	at org.mars_sim.msp.core.person.ai.mission.Mission.performMission(Mission.java:661)
	at org.mars_sim.msp.core.person.ai.Mind.resumeMission(Mind.java:336)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:313)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:241)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:844)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1124)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:998)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:953)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:753)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mokun** [comment]
@bevans2000 

Have you seen this from time to time ?

**Comment by bevans2000** [comment]
No, never seen it.

**Comment by bevans2000** [comment]
I've seen something similar today in the Meta classes where the ProcessOverride is checked for a Person who is not in a Settlement.

**Comment by mokun** [comment]
> ProcessOverride



> I've seen something similar today in the Meta classes where the ProcessOverride is checked for a Person who is not in a Settlement.

hmmm. I've just added a new override lately. 

which meta task ?

does he/she need to be in a settlement in principle to do that task ?

**Comment by bevans2000** [comment]
I think I might have found the problem. The method ```Person.getSettlement``` can return null when a Person is in a Building

**Comment by mokun** [comment]
Code smells point out the use of volatile is still haphazard for these maps in UnitManager class.

```
	/** A map of settlements with its unit identifier. */
	private volatile Map<Integer, Settlement> lookupSettlement;
	/** A map of sites with its unit identifier. */
	private volatile Map<Integer, ConstructionSite> lookupSite;
	/** A map of persons with its unit identifier. */
	private volatile Map<Integer, Person> lookupPerson;
	/** A map of robots with its unit identifier. */
	private volatile Map<Integer, Robot> lookupRobot;
	/** A map of vehicle with its unit identifier. */
	private volatile Map<Integer, Vehicle> lookupVehicle;
	/** A map of equipment (excluding robots and vehicles) with its unit identifier. */
	private volatile Map<Integer, Equipment> lookupEquipment;
	/** A map of building with its unit identifier. */
	private volatile Map<Integer, Building> lookupBuilding;
```

Shall we change it to, say, `ThreadLocal<Map<Integer, Settlement>) lookupSettlement`, etc. ?

**Comment by bevans2000** [comment]
No these can't be thread local because they are singletons. Just drop the volatile because the reference to the Map object is actually unchanging. It is the contents of the Map that changes.

**Comment by bevans2000** [comment]
I think this is fixed so let's close it
