### ISSUE TITLE
NPE on getOptionalEquipmentToLoad

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#602]
**Describe the bug**
- Unable to finish loading optional equipment when starting a mission
- Recent changes on parts name may have caused this but it cannot be tracked down

**Additional context**

```
00-Adir-01:254.494 (Info) MissionManager : [IronVille] James Landry - Mission Ice Prospecting with probability=1.0333333333333334 boost=0
00-Adir-01:254.494 (Info) MissionManager : [IronVille] James Landry - Mission Regolith Prospecting with probability=1.1 boost=0
00-Adir-01:254.494 (Info) MissionManager : [IronVille] James Landry - Mission Mineral Exploration with probability=1.0 boost=0
00-Adir-01:254.494 (Info) Mission : [IronVille] James Landry - Began organizing an Ice Prospecting mission.
00-Adir-01:254.494 (Info) CollectResourcesMission : Ice Prospecting totalSiteScore: 16.547   bestScore: 8.101
00-Adir-01:254.494 (Info) CollectResourcesMission : Ice Prospecting totalSiteScore: 24.682   bestScore: 8.135
00-Adir-01:254.494 (Info) CollectResourcesMission : [IronVille] Roadster - Target amount of resource per site: 666 kg of ice.
00-Adir-01:254.494 (Info) VehicleMission : [IronVille] Roadster - 1. Ice Prospecting #1 has an estimated remaining distance of 24.9 km.
00-Adir-01:254.494 (Info) VehicleMission : [IronVille] Roadster - Trip Distance: 24.9 km   Fuel Economy: 9.5 km/kg   Fuel Margin: 3.3   Fuel: 8.5 kg
00-Adir-01:254.494 (Info) VehicleMission : [IronVille] Roadster - Ice Prospecting #1 has an estimated remaining trip time of 535.5 millisols.
00-Adir-01:255.346 (Info) PlanMission : [IronVille] James Landry - Submitted a mission plan for Ice Prospecting #1.
00-Adir-01:256.201 (Info) Mission : [IronVille] James Landry - Serving as the mission lead on Ice Prospecting #1.
00-Adir-01:256.201 (Info) MissionManager : [IronVille] James Landry - Put together a mission plan for Ice Prospecting #1.
00-Adir-01:256.201 (Config) MissionManager : Added 'Ice Prospecting #1' mission.
00-Adir-01:392.927 (Info) ToggleResourceProcess : [IronVille] James Landry - Manually turned on Oxygen Generation System in Lander Hab 1.
00-Adir-01:505.930 (Warning) Storage : [IronVille] Ran out of potato.
00-Adir-01:510.192 (Info) ReviewMissionPlan : [IronVille] Maika Roy - Approved James Landry's Ice Prospecting mission plan. Total Score: 1596.0 (Min: 400.0).
00-Adir-01:512.750 (Info) Mission : [IronVille] James Landry - Getting ready to embark on Ice Prospecting.
00-Adir-01:534.925 (Info) VehicleMission : [IronVille] Roadster - 1. Ice Prospecting #1 has an estimated remaining distance of 24.9 km.
00-Adir-01:534.925 (Info) VehicleMission : [IronVille] Roadster - Trip Distance: 24.9 km   Fuel Economy: 9.5 km/kg   Fuel Margin: 3.3   Fuel: 8.5 kg
00-Adir-01:534.925 (Info) VehicleMission : [IronVille] Roadster - Ice Prospecting #1 has an estimated remaining trip time of 535.5 millisols.
00-Adir-01:640.891 (Info) VehicleMission : [IronVille] Roadster - Prepared a loading plan sourced from IronVille.
00-Adir-01:640.891 (Info) VehicleMission : [IronVille] Roadster - 1. Ice Prospecting #1 has an estimated remaining distance of 24.9 km.
00-Adir-01:640.891 (Info) VehicleMission : [IronVille] Roadster - Trip Distance: 24.9 km   Fuel Economy: 9.5 km/kg   Fuel Margin: 3.3   Fuel: 8.5 kg
00-Adir-01:640.891 (Severe) UnitManager$SettlementTask : Problem with pulse on IronVille: null
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.mission.VehicleMission.getOptionalEquipmentToLoad(VehicleMission.java:1557)
	at org.mars_sim.msp.core.person.ai.mission.RoverMission.getOptionalEquipmentToLoad(RoverMission.java:899)
	at org.mars_sim.msp.core.person.ai.mission.VehicleMission.prepareLoadingPlan(VehicleMission.java:280)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleEVA.initLoad(LoadVehicleEVA.java:124)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleEVA.<init>(LoadVehicleEVA.java:171)
	at org.mars_sim.msp.core.person.ai.mission.RoverMission.performEmbarkFromSettlementPhase(RoverMission.java:330)
	at org.mars_sim.msp.core.person.ai.mission.VehicleMission.performPhase(VehicleMission.java:739)
	at org.mars_sim.msp.core.person.ai.mission.RoverMission.performPhase(RoverMission.java:1095)
	at org.mars_sim.msp.core.person.ai.mission.CollectResourcesMission.performPhase(CollectResourcesMission.java:317)
	at org.mars_sim.msp.core.person.ai.mission.Mission.performMission(Mission.java:668)
	at org.mars_sim.msp.core.person.ai.Mind.resumeMission(Mind.java:336)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:313)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:241)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:844)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1122)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:998)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:953)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:753)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mokun** [comment]
@bevans2000 

Have you seen this lately ?

**Comment by bevans2000** [comment]
No I've never seen this. To be honest I haven't look at where the problem could be.

**Comment by mokun** [comment]
I received this every time when it was trying to start a mission.

Can't load anything now.

**Comment by mokun** [comment]
Interestingly, it's the resource id that is null. 

I forget what an optional equipment is and needs to look it up.

```
	/**
	 * Gets the optional containers needed for storing the optional resources when loading up the vehicle.
	 *
	 * @return the containers needed.
	 */
	protected Map<Integer, Integer> getOptionalEquipmentToLoad() {

		Map<Integer, Integer> result = new ConcurrentHashMap<>();

		// Figure out the type of containers needed by optional amount resources.
		Map<Integer, Number> optionalResources = getOptionalResourcesToLoad();
		Iterator<Integer> i = optionalResources.keySet().iterator();
		while (i.hasNext()) {
			Integer id = i.next();
			// Check if it's an amount resource that can be stored inside
			if (id < ResourceUtil.FIRST_ITEM_RESOURCE_ID) {
				double amount = (double) optionalResources.get(id);

				// Obtain a container for storing the amount resource
				EquipmentType containerType = ContainerUtil.getContainerClassToHoldResource(id);
				int containerID = EquipmentType.getResourceID(containerType);
				double capacity = ContainerUtil.getContainerCapacity(containerType);
				int numContainers = (int) Math.ceil(amount / capacity);

				if (result.containsKey(containerID)) {
					numContainers += result.get(containerID);
				}

				result.put(containerID, numContainers);
			}

			// Note: containers are NOT designed to hold parts
			// Parts do not need a container. Any exceptions for that ?
		}

		return result;
	}
```

**Comment by mokun** [comment]
It looks like EVA suit is considered an optional equipment here in `RoverMission` : 

```
	/**
	 * Gets the optional containers for a Rover mission. Add a spare EVASuit
	 *
	 * @return the containers needed.
	 */
	@Override
	protected Map<Integer, Integer> getOptionalEquipmentToLoad() {
		Map<Integer, Integer> result = super.getOptionalEquipmentToLoad();

		// Gets a spare EVA suit for each 4 members in a mission
		int numEVA = (int) (getPeopleNumber() * EXTRA_EVA_SUIT_FACTOR);
		result.put(EquipmentType.getResourceID(EquipmentType.EVA_SUIT), numEVA);

		return r
```esult;
	}

**Comment by mokun** [comment]
The thing is that EVA Suit as an equipment never need a container to hold it.

May be in future we could create a container type such as "box package". In today's world, we ordered a lot of things from Amazon and recycle/throw away a lot of those amazon boxes.

**Comment by mokun** [comment]
I just added a line for printing what's in that OptionalEquipment map right before calling `while (i.hasNext())`. See result below.
```
VehicleMission - getOptionalEquipmentToLoad - optionalResources -> {null=2, 513=1, 642=1, 530=4, 502=1, 503=1, 504=1, 554=1, 508=1, 637=1, 510=1, 527=3}
VehicleMission - getOptionalEquipmentToLoad: null
00-Adir-01:181.698 (Severe) UnitManager$SettlementTask : Problem with pulse on Zvezda: null
java.lang.NullPointerException
	at org.mars_sim.msp.core.person.ai.mission.VehicleMission.getOptionalEquipmentToLoad(VehicleMission.java:1559)
	at org.mars_sim.msp.core.person.ai.mission.RoverMission.getOptionalEquipmentToLoad(RoverMission.java:899)
	at org.mars_sim.msp.core.person.ai.mission.VehicleMission.prepareLoadingPlan(VehicleMission.java:280)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleGarage.initLoad(LoadVehicleGarage.java:122)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleGarage.<init>(LoadVehicleGarage.java:156)
	at org.mars_sim.msp.core.person.ai.mission.RoverMission.performEmbarkFromSettlementPhase(RoverMission.java:327)
	at org.mars_sim.msp.core.person.ai.mission.VehicleMission.performPhase(VehicleMission.java:739)
	at org.mars_sim.msp.core.person.ai.mission.RoverMission.performPhase(RoverMission.java:1097)
	at org.mars_sim.msp.core.person.ai.mission.CollectResourcesMission.performPhase(CollectResourcesMission.java:317)
	at org.mars_sim.msp.core.person.ai.mission.Mission.performMission(Mission.java:668)
	at org.mars_sim.msp.core.person.ai.Mind.resumeMission(Mind.java:336)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:313)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:241)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:844)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1136)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:1012)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:967)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:753)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mokun** [comment]
Ah I found out why.

I've changed the part 'rover wheel' and others lately and that's the reason for null. 

Fixing it now.

**Comment by bevans2000** [comment]
Can we close this now?
