### ISSUE TITLE
NPE at Heating for a Fish Farm

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#622]
**Describe the bug**
- Encountering this NPE only when starting a settlement with fish farm.
 
**Expected and unexpected behavior**
- Recent activities such as [1](https://github.com/mars-sim/mars-sim/commit/fe5ec96ff446fe95c0e50c2d493a5e23230009de) in removing the matching using building type may have contributed to this NPE. 
- a fish farm is different from a regular greenhouse but if they are adjacent to each other, checking for the temperature of one building may prompt for its adjacent building as well.

**Java classes involved**
- When calculating thermal requirements, namely, the temperature of a fish farm, it calls ThermalGenderation

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 6928

**Stacktrace**
```
00-Adir-01:025.234 (Severe) BuildingManager : [Kyocera] Fish Farm 1 - Problem applying pulse to Building
java.lang.NullPointerException
	at org.mars_sim.msp.core.structure.building.function.Heating.determineDeltaTemperature(Heating.java:496)
	at org.mars_sim.msp.core.structure.building.function.Heating.cycleThermalControl(Heating.java:953)
	at org.mars_sim.msp.core.structure.building.function.Heating.timePassing(Heating.java:928)
	at org.mars_sim.msp.core.structure.building.function.ThermalGeneration.timePassing(ThermalGeneration.java:238)
	at org.mars_sim.msp.core.structure.building.Building.timePassing(Building.java:1077)
	at org.mars_sim.msp.core.structure.building.BuildingManager.timePassing(BuildingManager.java:811)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:1007)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:965)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:753)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mokun** [comment]
@bevans2000 

In `BuildingCategory`, would FARMING to a category intended for both greenhouse and fish farm ?
