### ISSUE TITLE
Too much memory used (1.26 GB/1.5 GB) on Sol 14

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#649]
**Describe the bug**
- Too much heap memory being used on Sol 14 on a 9-settlement simulation

**Expected and unexpected behavior**
- Need to find out which class has mutable data that are growing over time

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/181651960-1130dde8-60d2-4aff-89a9-501564bfa8c0.png)

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7059

**Additional context**
- May use console to find out what serialized objects are the largest and still growing. 

**Stacktrace**
- This seems to have impacted how ObjectInputStream class is run when trying to deserializing objects. 
- It fails to load from saved sim (that are 10 sols older) from time to time.

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.io.ObjectInputStream$HandleTable.grow(ObjectInputStream.java:4088)
	at java.base/java.io.ObjectInputStream$HandleTable.assign(ObjectInputStream.java:3894)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
	at java.base/java.util.ArrayList.readObject(ArrayList.java:929)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2351)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
	at java.base/java.util.LinkedList.readObject(LinkedList.java:1153)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2351)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
```

**Comment by bevans2000** [comment]
The problem will be in historical recording of data/events. We should only hold previous data for the last 5 days. There is a common class that should be used for any historical data that will automatically drop data.

The Mission history is not purged I think nor is the outcome of Mission Reviews. This area should be addressed. 
But eventually a memory analyser will have to be used inside a debugger to see where the objects are being retained.

**Comment by bevans2000** [comment]
Going to close this as memory consumption has gone down now.
