### ISSUE TITLE
Relationship between settlements and sponsors

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#656]
**Is your feature request related to a problem?**
- We have modeled interpersonal relationship between any two individual with a permutation score
- It's about time we also model inter-settlement relationship
- Later we may model relationship between sponors as well as between sponors and settlements. 

**Describe the solution you'd like**
- Implement a score representing the opinion of a settlement toward another. 
- Implement it such that the opinion of settlement A on settlement B is NOT the same as the opinion of B on A. Thus {A, B} is NOT equal to {B, A}. They are NOT reciprocal.

**Describe alternatives you've considered**
- Implement more concretely how a settlement behaves toward another settlement, instead of a relationship score. 

**Specifications  (please complete the following information):**
- pre-3.4.0 build 7090

**Additional context**
- This would give player the motivation to perform certain activities in line with what his sponsor wants so as to improve their relationship

**Comment by Urwumpe** [comment]
I tend more towards the alternative, since mars-sim is still an agent simulation and thus, a settlement would have no opinion. An abstract off-world sponsor could be tolerable as abstraction to make it easier to focus on the main actors.

But on Mars, I think it would be better to let the settlers have their opinions on other settlements based on their experiences with settlers from those settlements or their own experiences there.

For the relations between settlements, I think contracts between the settlement could be a good option to indicate how close their relation is. The simplest kind of contract could simply be a contract that grants settlers from each settlement a common right at the other settlement, like the right to stay at a settlement for a certain amount of time (like a visa). Others could specify how resources are shared, like laboratories, fuel, water, food, etc.

For implementing the decisions, that are behind such contracts, I would add a new attribute to a relation called "trust". The more a settler or a settlement/Sponsor/organisation is observed to be fullfilling its obligations towards a settler, the more the settler trusts this settler or organisation and the more he is willed to rely on them. This could include its home settlement as well: A settlement that can't satify the needs of a settler as expected, would loose trust, especially relative to others or less known settlements (The grass is always greener on the other side), resulting in the settler desiring to move to a different settlement. Or a settler could decide to work for a different sponsor (if allowed) or become corrupt and secretly work for another sponsor (Maybe with something like hidden/unknown contracts).

Trust would be different to sympathy. A reliable enemy would still be your enemy, but you would trust him to fullfill his obligations to you OR other settlers (including his allies). A settlement, that is still in its infancy and still struggling supporting its population could still be highly attractive to a settler, but he wouldn't expect them to deliver an essential good to him on time.

For making this more fun to read in the UI, maybe we could also replace some history records by a sorted list of three to seven key events, that shaped the relation experience of a Settler to something else, only keeping the events, that had most impact on the rating (positive or negative). Less significant events could be forgotten, keeping the amount of history data lower, while still having the option that a Settler might talk about his experiences with somebody else or a settlement.

**Comment by mokun** [comment]
> I tend more towards the alternative, since mars-sim is still an agent simulation and thus, a settlement would have no opinion. An abstract off-world sponsor could be tolerable as abstraction to make it easier to focus on the main actors.

True it's merely business between settlements. But I thought you prefer to have some more **drama** going on between settlements :D 

> But on Mars, I think it would be better to let the settlers have their opinions on other settlements 
 
Yes. realistically speaking, settlers can develop their own opinions toward a settlement based on whatever experiences they have accumulated. 

For sure, we could model it as a opinion score. 

> based on their experiences with settlers from those settlements or their own experiences there.

For any personal experiences, we'll need to codify how to represent it since it'll be more than a simple integer/double to be able to save in a log. 

And we'll need to fix the serialization first in order to be able to log more.

**Comment by mokun** [comment]
@Urwumpe 

> For implementing the decisions, that are behind such contracts, I would add a new attribute to a relation called "trust". The more a settler or a settlement/Sponsor/organisation is observed to be fullfilling its obligations towards a settler, the more the settler trusts this settler or organisation and the more he is willed to rely on them. 

I took the inspiration from what you said and create a *trust* score as one of the 3 pillars (respect, care and trust) or opinions of a settler toward another. Still need to put it into use though.

But going back to contractual relationship between settlement, we could definitely create a trust score like you suggested as a way to motivate a settlement to help one another. 

I suppose in future, this trust will be further developed into some kind of legal binding obligations.

So *high trust* will promote collaboration on projects and even joining/signing of a treaty of some sorts while *low trust* will bar any future cooperation.

@bevans2000 

I'd like to create a relationship score between settlements that would be compatible with your **RatingScore** because it will nicely show the break down of how this composite trust score is computed.

But it would entail keeping track of some of the past history (either cooperation or conflict) between two settlements and even between their sponsors. 

How would you approach it ?

**Comment by mokun** [comment]
@bevans2000 

> Why has the changed to a Unit? Can a Vehicle or a Building have Relationship now?

I can create an interface called `Commenter` and have Person implements it.

With this `Commenter` interface, we can finally have a person comment on a settlement. 
 
Also, I can think of interesting use cases on how a settlement would comment on a person as well.

**Comment by mokun** [comment]
@Urwumpe 

> For the relations between settlements, I think contracts between the settlement could be a good option to indicate how close their relation is. 

We have now allowed up to 3 scores or dimensions between two commentors. 

In terms of between any two settlements, how do you like to have the following 3 aspects of relationship in near future:  
1. Diplomatic
2. Economic
3. Sociocultural

**Comment by bevans2000** [comment]
I like the idea of using an interface, it is a  better design. Otherwise an Equipment could have an opinion of a  vehicle which does make sense.

**Comment by mokun** [comment]
@bevans2000,

Currently, there are holes in Relation class, namely, we have NPE from time to time with Research.

In AssistScientificStudyRsearcher's assistingPhase, 

```java
		// Add relationship modifier for opinion of assistant from the researcher.
		RelationshipUtil.changeOpinion(researchTask.getResearcher(), person, BASE_RELATIONSHIP_MODIFIER * time);
```

In RelationshipUtil,

```java
	/**
	 * Changes the opinion of person1 toward person2.
	 * 
	 * @param person1
	 * @param person2
	 * @param opinion
	 */
	public static void changeOpinion(Person person1, Person person2, double mod) {
		person1.getRelation().changeOpinion(person2, mod);
	}
```	


```
01-Bora-08:278.224 (Severe) UnitManager : Problem with pulse on Terminus: Cannot read field "d1" because "found" is null
java.lang.NullPointerException: Cannot read field "d1" because "found" is null
	at com.mars_sim.core.person.ai.social.Relation.changeOpinion(Relation.java:144)
	at com.mars_sim.core.person.ai.social.RelationshipUtil.changeOpinion(RelationshipUtil.java:93)
	at com.mars_sim.core.science.task.AssistScientificStudyResearcher.assistingPhase(AssistScientificStudyResearcher.java:290)
	at com.mars_sim.core.science.task.AssistScientificStudyResearcher.performMappedPhase(AssistScientificStudyResearcher.java:253)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:681)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:637)
	at com.mars_sim.core.person.ai.task.util.TaskManager.executeTask(TaskManager.java:495)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:198)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:176)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:730)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1113)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:924)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:905)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

01-Bora-08:278.224 (Info) MaintainBuilding : [Kyocera - Garage 1] Soshi Ueda - Maintenance on Laboratory 1
01-Bora-08:278.224 (Info) MaintainBuildingEVA [x2] : [Kyocera - Garage 1] Takumi Okada - EVA Maintenance on Syngas Plant 1
01-Bora-08:278.224 (Info) Vehicle : [Kyocera] Chi-Ri - New parking loc found (iteration: 3).
01-Bora-08:278.224 (Info) Vehicle : [New Seoul] Naro - New parking loc found (iteration: 13).
01-Bora-08:278.224 (Info) Vehicle : [Tian Cheng] Changtu - New parking loc found (iteration: 7).
01-Bora-08:279.466 (Severe) UnitManager : Problem with pulse on Terminus: Cannot read field "d1" because "found" is null
java.lang.NullPointerException: Cannot read field "d1" because "found" is null
	at com.mars_sim.core.person.ai.social.Relation.changeOpinion(Relation.java:144)
	at com.mars_sim.core.person.ai.social.RelationshipUtil.changeOpinion(RelationshipUtil.java:93)
	at com.mars_sim.core.science.task.AssistScientificStudyResearcher.assistingPhase(AssistScientificStudyResearcher.java:290)
	at com.mars_sim.core.science.task.AssistScientificStudyResearcher.performMappedPhase(AssistScientificStudyResearcher.java:253)
	at com.mars_sim.core.person.ai.task.util.Task.executeMappedPhase(Task.java:681)
	at com.mars_sim.core.person.ai.task.util.Task.performTask(Task.java:637)
	at com.mars_sim.core.person.ai.task.util.TaskManager.executeTask(TaskManager.java:495)
	at com.mars_sim.core.person.ai.Mind.takeAction(Mind.java:198)
	at com.mars_sim.core.person.ai.Mind.moderateTime(Mind.java:176)
	at com.mars_sim.core.person.ai.Mind.timePassing(Mind.java:110)
	at com.mars_sim.core.person.Person.timePassing(Person.java:730)
	at com.mars_sim.core.structure.Settlement.timePassingCitizens(Settlement.java:1113)
	at com.mars_sim.core.structure.Settlement.timePassing(Settlement.java:924)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:905)
	at com.mars_sim.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
``` 

We'll need to avoid opinionMap being null.

**Comment by bevans2000** [comment]
I can't understand the complexity of the Relationship. Why do we need a range of values per relationship? Why not go for a simplify single  rating

**Comment by bevans2000** [comment]
There should be no need for a different create and adjust relationship, a person just adjusts their opinion of people, either up or down

**Comment by mokun** [comment]
> Why do we need a range of values per relationship? Why not go for a simplify single rating
