### ISSUE TITLE
Template ID in settlement template Phase xxx is not unique

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#715]
**Describe the bug**
- When reloading from a saved sim, 1/4 of the time IllegalStateException came along. Interestingly, the simulation seems unaffected and be able to continue.

**Expected and unexpected behavior**
- Obviously, mars-sim should save the template ID and don't have to reassign everytime when reloading from a saved sim

**Java classes involved**
List out possible Java classes/methods that are behaving incorrectly.

**Screenshots**
- SettlementConfig, UserConfigurableConfig

**Stacktrace**
```
01-Coan-19:259.869 (Severe) PersonTaskManager : [Europa] Paraskevi Vlachos - Trouble calling performTask(): 
java.lang.IllegalStateException: Error in SettlementConfig.xml: template ID in settlement template Phase 2-EU is not unique.
	at org.mars_sim.msp.core.structure.SettlementConfig.parseItemXML(SettlementConfig.java:256)
	at org.mars_sim.msp.core.structure.SettlementConfig.parseItemXML(SettlementConfig.java:1)
	at org.mars_sim.msp.core.configuration.UserConfigurableConfig.loadItem(UserConfigurableConfig.java:166)
	at org.mars_sim.msp.core.configuration.UserConfigurableConfig.getItem(UserConfigurableConfig.java:182)
	at org.mars_sim.msp.core.structure.building.BuildingManager.getEVAAttachedBuilding(BuildingManager.java:2166)
	at org.mars_sim.msp.core.structure.building.BuildingManager.isObservatoryAttached(BuildingManager.java:2201)
	at org.mars_sim.msp.core.person.ai.task.ExitAirlock.<init>(ExitAirlock.java:125)
	at org.mars_sim.msp.core.person.ai.task.Walk.egressingAirlockPhase(Walk.java:770)
	at org.mars_sim.msp.core.person.ai.task.Walk.performMappedPhase(Walk.java:444)
	at org.mars_sim.msp.core.person.ai.task.util.Task.executeMappedPhase(Task.java:665)
	at org.mars_sim.msp.core.person.ai.task.util.Task.performTask(Task.java:616)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:85)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:208)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:180)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:856)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1130)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:1001)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:954)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:754)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
**Version:**
 - pre-3.4.0 build 7463
 
**Additional context**
- Even though this exception happens when  loading from a saved sim, it was triggered when a person is walking and exiting an airlock

**Comment by bevans2000** [comment]
The TemplateId is actually an old attribute that is not really used. I'll take care of this.

**Comment by bevans2000** [comment]
Looking into this bug has opened a can of worms in how the ```SettlementTemplate``` & ```BuildingTemplate``` are used. There are redundant properties for the ids that are only used by themselves.

**Comment by mokun** [comment]
So how important is this id ? Will it be better off to replace it with enum?
