### ISSUE TITLE
Settlers trying to drink water when on the marsSurface

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#716]
**Describe the bug**
Getting a class case exception because the Settlers are trying to get Water from the marsSurface but it is not a ```ResourceHolder```. 

**To Reproduce (Please provide steps)**
Leave the sim running and it appears after a while.
```
01-Adir-01:458.436 (Severe) PersonTaskManager [x10] : [0.0000 N 0.0000 W] Vasileios Panagiotopoulos - Trouble calling performTask(): 
java.lang.ClassCastException: class org.mars_sim.msp.core.environment.MarsSurface cannot be cast to class org.mars_sim.msp.core.equipment.ResourceHolder (org.mars_sim.msp.core.environment.MarsSurface and org.mars_sim.msp.core.equipment.ResourceHolder are in unnamed module of loader 'app')
        at org.mars_sim.msp.core.person.ai.task.EatDrink.calculateWater(EatDrink.java:1031)
        at org.mars_sim.msp.core.person.ai.task.EatDrink.drinkingWaterPhase(EatDrink.java:464)
        at org.mars_sim.msp.core.person.ai.task.EatDrink.performMappedPhase(EatDrink.java:437)
        at org.mars_sim.msp.core.person.ai.task.util.Task.executeMappedPhase(Task.java:661)
        at org.mars_sim.msp.core.person.ai.task.util.Task.performTask(Task.java:616)
        at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:85)
        at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:208)
        at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:180)
        at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
        at org.mars_sim.msp.core.person.Person.timePassing(Person.java:856)
        at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1130)
        at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:1001)
        at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:954)
        at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:754)
        at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Expected and unexpected behavior**
During an EVA it was previously not possible to execute the EatDrink task as this assumed the Settler was inside; hence the container would be a ResourceHolder. The EatDrink task should be restricted to inside.

**Comment by bevans2000** [comment]
I haven't seen this reoccur
