### ISSUE TITLE
ClassCastException with Bar Charts

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#722]
**Describe the bug**
- When clicking on the bar chart icon in Monitor Tool, it fails to create a bar char for *certain selected columns*.
- The exception messages of the EDT persists and becomes excessive even after closing the Monitor Tool. They dominate the stack trace. 

**To Reproduce (Please provide steps)**
1. Open Monitor Tool 
2. On the bottom of the Monitor Tool, click on the 2nd icon (looks like a Bar Chart) from the left 
3. Select the Mars tab (showing all settlements)
4. The ClassCastException exception is created

**Expected and unexpected behavior**
- It should open a brand new tab with a bar chart created for the selected category (or the selected column of data).

**Java classes involved**
- `BarChartTab`, `SettlementTableModel`

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/194920058-df329e4e-ec5e-4152-8e47-cb1ca44aa52e.png)

**Stacktrace**
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at org.mars_sim.msp.ui.swing.tool.monitor.BarChartTab$TableBarDataset.getValue(BarChartTab.java:217)
	at org.jfree.data.general.DatasetUtils.iterateToFindRangeBounds(DatasetUtils.java:1027)
	at org.jfree.data.general.DatasetUtils.findRangeBounds(DatasetUtils.java:741)
	at org.jfree.chart.renderer.category.AbstractCategoryItemRenderer.findRangeBounds(AbstractCategoryItemRenderer.java:684)
	at org.jfree.chart.renderer.category.BarRenderer.findRangeBounds(BarRenderer.java:798)
	at org.jfree.chart.renderer.category.AbstractCategoryItemRenderer.findRangeBounds(AbstractCategoryItemRenderer.java:658)
	at org.jfree.chart.plot.CategoryPlot.getDataRange(CategoryPlot.java:3961)
	at org.jfree.chart.axis.NumberAxis.autoAdjustRange(NumberAxis.java:366)
	at org.jfree.chart.axis.NumberAxis.configure(NumberAxis.java:348)
	at org.jfree.chart.plot.CategoryPlot.datasetChanged(CategoryPlot.java:2053)
	at org.jfree.data.general.AbstractDataset.notifyListeners(AbstractDataset.java:205)
	at org.jfree.data.general.AbstractDataset.fireDatasetChanged(AbstractDataset.java:188)
	at org.mars_sim.msp.ui.swing.tool.monitor.BarChartTab$TableBarDataset.tableChanged(BarChartTab.java:264)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:276)
	at org.mars_sim.msp.ui.swing.tool.monitor.SettlementTableModel$SettlementTableCellUpdater.run(SettlementTableModel.java:609)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7481 
 
**Additional context**
- In `SettlementTableModel `, certain data set has **formatted String** as output and cannot be cast into Number.
- The benefit of the formatted decimal is that a [decimal separator](https://en.wikipedia.org/wiki/Decimal_separator) (such as a comma "," for English locale) can be inserted for easy reading.

```
public class SettlementTableModel extends UnitTableModel {

	private static final DecimalFormat df = new DecimalFormat("#,###,##0");
	private static final DecimalFormat df3 = new DecimalFormat("#,###,##0.000");
...
	/**
	 * Return the value of a Cell
	 *
	 * @param rowIndex    Row index of the cell.
	 * @param columnIndex Column index of the cell.
	 */
	public Object getValueAt(int rowIndex, int columnIndex) {
		Object result = null;

		if (rowIndex < getUnitNumber()) {
			Settlement settle = (Settlement) getUnit(rowIndex);
			Map<Integer, Double> resourceMap = resourceCache.get(settle);

			try {
				switch (columnIndex) {
...
				case COMPUTING_UNIT: {
					double computing = settle.getBuildingManager().getAllComputingResources();
					result = df3.format(computing);
				}
					break;
					
				case POWER_GEN: {
					double power = settle.getPowerGrid().getGeneratedPower();
					if (power < 0D || Double.isNaN(power) || Double.isInfinite(power))
						result = 0;
					else
						result = df.format(power);
				}
					break;

				case POWER_LOAD: {
					double power = settle.getPowerGrid().getRequiredPower();
					if (power < 0D || Double.isNaN(power) || Double.isInfinite(power))
						result = 0;
					else
						result = df.format(power);
				}
					break;

```

**Comment by mokun** [comment]
Another bug is that once a bar chart tab is created, the Mars tab has invalid states for its set of icons at the bottom. 

![image](https://user-images.githubusercontent.com/1168584/194927782-3ce05148-c18a-4f82-b6fe-20b13cf69a7a.png)

**Comment by mokun** [comment]
@bevans2000 

Do you still see exceptions from bar charts ?

**Comment by bevans2000** [comment]
> @bevans2000
> 
> Do you still see exceptions from bar charts ?

Not recently so happy to close it.
