### ISSUE TITLE
How to cache food and water resource stored in a ResourceHolder ?

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#736]
**Describe the bug**
- In order to avoid ConcurrentModificationException in high speed setting, what is the best strategy in caching food and water resource stored in a ResourceHolder ?

**Expected and unexpected behavior**
- Rather than having to look for `EquipmentInventory.java::getAmountResourceStored` each time and call up a chain of methods, can we cache a small amount of food (say 0.5 kg) and water (say 0.5 kg) on a ResourceHolder such as (a person, a settlement or a vehicle) ? 
- If it reaches zero amount, then the ResourceHolder will automatically replenish this cache back to 0.5 kg.

**Discuss any potential problems you have and have not ruled out**
- We want to avoid having to call in each frame of a person to see if foodAmount and waterAmount is greater than zero in EatDrinkMeta.

**Java classes involved**
- `ResourceHolder`, `EquipementInventory`, `EatDrinkMeta`
 
**Screenshots**
```
If applicable, add screenshots to help explain your problem.

**Stacktrace**
01-Adir-10:137.175 (Severe) UnitManager$SettlementTask : Problem with pulse on Schiaparelli Point: null
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1534)
	at org.mars_sim.msp.core.equipment.EquipmentInventory.getAmountResourceStored(EquipmentInventory.java:387)
	at org.mars_sim.msp.core.structure.Settlement.getAmountResourceStored(Settlement.java:3941)
	at org.mars_sim.msp.core.structure.building.Building.getAmountResourceStored(Building.java:1357)
	at org.mars_sim.msp.core.person.ai.task.meta.EatDrinkMeta.getProbability(EatDrinkMeta.java:71)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:160)
	at org.mars_sim.msp.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:509)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.startNewTask(PersonTaskManager.java:242)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:310)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:253)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:180)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:856)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1130)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:1001)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:954)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:768)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:748)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

01-Adir-10:137.175 (Info) EatDrink [x14] : [Starcity] Adele Landry - Drinking Soymilk.
01-Adir-10:137.175 (Info) EatDrink [x27] : [Starcity] Matthew Lee - Drinking Soymilk.
01-Adir-10:141.888 (Info) DriveGroundVehicle : [22.1293 N 82.9417 W - Reth] Parth Soni - Took the wheel of the rover.
01-Adir-10:141.888 (Info) OperateVehicle [x11] : [22.1293 N 82.9417 W] Reth - Case 3: Driving toward 22.2741 N 82.9920 W - 9.009 km away.
01-Adir-10:141.888 (Warning) Unit : Daniel Byrne expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Rik Declercq expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Aksel Johansen expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Poppy Robertson expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Emma De Boer expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Anna Farkas expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Pyotr Artsebarsky expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Leonardo DaVinci expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Yash Roy expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Martim Rodrigues expected pulse #1984 but received 1985
01-Adir-10:141.888 (Info) BotTaskManager : [Tian Cheng] MakerBot 003 - Forcing to be recharged due to low power.
01-Adir-10:141.888 (Warning) Unit : Zuzanna Kowalczyk expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Talgat Gargarin expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Pol López expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Lena LaGranda expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Emrick Li expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Alexander Hofer expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Alice Nieminen expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Oskar Koppel expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Fynn Zimmermann expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Sojourner II expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Solitude expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Drone 018 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Drone 020 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : LUV 019 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Sand Dancer expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Ridge Runner expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Wind Runner expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Dust Storm expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Drone 019 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : LUV 018 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : LUV 020 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : Windstorm expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : DeliveryBot 006 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : GardenBot 012 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : GardenBot 013 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : RepairBot 012 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : MakerBot 014 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : DeliveryBot 007 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : ChefBot 012 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : MedicBot 004 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : RepairBot 011 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : MakerBot 013 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : ConstructionBot 002 expected pulse #1984 but received 1985
01-Adir-10:141.888 (Warning) Unit : ChefBot 011 expected pulse #1984 but received 1985
01-Adir-10:149.686 (Info) OperateVehicle [x10] : [22.2720 N 82.9912 W] Reth - Case 1: Arriving near 22.2741 N 82.9920 W - 0.13 km away.
01-Adir-10:149.686 (Info) OperateVehicle : [22.2735 N 82.9917 W] Reth - Reducing speed from 17.5 kph  to 4.861 kph. Deceleration: -0.415 m/s2. Force: -9.145 N.

```
**Version**
 - pre-3.4.0 build 7559

**Additional context**
- May be this caching scheme can be applied elsewhere to avoid excessive calling of getAmountResourceStored() which results in  ConcurrentModificationException

**Comment by bevans2000** [comment]
I have some concerns about introducing caching as this is going back to the nightmare of the old ```Inventory``` object.
This error above suggest another Thread was modifying the ResourceHolder's contents as the main settlement thread is the one that gets the error. And that Thread should be the owner of this Resource Holder.
Was there a delivery or trade Mission activity? These Missions do take part on cross Settlement activities but the unloading/loading should be driven by the Settlement side; not the Vehicle/Person. 
It's important to have clear lines of control over shared entities.
I think the big question here is when looking for a Resource in a Settlement why are we going to scan the Equipment? Resources assigned to Equipment belong to the Equipment; we unload Equipment of any unneeded resource back to the Settlement.

**Comment by mokun** [comment]
> This error above suggest another Thread was modifying the ResourceHolder's contents as the main settlement thread is the one that gets the error.

Is there a way to know which thread is modifying the content of this person's content ?

> Was there a delivery or trade Mission activity?

I don't recall this person having a mission.

This person is simply calling EatDrinkMeta in order to decide which task to take.

**Comment by bevans2000** [comment]
This person is not doing the modification as it is in the Settlement thread. There will be something else going on.
I feel we should stop search g the contained Equipment, that wasn't in the original reworking.

**Comment by mokun** [comment]
Q: should we allow a person to hand carry food and water ?

This way, he/she doesn't always have to run to a lounge to eat/drink. 

It also helps out when a person is in a vehicle. Before departure, he will then be  eating the food he's hand carrying, not consuming the food stored in the vehicle.

**Comment by mokun** [comment]
btw, I'll need to fix the display of amount resources in InventoryTabPanel.

**Comment by mokun** [comment]
After the last fix, Amount Resources are now showing up in Inventory Tab. See below :

![image](https://github.com/mars-sim/mars-sim/assets/1168584/60ca5fe0-ae5a-495f-b37f-acff92a3e737)
