### ISSUE TITLE
NPE on Swing UI thread when reading the resource content within a person

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#738]
**Describe the bug**
- Why would swing UI thread causing null instances when reading the resource content within a person ?
- Is a person's resource content counted toward the sum owned by the settlement ? 

**To Reproduce (Please provide steps)**
1. Open Monitor Tool upon starting the default scenario
2. Wait until it gets to about sol 1:114
3. See NPE triggered by `SettlementTableModel`

**Expected and unexpected behavior**
- The UI thread cannot handle changes, especially when at high speed (> 512x)

**Java classes involved**
- `SettlementTableModel`, `EntityTableModel`

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/198816145-c44a10e2-e117-4986-8c62-ec70901ff679.png)

**Stacktrace**
```
01-Adir-01:111.183 (Info) MaintainBuilding [x2] : [New Boston] RepairBot 010 - Maintaining Inflatable Greenhouse 1.
01-Adir-01:114.267 (Info) MaintainBuilding [x2] : [Starcity] RepairBot 007 - Maintaining Residential Quarters 1.
01-Adir-01:114.995 (Config) SettlementBuilder : Creating 'Port Ares' based on template 'Phase 2-MS'...
01-Adir-01:114.995 (Warning) SettlementTransparentPanel : [System] SettlementTransparentPanel : Sun data at 20.0000 N 50.0000 W is not available.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mars_sim.msp.core.person.Person.getAmountResourceStored(Person.java:1935)
	at org.mars_sim.msp.core.structure.Settlement.getAllAmountResourceOwned(Settlement.java:3953)
	at org.mars_sim.msp.ui.swing.tool.monitor.SettlementTableModel.getEntityValue(SettlementTableModel.java:286)
	at org.mars_sim.msp.ui.swing.tool.monitor.SettlementTableModel.getEntityValue(SettlementTableModel.java:1)
	at org.mars_sim.msp.ui.swing.tool.monitor.EntityTableModel.getValueAt(EntityTableModel.java:266)
	at org.mars_sim.msp.ui.swing.tool.monitor.TableSorter.getValueAt(TableSorter.java:203)
	at java.desktop/javax.swing.JTable.getValueAt(JTable.java:2706)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5724)
	at com.alee.laf.table.TablePainter.paintCell(TablePainter.java:740)
	at com.alee.laf.table.TablePainter.paintContent(TablePainter.java:655)
	at com.alee.laf.table.TablePainter.paintContent(TablePainter.java:402)
	at com.alee.laf.table.TablePainter.paintContent(TablePainter.java:38)
	at com.alee.painter.decoration.AbstractDecorationPainter.paint(AbstractDecorationPainter.java:1363)
	at com.alee.painter.PainterSupport.paint(PainterSupport.java:557)
	at com.alee.laf.table.WebTableUI.paint(WebTableUI.java:174)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayer.paint(JLayer.java:475)
	at java.desktop/javax.swing.plaf.LayerUI.paint(LayerUI.java:80)
	at org.mars_sim.msp.ui.swing.tool.WaitLayerUIPanel.paint(WaitLayerUIPanel.java:44)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JLayer.paint(JLayer.java:470)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.JLayer.paintImmediately(JLayer.java:430)
	at java.desktop/javax.swing.plaf.LayerUI.paintImmediately(LayerUI.java:723)
	at java.desktop/javax.swing.JLayer.paintImmediately(JLayer.java:425)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:4994)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
01-Adir-01:114.995 (Config) UnitManager : Setting up settlement task thread for Port Ares.
01-Adir-01:114.995 (Info) TransportManager : A transport item arrived at Port Ares: 01-Adir-01
01-Adir-01:115.142 (Info) BotTaskManager : [Port Ares] DeliveryBot 005 - Forcing to be recharged due to low power.
01-Adir-01:115.142 (Info) Charge : [Port Ares] DeliveryBot 005 - canWalk: false.
01-Adir-01:115.142 (Info) ToggleResourceProcess : [New Boston] ERV-B 3 - Liam Pedersen: Attempting to toggle on 'Produce Ethylene'.
01-Adir-01:115.352 (Info) Read : [Port Ares] Julien Leclerc - Started reading on prospecting.
01-Adir-01:115.352 (Severe) WalkingSteps : [Port Ares] DeliveryBot 005 - initialWalkState : null
01-Adir-01:115.352 (Info) Charge : [Port Ares] DeliveryBot 005 - Walking to null.
```

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7563
 
**Additional context**
- eqmInventory is null in `Person::getAmountResourceStored`
```
	/**
	 * Gets the amount resource stored.
	 *
	 * @param resource
	 * @return quantity
	 */
	@Override
	public double getAmountResourceStored(int resource) {
		return eqmInventory.getAmountResourceStored(resource);
	}
```

**Comment by bevans2000** [comment]
Could be a person has died and they don't have a EquipmentInventory. But again it's the same question as #736. Should we really be counting resources that belong to a Person? I think the Settlement table should show what Resource the Settlement directly owns; not the sub units.

**Comment by mokun** [comment]
If I changed the TR to 2048x and above, I get more ConcurrentModificationException at getAmountResourceStored() when tending Crop, Cooking, and a few other seemingly normal activities. Why these race conditions?

Should we cache some small amount for each building?

**Comment by bevans2000** [comment]
The getAmountResourceStored method is traversing the contained Equipment to get a full deep count. If an Equipment is claimed and removed it will create a concurrency error. I think I mentioned above that we shouldn't be going into contained Equipment to get the resources for a Settlement. Equipment unload their contents anyway when going back to a Settlement so the checking is redundant anyway.
Change the method to stop scanning the Equipment and see if that helps.

**Comment by bevans2000** [comment]
No
