### ISSUE TITLE
Garage and Vehicle NPE issue when loading a vehicle using createTask()

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#750]
**Describe the bug**
- It seems that vehicle becomes null, thus causing NPE when checking if it's in a garage or not.

**Discuss any potential problems you have and have not ruled out**
- Vehicle is null at L1263 in BuildingManager's isInGarage() as follows: 

```
	/**
	 * Checks if the vehicle is currently in a garage or not.
	 *
	 * @return true if vehicle is in a garage.
	 */
	public boolean isInGarage(Vehicle vehicle) {
		if (settlement != null) {
			for (Building garageBuilding : getGarages()) {
				VehicleMaintenance garage = garageBuilding.getVehicleMaintenance();
				if (garage == null) {
					return false;
				}
				
				if (vehicle.getVehicleType() == VehicleType.DELIVERY_DRONE) {
					if (garage.containsFlyer((Flyer)vehicle)) {
						return true;
					}
				}
				else if (garage.containsVehicle(vehicle)) {
					return true;
				}
			}
		}
		return false;
	}
```

**Solution**
- We need to figure a way to prevent NPE defensively
 
**Java classes involved**
- BuildingManager, LoadVehicleEVA, LoadVehicleMeta.

**Stacktrace**
```
01-Adir-04:094.161 (Warning) ResourceProcess [x19] : [Kyocera] Case A. Used up all 'Carbon' input to start 'Produce Styrene'. Required: 14.274 kg. Remaining: 5.974 kg in storage.
01-Adir-04:094.161 (Info) EatDrink [x79] : [Schiaparelli Point] Ray Bradbury - Eating Granola Bar.
01-Adir-04:094.161 (Info) Fishery [x2] : [Schiaparelli Point] Large Greenhouse 1 - Weeds fully tended for 54.0 millisols.
01-Adir-04:094.161 (Info) TaskManager : [Schiaparelli Point] Yuki Endo - Given a new task order of 'EVA Load Regolith Prospecting #30'.
01-Adir-04:094.161 (Severe) UnitManager$SettlementTask : Problem with pulse on Schiaparelli Point: null
java.lang.NullPointerException
	at org.mars_sim.msp.core.structure.building.BuildingManager.isInGarage(BuildingManager.java:1263)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleEVA.<init>(LoadVehicleEVA.java:79)
	at org.mars_sim.msp.core.person.ai.task.meta.LoadVehicleMeta$EVALoadJob.createTask(LoadVehicleMeta.java:69)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.startNewTask(PersonTaskManager.java:217)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:310)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:253)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:180)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:856)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1104)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:987)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:940)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:770)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
**Version**
 - pre-3.4.0 build 7615

**Additional context**
- See similar NPE issue in previous commit at https://github.com/mars-sim/mars-sim/commit/d329b249d8086ea24eb38dcd2f7c5815a90f73a2

**Comment by bevans2000** [comment]
I know what the problem is. The Mission gets completed and hence there is no Vehicle attached.

**Comment by bevans2000** [comment]
Is this happening often ?

**Comment by bevans2000** [comment]
Already handled in f91a2f2ac2e3e273a11409445fbe541a45bb1499

**Comment by mokun** [comment]
@bevans2000 

```
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/mars-sim/mars-sim/pull/751/conflicts) or the  to resolve conflicts.
Conflicting files
mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/task/LoadVehicleEVA.java

```

I didn't pay attention to your pull request. Not knowing that you already revised `LoadVehicleEVA` to check if vehicle is null.

It won't let me merge now.

Do you mind revising it now so that we can merge ?

**Comment by bevans2000** [comment]
It's done
