### ISSUE TITLE
NPE in rebuilding task cache in BotTaskManager

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#757]
**Describe the bug**
- A NPE shows up when calling rebuildTaskCache() in BotTaskManager. 
- the list `potentials` in L186 is NPE

**To Reproduce (Please provide steps)**
- Start a new sim in the default scenario

**Java classes involved**
BotTaskManager, BotTaskManager,TaskCache

**Stacktrace**
```
2022-11-17T14:47:21.8 (Config) MarsProject : Starting Mars Simulation Project 3.4.0 - Build 923e018-dirty - 64-bit Java 11.0.17 - 8 CPU threads
2022-11-17T14:47:21.8 (Config) MarsProject : List of input args : [-new, -sandbox, -noaudio]
2022-11-17T14:47:22.0 (Config) SimulationConfig : The xml folder already existed.
2022-11-17T14:47:22.0 (Config) SimulationConfig : The version.txt is invalid.
2022-11-17T14:47:22.0 (Config) SimulationConfig : Case B2 : The backup folder C:\Users\mkhelios\.mars-sim\backup already exists. Back up to C:\Users\mkhelios\.mars-sim\backup\unknown\20221117T144722
2022-11-17T14:47:22.8 (Config) SimulationConfig : Done loading all xml config files.
2022-11-17T14:47:22.8 (Config) SimulationBuilder : ---------------------------------------------------
2022-11-17T14:47:22.8 (Config) SimulationBuilder :     Java Version Full String = 11.0.17+7-LTS
2022-11-17T14:47:22.8 (Config) SimulationBuilder : Java Version Feature Element = 11
2022-11-17T14:47:22.8 (Config) SimulationBuilder : Java Version Interim Element = 0
2022-11-17T14:47:22.8 (Config) SimulationBuilder :   Java Patch Element Version = 0
2022-11-17T14:47:22.8 (Config) SimulationBuilder :  Java Update Element Version = 17
2022-11-17T14:47:22.8 (Config) SimulationBuilder :           Java Version Build = 7
2022-11-17T14:47:22.8 (Config) SimulationBuilder :   Java additional build Info = LTS
2022-11-17T14:47:22.8 (Config) SimulationBuilder :        Java Pre-Release Info = NA
2022-11-17T14:47:22.8 (Config) Simulation : Initiating the simulation core engine...
2022-11-17T14:47:22.8 (Config) MasterClock : -----------------------------------------------------
2022-11-17T14:47:22.8 (Config) MasterClock :                  Base time-ratio : 128x
2022-11-17T14:47:22.8 (Config) MasterClock :           Min millisol per pulse : 0.0112644016
2022-11-17T14:47:22.8 (Config) MasterClock :       Optimal millisol per pulse : 0.169494645325
2022-11-17T14:47:22.8 (Config) MasterClock :           Max millisol per pulse : 10.138
2022-11-17T14:47:22.8 (Config) MasterClock :  Max elapsed time between pulses : 1000 ms
2022-11-17T14:47:22.8 (Config) MasterClock : -----------------------------------------------------
01-Adir-01:000.000 (Config) EVAOperation : Minimum sunlight for EVA = 7.0
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'scenario Default'.
01-Adir-01:000.000 (Config) SettlementBuilder : Default scenario loading...
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 2-US'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'New Plymouth' based on template 'Phase 2-US'...
01-Adir-01:000.000 (Info) Settlement : [New Plymouth] Settlement vicinity mineral concentration: {Sylvite=38.572790770115304, Kamacite=14.231735890278978, Goethite=1.3054345593074954}
01-Adir-01:000.000 (Config) EVASuit :  -----------------------------------------------------------------------
01-Adir-01:000.000 (Config) EVASuit :  Suit's Unloaded Weight : 14.05 kg
01-Adir-01:000.000 (Config) EVASuit :   Total Gas Tank Volume : 3.9L
01-Adir-01:000.000 (Config) EVASuit :            Full Tank O2 : 66.62 kPa -> 1.0  kg - Maximum Tank Pressure
01-Adir-01:000.000 (Config) EVASuit :              Nomimal O2 : 17.0  kPa -> 0.26 kg - Suit Target Pressure
01-Adir-01:000.000 (Config) EVASuit :              Minimum O2 : 11.94 kPa -> 0.18 kg - Safety Limit
01-Adir-01:000.000 (Config) EVASuit :  -----------------------------------------------------------------------
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 2-EU'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'Europa' based on template 'Phase 2-EU'...
01-Adir-01:000.000 (Info) Settlement : [Europa] Settlement vicinity mineral concentration: {Magnetite=1.4614781261757748, Chalcopyrite=22.85085865114119}
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 2-CN'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'Tian Cheng' based on template 'Phase 2-CN'...
01-Adir-01:000.000 (Info) Settlement : [Tian Cheng] Settlement vicinity mineral concentration: {Sylvite=51.49197135671021, Malachite=42.46944780715881}
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 2-IN'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'New Pompeii' based on template 'Phase 2-IN'...
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 2-JP'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'Kyocera' based on template 'Phase 2-JP'...
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 2-KR'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'New Seoul' based on template 'Phase 2-KR'...
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 3-SX'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'Starcity' based on template 'Phase 3-SX'...
01-Adir-01:000.000 (Info) Settlement : [Starcity] Settlement vicinity mineral concentration: {Sylvite=30.91181507657413, Goethite=100.0}
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 3-RU'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'Zvezda' based on template 'Phase 3-RU'...
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 3-MS'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'New Boston' based on template 'Phase 3-MS'...
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Alpha Base'.
01-Adir-01:000.000 (Config) SettlementBuilder : Creating 'Schiaparelli Point' based on template 'Alpha Base'...
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'crew Alpha'.
01-Adir-01:000.000 (Config) SettlementBuilder : Karen Andersen from crew 'Alpha' assigned to Schiaparelli Point.
01-Adir-01:000.000 (Config) SettlementBuilder : Rik Declercq from crew 'Alpha' assigned to Schiaparelli Point.
01-Adir-01:000.000 (Config) SettlementBuilder : Leonardo DaVinci from crew 'Alpha' assigned to Schiaparelli Point.
01-Adir-01:000.000 (Config) SettlementBuilder : Lena LaGranda from crew 'Alpha' assigned to Schiaparelli Point.
01-Adir-01:000.000 (Config) SettlementBuilder : Ray Bradbury from crew 'Alpha' assigned to Schiaparelli Point.
01-Adir-01:000.000 (Config) UserConfigurableConfig : Loading a template on demand: 'settlement Phase 2-MS'.
01-Adir-01:000.000 (Config) TransportManager : Scheduling a new settlement called 'Port Ares' to arrive at Sol 01-Adir-01:521
01-Adir-01:000.000 (Config) Simulation : Adding autosave handled for every 900000ms (15.0 mins).
01-Adir-01:000.000 (Config) MasterClock : Setting up 1 thread(s) for clock listener.
01-Adir-01:000.000 (Config) MasterClock : Setting up 1 thread(s) for clock executor.
01-Adir-01:000.000 (Config) Simulation :  - - - - - - - - - - - - - - Sol 1 (Cont') - - - - - - - - - - - - - - 
01-Adir-01:000.000 (Config) MasterClock : [System] MasterClock : Pulse width 0.0 increased to a minimum of 0.0112644016.
01-Adir-01:000.019 (Config) UnitManager : Setting up 5 thread(s) for running the settlement update.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for New Boston.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for New Pompeii.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for Tian Cheng.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for Europa.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for New Plymouth.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for New Seoul.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for Schiaparelli Point.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for Starcity.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for Zvezda.
01-Adir-01:000.019 (Config) UnitManager : Setting up settlement task thread for Kyocera.
01-Adir-01:000.019 (Info) BotTaskManager : [New Plymouth] MakerBot 001 - Forcing to be recharged due to low power.
01-Adir-01:000.019 (Severe) UnitManager$SettlementTask : Problem with pulse on New Plymouth: null
java.lang.NullPointerException
	at org.mars_sim.msp.core.robot.ai.task.BotTaskManager.rebuildTaskCache(BotTaskManager.java:186)
	at org.mars_sim.msp.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:502)
	at org.mars_sim.msp.core.robot.ai.task.BotTaskManager.startNewTask(BotTaskManager.java:230)
	at org.mars_sim.msp.core.robot.ai.BotMind.lookForATask(BotMind.java:197)
	at org.mars_sim.msp.core.robot.ai.BotMind.takeAction(BotMind.java:167)
	at org.mars_sim.msp.core.robot.ai.BotMind.decideTask(BotMind.java:116)
	at org.mars_sim.msp.core.robot.ai.BotMind.timePassing(BotMind.java:95)
	at org.mars_sim.msp.core.robot.Robot.timePassing(Robot.java:392)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1104)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:993)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:940)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:770)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

01-Adir-01:000.019 (Info) BotTaskManager : [New Seoul] GardenBot 006 - Forcing to be recharged due to low power.
01-Adir-01:000.019 (Info) BotTaskManager : [Kyocera] RepairBot 005 - Forcing to be recharged due to low power.
01-Adir-01:000.019 (Info) BotTaskManager : [New Boston] RepairBot 009 - Forcing to be recharged due to low power.
01-Adir-01:000.019 (Info) ToggleFuelPowerSource : [Tian Cheng] Guanyin Han - Turning on Fuel Power Source in Laboratory 1.
01-Adir-01:000.019 (Info) BotTaskManager : [Zvezda] MedicBot 002 - Forcing to be recharged due to low power.
01-Adir-01:000.019 (Info) BotTaskManager : [Starcity] MedicBot 001 - Forcing to be recharged due to low power.
01-Adir-01:000.019 (Info) BotTaskManager : [Starcity] ConstructionBot 001 - Forcing to be recharged due to low power.
01-Adir-01:000.019 (Info) BotTaskManager : [Schiaparelli Point] GardenBot 012 - Forcing to be recharged due to low power.
01-Adir-01:000.019 (Info) BotTaskManager : [Schiaparelli Point] DeliveryBot 006 - Forcing to be recharged due to low power.
01-Adir-01:004.214 (Info) ToggleFuelPowerSource : [New Pompeii] Ryan Patel - Turning on Fuel Power Source in Laboratory 1.
01-Adir-01:004.214 (Info) Crop : [New Plymouth - Inflatable Greenhouse 2] Soybean - Now in GERMINATION.
01-Adir-01:004.214 (Info) Crop : [Europa - Inflatable Greenhouse 1] Corn - Now in GERMINATION.
01-Adir-01:004.214 (Info) ToggleFuelPowerSource : [New Boston] Eevi Laine - Turning on Fuel Power Source in Lander Hab 2.
01-Adir-01:004.214 (Warning) Unit : GardenBot 001 expected pulse #1 but received 2
01-Adir-01:004.214 (Info) BotTaskManager : [New Plymouth] GardenBot 001 - Forcing to be recharged due to low power.
01-Adir-01:004.214 (Warning) Unit : ChefBot 001 expected pulse #1 but received 2

```

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7635 

**Additional context**
- This NPE doesn't happen each time but shows up about 20% of the time when starting a new sim.

**Comment by bevans2000** [comment]
Strange I haven't seen this at all. Your simulation is probably running with multiple unit threads so I wonder if the creation of the shared TaskCache is failing due to multiple threads. I'll take a look
