### ISSUE TITLE
Some SettlementTasks on the backlog are generating high scores

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#769]
**Describe the bug**
Tend greenhouse and toggle process are generating very high scores in the Task backlog. These are biasing the chance of other Tasks being selected.

**To Reproduce (Please provide steps)**
Run the simulation and observe the Task Tab in the Monitor Tool with a Settlement containing Greenhouses.

**Expected and unexpected behavior**
.A single Settlement task should be created for each Greenhouse. The demand attribute should be set to reflect how many farmers are needed. The score should be a biased count of the number of crops needing tending. Crops nearer harvesting will have a higher score.

**Comment by bevans2000** [comment]
GardenBots are helping it's just there are a lot of Crops and the Greenhouses always need help.

RepairBots got dropped from Toggle Resource process; I'll fix that.

**Comment by mokun** [comment]
How about we set up a "tier 2" response when a period of time has elapsed and certain tasks are not done ?

Say the reaource division will be in charge of sending their personnel and/or recruiting others during the off work shift hours to tend those needy crops.

> RepairBots got dropped from Toggle Resource process; I'll fix that.

That's great !

**Comment by bevans2000** [comment]
At the moment it's not that sophisticated. The Backlog is actually recalculated on demand from a Worker's request, so there is currently no concept of how long a SettlementTask has been on the list. We could do this but it would require a bit more work and I'm not sure how at the moment.

However IF we can balance the scores better it is possible that we could give high scoring tasks to OffDuty staff as well. That wouldn't be difficult to do; it could be done centrally in the SettlementTaskManager when it creates the personalized list. A score threshold would be set depending on On/Off Duty. At the moment we do have a slight problem that repairs are not offered to OffDuty staff. This is easy to resolve by comparing the WorkScope against the duty state.

**Comment by mokun** [comment]
I'm getting IndexOutOfBoundsException recently. 

```
01-Adir-01:026.765 (Severe) UnitManager$SettlementTask : Problem with pulse on Teslapolis : Invalid range
java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.rowsInserted(DefaultRowSorter.java:875)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4332)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4180)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:237)
	at org.mars_sim.msp.ui.swing.tool.monitor.EntityTableModel.resetEntities(EntityTableModel.java:102)
	at org.mars_sim.msp.ui.swing.tool.monitor.BacklogTableModel.resetTasks(BacklogTableModel.java:161)
	at org.mars_sim.msp.ui.swing.tool.monitor.BacklogTableModel.unitUpdate(BacklogTableModel.java:79)
	at org.mars_sim.msp.core.Unit.fireUnitUpdate(Unit.java:615)
	at org.mars_sim.msp.core.Unit.fireUnitUpdate(Unit.java:599)
	at org.mars_sim.msp.core.person.ai.task.util.SettlementTaskManager.getTasks(SettlementTaskManager.java:106)
	at org.mars_sim.msp.core.person.ai.task.util.SettlementTaskManager.getTasks(SettlementTaskManager.java:152)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:160)
	at org.mars_sim.msp.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:499)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.startNewTask(PersonTaskManager.java:249)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:306)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:249)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:182)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:119)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:835)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1079)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:916)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:750)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by bevans2000** [comment]
Where you viewing the backlog items in the monitor tool at the table and where they sorted?

**Comment by mokun** [comment]
> Where you viewing the backlog items in the monitor tool at the table and where they sorted?

Yes. this happens sometimes when I first create a brand new 4-persn settlement.

It loads up a monitor tool and switch to the backlog task tab automatically. 

I suppose I was previously at that tab in the last sim session when I saved the previous sim.

**Comment by bevans2000** [comment]
I think this is an issue with the table model being updated by the clock thread when the Table is being created. Although I don't know why the ```EntityTableModel.resetEntities``` method is calling an insert event. I will have a look later. Can certainly limit the blast radius of the error.

**Comment by mokun** [comment]
> a change to stop the listeners break the clock pulse thread with uncaught exception.

Sure. at least it's now caught and won't be a surprise anymore

**Comment by mokun** [comment]
@bevans2000 

How come it's too easy for a list of these toggling resource tasks to become 1000 ? 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/a37f0f6d-c406-45fa-95a1-d1089f77e32c)

**Comment by bevans2000** [comment]
It's because the associate MetaTask has a wrong calculation on the probability. The resource processes are based on the GoodValue of the outputs I think
