### ISSUE TITLE
NPE when opening Nav tab in Mission Tool

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#822]
**Describe the bug**
- NPE in Swing UI thread when opening Nav tab in Mission Tool.
- Line 421 has to do with adding mission listener to a mission.  

**Expected and unexpected behavior**

**Discuss any potential problems you have and have not ruled out**
- Somehow newMission is still Null.

**Java classes involved**
NavpintPanel, MissionWIndow

**Stacktrace**
```
01-Adir-01:177.379 (Warning) Msg : !!0.00 km/h??
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mars_sim.msp.ui.swing.tool.mission.NavpointPanel.setMission(NavpointPanel.java:421)
	at org.mars_sim.msp.ui.swing.tool.mission.MissionWindow.selectMission(MissionWindow.java:249)
	at org.mars_sim.msp.ui.swing.tool.mission.MissionWindow$2.valueChanged(MissionWindow.java:123)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191)
	at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1656)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2736)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4016)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3955)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$MouseHandler.mousePressed(BasicTreeUI.java:3208)
	at com.formdev.flatlaf.ui.FlatTreeUI$1.mousePressed(FlatTreeUI.java:247)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Note that NavpointPanel's setMission() is the culprit as follows :

```
	/**
	 * Sets the mission object.
	 * 
	 * @param newMission
	 */
	public void setMission(Mission newMission) {
		boolean isDiff = missionCache != newMission;
				
		if (isDiff) {
			// Remove this as previous mission listener.
			if (missionCache != null) {
				missionCache.removeMissionListener(this);
			}
			// Update the cache
			missionCache = newMission;
			// Add this as listener for new mission.
			missionCache.addMissionListener(this);
			// Update the mission content on the Nav tab
			updateNavTab();
		}
	}
```

**Comment by mokun** [comment]
@bevans2000 

It looks like this bug came from how setMission() is called. 

Good to see that the new code in calling setSettlement() and setMission() is now a lot more cleaner than in the past when it has to track the state of settlement and mission on both top left and bottom left panels in Mission Tool.

It's just a matter of fixing little things.

**Comment by bevans2000** [comment]
> @bevans2000
> 
> It looks like this bug came from how setMission() is called.
> 
> Good to see that the new code in calling setSettlement() and setMission() is now a lot more cleaner than in the past when it has to track the state of settlement and mission on both top left and bottom left panels in Mission Tool.
> 
> It's just a matter of fixing little things.

Odd, didn't see this myself. It's probably the missionCache is null.

**Comment by bevans2000** [comment]
Found it. If you select a settlement in the Tree; then no Mission is selected and hence newMission is null which is correct. I'll fix it now

**Comment by bevans2000** [comment]
@mokun But do you like it using a Tree control instead of the double list? Much cleaner in the code and easier to understand

**Comment by mokun** [comment]
> do you like it using a Tree control instead of the double list? 

Yes I like the tree structure 😃. Much more elegant 👏

I notice currently in Resupply Tool, each row on the top and bottom left panel represents a mission for a settlement. This can get disorganized and bad if player wants to keep track of which settlement has which mission.

Can we use the same tree structure  for both the past and fire missions ?

**Comment by bevans2000** [comment]
Yes we can do that. How would you see the structure? Settlements as the first level like Mission Tool. Then the supply missions under there? Maybe decorate with an icon to distinguish pending/completed supply missions?

**Comment by mokun** [comment]
> Settlements as the first level like Mission Tool.

Yes. The word "Settlements" as the first level is good. I suppose later we can even add "Mining Towns", "Outposts", "Weather Stations", "Monitoring Stations", etc. 

But for now, I suppose we are treating "Mining Towns" and "Outposts" as settlements. 

The super class "Structure" is already there. 

What do you see as the near future possible use case for a subclass under "Structure" ?

**Comment by bevans2000** [comment]
> btw, sometimes I notice the use of "Min..." as the name.
> 
> Is it because it's still under review and the name/unique id of the mission is not being formalized 

No idea but it looks good 😀
