### ISSUE TITLE
unable to save and simulation halt

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#831]
**Describe the bug**
- When clicking on the save button in the menu, the simulation unexpectedly halt at 01-Adir-02:533.
- The main window cannot respond and the simulation cannot even be quit. 

**Expected and unexpected behavior**
- If there's an issue in saving the simulation, it should just abort it and not halt the simulation, leaving things in limbo

**Discuss any potential problems you have and have not ruled out**
- It could have a caught exception that's not being reported in the stacktrace.

**Java classes involved**
- Simulation

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/228965019-63848a14-d0de-4805-812e-934d389562b2.png)

**Stacktrace**
```
01-Adir-02:525.630 (Info) ExitAirlock [x90] : [Tian Cheng - EVA Airlock 1] Chung Xu - Not fit enough to request egress. Current task: Performing EVA Egress.
01-Adir-02:525.777 (Info) PrepareDessert : [New Seoul] Min-seo Mun - Finished preparing Soymilk.
01-Adir-02:525.777 (Info) ToggleResourceProcess : [Schiaparelli Point] ERV-B 2 - Produce Polyethylene : Louise Koskinen made an attempt to toggle it on.
01-Adir-02:526.222 (Info) ExploredLocation : New Plymouth - 17.8915 N 26.2320 W   Estimated reserve: 123548 kg.  Concentration: {Hematite=0.7044884986901143, Olivine=0.0, Taenite=0.0, Magnesite=0.0, Sylvite=0.0, Magnetite=0.9425346182782484, Chalcopyrite=0.0, Kamacite=0.0, Goethite=0.4318823193113872, Malachite=0.0}
01-Adir-02:526.518 (Info) ToggleResourceProcess : [Starcity] ERV-B 2 - Extract minerals from basaltic deposits : RepairBot 007 made an attempt to toggle it on.
01-Adir-02:527.274 (Warning) ResourceProcess [x4] : [Kyocera] Case D. Not enough space for storing 'Sodium oxide' output to continue 'Extract minerals from basaltic deposits'. Required: 0.0 kg of storage. Remaining cap: 0.0 kg.
01-Adir-02:528.334 (Info) ToggleResourceProcess : [New Seoul] ERV-B 2 - Produce Polyethylene : Ji-min Jue made an attempt to toggle it on.
01-Adir-02:529.835 (Info) ExitAirlock [x19] : [0.8244 N 20.9857 E - Ma'adim] Lukas Steiner - Can't egress. other occupant(s) have already pre-breathed half-way thru. Current task: Collecting Resources.
01-Adir-02:532.338 (Info) ToggleResourceProcess : [New Boston] ERV-B 3 - Produce Styrene : RepairBot 011 made an attempt to toggle it on.
01-Adir-02:533.975 (Config) Simulation : Submitting the request for saving the simulation.
01-Adir-02:533.975 (Config) MainWindow : Save requested
01-Adir-02:533.975 (Warning) Msg : !!0.00 km/h??
01-Adir-02:533.975 (Config) Simulation : Submitting the request for saving the simulation.
01-Adir-02:533.975 (Config) MainWindow : Save requested
01-Adir-02:533.975 (Config) Simulation : Submitting the request for saving the simulation.
01-Adir-02:533.975 (Config) MainWindow : Save requested
```

**Specifications  (please complete the following information):**
 - pre-3.5.0 build 7897

**Comment by mokun** [comment]
@bevans2000 

I wonder if you have seen any failure in saving a sim like this.

> 01-Adir-02:533.975 (Warning) Msg : !!0.00 km/h??

btw, the stacktrace below has this line. was it about a mission vehicle's speed that can't be computed or displayed ?

**Comment by bevans2000** [comment]
The warning is because it is trying to use Msg bundle but the correct value is the key

**Comment by bevans2000** [comment]
I've found the Msg problem but I can't get the Save to fail. I don't think it is this Msg problem.

**Comment by mokun** [comment]
oh I just found out how to make it "failed".

If I open up Mission Tool, then I click Save. It will fail as follows:

```
01-Adir-01:271.220 (Info) ExitAirlock : [Schiaparelli Point - EVA Airlock 3] Lotte De Vries - Airlock is not in egress mode. Current task: Playing a Holo Game.
01-Adir-01:271.864 (Info) ReviewMissionPlan : [Tian Cheng] Jin Han - Grading Regolith Prospecting #10 Plan - Rels: 11, Site: 0.7, Review: 2; Subtotal: 13.7
01-Adir-01:271.864 (Info) ReviewMissionPlan : [Tian Cheng] Jin Han - Done reviewing Chung Xu's Regolith Prospecting #10 mission plan.
01-Adir-01:272.026 (Config) Simulation : Submitting the request for saving the simulation.
01-Adir-01:272.026 (Config) MainWindow : Save requested
01-Adir-01:272.187 (Config) Simulation : Saving the simulation as default.sim.
01-Adir-01:272.187 (Config) Simulation : Heap Max Size: 1.50 GB, Heap Free Size: 98.59 MB
01-Adir-01:272.187 (Config) Simulation :            File size: 1.24 MB
01-Adir-01:272.187 (Config) Simulation : Done saving. The simulation resumes.
01-Adir-01:272.187 (Config) UIConfig : Previous ui_settings.xml deleted.
01-Adir-01:272.187 (Severe) MasterClock : Can't send out clock pulse: 
java.lang.NullPointerException: Cannot invoke "org.mars_sim.msp.core.person.ai.mission.Mission.getName()" because "this.missionCache" is null
	at org.mars_sim.msp.ui.swing.tool.mission.MissionWindow.getUIProps(MissionWindow.java:311)
	at org.mars_sim.msp.ui.swing.UIConfig.saveFile(UIConfig.java:245)
	at org.mars_sim.msp.ui.swing.MainWindow.lambda$3(MainWindow.java:546)
	at org.mars_sim.msp.core.Simulation.saveSimulation(Simulation.java:831)
	at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1281)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:640)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-01:272.187 (Warning) MasterClock : Clock Thread stopping
```

Previously, the failure was kind of "quiet".

This time, failure is a lot more dramatic.

**Comment by bevans2000** [comment]
That is easy to fix. It's because there is no mission selected in the Mission Tool when saving the ui config. Just check it for null is the getUIProps method.
