### ISSUE TITLE
Null region in Radiation 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#847]
**Describe the bug**
- Region is null during radiation event

**Expected and unexpected behavior**
- It's not known why region becomes null as it should be 1 of the 3.

**Java classes involved**
- Radiation

**Stacktrace**
```
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0019 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Severe) PersonTaskManager [x12] : [41.0100 N 165.3200 E] Philippe Fournier - Trouble calling performTask(): 
java.lang.NullPointerException: Cannot invoke "org.mars_sim.msp.core.person.health.BodyRegionType.getName()" because "this.region" is null
	at org.mars_sim.msp.core.person.health.Radiation.toString(Radiation.java:48)
	at org.mars_sim.msp.core.person.health.RadiationExposure.isRadiationDetected(RadiationExposure.java:542)
	at org.mars_sim.msp.core.person.ai.task.EVAOperation.isRadiationDetected(EVAOperation.java:682)
	at org.mars_sim.msp.core.person.ai.task.EVAOperation.checkReadiness(EVAOperation.java:475)
	at org.mars_sim.msp.core.person.ai.task.DigLocal.collectResource(DigLocal.java:239)
	at org.mars_sim.msp.core.person.ai.task.DigLocal.performMappedPhase(DigLocal.java:189)
	at org.mars_sim.msp.core.person.ai.task.util.Task.executeMappedPhase(Task.java:672)
	at org.mars_sim.msp.core.person.ai.task.util.Task.performTask(Task.java:623)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:82)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:204)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:176)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:119)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:835)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1080)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:918)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:750)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0015 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0017 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0015 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0012 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0014 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0014 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0017 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0011 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0015 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 0.0012 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Philippe Fournier - Exposed to Baseline and received 7.0E-4 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Alycia Martin - Exposed to Baseline and received 0.0 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Severe) PersonTaskManager [x11] : [41.0100 N 165.3200 E] Alycia Martin - Trouble calling performTask(): 
java.lang.NullPointerException: Cannot invoke "org.mars_sim.msp.core.person.health.BodyRegionType.getName()" because "this.region" is null
	at org.mars_sim.msp.core.person.health.Radiation.toString(Radiation.java:48)
	at org.mars_sim.msp.core.person.health.RadiationExposure.isRadiationDetected(RadiationExposure.java:542)
	at org.mars_sim.msp.core.person.ai.task.EVAOperation.isRadiationDetected(EVAOperation.java:682)
	at org.mars_sim.msp.core.person.ai.task.EVAOperation.checkReadiness(EVAOperation.java:475)
	at org.mars_sim.msp.core.person.ai.task.DigLocal.collectResource(DigLocal.java:239)
	at org.mars_sim.msp.core.person.ai.task.DigLocal.performMappedPhase(DigLocal.java:189)
	at org.mars_sim.msp.core.person.ai.task.util.Task.executeMappedPhase(Task.java:672)
	at org.mars_sim.msp.core.person.ai.task.util.Task.performTask(Task.java:623)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:82)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:204)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:176)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:119)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:835)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1080)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:918)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:750)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Alycia Martin - Exposed to Baseline and received 0.0014 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Alycia Martin - Exposed to Baseline and received 0.0015 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Alycia Martin - Exposed to Baseline and received 0.0016 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Alycia Martin - Exposed to Baseline and received 0.001 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Alycia Martin - Exposed to Baseline and received 0.0012 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Alycia Martin - Exposed to Baseline and received 0.0019 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Alycia Martin - Exposed to Baseline and received 0.0012 mSv dose of radiation during an EVA operation.
01-Adir-01:550.208 (Info) RadiationExposure : [41.0100 N 165.3200 E] Alycia Martin - Exposed to Baseline and received 8.0E-4 mSv dose of radiation during an EVA operation.
```

**Specifications**
 - pre-3.6.0 build 7940

**Additional context**
```
	@Override
	public String toString() {
		String typeStr = type.getName();
		String regionStr = region.getName();
		return typeStr + " - " + regionStr + " - Dose: " + Math.round(amount * 10_000.0)/10_000.0;
	}
```
- Since region is null, region.getName() causes NPE.

**Comment by bevans2000** [comment]
Did this happen after a Radiation event? The problem exist in 3.5.0 probably so we need to fix it on the branch. Last night I found #848 which needs a bugfix.

**Comment by bevans2000** [comment]
I'll fix this, I've found the problem.
