### ISSUE TITLE
Vehicle Crew Tab created in Mission Tool but NOT being switched open

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#859]
**Describe the bug**
- In Vehicle Window at Crew Tab, when I click on the Monitor Tool icon (in red circle), the Monitor Tool is supposed to be opened and a new Vehicle Crew tab is supposed to be created and being switched open. 

**Expected and unexpected behavior**
- In Vehicle Window at Crew Tab, when I click on the Monitor Tool icon (in red circle), the Monitor Tool is supposed to be opened.
- Even though a new Vehicle Crew tab is successfully created, it fails to switch open this Crew tab.

**Java classes involved**
- List out possible Java classes/methods that are behaving incorrectly.

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/233256859-b7345571-3202-4f37-9420-47bfddc4cdde.png)

Note that the Task Backlog tab was previously opened in Monitor Tool. 

![image](https://user-images.githubusercontent.com/1168584/233257721-c6ff6881-026f-44ab-b587-bdd39fe0d35a.png)

Clicking the Monitor Tool icon twice would create the tab ***twice***

The new Crew tab created for this Vehicle is NOT automatically switched open. 

It would be great if the new Vehicle Crew has a blinking or bouncy rectangular hovering over it as a notification for player to pay attention to.

**Stacktrace**
```
WARNING: row index is bigger than sorter's row count. Most likely this is a wrong sorter usage.
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.rowsUpdated(DefaultRowSorter.java:907)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4323)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4180)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(AbstractTableModel.java:252)
	at org.mars_sim.msp.ui.swing.unit_window.vehicle.TabPanelCrew$MemberTableModel$MemberTableUpdater.run(TabPanelCrew.java:410)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.checkAgainstModel(DefaultRowSorter.java:932)
	at java.desktop/javax.swing.DefaultRowSorter.rowsUpdated(DefaultRowSorter.java:905)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4323)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4180)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(AbstractTableModel.java:252)
	at org.mars_sim.msp.ui.swing.unit_window.vehicle.TabPanelCrew$MemberTableModel$MemberTableUpdater.run(TabPanelCrew.java:410)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.checkAgainstModel(DefaultRowSorter.java:932)
	at java.desktop/javax.swing.DefaultRowSorter.rowsUpdated(DefaultRowSorter.java:905)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4323)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4180)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4457)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(AbstractTableModel.java:252)
	at org.mars_sim.msp.ui.swing.unit_window.vehicle.TabPanelCrew$MemberTableModel$MemberTableUpdater.run(TabPanelCrew.java:410)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
01-Adir-21:630.657 (Severe) MonitorWindow : org.mars_sim.msp.ui.swing.tool.monitor.PersonTableModel@674c801b not found.
01-Adir-21:630.657 (Severe) MonitorWindow : org.mars_sim.msp.ui.swing.tool.monitor.PersonTableModel@3ca85d0f not found.
01-Adir-21:630.657 (Severe) MonitorWindow : org.mars_sim.msp.ui.swing.tool.monitor.PersonTableModel@22b4bb5c not found.
01-Adir-21:630.657 (Severe) MonitorWindow : org.mars_sim.msp.ui.swing.tool.monitor.PersonTableModel@49e913a5 not found.
01-Adir-21:630.657 (Severe) MonitorWindow : org.mars_sim.msp.ui.swing.tool.monitor.PersonTableModel@f478a13 not found.
01-Adir-21:630.657 (Severe) MonitorWindow : org.mars_sim.msp.ui.swing.tool.monitor.PersonTableModel@33126cdd not found.
01-Adir-21:630.657 (Severe) MonitorWindow : org.mars_sim.msp.ui.swing.tool.monitor.PersonTableModel@51f18628 not found.
```

**Specifications**
 - pre-3.6.0 build 7962

**Comment by bevans2000** [comment]
Just to note that the Monitor Window only shows Persons on board the Vehicle. But the Vehicle Crew tab shows anyone assigned to the Vehicle; hence sometimes there is an expected difference between the two tables.
