### ISSUE TITLE
ConcurrentModificationException in Relation's getAllKnownPeople() method

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#893]
**Describe the bug**
- While putting together a set of known persons by thread 1, this set is potentially being visited/updated by thread 2. 
- The Person collection in UnitManager involved people from all settlements and thus from all threads.

**Expected and unexpected behavior**
- Will create a brand new set of persons with `new ArrayList<>()` help, since it involves 2 threads ?
- Q: what is the best strategy to avoid this ConcurrentModificationException ?

**Java classes involved**
- Relation, RelationshipUtil

**Stacktrace**
```
01-Adir-01:600.014 (Severe) UnitManager$SettlementTask : Problem with pulse on Tian Cheng: null
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.mars_sim.msp.core.person.ai.social.Relation.getAllKnownPeople(Relation.java:220)
	at org.mars_sim.msp.core.person.ai.social.RelationshipUtil.getAllKnownPeople(RelationshipUtil.java:165)
	at org.mars_sim.msp.core.person.ai.social.RelationshipUtil.getAverageOpinionOfMe(RelationshipUtil.java:219)
	at org.mars_sim.msp.core.person.ai.EmotionManager.checkStimulus(EmotionManager.java:129)
	at org.mars_sim.msp.core.person.ai.Mind.updateEmotion(Mind.java:551)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:128)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:836)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1086)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:923)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:750)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Specifications  (please complete the following information)**
 - pre 3.6.0 build 8083

**Additional context**
- How similar or disimilar is this concurrency situation compared to that of https://github.com/mars-sim/mars-sim/issues/883 ?

**Comment by mokun** [comment]
@bevans2000 

I wonder if the culprit has to do with mixing/putting person A from settlement X and person B from settlement Y into creating this set of persons.

**Comment by bevans2000** [comment]
Yes exactly that. Relationship management is one of the places where there is cross-Settlement logic. This should be a rare occurrence so you could put a synchronized block on the optionsMap in the methods in ```Relational``. Key would be the 2 methods that change options and the geAllKnownPeople method
Alternatively only capture Relationship between people in the same Settlement.

**Comment by mokun** [comment]
But before we put the synchronized block out to stop it, can we  st up a test to see if it's indeed another thread that's trying to update the `opinionMap` ? 

Also, I don't know if it's possible to "catch" this concurrency exception when it's about to happen.

If we could, then we could make it print out some log statements to show which settler on what settlement is trying to access that same `opinionMap` , can we ?

**Comment by bevans2000** [comment]
Sure. Let me finish #827 this weekend and I'll have a look

**Comment by bevans2000** [comment]
So the code is not thread safe here BUT the root cause is how we make an initial relationship. In this creations phase we create an opinion of P1 -> P2 & P2 -> P1 where P1 is the instigator. For example P1 is the lead on a Study and P2 is invited. The 2nd relationship has the risk of going cross thread.

But the P2 -> P1 should not be created. Only P2 should be creating an opinion of P1. P1 cannot say what P2 thinks of P1 which is the current logic.
So if we correct this issue then a Person only ever updates their own opinions of other then it will stop the cross thread issue. 
The net effect is a Person only has an opinion of someone else when they directly interact with them.

**Comment by mokun** [comment]
> The net effect is a Person only has an opinion of someone else when they directly interact with them.

Ok. I agree we can simply the interaction by making it one way.

So in general if person A did something and that happens to impact person B or affect the locale where person B is at, then this situation creates an opinion within the mind of person B regarding person A.

So how do we make this happen more often to update an opinion of someone ?

Now it only gets called in a very limited fashion.

I see mars-sim has the potential of becoming a social simulation experiment of sorts if we add more features in how they may interact.

**Comment by mokun** [comment]
Yes. Those are very good examples. I imagine as long as a person is alive he would consciously or unconsciously formulate an opinion about someone. 

So interaction with someone can be direct or indirect. 

We could even expand the opinion toward a settlement, or toward the sponsor, or toward a leadership structure.

Group interaction, such as groupthink, peer pressure, would be something very interesting to simulate in future.

**Comment by bevans2000** [comment]
Yes I think it will be a clearer and more accurate implementation. 

I'm just finishing #855 at the moment.
