### ISSUE TITLE
ConcurrentModificationException in getSToredMass() when loading at the start of regolith mission

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#894]
**Describe the bug**
- `equipmentSet` can trigger concurrency issue when loading resources into an equipment.

**Expected and unexpected behavior**
- This concurrency issue apparently happens within when the UI thread is trying to assess `equipmentSet` when this set is being changed. It needs to be resolved.

**Java classes involved**
- EquipmentInventory
- LoadingController
- VehicleMapLayer

```java
	/**
	 * Gets the total mass of this inventory including the total mass of any held equipment.
	 * 
	 * @return
	 */
	@Override
	public double getStoredMass() {
		double result = 0;
		for (Equipment e: equipmentSet) {
			result += e.getMass();
		}
		return result +  microInventory.getStoredMass();
	}
```

**Stacktrace**
```
01-Adir-01:592.878 (Info) TaskManager : [Camp Kelper] Jonathan Anderson - Given a new task order of 'Load Regolith Prospecting #1'.
01-Adir-01:592.878 (Info) TaskManager : [Camp Kelper] Willie Perez - Given a new task order of 'Load Regolith Prospecting #1'.
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1579)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1602)
	at org.mars_sim.msp.core.equipment.EquipmentInventory.getStoredMass(EquipmentInventory.java:66)
	at org.mars_sim.msp.core.equipment.EquipmentInventory.getRemainingCargoCapacity(EquipmentInventory.java:365)
	at org.mars_sim.msp.core.vehicle.Vehicle.getRemainingCargoCapacity(Vehicle.java:1884)
	at org.mars_sim.msp.core.person.ai.task.LoadingController.isCompleted(LoadingController.java:528)
	at org.mars_sim.msp.ui.swing.tool.settlement.VehicleMapLayer.isVehicleLoading(VehicleMapLayer.java:201)
	at org.mars_sim.msp.ui.swing.tool.settlement.VehicleMapLayer.drawVehicle(VehicleMapLayer.java:133)
	at org.mars_sim.msp.ui.swing.tool.settlement.VehicleMapLayer.drawVehicles(VehicleMapLayer.java:106)
	at org.mars_sim.msp.ui.swing.tool.settlement.VehicleMapLayer.displayLayer(VehicleMapLayer.java:83)
	at org.mars_sim.msp.ui.swing.tool.settlement.SettlementMapPanel.paintComponent(SettlementMapPanel.java:1075)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JLayer.paint(JLayer.java:476)
	at java.desktop/javax.swing.plaf.LayerUI.paint(LayerUI.java:85)
	at org.mars_sim.msp.ui.swing.tool.SpotlightLayerUI.paint(SpotlightLayerUI.java:67)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
	at java.desktop/javax.swing.JLayer.paint(JLayer.java:471)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Specifications  (please complete the following information)**
 - pre 3.6.0 build 8085

**Additional context**
- May be related tohttps://github.com/mars-sim/mars-sim/issues/893, and https://github.com/mars-sim/mars-sim/issues/883, and even https://github.com/mars-sim/mars-sim/issues/484

**Comment by bevans2000** [comment]
I didn't even know that the ui called the LoadingController. I can fix this, no reason why the isCompleted method needs to look at the storage.

**Comment by bevans2000** [comment]
The fix removes the need to recalculate the remaining capacity in every call. The capacity is now only calculated in the load routine but the results is saved to be used later in the isCompleted method.

**Comment by mokun** [comment]
> The fix removes the need to recalculate the remaining capacity in every call. The capacity is now only calculated in the load routine but the results is saved to be used later 

I thought it's not necessary to see the remaining amount when retrieving resources.

It's only needed when I have to store resources because I need to check how much space is available, right?
