### ISSUE TITLE
Cannot load from default.sim

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#902]
**Describe the bug**
- Currently, it's not possible to use the Eclipse launcher "MarsProject -load.launch" to load from default.sim using JFileChooser
EDIT :
- It's having the same issue with the Eclipse launcher "MarsProject -load default.launch" for loading the same sim file.

**Expected and unexpected behavior**
- Any files with ".sim" as extension that are saved in mars-sim should be loadable. and not getting terminated.

**Java classes involved**
- MonitorWindow's `PersonTableModel` cannot figure out the settlement in the saved sim.

**Screenshot**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/a5b2ac12-15e7-4d0e-a49e-e74ef1e0ebe9)

**Stacktrace**
```
01-Adir-01:000.077 (Severe) MarsProject : Problem starting Cannot invoke "org.mars_sim.msp.core.structure.Settlement.getAllAssociatedPeople()" because "this.settlement" is null
java.lang.NullPointerException: Cannot invoke "org.mars_sim.msp.core.structure.Settlement.getAllAssociatedPeople()" because "this.settlement" is null
	at org.mars_sim.msp.ui.swing.tool.monitor.PersonTableModel.setSettlementFilter(PersonTableModel.java:230)
	at org.mars_sim.msp.ui.swing.tool.monitor.PersonTableModel.<init>(PersonTableModel.java:184)
	at org.mars_sim.msp.ui.swing.tool.monitor.MonitorWindow.addAllTabs(MonitorWindow.java:204)
	at org.mars_sim.msp.ui.swing.tool.monitor.MonitorWindow.<init>(MonitorWindow.java:160)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.getToolWindow(MainDesktopPane.java:348)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.openToolWindow(MainDesktopPane.java:409)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.openInitialWindows(MainDesktopPane.java:733)
	at org.mars_sim.msp.ui.swing.MainWindow.<init>(MainWindow.java:194)
	at org.mars_sim.main.MarsProject.setupMainWindow(MarsProject.java:417)
	at org.mars_sim.main.MarsProject.parseArgs(MarsProject.java:209)
	at org.mars_sim.main.MarsProject.main(MarsProject.java:476)
```

Below is the snapshot of a portion of the Eclipse launcher "MarsProject -load.launch" : 
```
   <booleanAttribute key="org.eclipse.jdt.launching.ATTR_ATTR_USE_ARGFILE" value="false"/>
    <booleanAttribute key="org.eclipse.jdt.launching.ATTR_USE_CLASSPATH_ONLY_JAR" value="false"/>
    <stringAttribute key="org.eclipse.jdt.launching.CLASSPATH_PROVIDER" value="org.eclipse.m2e.launchconfig.classpathProvider"/>
    <stringAttribute key="org.eclipse.jdt.launching.MAIN_TYPE" value="org.mars_sim.main.MarsProject"/>
    <stringAttribute key="org.eclipse.jdt.launching.MODULE_NAME" value="mars-sim-main"/>
    <stringAttribute key="org.eclipse.jdt.launching.PROGRAM_ARGUMENTS" value="-load"/>
    <stringAttribute key="org.eclipse.jdt.launching.PROJECT_ATTR" value="mars-sim-main"/>
    <stringAttribute key="org.eclipse.jdt.launching.SOURCE_PATH_PROVIDER" value="org.eclipse.m2e.launchconfig.sourcepathProvider"/>
    <stringAttribute key="org.eclipse.jdt.launching.VM_ARGUMENTS" value="-Xmx1536m --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.desktop/javax.swing=ALL-UNNAMED --add-opens java.desktop/javax.swing.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.desktop/java.awt.geom=ALL-UNNAMED --add-opens java.desktop/java.awt=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/javax.swing.table=ALL-UNNAMED --add-opens java.desktop/sun.awt=ALL-UNNAMED --add-opens java.desktop/sun.swing=ALL-UNNAMED --add-opens java.desktop/sun.font=ALL-UNNAMED --add-opens java.desktop/javax.swing.plaf.basic=ALL-UNNAMED --add-opens java.desktop/javax.swing.plaf.synth=ALL-UNNAMED"/>
```

If using only "-load", instead of "-load default.sim", the JFileChooser will pop up in the background (it should be in the foreground, or else no one knows).

**Specifications  (please complete the following information)**
 - pre 3.6.0 build 8129

**Additional context**
- JFileChooser should not pop up in the background, or else no one knows.

**Comment by mokun** [comment]
In PersonTableModel,
```java
	@Override
	public boolean setSettlementFilter(Settlement filter) {	
		if ((sourceType != ValidSourceType.SETTLEMENT_ALL_ASSOCIATED_PEOPLE) &&
			(sourceType != ValidSourceType.SETTLEMENT_INHABITANTS)) {
				return false;
		}

		if (settlementListener != null) {
			settlement.removeUnitListener(settlementListener);
		}

		this.settlement = filter;
		if (sourceType == ValidSourceType.SETTLEMENT_ALL_ASSOCIATED_PEOPLE) {
			resetEntities(settlement.getAllAssociatedPeople());
			settlementListener = new PersonChangeListener(UnitEventType.ADD_ASSOCIATED_PERSON_EVENT,
														UnitEventType.REMOVE_ASSOCIATED_PERSON_EVENT);
			settlement.addUnitListener(settlementListener);
		} else {
			resetEntities(settlement.getIndoorPeople());
			settlementListener = new PersonChangeListener(UnitEventType.INVENTORY_STORING_UNIT_EVENT,
														UnitEventType.INVENTORY_RETRIEVING_UNIT_EVENT);
			settlement.addUnitListener(settlementListener);
		}

		return true;
	}
```

The line `resetEntities(settlement.getAllAssociatedPeople())` triggers NPE settlement

**Comment by mokun** [comment]
EDIT :
- I'm having the same issue with the Eclipse launcher "MarsProject -load default.launch" for loading the same sim file.

So, it has nothing to do with JFileChooser.

PersonTableModel is the culprit.

**Comment by mokun** [comment]
@bevans2000

EDIT :

I'm having the same issue with the Eclipse launcher "MarsProject -load default.launch" for loading the same sim file.
So, it has nothing to do with JFileChooser.

PersonTableModel is the culprit.

**Comment by bevans2000** [comment]
If you delete your ipconfig file I think it will work. My guess is the monitor window is restart on a none existent Settlement from the previous run.
I'll take a look tomorrow

**Comment by bevans2000** [comment]
I couldn't reproduce this but I did find a minor problem in PersonTableModel where it may remove the listener but still think it is active. I can't understand how it generates a NPE but have but a more defensive code in place.

**Comment by mokun** [comment]
I don't know. May be in that saved sim session I never opened monitor tool ?!

Have you by any chance tried those Eclipse Launchers to load a saved sim  ?

**Comment by bevans2000** [comment]
I'm not using Eclipse any more sorry. But it's the command line that matter.
