### ISSUE TITLE
How to build communication, seismic, weather monitoring stations

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#907]
**Is your feature request related to a problem? Please describe.**
- What would it take to build communication, seismic, weather monitoring stations that belongs to a settlement ?

**Describe the rationale**
- As a settlement expands, it needs to track the changes or the impact made to its local environment. 
- Monitoring stations :
   - Enhance the understanding of the natural environment of Mars.
   - Collect on-site weather and seismic data, process them and relay them back to the settlement that owns it.
   - A mesh network of monitoring stations would provide valuable environment security to the health and well-being of a settlement.

- Communication Towers : 
   - Without communication towers, a settlement would have to rely on limited narrow bandwidth satellite comm for long-haul, such as connecting with remote rovers over hundreds of miles away or other settlements thousands of miles away.
   - Setting up remote communication towers along a mission corridor would pave the way for high bandwidth terrestrial 
communication with mission rovers.

**Describe the solution you desire to see**
- For players, use Mission Tool to create a *Building a monitoring station* mission
- For AI, use a weather debt score or a communication debt score to gauge the demand on when to dispatch such a mission.
- It is both a Building Mission and a Vehicle Mission. 
- It would require vehicles loaded with concretes or other building materials to be sent to a remote location
 
- For a small outside-only station, 
   - It only need to assemble large parts on-site and firmly secure the equipment to the ground and calibrate the instrument to function. 
   - It would need to place some kind of weather protective barrier around the equipment stations and instruments
   - It would need to periodically send settlers once in a while to check up what a robot cannot do or to perform upgrades
   - Passive remote stations would collect and relay data immediately back to the settlement.
   - Active stations would need to be furnished with computing equipment to process the data on site. 

- For a habitat-size station having indoor space, 
   - it would look like a small settlement and may require constructing a foundation, a frame and a building, much like a *Building Construction* mission.
   - it will need to have living space with life support built-in to house staff and researchers and it would need to house a robot to do on-site, regular maintenance

**Specifications  (please complete the following information):**
 -pre 3.6.0 build 8142

**Comment by mokun** [comment]
@bevans2000 

I began a manual *Building Construction* mission. I picked 4 persons and a vehicle.

```java
01-Adir-01:386.550 (Info) AbstractMission : [Camp Kelper] Amy Kelly - Began organizing a Building Construction #5 mission.
01-Adir-01:386.550 (Info) BuildingConstructionMission : [Camp Kelper] Case 3 : site has NOT been picked yet and the construction is manually started by users
01-Adir-01:386.550 (Info) BuildingConstructionMission : [Camp Kelper] stageInfo: surface foundation 7m x 9m
01-Adir-01:386.550 (Info) BuildingConstructionMission : [Camp Kelper] Starting new construction stage: Constructing Surface Foundation 7m X 9m
01-Adir-01:433.017 (Severe) AbstractMission : [Camp Kelper] Amy Kelly - In a Settlement during ACTIVE mission phase Prepare Site
01-Adir-01:433.017 (Info) BuildingConstructionMission [x3] : [Camp Kelper] Amy Kelly - Preparing a construction site 'A Construction Site.
01-Adir-01:433.750 (Severe) AbstractMission : [Camp Kelper] Amy Kelly - In a Settlement during ACTIVE mission phase Prepare Site
01-Adir-01:435.505 (Info) ReviewMissionPlan : [Camp Kelper] Phillip Cox - Grading Ice Prospecting #3 Plan - Rels: 9, Site: 3.0, Review: 5; Subtotal: 17.0
01-Adir-01:435.505 (Info) ReviewMissionPlan : [Camp Kelper] Phillip Cox - Done reviewing Janet Adams's Ice Prospecting #3 mission plan.
01-Adir-01:440.879 (Severe) AbstractMission : [Camp Kelper] Amy Kelly - In a Settlement during ACTIVE mission phase Prepare Site
01-Adir-01:440.879 (Info) BuildingConstructionMission [x2] : [Camp Kelper] Amy Kelly - Preparing a construction site 'A Construction Site.
01-Adir-01:445.441 (Warning) LoadingController : [Camp Kelper] Gemini - Harold Roriguez item Optical cable, 1 not loaded 
01-Adir-01:446.323 (Info) Walk : [Camp Kelper - Gemini] Manuel Jones - Entered rover Gemini inside Garage 1.
01-Adir-01:446.323 (Info) Walk : [Camp Kelper - Gemini] Robert Carter - Entered rover Gemini inside Garage 1.
01-Adir-01:446.323 (Info) Walk : [Camp Kelper - Gemini] Anna Torres - Entered rover Gemini inside Garage 1.
01-Adir-01:452.356 (Severe) AbstractMission : [Camp Kelper] Amy Kelly - In a Settlement during ACTIVE mission phase Prepare Site
01-Adir-01:463.122 (Severe) AbstractMission : [Camp Kelper] Amy Kelly - In a Settlement during ACTIVE mission phase Prepare Site
...
01-Adir-01:476.319 (Severe) AbstractMission : [Camp Kelper] Amy Kelly - In a Settlement during ACTIVE mission phase Prepare Site
01-Adir-01:476.319 (Info) BuildingConstructionMission [x3] : [Camp Kelper] Amy Kelly - Preparing a construction site 'A Construction Site.
...
01-Adir-01:487.443 (Severe) AbstractMission : [Camp Kelper] Amy Kelly - In a Settlement during ACTIVE mission phase Prepare Site
01-Adir-01:493.238 (Severe) AbstractMission : [Camp Kelper] Amy Kelly - In a Settlement during ACTIVE mission phase Construction
...
01-Adir-01:507.439 (Severe) UnitManager : Problem with pulse on Camp Kelper: Cannot invoke "Object.equals(Object)" because the return value of "org.mars_sim.msp.core.vehicle.GroundVehicle.getMission()" is null
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.mars_sim.msp.core.vehicle.GroundVehicle.getMission()" is null
	at org.mars_sim.msp.core.person.ai.mission.BuildingConstructionMission.endMission(BuildingConstructionMission.java:757)
	at org.mars_sim.msp.core.person.ai.mission.BuildingConstructionMission.determineNewPhase(BuildingConstructionMission.java:595)
	at org.mars_sim.msp.core.person.ai.mission.AbstractMission.performMission(AbstractMission.java:584)
	at org.mars_sim.msp.core.person.ai.Mind.resumeMission(Mind.java:307)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:287)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:250)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:183)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:120)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:836)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1094)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:931)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:787)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It's probably that vehicle I picked earlier did not actually get reserved or may be the vehicle.getMission() is null because it's not tagged properly.

Can you see if you can duplicate this ?

**Comment by mokun** [comment]
hmm. I actually was never asked to choose a rover. I did choose a LUV.

**Comment by mokun** [comment]
I can see in `BuildingConstructionMission` class : 

```java
	/**
	 * Reserve construction vehicles for the mission.
	 */
	public void reserveConstructionVehicles() {
		if (stage != null) {
			// Construct a new list of construction vehicles
			constructionVehicles = new ArrayList<>();
			Iterator<ConstructionVehicleType> j = stage.getInfo().getVehicles().iterator();
			while (j.hasNext()) {
				ConstructionVehicleType vehicleType = j.next();
				// Only handle light utility vehicles for now.
				if (vehicleType.getVehicleType().equalsIgnoreCase(VehicleType.LUV.getName())) {
					LightUtilityVehicle luv = reserveLightUtilityVehicle();
					if (luv != null) {
						constructionVehicles.add(luv);
						luv.setMission(this);
					} else {
						logger.warning(settlement, "BuildingConstructionMission : LUV not available");
						endMission(LUV_NOT_AVAILABLE);
					}
				}
			}
		}
	}
```

**Comment by mokun** [comment]
I suppose you are only fixing other mission class and haven't touch `BuildingConstructionMission`, rigtht ? 

I'm going to commit some changes in it to make building construction working again to test other features.

**Comment by bevans2000** [comment]
Correct, not touching construction.

**Comment by mokun** [comment]
@Urwumpe @bevans2000 

I see that we may be getting close to implementing weather stations. 

After we fully fix the construction mission, we could in principle create missions that send rovers and luv out to a site and use a weather station "template", much like those arriving settlement templates, to start a new 'settlememt instance'.

Can you guys comment and chime in how you feel about this or what you would do to make this a reality?

**Comment by Urwumpe** [comment]
@mokun I think that a great step back to the science and exploration character of marssim. 

How well is the simulation of Mars Weather now? Already at CO2 snowfall?

Maybe we can then also soon make the supply depots functional, to allow further exploration of Mars.

**Comment by mokun** [comment]
> How well is the simulation of Mars Weather now? 

For now, there's a Weather tab in Settlement Unit Window : 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/d1d4f03a-6eb8-48e7-b74e-d97d2e23b42f)

**Comment by mokun** [comment]
> Already at CO2 snowfall?

When I ask a chatgpt-like bot the question of whether we would find snowfall on Mars, it responds : 


> Recent studies with NASA's Mars Reconnaissance Orbiter have revealed that carbon dioxide snow clouds are thick enough to result in snowfall accumulation on the surface of Mars.
> 
> Snow has not yet been observed in the process of actually reaching the ground on Mars, but it has been seen falling through the sky.
> 
> In 2008, NASA's Mars Phoenix Lander detected snow falling from clouds about 4km above the planet's surface.
> Observations by NASA's Mars Reconnaissance Orbiter have detected carbon-dioxide snow clouds on Mars and evidence of carbon-dioxide snow falling to the surface. Deposits of small particles of carbon-dioxide ice are formed by snowfall from carbon-dioxide clouds.
> 
> Despite a steady supply of clouds, snow rarely accumulates on the Red Planet's surface
> 

How do you like the sound of it :D ?

**Comment by Urwumpe** [comment]
> > How well is the simulation of Mars Weather now?
> 
> For now, there's a Weather tab in Settlement Unit Window :
> 


Wasn't it still very crude? I think we wanted to implement an old Mars global circulation modell one day, that could produce more realistic weather and seasons.

**Comment by mokun** [comment]
> Wasn't it still very crude? 

Yes it only shows a bunch of params and there's very little use of them. 

Any new ideas in making these data more useful for players running a settlement ?

Especially that we are talking about building weather stations. 

What do you see as use cases for these stations ?

> an old Mars global circulation modell one day, that could produce more realistic weather and seasons.

This is ambitious but doable. We'll need some equations and write out some design goals laid out.

**Comment by mokun** [comment]
Also in Settlement Map, we are supposed to display 3 separate weather icons that tell player the weather condition visually. 

But we could have given each icon a pop tooltip that will give some quantitative figures if we like.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/32dd78a7-310d-41e2-ab7d-5b554e5f4cda)

Btw, the above screenshot shows the center icon is missing. Will need to go back to find out why.

**Comment by Urwumpe** [comment]
Maybe not so ambitious if the model is old and the resolution of our Mars lower than originally used. Any PC today has way more computing power as a Cray-2 back then. It will not produce real weather, of course, but if it could produce sandstorm seasons, it would be more than good enough for us. Also we don't need to update the weather every tick, we can let it compute in the background and just interpolate between last forecast and current forecast, before switching to the next forecast for interpolation. T

Also, we measure the weather only at few sparse places, which could also simplify things.

**Comment by mokun** [comment]
Let's go back to the topic of constructing weather stations, communication towers and other remote facilities. 

- First, they are not going to be full-blown settlements. How do we treat these types of remote facilities, that are different from a settlement ? 
- Second, to do so, building construction needs to be working. See [#909](#909).
- Third, We'll need to design a special vehicle mission that can send a group of vehicles out there and also build a facility. Some resources will bring needed initial resources out there. Some will be operational vehicles. We'll need to create mobile concrete plants for synthesizing the cement/concrete. Note that currently, we designate ERV-B as the plant that process raw regolith into something useful. And we could fast-track research program that work on [#936](#936) to bring 3-D printing tech online.
- Fourth, we'll need to fix the old walking issue with Constructionbots that can go outside the settlement to aid settlers.

**Comment by bevans2000** [comment]
Sounds like you should close this and create a project to outline all these steps.

**Comment by mokun** [comment]
> create a project to outline all these steps.

Done !

> Sounds like you should close this 

We'll just leave it open for the time being since we haven't even started working on how to model what a weather station and a comm tower would look like.

**Comment by bevans2000** [comment]
Picking up on the earlier conversation. I don't think there is a need to create any new Unit for these. All the behaviour of a Settlement is applicable to a Station. There still have a single building with a Function. Potentially they could have a habitat as well,
Potentially we should rename Settlement to Base remove the interpretation it is where Persons live

**Comment by mokun** [comment]
Would you like to change how the threads are created ? 

Currently, it first looks at how many threads are available. 

Then it assigns one or two thread per settlement if possible.

Now, can we have one or two thread per sponsor or per country instead ? 

This way, a weather station and communication tower that belong to the same sponsor would be under one thread.

Would you agree ?

**Comment by bevans2000** [comment]
I would like to revisit the Threads but I can be done separate from this issue.
But to solve the problem with cross Settlement updates I know how to fix it now and it's what I originally wanted. Vehicles and Person are updated from the Settlement where they are not the Associated Settlement as is the case now. This means visiting Vehicles and Persons are updated from the Settlement they are visiting not their home one. This means remote loading and unloading is controlled by the remote Settlement.
It needs a change to the Transfer methods to transfer control. I want to do this as part of the release under the other issue.
But we can still add weather station as a special Settlement template. However what does a weather station provide to those already leaving on Mars?

**Comment by mokun** [comment]
I can start creating a building called Communication Tower. A settlement can have Command and Control building for doing similar thing. 

This specialized building will be mostly automated and unmanned (may have robots).

We'll need to add models in terms of how   communication is handled (amount of bandwidth, at what frequency, etc.)

**Comment by mokun** [comment]
So if settlement A builds and owns a communication tower located at 10 km from it, how do you handle the thread for this tower ? 

Can you offer a mechanism for using the same thread for spawning off-site stationary assets ?

**Comment by bevans2000** [comment]
We could but what's the benefit of having the station and parent settlement in the same thread?

**Comment by mokun** [comment]
> We could but what's the benefit of having the station and parent settlement in the same thread?

Doing the supply runs would be easier.

When a vehicle and settlers from the parent settlement visits this station to do things inside and outside, it would be handy for all of these units to be on the thread, right ?

Also, if  I use my laptop that has 8 threads to run that simulation session and it has a dozen of settlements, it makes no sense to create another thread to separate the parent settlement and its stations to run on two different thread. 

Say if each of those dozen settlements have 3 off-site stations, we are talking about 12 * 3 = 36 threads.

**Comment by bevans2000** [comment]
So at the moment each Settlement does not run in it's own Thread. There is a pool of Threads based on the machine size and the Settlements get assigned. 
We need to solve the visiting settlement problems which we will do as part of this release. Then functionally there is no need to enforce the same Thread to be used

**Comment by mokun** [comment]
In case of a high number of settlement (like in the default scenario), I want to take one step further by organizing the thread generation to be based upon the sponsorship authority. 

So if Settlement A and B are under NASA, then the two settlement are on the same thread. Any exchange between these two settlements would be easily manageable.

**Comment by mokun** [comment]
@bevans2000 

I very much want to make the construction mission tenable again in v3.10.0. 

As we rework construction, we'll make design changes in construction so that it can be expanded to building communication/sensor towers.

**Comment by bevans2000** [comment]
I've had a rethink on this and maybe we do need a Base class. A Settlement would be a subclass obviously of Base. But Base would not have the higher level controls such as

- Shift control
- Backlog Tasks
- Meal Schedule
- Goods Manager

It would just have Buildings. But it a big new concept

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

Before we can construct communication relay, etc. in remote places, I'm planning to add some modeling fidelity to what a communication channel really means. 

So far, we haven't accounted for what kind of communication resources the settlement will develop. 

The best we have is from the `Computation` class, where computing resources must be acquired in order for someone to connect online and dial home to talk to their significant others. 

We should definitely go ahead defining communication channels, bandwidth, range, power, etc. 

Only then will it make sense to build relay stations.

**Comment by mokun** [comment]
> a rethink on this and maybe we do need a Base class. A Settlement would be a subclass obviously of Base. But Base would not have the higher level controls

Sure. Please feel free to go ahead implementing the idea of the bare bone `Base` class.

I suppose a weather station or a remote way station would have very minimal building functions. It may have one or two adjacent buildings and that's it.

**Comment by bevans2000** [comment]
Ok but not in this release, we have enough work going on. Nevertheless I see a remote Westher Station as largely a Settlement. We need to think through what the differences are.
But a weather station could eventually grow into a Settlement so they are the same thing in terms of modelling.
There maybe a small difference in terms of Commerce

**Comment by mokun** [comment]
See the infographic below : 

<img width="941" height="715" alt="Image" src="https://github.com/user-attachments/assets/f3396a94-3f63-459c-8c7e-e1ded75d7cc7" />

We could implement the followings: 

1. Create remote meteorology site missions that will commence the building of a tower for drilling underground.
2. Beef up the mobile lab in a rover to support field science experiments.
3. Construct fixed site observation stations for performing measurement.

**Comment by mokun** [comment]
@bevans2000  @Urwumpe 

Feels like we are getting really closed to collecting seismic data.

Once GatherDataMeta and GatherData are complete, we could reuse them for not just water/ice data measurement, but also for seismic and weather measurement.

As suggested in this thread, we could have meteorology missions participating in the construction, commissioning and operations of weather stations.

In that case, we will need to make remote site construction as plug-and-play as possible, as if it's a task that any mission members can do, given the available construction resources.

Or we could have multiple mission rovers each having an unique objective to arrive at one site and do their own job.

What do you envision and which approach would you favor ?

**Comment by bevans2000** [comment]
Havent thought this through actually

**Comment by mokun** [comment]
> But a weather station could eventually grow into a Settlement so they are the same thing in terms of modelling.

This is an interesting observation. By then, we can treat the new settlement as an arriving settlement from a resupply mission.

One consideration is to allow the natural upgrade of a weather station into an outpost or trading post as settlers move in to work and live there on a more permanent basis. 

I myself haven't played any outpost or trading post that much. They are essentially a settlement no doubt.

**Comment by bevans2000** [comment]
Yes I think earlier post I said we should treat these as Settlements. I wonder if we should create a Settlement Group so they stay inside the same Updater Thread.
