### ISSUE TITLE
ClassCastException when viewing the Power Grid tab in Building

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#922]
**Describe the bug**
There is a Class cast exception when showing the UI Power Grid tab in a Solar Array building unit window. Looks like the tab has been changed to only support Fission power source.

**Java classes involved**
- List out possible Java classes/methods that are behaving incorrectly.

**To Reproduce (Please provide steps)**
- Steps to reproduce the behavior:
1. Go to a Solar Power building
2.  Open the Unit Window
3. Display the Power Grid tab

**Stacktrace**
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class org.mars_sim.msp.core.structure.building.function.SolarPowerSource cannot be cast to class org.mars_sim.msp.core.structure.building.function.FissionPowerSource (org.mars_sim.msp.core.structure.building.function.SolarPowerSource and org.mars_sim.msp.core.structure.building.function.FissionPowerSource are in unnamed module of loader 'app')
        at org.mars_sim.msp.ui.swing.unit_window.structure.building.BuildingPanelPower.buildUI(BuildingPanelPower.java:100)   
        at org.mars_sim.msp.ui.swing.unit_window.TabPanel.initializeUI(TabPanel.java:145)
        at org.mars_sim.msp.ui.swing.unit_window.UnitWindow$1.stateChanged(UnitWindow.java:118)
        at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:444)
        at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
        at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)        
        at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)
        at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:648)
        at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:623)
        at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4101)
        at com.formdev.flatlaf.ui.FlatTabbedPaneUI$Handler.mousePressed(FlatTabbedPaneUI.java:2630)
        at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
        at java.desktop/java.awt.AWTEventMulticaster.mousePressed
```

**Comment by mokun** [comment]
Good catch ! I'll fix this illegal casting of powerSource.

```java
double loadCapacity = ((FissionPowerSource)powerSource).getCurrentLoadCapacity();
```
