### ISSUE TITLE
New concurrency issue with PlanMission

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#950]
**Describe the bug**
- PlanMission has concurrency issue

**Discuss any potential problems you have and have not ruled out**
- It seems like after this [commit](https://github.com/mars-sim/mars-sim/tree/322c844ac09de410d3ef5d5a06e4557914dae0fa), we've been having this exception.
 
**Java classes involved**
- MissionManager
- Mind
- PlanMission

**To Reproduce (Please provide steps)**
- Steps to reproduce the behavior:
1. Use Eclipse launcher to start in sandbox mode directly with the default 12 settlements with no dialog box
2. ~50% of the time, this exception will pop up during the startup

**Stacktrace**
```
01-Adir-01:000.111 (Severe) PersonTaskManager : [Catarina] Aline Rocha - Trouble calling performTask(): 
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at org.mars_sim.msp.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:199)
	at org.mars_sim.msp.core.person.ai.Mind.getNewMission(Mind.java:459)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:137)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at org.mars_sim.msp.core.person.ai.task.util.Task.executeMappedPhase(Task.java:673)
	at org.mars_sim.msp.core.person.ai.task.util.Task.performTask(Task.java:628)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:82)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:204)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:182)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:119)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:854)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1038)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:892)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:804)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-01:000.111 (Severe) PersonTaskManager : [Kyocera] Hayato Harada - Trouble calling performTask(): 
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at org.mars_sim.msp.core.person.ai.mission.MissionManager.getNewMission(MissionManager.java:199)
	at org.mars_sim.msp.core.person.ai.Mind.getNewMission(Mind.java:459)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.selectingPhase(PlanMission.java:137)
	at org.mars_sim.msp.core.person.ai.task.PlanMission.performMappedPhase(PlanMission.java:114)
	at org.mars_sim.msp.core.person.ai.task.util.Task.executeMappedPhase(Task.java:673)
	at org.mars_sim.msp.core.person.ai.task.util.Task.performTask(Task.java:628)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:82)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:204)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:182)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:119)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:854)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1038)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:892)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:804)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Specifications (please complete the following information)**
- pre 3.6.0 build 8269

**Additional context**
- Add any other context about the problem here.

**Comment by bevans2000** [comment]
I can fix this. Its because we add new Missions in parallel.

**Comment by bevans2000** [comment]
Found it. It is because at the start 2 Threads are creating the meta mission list. Easy to fix
