### ISSUE TITLE
Consolidate battery modeling and turn battery into Equipment

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#982]
**Is your feature request related to a problem? Please describe.**
- So far, we have separate class and methods for charging/discharging battery for Robot, Vehicle, & Power Grid
- EVA Suit has a battery embedded in the suit but it's currently not being able for tracking power use and charging/discharging.

**Describe the solution you desire to see**
- Consolidate all 4 to use the same Battery class
- Experiment with turning battery into extending the Equipment class

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8449

**Comment by bevans2000** [comment]
Before making Battery an Equipment the whole problem with containers and bins need sorting. I don't understand what Bins are providing to us. Why can't we make them a new Container type? Do we now have 2 approach has to storing Resources?
Also are we closing 3.6.0 off soon as we seem to be adding large bits of untested new code

**Comment by mokun** [comment]
> the whole problem with containers and bins need sorting. I don't understand what Bins are providing to us. 

Bins are not put into use yet. 

> Why can't we make them a new Container type? Do we now have 2 approach has to storing Resources?

I want to use Bin to store items such as Crop and other non-unit things.

It's hard to change the current container. I suppose it's still possible but I'd rather start brand new with Bin to do it.

If Bin turns out to be a bad idea, then I'll remove them.

> as we seem to be adding large bits of untested new code

They don't affect anything at all at this point.

**Comment by bevans2000** [comment]
But doesn't the Container concept allow us to store non-Unit things? I feel that we need to stop Containers being Units because that adds a lot of extra complexity that is not needed for Containers.
We should look to redesign this as part of 3.7.0 and work out the best way. There are passive (Bag) & active (EVASuit) Equipment and we treat everything as active which means everything needs to be a Unit.
Also it means that Containers would not need to be managed by the large UnitManager lookups which would be a big memory saving. Remember Containers is the most common "Entity" we have in terms of numbers but they are passive; they cannot act on their own.
I think we have an Issue already for the Container issue.

**Comment by mokun** [comment]
Well. That means at the end, Containers would look like Bins and Bins would look like Containers.

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

I do have in mind improving the power grid, namely the power generation and power storage, particularly when the power demand exceeds the power generated. 

In that case, the grid battery system is put into use. 

However, the way the grid battery is currently utilized is not as desirable.

Currently, all batteries that are individually attached to a building are function as one single entity. 

Ideally, it should first supplement the power demand of that building first and foremost. 

After that, if there's not enough power from the rest of the power grid, then it will look into how much it may individually draw out.

So there should be a difference between local power delivery and settlement-wide power delivery.

We could create a checkbox for each building to configure how he wants each building's battery system to function such as 
1. what *modes* to choose from
2. what percentage to set aside for powering only this building vs. the percentage for serving the entire power grid

Many home energy storage system (such as Tesla Powerwall and others brands out there) by design can store electricity generated by solar panels or drawn from the grid for later use. 

There are options in place for users to choose the way the solar hybrid converter to function according to their lifestyle.

**Comment by Urwumpe** [comment]
Can we also use vehicle batteries in a Vehicle-to-Grid (V2G) way to power the settlements?

Also, I would maybe allow configuring the batteries for their role, too - Should they be local storage, powering the buildings? Should they be factory storage (Larger for a group of buildings)? Should it be grid storage (like right now)?

We have some special batterie buildings, powering these by the batteries first makes little sense, since they should serve other buildings first, that can be more important - for example preserving the local battery storage in a life-support building. And by having some way to limit their role (or not), we could optimize the battery storage better, getting more utility out of the same amount of kWh.

**Comment by mokun** [comment]
@bevans2000 

Somehow after recent changes in `RobotTableModel`, when I clicked on the battery column to sort it, it would give me the following exception : 

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
	at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
	at java.base/java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:413)
	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.base/java.util.Arrays.sort(Arrays.java:1038)
	at java.desktop/javax.swing.DefaultRowSorter.sortExistingData(DefaultRowSorter.java:562)
	at java.desktop/javax.swing.DefaultRowSorter.setSortKeys(DefaultRowSorter.java:317)
	at java.desktop/javax.swing.DefaultRowSorter.toggleSortOrder(DefaultRowSorter.java:476)
	at java.desktop/javax.swing.plaf.basic.BasicTableHeaderUI$MouseInputHandler.mouseClicked(BasicTableHeaderUI.java:130)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:280)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6573)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3390)
	at java.desktop/java.awt.Component.processEvent(Component.java:6335)
	at java.desktop/java.awt.Container.processEvent(Container.java:2260)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4952)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2318)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4784)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4917)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4569)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4501)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2304)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2667)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4784)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:716)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Note that in `BaseRobotModel`, we have 

```java

protected static final EntityColumnSpec BATTERY = new EntityColumnSpec(new ColumnSpec(BATTERY_VAL, Msg.getString("battery.singular"),
                                                        String.class), Set.of(Battery.BATTERY_EVENT));

  /**
     * Get a cell value for the associated Robot. Column index maps to the associated ColumnSpec where the id
     * is used to determine the value to return.
     * @param entity The Robot entity.
     * @param valueIndex Column index. 
     * @return Associated value.
     */
    @Override
    protected Object getEntityValue(Robot entity, int valueIndex) {
        return switch (valueIndex) {
            case TYPE_VAL -> entity.getModel();
            case LOCATION_VAL -> entity.getLocationTag().getImmediateLocation();
            case MODE_VAL -> entity.printStatusModes();
            case HEALTH_VAL -> entity.isOperable() ? OPERABLE : INOPERABLE;
            case BATTERY_VAL -> entity.getSystemCondition().getBattery().getBatteryStatus().getName();
            case BATT_TEMPERATURE_VAL -> entity.getSystemCondition().getBattery().getInternalTemperature();
            case PERFORMANCE_VAL -> entity.getSystemCondition().getPerformanceLevel().getName();
            default -> BaseWorkerModel.getWorkerValue(entity, valueIndex);
        };
    }

```

I'm running the default scenario and there are 176 rows in the Robot tab.

**Comment by bevans2000** [comment]
Never seen that error

**Comment by mokun** [comment]
I asked Brave AI : 

> This java.lang.IllegalArgumentException is thrown by TimSort, Java’s default sorting algorithm (introduced in Java 7), when a custom Comparator violates the mathematical properties required for sorting.  The algorithm is stricter than the previous MergeSort, which previously ignored such violations...

https://search.brave.com/search?q=IllegalArgumentException%3A+Comparison+method+violates+its+general+contract%21&source=desktop&conversation=09599ce780d96663a687722c03c671147066&summary=1

**Comment by bevans2000** [comment]
My guess is one of the values has been changed by the Settlement thread when the sort was happening. So it partially sort the list and then it finds the sorting incorrect.
It's a problem of having multiple threads. 
Just keep at eye on it. Does it happen all the time? What about changing the column and then reselect?
We could write a proxy class for the sorter that catches the exception and attempts a retry.

**Comment by mokun** [comment]
It only happens once in a long while. It had happened to me in the past when sorting the Temp deg C and the Battery status

Don't know why.

**Comment by bevans2000** [comment]
It's a rare race condition. If the battery value changes in the middle of the column sorting the error occurs.
