### ISSUE TITLE
ConcurrentModificationException when unloading equipment from vehicle

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#990]
**Describe the bug**
- Unable to unload equipment from vehicle since the equipment set triggers `ConcurrentModificationException` 

**Expected and unexpected behavior**
- This should be a very common operation and should not trigger `ConcurrentModificationException` 

**Discuss any potential problems you have and have not ruled out**
- If a equipment needs to be transferred, should it call transfer() method and in what way should we allow that equipment to be removed ? set to be changed

- Should we call i.remove() to safely remove an element ?

**Java classes involved**
- In `UnloadVehicleEVA`'s unloadingPhase()
```java
	/**
	 * Perform the unloading phase of the task.
	 * 
	 * @param time the amount of time (millisol) to perform the phase.
	 * @return the amount of time (millisol) after performing the phase.
	 */
	protected double unloadingPhase(double time) {		
		double remainingTime = 0;
		
		if (checkReadiness(time, true) > 0)
			return time;
		
		if (settlement == null || vehicle == null) {
			checkLocation();
			return time;
		}

		if (settlement.getBuildingManager().isInGarage(vehicle)) {
			checkLocation();
			return time;
		}
		
		// Determine unload rate.
		int strength = worker.getNaturalAttributeManager().getAttribute(NaturalAttributeType.STRENGTH);
		double strengthModifier = .1D + (strength * .018D);
		double amountUnloading = UNLOAD_RATE * strengthModifier * time / 4D;

		// Unload equipment.
		if (amountUnloading > 0D) {
			Iterator<Equipment> k = vehicle.getEquipmentSet().iterator();
			while (k.hasNext() && (amountUnloading > 0D)) {	
				Equipment equipment = k.next();
				boolean doUnload = true;
				
				if (vehicle instanceof Crewable crew && equipment.getEquipmentType() == EquipmentType.EVA_SUIT) {
					int numSuit = vehicle.findNumContainersOfType(EquipmentType.EVA_SUIT);
					int numCrew = crew.getCrewNum();
					// Note: Ensure each crew member in the vehicle has an EVA suit to wear
					doUnload = (numSuit > numCrew);
				}
				
				// Unload the equipment
				if (doUnload) {
					// Unload inventories of equipment (if possible)
					UnloadVehicleGarage.unloadEquipmentInventory(equipment, settlement);
					equipment.transfer(settlement);		
					amountUnloading -= equipment.getMass();
					
					logger.log(worker, Level.INFO, 10_000, "Unloaded " + equipment.getNickName()
						+ " from " + vehicle.getName() + ".");
				}
			}
		}
```

**Screenshots**

**Stacktrace**
```
01-Adir-09:434.679 (Info) UnloadVehicleEVA : [10.6300 N 29.7500 W] Jerry Cox - Unloaded Specimen Box 004 from Mercury.
01-Adir-09:434.679 (Info) ConnectWithEarth [x22] : [Port Ares] Gabriel Radu - Connecting with Friends/Family - 0.2 CUs Used.
01-Adir-09:434.679 (Severe) PersonTaskManager : [10.6300 N 29.7500 W] Jerry Cox - Trouble calling performTask(): 
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1579)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1602)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1054)
	at org.mars_sim.msp.core.person.ai.task.UnloadVehicleEVA.unloadingPhase(UnloadVehicleEVA.java:150)
	at org.mars_sim.msp.core.person.ai.task.UnloadVehicleEVA.performMappedPhase(UnloadVehicleEVA.java:113)
	at org.mars_sim.msp.core.person.ai.task.util.Task.executeMappedPhase(Task.java:676)
	at org.mars_sim.msp.core.person.ai.task.util.Task.performTask(Task.java:627)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.executeTask(PersonTaskManager.java:82)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:203)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:175)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:118)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:865)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1169)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:905)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:816)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Specifications (please complete the following information)**
- pre 3.6.0 build 8478

**Additional context**
- Q: why does equipmentSet need to be made unmodifiable in EquipmentInventory ?
```java
	/**
	 * Gets the equipment set.
	 *
	 * @return
	 */
	@Override
	public Set<Equipment> getEquipmentSet() {
		if (equipmentSet == null)
			equipmentSet = new UnitSet<>();
		return Collections.unmodifiableSet(equipmentSet);
	}
```

**Comment by bevans2000** [comment]
No usiny the iterator remove causes problems elsewhere as it breaks thr containment of the EquipmentOwner.
Put the surplus Equipment is a temp Set and then transfer them as a second phase.. So first phase identifies what to transfer and second does the transfer. Assign it to me if you want

**Comment by mokun** [comment]
This is very similar to https://github.com/mars-sim/mars-sim/issues/883.
