### ISSUE TITLE
DOMException and invalid CSS attribute on lowWind.svg

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#992]
**Describe the bug**
- When running compiled swing jar, some weather svg icons are unable to be displayed

**Expected and unexpected behavior**
- This issue does not exist when running mars-sim on Eclipse IDE

**Discuss any potential problems you have and have not ruled out**
- The Apache Batik package is not configured to support animated svg icons such as lowWind 

**Stacktrace**
```
org.w3c.dom.DOMException: jar:file:/D:/Data/msp/msp%20binary/3.6.0/3.6.0.jar!/svg/weather/lowWind.svg:
The attribute "stroke" represents an invalid CSS value ("url(#b)").
Original message:
begin 0, end 4, length 2
        at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:775)
        at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:867)
        at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
        at org.apache.batik.bridge.CSSUtilities.convertDisplay(CSSUtilities.java:563)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:206)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
        at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:210)
        at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
        at org.mars_sim.msp.ui.swing.tool.svg.SVGIcon.generateBufferedImage(SVGIcon.java:98)
        at org.mars_sim.msp.ui.swing.tool.svg.SVGIcon.<init>(SVGIcon.java:81)
        at org.mars_sim.msp.ui.swing.ImageLoader.loadSVGIcon(ImageLoader.java:126)
        at org.mars_sim.msp.ui.swing.ImageLoader.getIconByName(ImageLoader.java:88)
        at org.mars_sim.msp.ui.swing.tool.settlement.SettlementTransparentPanel.updateIcon(SettlementTransparentPanel.java:679)
        at org.mars_sim.msp.ui.swing.tool.settlement.SettlementTransparentPanel.buildWeatherPanel(SettlementTransparentPanel.java:618)
        at org.mars_sim.msp.ui.swing.tool.settlement.SettlementTransparentPanel.createAndShowGUI(SettlementTransparentPanel.java:234)
        at org.mars_sim.msp.ui.swing.tool.settlement.SettlementMapPanel.initLayers(SettlementMapPanel.java:196)
        at org.mars_sim.msp.ui.swing.tool.settlement.SettlementMapPanel.createUI(SettlementMapPanel.java:160)
        at org.mars_sim.msp.ui.swing.tool.settlement.SettlementWindow.<init>(SettlementWindow.java:132)
        at org.mars_sim.msp.ui.swing.MainDesktopPane.getToolWindow(MainDesktopPane.java:342)
        at org.mars_sim.msp.ui.swing.MainDesktopPane.openToolWindow(MainDesktopPane.java:409)
        at org.mars_sim.msp.ui.swing.MainDesktopPane.openInitialWindows(MainDesktopPane.java:734)
        at org.mars_sim.msp.ui.swing.MainWindow.<init>(MainWindow.java:190)
        at org.mars_sim.main.MarsProject.setupMainWindow(MarsProject.java:427)
        at org.mars_sim.main.MarsProject.parseArgs(MarsProject.java:212)
        at org.mars_sim.main.MarsProject.main(MarsProject.java:486)
ERROR: null
Enclosed Exception:
jar:file:/D:/Data/msp/msp%20binary/3.6.0/3.6.0.jar!/svg/weather/lowWind.svg:
The attribute "stroke" represents an invalid CSS value ("url(#b)").
Original message:
begin 0, end 4, length 2
org.w3c.dom.DOMException: jar:file:/D:/Data/msp/msp%20binary/3.6.0/3.6.0.jar!/svg/weather/lowWind.svg:
The attribute "fill" represents an invalid CSS value ("url(#a)").
```

**Specifications**
- pre 3.6.0 build 8492

**Comment by bevans2000** [comment]
@mokun  I think this must be a problem with your build environment in Eclipse. I have added a new UnitTest that loads the animated SVGs using the defined libraries from Maven.

**Comment by mokun** [comment]
The DOMException happens only when running the compiled swing jar on the day this issue was created.

Yesterday I didn't see this anymore when running the compiled swing jar.

But in both cases (compiled swing jar or eclipse), I can't get the animated svg to move. They act just like static svg with no animation.
